require("$api/i18n $api/models $api/relations#Relations $api/toplists#Toplist $shared/events#EventHandler $views/buttons#SubscribeButton $views/image#Image $views/utils/css strings/people.lang".split(" "),function(j,e,m,p,q,r,s,f,n){function i(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}function k(a,b){var d=b||new e.Promise,g=a.shift();if(!g)return d.setFail(),g;g.collection.snapshot(0,3).done(function(b){b.length?b.loadAll("name").done(function(a){d.object={label:h(g.stringId),
items:a};d.setDone()}):k(a,d)}).fail(function(){k(a,d)});return d}function c(a){e.Observable.call(this);this._eventHandler=new q(this);this.set(a)}var h=SP.bind(n.get,n);SP.inherit(c,e.Observable);c.prototype._handleSubscribedChange=function(){if(!this.dispatchEvent({type:"subscriptionchange",user:this.data.user}))return!1;var a=this.data.user.subscribed;this._setCount(this.data.subscriberCount+(a?1:0));if(a){var b=this;this._removalTimer=setTimeout(function(){f.addClass(b._node,"subscribed")},100)}else clearTimeout(this._removalTimer)};
c.prototype._setCount=function(a){"number"!=typeof a?this._subscriberCount.style.visibility="hidden":(this._subscriberCount.style.visibility=null,this._subscriberCount.textContent=h(1==a?"SubscriberCountSingle":"SubscriberCountPlural",j.number(a)))};c.prototype._updateNode=function(){if(this._node){f.addClass(this._node,"loading");var a=this.data.user;this._imagePromise=new e.Promise;this._image.setImage(a);this._subscribe.setItem(a);this._subscribe.setDisabled(!1);this._name.innerHTML="&nbsp;";this._setCount(this.data.subscriberCount);
this._subscriberCount.href=a.uri+":followers";switch(this.data.reason){case "SUBSCRIPTION_OF_SUBSCRIPTION":var b=this.data.reasonUris.slice(0,3).map(function(a){return a.load("name")});e.Promise.join(b).done(this,function(a){var b=this.data.subscriberCount;if("number"!=typeof b||0>b)b=Infinity;a.length=Math.min(this.data.reasonUris.length,b);this.setMetadata(h("InfoFollowedBy"),a)});break;case "MY_SUBSCRIBER":this.setMetadata(h("InfoFollowsYou"));break;default:this.setMetadata(),b=p.forUser(a),this._metadataPromise=
k([{stringId:"InfoTopArtists",collection:b.artists},{stringId:"InfoPlaylists",collection:b.playlists}]),this._metadataPromise.done(this,function(a){this.setMetadata(a.label,a.items)})}b=[this._imagePromise,a.load("name","subscribed")];"number"!=typeof this.data.subscriberCount&&(a=m.forUser(this.data.user).subscribers.snapshot(0,0),a.done(this,function(a){this.data.subscriberCount=a.length;this._setCount(a.length)}),b.push(a));e.Promise.join(b).done(this,this._updateNodeDone)}};c.prototype._updateNodeDone=
function(){var a=this.data.user;this._name.href=a.uri;this._name.textContent=a.name.decodeForText()||"&nbsp;";f.removeClass(this._node,"loading");f.removeClass(this._node,"dismissed");f.removeClass(this._node,"subscribed")};c.prototype.getNode=function(){if(this._node)return this._node;var a=document.createElement("div");a.className="suggestion";var b=document.createElement("span");b.className="dismiss";b.textContent="\u00d7";a.appendChild(b);var d=s.forUser(this.data.user,{link:"auto",style:"plain",
width:80,height:80,animate:!1});this._eventHandler.listen(d,"load",function(){this._imagePromise&&this._imagePromise.setDone()}).listen(d,"reset",function(){this._imagePromise&&this._imagePromise.setDone()});a.appendChild(d.node);var g=document.createElement("a");g.className="name";a.appendChild(g);var c=document.createElement("a");c.className="subscriber-count";a.appendChild(c);var l=document.createElement("span");l.className="metadata";a.appendChild(l);var e=document.createElement("div");e.className=
"buttonArea";var f=r.forUser(this.data.user);e.appendChild(f.node);a.appendChild(e);this._eventHandler.listen(b,"click",function(){this.dispatchEvent({type:"dismiss",user:this.data.user});m.forCurrentUser().dismiss(this.data.user);this.remove()}).listen(g,"click",function(){this.dispatchEvent({type:"navigate",href:this.data.user.uri})}).listen(d.node,"click",function(){this.dispatchEvent({type:"navigate",href:this.data.user.uri})}).listen(a,"webkitAnimationEnd",function(a){switch(a.animationName){case "dismissed":case "subscribed":this.dispatchEvent({type:"removing"})&&
this.dispose()}}).listen(f,"click",function(a){f.setDisabled(!0);this.remove();a.preventDefault()});this._image=d;this._metadata=l;this._name=g;this._node=a;this._subscribe=f;this._subscriberCount=c;this._updateNode();return a};c.prototype.dispose=function(){this._node&&(this._eventHandler.removeAll(),this._node.parentNode&&this._node.parentNode.removeChild(this._node),this._metadataPromise&&this._metadataPromise.setFail(),clearTimeout(this._removalTimer),delete this.data,delete this._eventHandler,
delete this._image,delete this._metadata,delete this._metadataPromise,delete this._node,delete this._subscribe)};c.prototype.remove=function(){f.addClass(this.getNode(),"dismissed")};c.prototype.setMetadata=function(a,b){if(b)if(b.length){var d=b.length-3;if(0<d){for(var c=2;0<c&&!b[c];)c--,d++;b=b.slice(0,c);b.push(h("ListXOthers",j.number(d+1)))}b=b.map(function(a){if(a instanceof e.Loadable){var b=a.name;20<b.length&&(b=b.substr(0,20)+"\u2026");return'<a href="'+a.uri+'">'+i(b)+"</a>"}return i(a)});
this._metadata.innerHTML=i(a)+" "+j.list(b)}else this._metadata.innerHTML="";else this._metadata.innerHTML=i(a||"")};c.prototype.set=function(a){this.data&&this._eventHandler.unlisten(this.data.user,"change:subscribed");this._metadataPromise&&this._metadataPromise.setFail();clearTimeout(this._removalTimer);this.data=a;this._eventHandler.listen(a.user,"change:subscribed",this._handleSubscribedChange);this.dispatchEvent({type:"userchange",user:a.user});this._updateNode()};exports.Suggestion=c});
