require(["$api/models","$api/private/relationsartist"],function(b,d){function n(a,i,h){var e=[];if(0!=h){var l=b.Promise.join([d.artistSubscriptions(a),c.forUser(b.User.fromURI(a)).subscriptions.snapshot()]),f=new b.Promise;l.done(function(b){var a=b[0].map(function(b){return b.uri}),b=b[1].toURIs(),a=a.concat(b);d.categorizeUsersAndArtists(a).done(function(b){f.setDone(b)}).fail(function(b,a){f.setFail(a)})});l.fail(function(b,a){f.setFail(a)});e.push(f)}var g=d.combinedSubscriptionCount(a);e.push(g);
var k=new b.Promise;b.Promise.join(e).done(function(){var a={array:[]};if(0!=h){a.metadata=[];var c,e=f.object;for(c=0;c<e.artistUris.length;c++){var d=e.artistUris[c];0<=e.mergedUris.indexOf(d)||(a.array.push(d),a.metadata.push({artist:d,user:null}))}for(c=0;c<e.userUris.length;c++)d=b.User.fromURI(e.userUris[c]),d.artist?(a.array.unshift(d.uri),a.metadata.unshift({artist:d.artist.uri,user:d.uri})):(a.array.push(d.uri),a.metadata.push({artist:null,user:d.uri}));if(i||-1<h)c=i+(-1<h?h:a.array.length),
a.array=a.array.slice(i,c),a.metadata=a.metadata.slice(i,c)}a.length=g.object;k.setDone(a)}).fail(function(a,b){k.setFail(b)});return k}function c(a){b.BridgeLoadable.call(this);a=b.User.fromURI(a);this.resolve("owner",a);this.resolve("subscribers",new b.BridgeCollection(b.User,null,"relations_subscribers_users",a.uri));this.resolve("subscriptions",new b.BridgeCollection(b.User,null,"relations_subscriptions_users",a.uri));this.resolve("combinedSubscriptions",new b.Collection(b.Profile,null,n,a.uri))}
function e(a){c.call(this,a);this.resolve("blocked",new b.BridgeCollection(b.User,null,"relations_blocked_users",this.owner.uri));this.resolve("dismissed",new b.BridgeCollection(b.User,null,"relations_dismissed_users",this.owner.uri));this.resolve("hidden",new b.BridgeCollection(b.User,null,"relations_hidden_users",this.owner.uri));b.User.getOrCreateRelationsListener().proxyTo(this)}function j(a){for(var d=0;d<a.uris.length;d++)b.User.fromURI(a.uris[d]).load("artist").done(function(b){b.artist&&b.artist.resolve("subscribed",
"add"==a.type)});c.forCurrentUser().combinedSubscriptions.dispatchEvent({type:a.type,receiver:"combinedSubscriptions",uris:a.uris})}SP.inherit(c,b.BridgeLoadable);c.fromURI=b.Cache.lookup;c._cache=new b.Cache(c);b.Loadable.define(c,["owner","subscribers","subscriptions","combinedSubscriptions"]);SP.inherit(e,c);b.Loadable.define(e,["blocked","dismissed","hidden"]);e.prototype.block=function(a){return b.promisedRequest(this,"relations_block",[this.owner.uri].concat(SP.uris(arguments)))};e.prototype.dismiss=
function(a){return b.promisedRequest(this,"relations_dismiss",[this.owner.uri].concat(SP.uris(arguments)))};e.prototype.subscribe=function(a){return this._changeRelation(SP.uris(arguments),d.Relationship.SUBSCRIBED)};e.prototype.unblock=function(a){return b.promisedRequest(this,"relations_unblock",[this.owner.uri].concat(SP.uris(arguments)))};e.prototype.unsubscribe=function(a){return this._changeRelation(SP.uris(arguments),d.Relationship.NOT_SUBSCRIBED)};e.prototype._changeRelation=function(a,c){var e=
new b.Promise,j=c===d.Relationship.SUBSCRIBED?"subscribe":"unsubscribe";d.categorizeUsersAndArtists(a).done(this,function(a){var f=[];if(a.userUris.length){var g=b.promisedRequest(this,"relations_"+j,[this.owner.uri].concat(a.userUris));g.done(this,function(){d.updateCache(a.mergedUris,c)});f.push(g)}a.artistUris.length&&(g=d.changeRelation(a.artistUris,c),g.done(this,function(){this.eventDone({type:c===d.Relationship.SUBSCRIBED?"add":"remove",receiver:"combinedSubscriptions",uris:a.artistUris})}),
f.push(g));b.Promise.join(f).done(this,function(){e.setDone(this)}).fail(function(a,b){e.setFail(b)})});return e};c._currentUser=null;c.forCurrentUser=function(){c._currentUser||(c._currentUser=new e(b.session.user.uri));return c._currentUser};c.forUser=function(a){return c.fromURI(a.uri)};b.Loadable.define(b.Artist,["subscribed"],"_relations__temp_patch");b.Artist.prototype._relations__temp_patch=function(a){d.isSubscribed(this.uri).done(this,function(b){this.resolveMany(a,{subscribed:b})}).fail(this,
function(){this.resolveFail(a,{error:"Cannot load subscribed property"})})};var m=c.forCurrentUser().subscriptions;m.addEventListener("add",j);m.addEventListener("remove",j);exports.Relations=c});
