require("$api/library#Library $api/models $api/relations#Relations $views/popup#Popup $views/strings/buttons.lang $views/utils/css $views/utils/dom".split(" "),function(q,i,r,t,s,f,l){function e(a,b,c){this.disabled=this.accentuated=!1;this._accentuatedEffect=null;this._nodeClass=a;this._setupTouch();this._buildButton();this._addBehavior();this.label="";"string"===typeof b&&this.setLabel(b);this.icon="";"string"===typeof c&&this.setIcon(c);this.addEventListener("click",this._clicked)}function g(a,
b){e.call(this,"sp-button",a,b);this.size="normal"}function n(a,b,c){e.call(this,"sp-button-empty "+a,b,c)}function j(a){g.call(this,h("ButtonShare"));this.setIconClass("sp-icon-share");this.item=a}function k(a){g.call(this,h("ButtonStartRadio"));this.setIconClass("sp-icon-radio");this.item=a}function d(a){var b=this;g.call(this,h("ButtonSubscribe"));this.setIconClass("sp-icon-add");f.addClass(this.node,"sp-button-subscribe");this._updateMinWidth();this._pending=!1;this._subscribed=null;var c=function(a,
c){b.setAccentuated(!!c,c?"negative":void 0);b.setLabel(c?h("ButtonUnsubscribe"):h("ButtonSubscribed"))};this.addEventListener("pointerend",function(a){b._subscribed&&c(a,!1)});var e=function(a){b.disabled||(b._isMouseHovering="mouseover"===a.type,b._subscribed&&(b._active&&b._isMouseHovering||!b._active)&&c(a,b._isMouseHovering))};l.addEventListener(this.node,"mouseover",e);l.addEventListener(this.node,"mouseout",e);this._mouseHandler=e;this._setSubscribed(!1);this.setItem(a)}function p(a){if(!(a instanceof
i.Playlist))throw Error("not a Playlist");d.call(this,a)}function m(a){if(!(a instanceof i.User||a instanceof i.Artist))throw Error(a+" not a User or Artist");d.call(this,a)}var h=SP.bind(s.get,s);SP.inherit(e,i.Observable);e.prototype.getTextWidth=function(a,b){var c,d;e._measureNode?(c=e._measureNode,d=e._measureNodeSpan):(c=document.createElement("button"),c.style.position="absolute",c.style.visibility="hidden",d=document.createElement("span"),d.className="sp-button-text",c.appendChild(d),e._measureNode=
c,e._measureNodeSpan=d);document.body.appendChild(c);c.className="string"==typeof b?b:this.node.className;d.textContent=a;d=d.getBoundingClientRect().width;document.body.removeChild(c);return d};e.prototype.setLabel=function(a){this.label=a;this._label.data=a||""};e.prototype.setIcon=function(a,b){"string"===typeof b&&this.setIconClass(b);this.icon=a;this._icon.style.backgroundImage=a?'url("'+a+'")':null;this._icon.style.display=a?"inline-block":"none"};e.prototype.setIconClass=function(a){f.removeClass(this._icon,
this._iconClass);f.addClass(this._icon,a);this._iconClass=a};e.prototype.setDisabled=function(a){(this.disabled=!!a)?this.node.setAttribute("disabled","disabled"):this.node.removeAttribute("disabled")};e._accentuationEffects={positive:"sp-button-accentuated-positive",negative:"sp-button-accentuated-negative"};e.prototype.setAccentuated=function(a,b){this.accentuated=a;var c=e._accentuationEffects;this._accentuatedEffect in c&&(f.removeClass(this.node,c[this._accentuatedEffect]),this._accentuatedEffect=
null);if(a){var d=c[b]?b:"positive",c=c[d];f.addClass(this.node,"sp-button-accentuated");f.addClass(this.node,c);this._accentuatedEffect=d}else f.removeClass(this.node,"sp-button-accentuated")};e.prototype._setupTouch=function(){this._touchDevice="ontouchstart"in window||"createTouch"in document;this.touchPreventsScrolling=!0};e.prototype._buildButton=function(){this.node=document.createElement("button");this.node.setAttribute("type","button");f.addClass(this.node,this._nodeClass);var a=document.createElement("span");
f.addClass(a,"sp-button-text");this.node.appendChild(a);this._icon=document.createElement("div");f.addClass(this._icon,"sp-button-icon");this.icon&&(this._icon.style.backgroundImage='url("'+this.icon+'")');a.appendChild(this._icon);this._label=document.createTextNode(this.label||"");a.appendChild(this._label)};e.prototype._addBehavior=function(){var a=this;l.addEventListener(this.node,this._touchDevice?"touchstart":"mousedown",function(b){a._startHandler(b)});l.addEventListener(document,this._touchDevice?
"touchmove":"mousemove",function(b){a._moveHandler(b)});l.addEventListener(document,this._touchDevice?"touchend":"mouseup",function(b){a._endHandler(b)})};e.prototype._startHandler=function(a){this.disabled||((!this._touchDevice||!this.touchPreventsScrolling)&&a.preventDefault(),this._buttonPos=this._getPos(),this._active=!0,f.addClass(this.node,"sp-button-active"))};e.prototype._moveHandler=function(a){!this.disabled&&this._active&&(this._isPointerInside(a)?f.addClass(this.node,"sp-button-active"):
f.removeClass(this.node,"sp-button-active"))};e.prototype._endHandler=function(a){!this.disabled&&this._active&&(this._active=!1,f.removeClass(this.node,"sp-button-active"),this.dispatchEvent("pointerend"),this._isPointerInside(a)&&this.dispatchEvent({type:"click",browserEvent:a}))};e.prototype._getPos=function(){var a=this._scrollValues||{};a.x=window.pageXOffset||document.documentElement.scrollLeft;a.y=window.pageYOffset||document.documentElement.scrollTop;this._scrollValues=a;var b=this._buttonPos||
{},c=this.node.getBoundingClientRect(),d=this._touchDevice?20:-1,e=this._touchDevice?20:-1;b.left=c.left+a.x-d;b.top=c.top+a.y-e;b.right=b.left+c.width+2*d;b.bottom=b.top+c.height+2*e;return b};e.prototype._isPointerInside=function(a){var b=this._touchDevice?a.changedTouches[0].pageX:a.pageX,c=this._touchDevice?a.changedTouches[0].pageY:a.pageY,a=this._buttonPos||this._getPos(),c=c>a.top&&c<=a.bottom;return b>a.left&&b<=a.right&&c};SP.inherit(g,e);g.withLabel=function(a,b){return new g(a,b)};g._sizes=
{normal:"",small:"sp-button-small"};g.prototype.setSize=function(a){if(this.size!=a){if(!(a in g._sizes))throw Error(a+" is not a valid size");f.removeClass(this.node,g._sizes[this.size]);f.addClass(this.node,g._sizes[a]);this.size=a}};g.prototype._buildButton=function(){g._superClass._buildButton.call(this);var a=document.createElement("span");f.addClass(a,"sp-button-background");this.node.appendChild(a)};SP.inherit(n,e);n.withClass=function(a,b,c){return new n(a,b,c)};SP.inherit(j,g);j.prototype._clicked=
function(){var a=this.node.getBoundingClientRect();i.client.showShareUI(this.item.uri,"",{x:a.left+a.width/2,y:a.top+a.height/2})};j.forAlbum=function(a){return new j(a)};j.forArtist=function(a){return new j(a)};j.forPlaylist=function(a){return new j(a)};j.forTrack=function(a){return new j(a)};SP.inherit(k,g);k.prototype._clicked=function(){var a=this.item.uri.replace(/^spotify:/,"spotify:radio:");i.application.openURI(a)};k.forAlbum=function(a){if(!(a instanceof i.Album))throw Error("not an Album");
return new k(a)};k.forArtist=function(a){if(!(a instanceof i.Artist))throw Error("not an Artist");return new k(a)};k.forPlaylist=function(a){if(!(a instanceof i.Playlist))throw Error("not a Playlist");return new k(a)};k.forTrack=function(a){if(!(a instanceof i.Track))throw Error("not a Track");return new k(a)};SP.inherit(d,g);d.prototype._clicked=function(){var a=this.item.subscribed;"boolean"!=typeof a||this._pending||(this._setSubscribed(!a),this._updateSubscription(!a))};d.prototype._call=function(a,
b){this._pending=!0;return a[b](this.item).done(this,this._done).fail(this,this._fail)};d.prototype._done=function(){this._pending=!1;this.dispatchEvent({type:this._subscribed?"subscribe":"unsubscribe",item:this.item})};d.prototype._fail=function(a){this._pending=!1;this.dispatchEvent({type:(this._subscribed?"subscribe":"unsubscribe")+"-fail",item:this.item,error:a});this._setSubscribed(this.item.subscribed)};d.prototype._setSubscribed=function(a){this._subscribed!==a&&(this._subscribed=a,this.setAccentuated(!a),
this.setLabel(a?h("ButtonSubscribed"):h("ButtonSubscribe")),this.setIconClass(a?"":"sp-icon-add"),this._isMouseHovering&&this._mouseHandler.call(this.node,{type:"mouseover"}))};d.prototype._updateMinWidth=function(){var a=[this.getTextWidth(h("ButtonSubscribe"))+20,this.getTextWidth(h("ButtonSubscribed")),this.getTextWidth(h("ButtonUnsubscribe"))],a=Math.max.apply(Math,a)+8;this.node.style.minWidth=a+"px"};d.prototype._updateSubscription=function(){throw Error("SubscribeButton _updateSubscription not implemented");
};d.prototype.setItem=function(a){function b(){c._setSubscribed(a.subscribed)}this.item&&this.item.removeEventListener("change:subscribed",this._update);this.item=a;var c=this;this._update=b;a.load("subscribed").done(function(){b();a.addEventListener("change:subscribed",b)})};d.prototype.setSize=function(a){d._superClass.setSize.call(this,a);this._updateMinWidth()};SP.inherit(p,d);p.prototype._showPopup=function(){this._popup&&this._popup.dispose();var a=document.createDocumentFragment(),b=document.createElement("p");
b.innerHTML=h("PopupPlaylistSubscribeLine1","<strong>"+this.item.owner.name.decodeForHtml()+"</strong>")+"<br><br>"+h("PopupPlaylistSubscribeLine2");a.appendChild(b);var c=document.createElement("p");c.className="sp-popup-buttons";a.appendChild(c);var d=g.withLabel(h("PopupPlaylistSubscribeCancel"));c.appendChild(d.node);var e=g.withLabel(h("PopupPlaylistSubscribeConfirm"));e.setAccentuated(!0);c.appendChild(e.node);var f=t.withContent(a,250,0,"sp-playlist-subscribed"),i=this.item.owner;d.addEventListener("click",
function(){this.setDisabled(!0);r.forCurrentUser().unsubscribe(i);f.hide(100)});e.addEventListener("click",function(){f.hide()});f.showFor(this.node);a=b.getBoundingClientRect();f.resize(f.width,a.height+44);this._popup=f};p.prototype._updateSubscription=function(a){if(a){var b=this;i.client.load("features").done(function(a){a.features.autoFollowPlaylistOwners?b.item.load("owner").done(function(a){a.owner.load("name","subscribed").done(function(a){a.subscribed||b._showPopup();b._call(q.forCurrentUser(),
"subscribe")})}):b._call(q.forCurrentUser(),"subscribe")})}else this._call(q.forCurrentUser(),"unsubscribe")};SP.inherit(m,d);m.prototype._updateSubscription=function(a){this._call(r.forCurrentUser(),a?"subscribe":"unsubscribe")};d.forArtist=function(a){return new m(a)};d.forProfile=function(a){return new m(a)};d.forPlaylist=function(a){return new p(a)};d.forUser=function(a){return new m(a)};exports.Button=g;exports.CustomButton=n;exports.ShareButton=j;exports.StartRadioButton=k;exports.SubscribeButton=
d});
