require("$api/library#Library $api/models $api/relations#Relations $views/popup#Popup $views/strings/buttons.lang $views/utils/css $views/utils/dom $views/contextapp#ContextApp".split(" "),function(p,j,u,w,v,d,n,x){function e(a,b,c){this.disabled=this.accentuated=!1;this._accentuatedEffect=null;this._nodeClass=a;this._setupTouch();this._buildButton();this._addBehavior();this.label="";"string"===typeof b&&this.setLabel(b);this.icon="";"string"===typeof c&&this.setIcon(c);this.addEventListener("click",
this._clicked)}function h(a,b){e.call(this,"sp-button",a,b);this.size="normal"}function s(a,b,c){e.call(this,"sp-button-empty "+a,b,c)}function l(a){h.call(this,i("ButtonShare"));this.setIconClass("sp-icon-share");this.item=a}function m(a){h.call(this,i("ButtonStartRadio"));this.setIconClass("sp-icon-radio");this.item=a}function g(a){var b=this;h.call(this,i("ButtonSubscribe"));this.setIconClass("sp-icon-add");d.addClass(this.node,"sp-button-subscribe");this._updateMinWidth();this._pending=!1;this._subscribed=
null;this._isAutoAccentuated=!0;var c=function(a,c){b.setAccentuated(!!c,c?"negative":void 0);b.setLabel(c?i("ButtonUnsubscribe"):i("ButtonSubscribed"))};this.addEventListener("pointerend",function(a){b._subscribed&&c(a,!1)});var k=function(a){b.disabled||(b._isMouseHovering="mouseover"===a.type,b._subscribed&&(b._active&&b._isMouseHovering||!b._active)&&c(a,b._isMouseHovering))};n.addEventListener(this.node,"mouseover",k);n.addEventListener(this.node,"mouseout",k);this._mouseHandler=k;this._setSubscribed(!1);
this.setItem(a)}function t(a){if(!(a instanceof j.Playlist))throw Error("not a Playlist");g.call(this,a)}function q(a){if(!(a instanceof j.User||a instanceof j.Artist))throw Error(a+" not a User or Artist");g.call(this,a)}function r(a,b,c){this.item=a;this.origin=b;this.indexGetter=c;var k=document.createElement("div");d.addClass(k,"sp-quickactionbuttons");var e;j.session.load("device").done(this,function(a){"web"===a.device&&(e=a=document.createElement("button"),k.appendChild(a),a.setAttribute("type",
"button"),d.addClass(k,"sp-with-contextbutton"),d.addClass(a,"sp-contextmenu"),a.addEventListener("click",SP.bind(this._clicked,this)))});j.client.load("features").done(function(b){b.features.collection&&(d.addClass(k,"sp-with-collection"),b=new f(a),k.insertBefore(b.node,e))});this.node=k}function f(a){var b=this;this._notInCollectionLabel=i("AddToCollection");this._inCollectionLabel=i("InYourCollection");this._removeFromCollectionLabel=i("RemoveFromCollection");h.call(this,this._notInCollectionLabel);
this.item=a;this._autoAccentuated=!0;d.addClass(this.node,"sp-add-to-collection-button");this._library=p.forCurrentUser();this.node.buttonInstance=this;this._isInCollection=!1;n.addEventListener(this.node,"mouseover",function(){b._isMouseHovering=!0;b._updateLooks()});n.addEventListener(this.node,"mouseout",function(){b._isMouseHovering=!1;b._updateLooks()});this._updateLooks();f.updateStates()}var i=SP.bind(v.get,v);exports.Button=h;exports.CustomButton=s;exports.ShareButton=l;exports.StartRadioButton=
m;exports.SubscribeButton=g;exports.QuickActionButtons=r;exports.AddToCollectionButton=f;SP.inherit(e,j.Observable);e.prototype.getTextWidth=function(a,b){var c,d;e._measureNode?(c=e._measureNode,d=e._measureNodeSpan):(c=document.createElement("button"),c.style.position="absolute",c.style.visibility="hidden",d=document.createElement("span"),d.className="sp-button-text",c.appendChild(d),e._measureNode=c,e._measureNodeSpan=d);document.body.appendChild(c);c.className="string"==typeof b?b:this.node.className;
d.textContent=a;d=d.getBoundingClientRect().width;document.body.removeChild(c);return d};e.prototype.setLabel=function(a){this.label=a;this._label.data=a||""};e.prototype.setIcon=function(a,b){"string"===typeof b&&this.setIconClass(b);this.icon=a;this._icon.style.backgroundImage=a?'url("'+a+'")':null;this._icon.style.display=a?"inline-block":"none"};e.prototype.setIconClass=function(a){d.removeClass(this._icon,this._iconClass);d.addClass(this._icon,a);this._iconClass=a};e.prototype.setDisabled=function(a){(this.disabled=
!!a)?this.node.setAttribute("disabled","disabled"):this.node.removeAttribute("disabled")};e._accentuationEffects={positive:"sp-button-accentuated-positive",negative:"sp-button-accentuated-negative"};e.prototype.setAccentuated=function(a,b){this.accentuated=a;var c=e._accentuationEffects;this._accentuatedEffect in c&&(d.removeClass(this.node,c[this._accentuatedEffect]),this._accentuatedEffect=null);if(a){var k=c[b]?b:"positive",c=c[k];d.addClass(this.node,"sp-button-accentuated");d.addClass(this.node,
c);this._accentuatedEffect=k}else d.removeClass(this.node,"sp-button-accentuated")};e.prototype._setupTouch=function(){this._touchDevice="ontouchstart"in window||"createTouch"in document;this.touchPreventsScrolling=!0};e.prototype._buildButton=function(){this.node=document.createElement("button");this.node.setAttribute("type","button");d.addClass(this.node,this._nodeClass);this._touchDevice&&d.addClass(this.node,"sp-button-touch");if(this._touchDevice){var a=document.createElement("span");d.addClass(a,
"sp-button-hitarea");this.node.appendChild(a);this.hitArea=a}else this.hitArea=this.node;a=document.createElement("span");d.addClass(a,"sp-button-text");this.node.appendChild(a);this._icon=document.createElement("div");d.addClass(this._icon,"sp-button-icon");this.icon&&(this._icon.style.backgroundImage='url("'+this.icon+'")');a.appendChild(this._icon);this._label=document.createTextNode(this.label||"");a.appendChild(this._label)};e.prototype._addBehavior=function(){var a=this;n.addEventListener(this.hitArea,
this._touchDevice?"touchstart":"mousedown",function(b){a._startHandler(b)});n.addEventListener(document,this._touchDevice?"touchmove":"mousemove",function(b){a._moveHandler(b)});n.addEventListener(document,this._touchDevice?"touchend":"mouseup",function(b){a._endHandler(b)})};e.prototype._startHandler=function(a){if(!this.disabled&&(this._touchDevice&&this.touchPreventsScrolling&&a.preventDefault(),!(void 0!==a.button&&0!==a.button)&&(e._isMac=e._isMac||-1<navigator.userAgent.indexOf("Macintosh")?
!0:!1,!e._isMac||!a.ctrlKey)))this._buttonPos=this._getPos(),this._active=!0,d.addClass(this.node,"sp-button-active")};e.prototype._moveHandler=function(a){!this.disabled&&this._active&&(this._isPointerInside(a)?d.addClass(this.node,"sp-button-active"):d.removeClass(this.node,"sp-button-active"))};e.prototype._endHandler=function(a){!this.disabled&&this._active&&(this._active=!1,d.removeClass(this.node,"sp-button-active"),this.dispatchEvent("pointerend"),this._isPointerInside(a)&&this.dispatchEvent({type:"click",
browserEvent:a}))};e.prototype._getPos=function(){var a=this._scrollValues||{};a.x=window.pageXOffset||document.documentElement.scrollLeft;a.y=window.pageYOffset||document.documentElement.scrollTop;this._scrollValues=a;var b=this._buttonPos||{},c=this.hitArea.getBoundingClientRect();b.left=c.left+a.x;b.top=c.top+a.y;b.right=b.left+c.width;b.bottom=b.top+c.height;return b};e.prototype._isPointerInside=function(a){var b=this._touchDevice?a.changedTouches[0].pageX:a.pageX,c=this._touchDevice?a.changedTouches[0].pageY:
a.pageY,a=this._buttonPos||this._getPos(),c=c>a.top&&c<=a.bottom;return b>a.left&&b<=a.right&&c};SP.inherit(h,e);h.withLabel=function(a,b){return new h(a,b)};h._sizes={normal:"",small:"sp-button-small",large:"sp-button-large"};h.prototype.setSize=function(a){if(this.size!=a){if(!(a in h._sizes))throw Error(a+" is not a valid size");d.removeClass(this.node,h._sizes[this.size]);d.addClass(this.node,h._sizes[a]);this.size=a}};h.prototype._buildButton=function(){h._superClass._buildButton.call(this);
var a=document.createElement("span");d.addClass(a,"sp-button-background");this.node.appendChild(a)};SP.inherit(s,e);s.withClass=function(a,b,c){return new s(a,b,c)};SP.inherit(l,h);l.forAlbum=function(a){return new l(a)};l.forArtist=function(a){return new l(a)};l.forPlaylist=function(a){return new l(a)};l.forTrack=function(a){return new l(a)};l.prototype._clicked=function(){var a=this.node.getBoundingClientRect();j.client.showShareUI(this.item.uri,"",{x:a.left+a.width/2,y:a.top+a.height/2})};SP.inherit(m,
h);m.forAlbum=function(a){if(!(a instanceof j.Album))throw Error("not an Album");return new m(a)};m.forArtist=function(a){if(!(a instanceof j.Artist))throw Error("not an Artist");return new m(a)};m.forPlaylist=function(a){if(!(a instanceof j.Playlist))throw Error("not a Playlist");return new m(a)};m.forTrack=function(a){if(!(a instanceof j.Track))throw Error("not a Track");return new m(a)};m.prototype._clicked=function(){var a=this.item.uri.replace(/^spotify:/,"spotify:radio:");j.application.openURI(a)};
SP.inherit(g,h);g.prototype.setItem=function(a){function b(){c._setSubscribed(a.subscribed)}this.item&&this.item.removeEventListener("change:subscribed",this._update);this.item=a;var c=this;this._update=b;a.load("subscribed").done(function(){b();a.addEventListener("change:subscribed",b)})};g.prototype.setSize=function(a){g._superClass.setSize.call(this,a);this._updateMinWidth()};g.prototype.setAutoAccentuated=function(a){(this._isAutoAccentuated=!!a)?this.setAccentuated(!this._subscribed):this.setAccentuated(!1)};
g.prototype._clicked=function(){var a=this.item.subscribed;"boolean"!=typeof a||this._pending||(this._setSubscribed(!a),this._updateSubscription(!a))};g.prototype._call=function(a,b){this._pending=!0;return a[b](this.item).done(this,this._done).fail(this,this._fail)};g.prototype._done=function(){this._pending=!1;this.dispatchEvent({type:this._subscribed?"subscribe":"unsubscribe",item:this.item})};g.prototype._fail=function(a){this._pending=!1;this.dispatchEvent({type:(this._subscribed?"subscribe":
"unsubscribe")+"-fail",item:this.item,error:a});this._setSubscribed(this.item.subscribed)};g.prototype._setSubscribed=function(a){this._subscribed!==a&&(this._subscribed=a,this._isAutoAccentuated&&this.setAccentuated(!a),this.setLabel(a?i("ButtonSubscribed"):i("ButtonSubscribe")),this.setIconClass(a?"":"sp-icon-add"),this._isMouseHovering&&this._mouseHandler.call(this.node,{type:"mouseover"}))};g.prototype._updateMinWidth=function(){var a=[this.getTextWidth(i("ButtonSubscribe"))+20,this.getTextWidth(i("ButtonSubscribed")),
this.getTextWidth(i("ButtonUnsubscribe"))],a=Math.max.apply(Math,a)+8;this.node.style.minWidth=a+"px"};g.prototype._updateSubscription=function(){throw Error("SubscribeButton _updateSubscription not implemented");};SP.inherit(t,g);t.prototype._showPopup=function(){this._popup&&this._popup.dispose();var a=document.createDocumentFragment(),b=document.createElement("p");b.innerHTML=i("PopupPlaylistSubscribeLine1","<strong>"+this.item.owner.name.decodeForHtml()+"</strong>")+"<br><br>"+i("PopupPlaylistSubscribeLine2");
a.appendChild(b);var c=document.createElement("p");c.className="sp-popup-buttons";a.appendChild(c);var d=h.withLabel(i("PopupPlaylistSubscribeCancel"));c.appendChild(d.node);var e=h.withLabel(i("PopupPlaylistSubscribeConfirm"));e.setAccentuated(!0);c.appendChild(e.node);var f=w.withContent(a,250,0,"sp-playlist-subscribed"),g=this.item.owner;d.addEventListener("click",function(){this.setDisabled(!0);u.forCurrentUser().unsubscribe(g);f.hide(100)});e.addEventListener("click",function(){f.hide()});f.showFor(this.node);
a=b.getBoundingClientRect();f.resize(f.width,a.height+44);this._popup=f};t.prototype._updateSubscription=function(a){if(a){var b=this;j.client.load("features").done(function(a){a.features.autoFollowPlaylistOwners?b.item.load("owner").done(function(a){a.owner.load("name","subscribed").done(function(a){a.subscribed||b._showPopup();b._call(p.forCurrentUser(),"subscribe")})}):b._call(p.forCurrentUser(),"subscribe")})}else this._call(p.forCurrentUser(),"unsubscribe")};SP.inherit(q,g);q.prototype._updateSubscription=
function(a){this._call(u.forCurrentUser(),a?"subscribe":"unsubscribe")};g.forPlaylist=function(a){return new t(a)};g.forArtist=function(a){return new q(a)};g.forUser=function(a){return new q(a)};g.forProfile=function(a){return new q(a)};r.forItem=function(a,b,c){return new r(a,b,c)};r.prototype._clicked=function(a){var b=this,c,e=0,f=void 0;this.indexGetter&&(f=this.indexGetter(a));x.show("context-actions",[this.item.uri],a.target,this.origin,f,this._getLoggingContext()).done(function(){c=function(){e++;
2==e&&(d.removeClass(b.node,"sp-quickactionbuttons-popup"),document.removeEventListener("mousemove",c))};document.addEventListener("mousemove",c)});d.addClass(this.node,"sp-quickactionbuttons-popup")};r.prototype._getLoggingContext=function(){var a=[],b,c=this.node;if(c){do c&&(c.getAttribute&&(b=c.getAttribute("data-log-context")))&&a.push(b);while(c=c.parentNode)}return a.reverse().join("/")};SP.inherit(f,h);f.forItem=function(a){return new f(a)};f.prototype.setAutoAccentuated=function(a){this._autoAccentuated=
a;this._updateLooks()};f.prototype._setInCollectionState=function(a){this._isInCollection!=a&&(this._isInCollection=a,this._updateLooks())};f.prototype._clicked=function(a){a.target===this.node&&(a.preventDefault(),a.stopPropagation());this._isInCollection?this.item instanceof j.Track?this._library.tracks.remove(this.item):this._library.albums.remove(this.item):this.item instanceof j.Track?this._library.tracks.add(this.item):this._library.albums.add(this.item)};f.prototype._updateLooks=function(){this._isInCollection?
(this.setIconClass(""),d.addClass(this.node,"sp-in-collection"),d.removeClass(this.node,"sp-button-accentuated-positive"),this._isMouseHovering?(this.setLabel(this._removeFromCollectionLabel),d.addClass(this.node,"sp-button-accentuated-negative"),d.addClass(this.node,"sp-button-accentuated")):(this.setLabel(this._inCollectionLabel),d.removeClass(this.node,"sp-button-accentuated-negative"),d.removeClass(this.node,"sp-button-accentuated"))):(this.setIconClass("sp-icon-add"),this.setLabel(this._notInCollectionLabel),
d.removeClass(this.node,"sp-in-collection"),d.removeClass(this.node,"sp-button-accentuated-negative"),this._autoAccentuated?(d.addClass(this.node,"sp-button-accentuated-positive"),d.addClass(this.node,"sp-button-accentuated")):(d.removeClass(this.node,"sp-button-accentuated-positive"),d.removeClass(this.node,"sp-button-accentuated")))};f._updateSubsetStates=function(a,b,c){for(var d=[],e=[],f=0;f<a.length;f++){var g=a[f].buttonInstance.item.uri;0==g.indexOf(b)&&(d.push(a[f]),e.push(j.Track.fromURI(g)))}c.contains(e).done(function(a){for(var b=
0;b<e.length;b++)d[b].buttonInstance._setInCollectionState(a[b])})};f._updateStates=function(){var a=p.forCurrentUser(),b=document.querySelectorAll(".sp-add-to-collection-button");f._updateSubsetStates(b,"spotify:track",a.tracks);f._updateSubsetStates(b,"spotify:album",a.albums)};f.updateStates=function(){f._timer&&clearTimeout(f._timer);f._timer=setTimeout(f._updateStates,10)};f._initGlobally=function(){var a=p.forCurrentUser();a.tracks.addEventListener("changed",function(){f.updateStates()});a.albums.addEventListener("changed",
function(){f.updateStates()})};f._initGlobally()});
