require("$api/models $api/toplists#Toplist $views/utils/css $views/utils/dom $views/utils/dnd $views/buttons".split(" "),function(g,n,e,l,m,p){function f(a,b){b=b||{};this._title=b.title;this._link=b.link||"";this._animateLoaded=void 0===b.animate?!0:b.animate;this._placeholder=void 0===b.placeholder?"auto":b.placeholder;this._player=!!b.player;this._playerItem=b.playerItem;this._swap="immediate"===b.swap?"immediate":"wait";this._overlay=void 0===b.overlay?[]:b.overlay;this._style=~["plain","inset",
"rounded","embossed"].indexOf(b.style)?b.style:"inset";this._getContextGroupData=b.getContextGroupData;this._acceptedLoadTime=200;this._width=b.width||b.height||200;this._height=b.height||b.width||200;var c={artist:"Artist",album:"Album",track:"Track",playlist:"Playlist",user:"User"};!~" auto none empty ".indexOf(" "+this._placeholder+" ")&&!(this._placeholder in c)&&(this._placeholder="auto");this._placeholderType=c[this._placeholder]||"auto";this._buildNode();this._isCustomImage=a?"string"===typeof a?
!0:!1:!0;"none"!==this._placeholder&&this._buildPlaceholder();void 0!==a?this.setImage(a):"none"!==this._placeholder&&this._setPlaceholder(this._getSuitableSize("placeholder"));this._player&&this._buildPlayer();this._player&&this._playStateChanged();this._link&&this.setLink(this._link);m.drag.hasDragSupport&&this._addDragHandler();var d=this;g.session.load("device").done(function(){"desktop"===g.session.device&&d._addContextUIHandler()})}exports.Image=f;var h=g.player;SP.inherit(f,g.Observable);"Album Artist Playlist Profile Track User".split(" ").forEach(function(a){f["for"+
a]=function(b,c){var d=g[a];if("string"===typeof b)b=d.fromURI(b);else if(!(b instanceof d))throw Error("The type of the object is not "+a);return new f(b,c)}});f.fromSource=function(a,b){return new f(a,b)};f.prototype.setImage=function(a){this.isLoaded=!1;if(this._isCustomImage="string"===typeof a)this._item=null,this._src=a;else{var b=this._item instanceof g.Track,c=this._item instanceof g.Playlist;if(this._item&&(b||c))this._item.removeEventListener("change:image",this._changeEventHandler),this._changeEventHandler=
null;this._src=null;this._item=a;b=a instanceof g.Playlist;if(a instanceof g.Track||b){var d=this;a.load("image").done(function(){d._changeEventHandler=function(){d._resetImage();d._buildImage()};a.addEventListener("change:image",d._changeEventHandler)})}}"none"!==this._placeholder&&this._setPlaceholder(this._getSuitableSize("placeholder"));"immediate"===this._swap&&this._resetImage();this._buildImage();!this.node.overlay&&0<this._overlay.length&&this.setOverlay(this._overlay[0],this._overlay[1]);
this._player&&(this.playerButton&&!this._playerItem)&&this._createContext();return this};f.prototype.setOverlay=function(a,b){!a&&!b?this.node.overlay&&(this.node.removeChild(this.node.overlay),delete this.node.overlay):(this._overlay[0]=a||"",b?this._overlay[1]=b:this._overlay.splice(1,1),this.node.overlay||this._buildOverlay(),this.node.overlay.firstLine.innerHTML=this._overlay[0],this.node.overlay.secondLine.innerHTML=this._overlay[1]||"",1<this._overlay.length?e.addClass(this.node.overlay,"sp-image-overlay-2-lines"):
e.removeClass(this.node.overlay,"sp-image-overlay-2-lines"))};f.prototype.setLink=function(a){var b=this.node;this._link=a||"";if("auto"===this._link&&!this._isCustomImage)this._item&&this._item.uri?(b.href=this._item.uri.toSpotifyLink(),b.setAttribute("data-uri",this._item.uri)):(b.href="#",b.setAttribute("data-uri",""));else{var c=0===this._link.indexOf("spotify:"),a=c?this._link.toSpotifyLink():this._link,a=this._isCustomImage?"#":a;b.href=a;b.setAttribute("data-uri",c?this._link:"")}};f.prototype.setSize=
function(a,b){this.node.style.width=a+"px";this.node.style.height=b+"px";this._width=a;this._height=b;"none"!==this._placeholder&&this.node.placeholder&&this._setPlaceholder(this._getSuitableSize("placeholder"));this.isImageInitialized&&this._player&&this._setPlayButtonSize();this.dispatchEvent("resize");return this};f.prototype._buildNode=function(){var a,b=this;this._link?(this.node=a=document.createElement("a"),this.setLink(this._link),l.addEventListener(a,"click",function(a){var c=!!b.playerButton&&
a.target===b.playerButton.node,e=this.getAttribute("data-uri");!c&&(e&&0===e.indexOf("spotify:"))&&(a.preventDefault(),a.stopPropagation(),g.application.openURI(e))})):this.node=a=document.createElement("div");this.node.setAttribute("draggable","true");this._title&&(a.title=this._title);this.setSize(this._width,this._height);e.addClass(a,"sp-image");this._animateLoaded&&e.addClass(a,"sp-image-animated");e.addClass(a,"sp-image-style-"+this._style);if("inset"===this._style||"embossed"===this._style){e.addClass(a,
"sp-image-style-rounded");var c=document.createElement("div");e.addClass(c,"sp-image-inset");a.appendChild(c)}e.addClass(a,"sp-image-hidden");this.isImageInitialized=!0;return this};f.prototype._buildPlaceholder=function(){var a=document.createElement("div");e.addClass(a,"sp-image-placeholder-visible");a.style.position="absolute";a.style.top="-9999px";document.body.appendChild(a);var b=/url\("?(.*?)"?\)/.exec(e.getStyle(a,"background-image"));document.body.removeChild(a);a=document.createElement("div");
e.addClass(a,"sp-image-placeholder");if(b&&"string"===typeof b[1]){var b=this._placeholder,c=this._isCustomImage;("empty"!==b&&!c||c&&"auto"!==b&&"empty"!==b)&&e.addClass(a,"sp-image-placeholder-visible")}this.node.appendChild(a);this.node.placeholder=a;e.addClass(a,"sp-image-placeholder-hidden")};f.prototype._buildPlayer=function(){var a=this,b=p.CustomButton.withClass("sp-image-player sp-image-player-play");this.node.appendChild(b.node);this.playerButton=b;this.isPlaying=!1;this._playButtonSizes=
{40:"xs",64:"small",128:"medium",200:"large",300:"xl"};this._setPlayButtonSize();b.addEventListener("click",function(){a._playClick()});l.addEventListener(this.node,"click",function(a){a.target===b.node&&(a.preventDefault(),a.stopPropagation())});h.addEventListener("change",function(){a._playStateChanged()});this._createContext()};f.prototype._buildOverlay=function(){var a=document.createElement("div");e.addClass(a,"sp-image-overlay");var b=document.createElement("p");b.className="sp-image-overlay-line1";
a.appendChild(b);var c=document.createElement("p");c.className="sp-image-overlay-line2";a.appendChild(c);this.node.appendChild(a);this.node.overlay=a;this.node.overlay.firstLine=b;this.node.overlay.secondLine=c};f.prototype._resetImage=function(){this.node.wrapper&&(this.node.wrapper.innerHTML="");e.removeClass(this.node,"sp-image-loaded");e.removeClass(this.node,"sp-image-hidden");this.node.placeholder&&e.removeClass(this.node.placeholder,"sp-image-placeholder-hidden");this.dispatchEvent("reset")};
f.prototype._createContext=function(){var a=this._playerItem||this._item;this.context=a instanceof g.Artist?n.forArtist(a):a;this._playStateChanged()};f.prototype._setPlayButtonSize=function(){var a,b;for(b in this._playButtonSizes){if(b>this._width)break;a=b}this._currentPlayButtonSize&&e.removeClass(this.playerButton.node,"sp-image-player-"+this._currentPlayButtonSize);a?(e.addClass(this.playerButton.node,"sp-image-player-"+this._playButtonSizes[a]),e.removeClass(this.playerButton.node,"sp-image-player-hidden"),
0<this._overlay.length&&e.addClass(this.playerButton.node,"sp-image-player-centered"),"xs"===this._playButtonSizes[a]&&!(this._item instanceof g.Track||this._playerItem instanceof g.Track)&&e.addClass(this.playerButton.node,"sp-image-player-hidden")):e.addClass(this.playerButton.node,"sp-image-player-hidden");this._currentPlayButtonSize=this._playButtonSizes[a]};f.prototype._playClick=function(){this.isPlaying?this.pause():this.play()};f.prototype._playStateChanged=function(a){h.load("playing").done(this,
function(){var b=this._item instanceof g.Track?h.track:h.context,b=b?!!(this._item&&b.uri===this._item.uri||this._link&&b.uri===this._link.toSpotifyURI()||this.context&&b.uri===this.context.uri):!1,c=!1;if(a)c=this.isPlaying?!0:!1;else if(b){if(h.playing===this.isPlaying)return;c=h.playing?!0:!1}else this.isPlaying&&(c=!1);c?(e.removeClass(this.playerButton.node,"sp-image-player-play"),e.addClass(this.playerButton.node,"sp-image-player-pause"),this.isPlaying=!0):(e.removeClass(this.playerButton.node,
"sp-image-player-pause"),e.addClass(this.playerButton.node,"sp-image-player-play"),this.isPlaying=!1)})};f.prototype.play=function(){this.isPlaying=!0;this._playStateChanged(!0);var a=this._playerItem||this._item,b=a instanceof g.Track,c=b?h.track:h.context;c&&(c.uri===a.uri||this.context&&c.uri===this.context.uri)?h.play():"function"===typeof this._getContextGroupData?(a=this._getContextGroupData(),a.group&&h.playContextGroup(a.group,a.index||0,0).fail(this,function(){this._playStateChanged(!1)})):
b?h.playTrack(a).fail(this,function(){this._playStateChanged(!1)}):this.context&&h.playContext(this.context).fail(this,function(){this._playStateChanged(!1)})};f.prototype.pause=function(){this.isPlaying=!1;this._playStateChanged(!0);h.pause()};f.prototype._buildImage=function(){if(this._isCustomImage)this._loadingStarted(),this._createImage(this._src);else{var a;a=this._item instanceof g.Album||this._item instanceof g.Track?["image","name","artists"]:["image","name"];this._loadingStarted();this._item.load(a).done(this,
function(a){var c=Math.max(this._width,this._height);(c=a.imageForSize(c))?this._createImage(c):this._resetImage();if(a.artists){for(var c=[],d=0,e=a.artists.length;d<e;d++)c.push(a.artists[d].load("name"));g.Promise.join(c).done(this,function(c){this.node.setAttribute("data-tooltip",a.name+" by "+this._getArtistsAsString(c))})}else this.node.setAttribute("data-tooltip",a.name);this.node.setAttribute("data-uri",a.uri)}).fail(this,function(){this._resetImage()})}};f.prototype._loadingStarted=function(){var a=
this;setTimeout(function(){a.isLoaded||(e.removeClass(a.node,"sp-image-hidden"),e.removeClass(a.node.placeholder,"sp-image-placeholder-hidden"))},this._acceptedLoadTime);this._startLoadTime=+new Date};f.prototype._createImage=function(a){var b=this,c=document.createElement("img"),d=document.createElement("div");e.addClass(d,"sp-image-img");c.src=a;c.onload=function(){b._onLoad(d)};c.onerror=function(){b._resetImage()};d.style.backgroundImage="url("+a+")"};f.prototype._artificialLoading=function(a){var b=
+new Date-this._startLoadTime,c=this._acceptedLoadTime;if(b>=c&&b<=c+500){var d=this;setTimeout(function(){d._startLoadTime=+new Date;d._onLoad(a)},500);return!0}return!1};f.prototype._onLoad=function(a){if(!this._artificialLoading(a)){var b=!1;if(this.hasBuiltOnce&&"wait"===this._swap){e.addClass(this.node.wrapper,"sp-image-wrapper-waiting-kill");e.removeClass(this.node,"sp-image-loaded");var b=!0,c=this.node.wrapper}var d=document.createElement("div");e.addClass(d,"sp-image-wrapper");d.appendChild(a);
var f;this.playerButton&&(f=this.playerButton.node);(a=this.node.wrapper||this.node.placeholder||f)?this.node.insertBefore(d,a):this.node.appendChild(d);this.node.wrapper=d;this.hasBuiltOnce&&"wait"===this._swap&&e.addClass(d,"sp-image-wrapper-waiting");this.isLoaded=this.hasBuiltOnce=!0;e.removeClass(this.node,"sp-image-hidden");SP.defer(this,function(){e.addClass(this.node,"sp-image-loaded");this._link&&this.setLink(this._link);this.dispatchEvent("load");this.dispatchEvent("change");if(b){var a=
this;setTimeout(function(){c.parentNode.removeChild(c);"wait"===a._swap&&e.removeClass(d,"sp-image-wrapper-waiting");e.removeClass(a.node.placeholder,"sp-image-placeholder-hidden")},this._animateLoaded?150:1)}})}};f.prototype._getSize=function(){return{width:parseInt(e.getStyle(this.node,"width"))||this._width,height:parseInt(e.getStyle(this.node,"height"))||this._height}};f.prototype._getSuitableSize=function(a){var b=this._getSize(),c,d;if("placeholder"===a){if("empty"===this._placeholder||this._isCustomImage&&
"auto"===this._placeholder)return"empty";var e=k.placeholder.images;for(c in e){a=e[c];if(a.width<b.width||a.height<b.height||void 0===a.width)break;d=c}return d?d:c}};f.prototype._setPlaceholder=function(a){var b=this._getSize(),c=this.node.placeholder;if("empty"===a||"auto"===this._placeholder&&!this._item&&!this._src)e.removeClass(c,"sp-image-placeholder-visible");else if(this._item||"auto"!==this._placeholder)if(e.addClass(c,"sp-image-placeholder-visible"),a=k.placeholder.images[a]){var d,f,h,
j;d=k.placeholder.total;f=b.width/a.width;h=b.height/a.height;j=100*(f*d.width/b.width);f=100*(f*a.x/(d.width*f-b.width));var a=100*(h*a.y/(d.height*h-b.height)),i;this._item instanceof g.Album?i="Album":this._item instanceof g.Artist?i="Artist":this._item instanceof g.Playlist?i="Playlist":this._item instanceof g.Profile?i="User":this._item instanceof g.Track?i="Track":this._item instanceof g.User&&(i="User");a+=100*(d.height/d.numTypes*k.placeholder.offsets["auto"===this._placeholder?i:this._placeholderType]*
h/(d.height*h-b.height));c.style.backgroundSize=j+"% "+j*(d.height/d.width)+"%";c.style.backgroundPosition=f+"% "+a+"%"}};f.prototype._addDragHandler=function(){if(!f.sp_isDndAddedForImages){f.sp_isDndAddedForImages=!0;var a=this;m.drag.addHandler(function(b){if(a._isElementInAnyImage(b)){var c=a._getImageNodeFromElement(b),b=!!c.getAttribute("data-uri"),c=!!c.getAttribute("data-tooltip");return b&&c}return!1},function(b){var c=a._getImageNodeFromElement(b),b=c.getAttribute("data-uri"),c=c.getAttribute("data-tooltip"),
b=[b.toSpotifyURL()];return{"text/plain":b,"text/html":['<a href="'+b[0]+'">'+c+"</a>"]}},function(b){return a._getImageNodeFromElement(b).getAttribute("data-tooltip")})}};f.prototype._addContextUIHandler=function(){var a=this;this.node.oncontextmenu=function(b){var c="a"===b.target.tagName.toLowerCase(),d="a"===this.tagName.toLowerCase();if(c||d){if(d=c?b.target:this,c=(c=d.getAttribute("data-uri"))||d.href,d=SpotifyApi.Exps.http,c.match(SpotifyApi.Exps.spotify)||c.match(d))if(c=g.fromURI(c))return d=
b.pageX-window.pageXOffset,b=b.pageY-window.pageYOffset,g.client.showContextUI(c,{x:d,y:b}),!1}else if(a._item)return d=b.pageX-window.pageXOffset,b=b.pageY-window.pageYOffset,g.client.showContextUI(a._item,{x:d,y:b}),!1}};f.prototype._isElementInAnyImage=function(a){return this._getImageNodeFromElement(a)!==document.documentElement?!0:!1};f.prototype._getImageNodeFromElement=function(a){for(;!e.hasClass(a,"sp-image")&&a!==document;)a=a.parentNode;return a!==document?a:document.documentElement};f.prototype._getArtistsAsString=
function(a){for(var b="",c=0,d=a.length;c<d;c++)b+=a[c].name+(c<d-1?", ":"");return b};var k={placeholder:{images:{1:{x:0,y:0,width:300,height:300},2:{x:300,y:0,width:150,height:150},3:{x:450,y:0,width:128,height:128},4:{x:300,y:150,width:64,height:64},5:{x:300,y:214,width:40,height:40},empty:{}},total:{width:578,height:1500,numTypes:5},offsets:{Album:0,Artist:1,Playlist:2,Track:3,User:4}}},j=document.createElement("div");j.className="sp-image-preloader";document.body.appendChild(j);setTimeout(function(){document.body.removeChild(j)},
5E3)});
