require("$api/models $api/toplists#Toplist $views/utils/css $views/utils/dom $views/utils/dnd $views/buttons".split(" "),function(f,s,c,n,q,r){function e(a,b){b=b||{};this._title=b.title;this._link=b.link||"";this._animateLoaded=void 0===b.animate?!0:b.animate;this._placeholder=void 0===b.placeholder?"auto":b.placeholder;this._player=!!b.player;this._quickActionMenu=void 0===b.quickActionMenu?"auto":b.quickActionMenu;this._playerItem=b.playerItem;this._swap="immediate"===b.swap?"immediate":"wait";
this._overlay=void 0===b.overlay?[]:b.overlay;this._playerCentered=b.playerCentered||!1;this._style=~["plain","inset","rounded","embossed"].indexOf(b.style)?b.style:"inset";this._getContextGroupData=b.getContextGroupData;this._acceptedLoadTime=200;this._width=b.width||b.height||200;this._height=b.height||b.width||200;var d={artist:"Artist",album:"Album",track:"Track",playlist:"Playlist",user:"User"};!~" auto none empty ".indexOf(" "+this._placeholder+" ")&&!(this._placeholder in d)&&(this._placeholder=
"auto");this._placeholderType=d[this._placeholder]||"auto";this._buildNode();this._isCustomImage=a?"string"===typeof a?!0:!1:!0;"none"!==this._placeholder&&this._buildPlaceholder();void 0!==a?this.setImage(a):"none"!==this._placeholder&&this._setPlaceholder(this._getSuitableSize("placeholder"));this._player&&this._buildPlayer();this._player&&this._playStateChanged(void 0,void 0,!0);this._link&&this.setLink(this._link);q.drag.hasDragSupport&&this._addDragHandler();var g=this;f.session.load("device").done(function(){"desktop"===
f.session.device&&g._addContextUIHandler()})}exports.Image=e;var h=f.player,t=f.Observable,l;f.session.load("device").done(function(){l=f.session.device}).fail(function(){l="unknown"});SP.inherit(e,t);e.forAlbum=function(a,b){if(!(a instanceof f.Album))throw Error("The type of the object is not Album");return new e(a,b)};e.forArtist=function(a,b){if(!(a instanceof f.Artist))throw Error("The type of the object is not Artist");return new e(a,b)};e.forPlaylist=function(a,b){if(!(a instanceof f.Playlist))throw Error("The type of the object is not Playlist");
return new e(a,b)};e.forTrack=function(a,b){if(!(a instanceof f.Track))throw Error("The type of the object is not Track");return new e(a,b)};e.forUser=function(a,b){if(!(a instanceof f.User))throw Error("The type of the object is not User");return new e(a,b)};e.forProfile=function(a,b){if(!(a instanceof f.Profile))throw Error("The type of the object is not Profile");return new e(a,b)};e.fromSource=function(a,b){if("string"!==typeof a)throw Error("The source path you pass in must be a string.");return new e(a,
b)};e.availableOptions={};e.prototype.setImage=function(a){var b=this;this.isLoaded=!1;if(this._isCustomImage="string"===typeof a)this._item=null,this._src=a;else{var d=this._item instanceof f.Track,g=this._item instanceof f.Playlist;if(this._item&&(d||g))this._item.removeEventListener("change:image",this._changeEventHandler),this._changeEventHandler=null;this._src=null;this._item=a;d=a instanceof f.Playlist;if(a instanceof f.Track||d)b=this,a.load("image").done(function(){b._changeEventHandler=function(){b._resetImage();
b._buildImage()};a.addEventListener("change:image",b._changeEventHandler)})}"none"!==this._placeholder&&this._setPlaceholder(this._getSuitableSize("placeholder"));"immediate"===this._swap&&this._resetImage();this.setDraggable();this._buildImage();!this.node.overlay&&0<this._overlay.length&&this.setOverlay(this._overlay[0],this._overlay[1]);this._player&&(this.playerButton&&!this._playerItem)&&this._createContext();d=(this._item instanceof f.Track||this._item instanceof f.Album)&&64<this._getSize().width;
if(!0===this._quickActionMenu||"auto"==this._quickActionMenu&&d){var c=!1;f.client.load("features").done(function(d){!c&&d.features.collection&&(c=!0,b._buildQuickActionButtons(a))});f.session.load("device").done(function(d){!c&&"web"===d.device&&(c=!0,b._buildQuickActionButtons(a))})}return this};e.prototype.setOverlay=function(a,b){!a&&!b?this.node.overlay&&(this.node.removeChild(this.node.overlay),delete this.node.overlay):(this._overlay[0]=a||"",b?this._overlay[1]=b:this._overlay.splice(1,1),
this.node.overlay||this._buildOverlay(),this.node.overlay.firstLine.innerHTML=this._overlay[0],this.node.overlay.secondLine.innerHTML=this._overlay[1]||"",1<this._overlay.length?c.addClass(this.node.overlay,"sp-image-overlay-2-lines"):c.removeClass(this.node.overlay,"sp-image-overlay-2-lines"))};e.prototype.setLink=function(a){var b=this.node;this._link=a||"";if("auto"===this._link&&!this._isCustomImage)this._item&&this._item.uri?(b.href=this._item.uri.toSpotifyLink(),b.setAttribute("data-uri",this._item.uri)):
(b.href="#",b.setAttribute("data-uri",""));else{var d=0===this._link.indexOf("spotify:"),a=d?this._link.toSpotifyLink():this._link,a=this._isCustomImage?"#":a;b.href=a;b.setAttribute("data-uri",d?this._link:"")}};e.prototype.setSize=function(a,b){this.node.style.width=a+"px";this.node.style.height=b+"px";this._width=a;this._height=b;"none"!==this._placeholder&&this.node.placeholder&&this._setPlaceholder(this._getSuitableSize("placeholder"));this.isImageInitialized&&this._player&&this._setPlayButtonSize();
this.dispatchEvent("resize");return this};e.prototype.setDraggable=function(a){(void 0!==a?a:!this._isCustomImage||this._playerItem)?(this.node.setAttribute("draggable","true"),c.removeClass(this.node,"sp-image-disable-dnd")):(this.node.setAttribute("draggable","false"),c.addClass(this.node,"sp-image-disable-dnd"))};e.prototype._buildNode=function(){var a,b=this;this._link?(this.node=a=document.createElement("a"),this.setLink(this._link),n.addEventListener(a,"click",function(a){var d=a.target;do if("a"===
d.nodeName.toLowerCase())break;while((d=d.parentNode)&&d!==document.body);var c=d.getAttribute("data-uri");if(!c){c=d.getAttribute("href");if(!c)return;c=c.toSpotifyURI()}c&&0===c.indexOf("spotify:")&&(a.preventDefault(),a.stopPropagation(),f.application.openURI(c),b.dispatchEvent({type:"link-click",uri:c,targetElement:d}))})):this.node=a=document.createElement("div");this._title&&(a.title=this._title);this.setSize(this._width,this._height);c.addClass(a,"sp-image");this._animateLoaded&&c.addClass(a,
"sp-image-animated");c.addClass(a,"sp-image-style-"+this._style);if("inset"===this._style||"embossed"===this._style){c.addClass(a,"sp-image-style-rounded");var d=document.createElement("div");c.addClass(d,"sp-image-inset");a.appendChild(d)}c.addClass(a,"sp-image-hidden");this.isImageInitialized=!0;return this};e.prototype._buildPlaceholder=function(){var a=document.createElement("div");c.addClass(a,"sp-image-placeholder-visible");a.style.position="absolute";a.style.top="-9999px";document.body.appendChild(a);
var b=/url\("?(.*?)"?\)/.exec(c.getStyle(a,"background-image"));document.body.removeChild(a);a=document.createElement("div");c.addClass(a,"sp-image-placeholder");if(b&&"string"===typeof b[1]){var b=this._placeholder,d=this._isCustomImage;("empty"!==b&&!d||d&&"auto"!==b&&"empty"!==b)&&c.addClass(a,"sp-image-placeholder-visible")}this.node.appendChild(a);this.node.placeholder=a;c.addClass(a,"sp-image-placeholder-hidden")};e.prototype._buildPlayer=function(){var a=this,b=r.CustomButton.withClass("sp-image-player");
this.node.appendChild(b.node);this.playerButton=b;this.isPlaying=void 0;this._playButtonSizes={40:"xs",64:"small",128:"medium",200:"large",300:"xl"};this._setPlayButtonSize();b.addEventListener("click",function(){a._playClick()});n.addEventListener(this.playerButton.node,"click",function(a){a.preventDefault();a.stopPropagation()});h.addEventListener("change",function(){a._blockNextChangeEvent||a._playStateChanged();a._blockNextChangeEvent=!1});this._createContext()};e.prototype._buildOverlay=function(){var a=
document.createElement("div");c.addClass(a,"sp-image-overlay");var b=document.createElement("p");b.className="sp-image-overlay-line1";a.appendChild(b);var d=document.createElement("p");d.className="sp-image-overlay-line2";a.appendChild(d);this.node.appendChild(a);this.node.overlay=a;this.node.overlay.firstLine=b;this.node.overlay.secondLine=d};e.prototype._buildQuickActionButtons=function(a){a=r.QuickActionButtons.forItem(a);n.addEventListener(a.node,"click",function(a){a.preventDefault();a.stopPropagation()});
this.node.appendChild(a.node)};e.prototype._resetImage=function(){this.node.wrapper&&(this.node.wrapper.innerHTML="");c.removeClass(this.node,"sp-image-loaded");c.removeClass(this.node,"sp-image-hidden");this.node.placeholder&&c.removeClass(this.node.placeholder,"sp-image-placeholder-hidden");this.dispatchEvent("reset")};e.prototype._createContext=function(){var a=this._playerItem||this._item;this.context=a instanceof f.Artist?s.forArtist(a):a;this._playStateChanged(void 0,void 0,!0)};e.prototype._setPlayButtonSize=
function(){if(l){var a,b;for(b in this._playButtonSizes){if(b>this._width)break;a=b}this._currentPlayButtonSize&&c.removeClass(this.playerButton.node,"sp-image-player-"+this._currentPlayButtonSize);a?(b=this._playButtonSizes[a],"mobile"===l&&(b="medium"),c.addClass(this.playerButton.node,"sp-image-player-"+b),c.removeClass(this.playerButton.node,"sp-image-player-hidden"),(0<this._overlay.length||this._playerCentered)&&c.addClass(this.playerButton.node,"sp-image-player-centered"),"xs"===this._playButtonSizes[a]&&
!(this._item instanceof f.Track||this._playerItem instanceof f.Track)&&c.addClass(this.playerButton.node,"sp-image-player-hidden")):c.addClass(this.playerButton.node,"sp-image-player-hidden");this._currentPlayButtonSize=this._playButtonSizes[a]}else{var d=this;setTimeout(function(){d._setPlayButtonSize()},10)}};e.prototype._playClick=function(){this.isPlaying?this.pause():this.play()};e.prototype._playStateChanged=function(a,b,d){var g=function(){var g=a&&b||h.playing,e=this._item instanceof f.Track?
h.track:h.context,k=e?!!(this._item&&e.uri===this._item.uri||this._link&&e.uri===this._link.toSpotifyURI()||this.context&&e.uri===this.context.uri):!1,e=!1;if(a)e=g?!0:!1;else if(k){if(g===this.isPlaying)return;e=g?!0:!1}else this.isPlaying&&(e=!1);g=this.playerButton.node;e?(c.removeClass(g,"sp-image-player-play"),c.addClass(g,"sp-image-player-pause"),!d&&!this.isPlaying&&(c.addClass(g,"sp-image-player-animation"),c.removeClass(g,"sp-image-player-play-animation"),c.addClass(g,"sp-image-player-pause-animation")),
this.isPlaying=!0):(c.removeClass(g,"sp-image-player-pause"),c.addClass(g,"sp-image-player-play"),!d&&this.isPlaying&&(c.addClass(g,"sp-image-player-animation"),c.removeClass(g,"sp-image-player-pause-animation"),c.addClass(g,"sp-image-player-play-animation")),this.isPlaying=!1)};a&&g.call(this);h.load("playing").done(this,g)};e.prototype.play=function(){this._blockNextChangeEvent=!0;this._playStateChanged(!0,!0);var a=this._playerItem||this._item,b=a instanceof f.Track,d=b?h.track:h.context;d&&(d.uri===
a.uri||this.context&&d.uri===this.context.uri)?h.play():"function"===typeof this._getContextGroupData?(a=this._getContextGroupData(),a.group&&h.playContextGroup(a.group,a.index||0,0).fail(this,function(){this._playStateChanged(!1)})):b?h.playTrack(a).fail(this,function(){this._playStateChanged(!1)}):this.context&&h.playContext(this.context).fail(this,function(){this._playStateChanged(!1)});this.dispatchEvent("play-click")};e.prototype.pause=function(){this._playStateChanged(!0,!1);h.pause();this.dispatchEvent("pause-click")};
e.prototype._buildImage=function(){if(this._isCustomImage){if(this._loadingStarted(),this._createImage(this._src),this._playerItem){var a=this;this._playerItem.load("name").done(function(b){var g;if(!(g=b.name))g=-1<b.uri.indexOf(":starred")?"Starred":-1<b.uri.indexOf(":toplist")?"Top Tracks":void 0;(b=g)?a.node.setAttribute("data-tooltip",b):a.setDraggable(!1)})}}else{var b;b=this._item instanceof f.Album||this._item instanceof f.Track?["image","name","artists"]:["image","name"];this._loadingStarted();
this._item.load(b).done(this,function(a){var b=Math.max(this._width,this._height);(b=a.imageForSize(b))?this._createImage(b):this._resetImage();if(a.artists){for(var b=[],c=0,e=a.artists.length;c<e;c++)b.push(a.artists[c].load("name"));f.Promise.join(b).done(this,function(b){this.node.setAttribute("data-tooltip",a.name+" by "+this._getArtistsAsString(b))})}else this.node.setAttribute("data-tooltip",a.name);this.node.setAttribute("data-uri",a.uri)}).fail(this,function(){this._resetImage()})}};e.prototype._loadingStarted=
function(){var a=this;setTimeout(function(){a.isLoaded||(c.removeClass(a.node,"sp-image-hidden"),c.removeClass(a.node.placeholder,"sp-image-placeholder-hidden"))},this._acceptedLoadTime);this._startLoadTime=+new Date};e.prototype._createImage=function(a){var b=this,d=document.createElement("img"),g=document.createElement("div");c.addClass(g,"sp-image-img");d.src=a;d.onload=function(){b._onLoad(g)};d.onerror=function(){b._resetImage()};g.style.backgroundImage="url("+a+")"};e.prototype._artificialLoading=
function(a){var b=+new Date-this._startLoadTime,d=this._acceptedLoadTime;if(b>=d&&b<=d+500){var c=this;setTimeout(function(){c._startLoadTime=+new Date;c._onLoad(a)},500);return!0}return!1};e.prototype._onLoad=function(a){if(!this._artificialLoading(a)){var b=!1;if(this.hasBuiltOnce&&"wait"===this._swap){c.addClass(this.node.wrapper,"sp-image-wrapper-waiting-kill");c.removeClass(this.node,"sp-image-loaded");var b=!0,d=this.node.wrapper}var g=document.createElement("div");c.addClass(g,"sp-image-wrapper");
g.appendChild(a);var e;this.playerButton&&(e=this.playerButton.node);(a=this.node.wrapper||this.node.placeholder||e)?this.node.insertBefore(g,a):this.node.appendChild(g);this.node.wrapper=g;this.hasBuiltOnce&&"wait"===this._swap&&c.addClass(g,"sp-image-wrapper-waiting");this.isLoaded=this.hasBuiltOnce=!0;c.removeClass(this.node,"sp-image-hidden");SP.defer(this,function(){c.addClass(this.node,"sp-image-loaded");this._link&&this.setLink(this._link);this.dispatchEvent("load");this.dispatchEvent("change");
if(b){var a=this;setTimeout(function(){d.parentNode.removeChild(d);"wait"===a._swap&&c.removeClass(g,"sp-image-wrapper-waiting");c.removeClass(a.node.placeholder,"sp-image-placeholder-hidden")},this._animateLoaded?150:1)}})}};e.prototype._getSize=function(){return{width:parseInt(c.getStyle(this.node,"width"))||this._width,height:parseInt(c.getStyle(this.node,"height"))||this._height}};e.prototype._getSuitableSize=function(a){var b=this._getSize(),d,c;if("placeholder"===a){if("empty"===this._placeholder||
this._isCustomImage&&"auto"===this._placeholder)return"empty";var e=m.placeholder.images;for(d in e){a=e[d];if(a.width<b.width||a.height<b.height||void 0===a.width)break;c=d}return c?c:d}};e.prototype._setPlaceholder=function(a){var b=this._getSize(),d=this.node.placeholder;if("empty"===a||"auto"===this._placeholder&&!this._item&&!this._src)c.removeClass(d,"sp-image-placeholder-visible");else if(this._item||"auto"!==this._placeholder)if(c.addClass(d,"sp-image-placeholder-visible"),a=m.placeholder.images[a]){var e,
h,j,k;e=m.placeholder.total;h=b.width/a.width;j=b.height/a.height;k=100*(h*e.width/b.width);h=100*(h*a.x/(e.width*h-b.width));var a=100*(j*a.y/(e.height*j-b.height)),i;this._item instanceof f.Album?i="Album":this._item instanceof f.Artist?i="Artist":this._item instanceof f.Playlist?i="Playlist":this._item instanceof f.Profile?i="User":this._item instanceof f.Track?i="Track":this._item instanceof f.User&&(i="User");a+=100*(e.height/e.numTypes*m.placeholder.offsets["auto"===this._placeholder?i:this._placeholderType]*
j/(e.height*j-b.height));d.style.backgroundSize=k+"% "+k*(e.height/e.width)+"%";d.style.backgroundPosition=h+"% "+a+"%"}};e.prototype._addDragHandler=function(){if(!e.sp_isDndAddedForImages){e.sp_isDndAddedForImages=!0;var a=this;q.drag.addHandler(function(b){if(a._isElementInAnyImage(b)){var d=a._getImageNodeFromElement(b),b=!!d.getAttribute("data-uri"),d=!!d.getAttribute("data-tooltip");return b&&d}return!1},function(b){var d=a._getImageNodeFromElement(b),b=d.getAttribute("data-uri"),d=d.getAttribute("data-tooltip"),
b=[b.toSpotifyURL()];return{"text/plain":b,"text/html":['<a href="'+b[0]+'">'+d+"</a>"]}},function(b){return a._getImageNodeFromElement(b).getAttribute("data-tooltip")})}};e.prototype._addContextUIHandler=function(){var a=this;this.node.oncontextmenu=function(b){var d="a"===b.target.tagName.toLowerCase(),c="a"===this.tagName.toLowerCase();if(d||c){if(c=d?b.target:this,d=(d=c.getAttribute("data-uri"))||c.href,c=SpotifyApi.Exps.http,d.match(SpotifyApi.Exps.spotify)||d.match(c))if(d=f.fromURI(d))return c=
b.pageX-window.pageXOffset,b=b.pageY-window.pageYOffset,f.client.showContextUI(d,{x:c,y:b}),!1}else if(a._item)return c=b.pageX-window.pageXOffset,b=b.pageY-window.pageYOffset,f.client.showContextUI(a._item,{x:c,y:b}),!1}};e.prototype._isElementInAnyImage=function(a){return this._getImageNodeFromElement(a)!==document.documentElement?!0:!1};e.prototype._getImageNodeFromElement=function(a){for(;!c.hasClass(a,"sp-image")&&a!==document;)a=a.parentNode;return a!==document?a:document.documentElement};e.prototype._getArtistsAsString=
function(a){for(var b="",c=0,e=a.length;c<e;c++)b+=a[c].name+(c<e-1?", ":"");return b};var m={placeholder:{images:{1:{x:0,y:0,width:300,height:300},2:{x:300,y:0,width:150,height:150},3:{x:450,y:0,width:128,height:128},4:{x:300,y:150,width:64,height:64},5:{x:300,y:214,width:40,height:40},empty:{}},total:{width:578,height:1500,numTypes:5},offsets:{Album:0,Artist:1,Playlist:2,Track:3,User:4}}},p=document.createElement("div");p.className="sp-image-preloader";document.body.appendChild(p);setTimeout(function(){document.body.removeChild(p)},
5E3)});
