require("$api/models $views/utils/css $views/utils/dom $views/list/model#ListModel $views/list/view#ListView $views/throbber#Throbber".split(" "),function(g,r,k,s,m,t){function e(a,b){var c=a instanceof g.Collection;this.eventHandlers=[];this.listIndex=0;this._parseOptions(b);c?(this.item=a,this._init(a)):this._loadItem(a)}function q(a,b){for(var c in b)a[c]=b[c];return a}exports.List=e;SP.inherit(e,g.Observable);e.forCollection=function(a,b){return new e(a,b)};e.forAlbum=function(a,b){return new e(a,
b)};e.forDisc=function(a,b){return new e(a,b)};e.forPlaylist=function(a,b){return new e(a,b)};e.availableOptions={};e.prototype.init=function(){function a(){b.initialized=!0;b.dispatchEvent("initialized");b.parentList&&(b.parentList.numDiscsInitialized++,b.parentList.numDiscsInitialized===b.parentList.numDiscs&&b.parentList.dispatchEvent("initialized"))}if(!this.destroyed)if(this.isDiscsList)this._callForEachList("init"),this.initialized=!0;else{var b=this;if((!this.view||!this.model||"tracks"===
this.type&&!this.model.context)&&50>(this.numInitTries||0))setTimeout(function(){b.numInitTries=(b.numInitTries||0)+1;b.init()},100);else if(50<=this.numInitTries)this.numInitTries=0;else{this.numInitTries=0;this.view.addedToDOM();this.throbber||this._createThrobber();var c=null;this.isPartOfDiscsList?(this.isAlbumItem=this.parentList.item instanceof g.Album,c=this.parentList.item):(this.isAlbumItem=this.item instanceof g.Album,c=this.item);this.isAlbumItem?c.load("artists").done(function(c){b.albumArtists=
b._getArtistsURIString(c.artists);a()}).fail(function(){a()}):a()}}};e.prototype.more=function(){};e.prototype.playTrack=function(a,b){if(!this.destroyed){var c=[],d;if(this.isPartOfDiscsList||this.isDiscsList){d=this.isPartOfDiscsList?this.parentList.lists:this.lists;if(b>d.length-1)return;for(var f=0,e=d.length;f<e;f++)c=c.concat(d[f].model.items),void 0!==b&&f<b&&(a+=d[f].length);d=this.isPartOfDiscsList?this.model:this.lists[0].model}else d=this.model,c=d.items;c=c[a];this.isTrackList&&(c&&c instanceof
g.Track)&&(this.contextGroup?(g.player.playContextGroup(this.contextGroup,this._indexInContextGroup,a),d.contextHasUpdates=!1):d.context?(g.player.playContext(d.context,a),d.contextHasUpdates=!1):g.player.playTrack(c),this.dispatchEvent("play"))}};e.prototype.setItem=function(a,b){if(!this.destroyed){var c=this,d=a instanceof g.Collection;b&&(this.options.context=b);!this.lists&&d?(this.model.setCollection(a),this.dispatchEvent({type:"set-item",item:a}),this._resetContextGroup(),this.refresh()):(this.lists&&
this._callForEachList("destroy"),this.destroy(),this.addEventListener("list-init",function j(){c.removeEventListener("list-init",j);c.dispatchEvent({type:"set-item",item:a});this._resetContextGroup();c._oldParentNode&&c._oldParentNode.appendChild(c.node);this.init()}),d?this._init(a):this._loadItem(a),this.destroyed=!1)}};e.prototype.setCollection=function(a){this.destroyed||(this.setItem(a),this.dispatchEvent({type:"set-collection",collection:a}))};e.prototype.setContext=function(a){if(!this.destroyed){if(this.lists)for(var b=
0,c=this.lists.length;b<c;b++)this.lists[b].model.context=a,this.lists[b].options.context=a;else this.model.context=a,this.options.context=a;this.dispatchEvent({type:"set-context",context:a})}};e.prototype.refresh=function(){if(!this.destroyed){this.clear();for(var a=this.lists||[this],b=0,c=a.length;b<c;b++)a[b].view.setFixedHeight(),a[b].throbber&&(a[b].throbber.show(),"show-content"===a[b].options.throbber&&a[b].throbber.showContent()),a[b].view.setupItemFetching(),a[b].dispatchEvent("refresh");
this.lists&&this.dispatchEvent("refresh")}};e.prototype.clear=function(){if(!this.destroyed){for(var a=this.lists||[this],b=0,c=a.length;b<c;b++)a[b].model.reset(),a[b].view.reset(),a[b].dispatchEvent("clear");this.lists&&this.dispatchEvent("clear")}};e.prototype.destroy=function(){if(!this.destroyed){this.view&&this.view.removeDndHandlers();this.view&&this.view.scrollAgent&&this.view.scrollAgent.destroy();this.node.parentNode&&(this._oldParentNode=this.node.parentNode,this.node.parentNode.removeChild(this.node));
if(this.eventHandlers)for(var a=0,b=this.eventHandlers.length,c;a<b;a++)c=this.eventHandlers[a],c.dom?k.removeEventListener(c.obj,c.type,c.handler):c.obj&&c.obj.removeEventListener&&c.obj.removeEventListener(c.type,c.handler);a=this.node.getAttribute("data-connected-lists-index");if(a=m.listViewConnectedContainerArray[a])b=a.indexOf(this),-1<b&&a.splice(b,1);this.view&&(this.view.nodes.tableBody.oncontextmenu=null);delete this.lists;delete this.node;delete this.model;delete this.view;delete this.eventHandlers;
delete this.length;delete this.isDiscsList;delete this.isPartOfDiscsList;delete this.isDisc;delete this.discNumber;delete this.throbber;this.destroyed=!0;this.initialized=!1;this.dispatchEvent("destroyed")}};e.prototype.connect=function(a){if(!this.destroyed){this.nextList=a;a.previousList=this;for(var b=this.lists?this.lists[this.lists.length-1]:this,c=!1,d=a.lists||[a],f=b.listIndex,e,h,n,g,i=0,u=d.length;i<u;i++)if(d[i].view.removeDndHandlers(),b.view.selection.addList(d[i]),d[i].view.selection=
b.view.selection,f++,d[i].listIndex=f,void 0!==d[i]._connectedListsIndex||!c&&void 0!==a._connectedListsIndex){var l=d[i];void 0===d[i]._connectedListsIndex&&void 0!==a._connectedListsIndex&&(c=!0,l=a);e=m.listViewConnectedContainerArray;h=e[l._connectedListsIndex];n=h.indexOf(l);g=h.indexOf(this);if(-1===g&&-1<n){h.splice(n,1);d[i].view.listViewDocMouseDownHandler&&k.removeEventListener(document,"mousedown",d[i].view.listViewDocMouseDownHandler);h=0;for(n=e.length;h<n;h++)if(g=e[h].indexOf(this),
-1<g){e[h].push(l);l._connectedListsIndex=h;l.node.setAttribute("data-connected-lists-index",h);break}}}if(!this.isPartOfDiscsList){var p=this;if(!this.initialized&&50>(this.numConnectTries||0)){setTimeout(function(){p.numConnectTries=(p.numConnectTries||0)+1;p.connect(a)},100);return}if(50<=this.numConnectTries){this.numConnectTries=0;return}this.numConnectTries=0;this._inContextGroup||this._addToContextGroup(this);this._addToContextGroup(a)}return this}};e.prototype.focus=function(){this.destroyed||
(this.isDiscsList?this.lists[0].view.focus():this.view.focus())};e.prototype.blur=function(){this.destroyed||(this.isDiscsList?this._callForEachList("blur"):this.view.blur())};e.prototype.selectItem=function(a){if(!this.destroyed)if(this.isDiscsList){for(var b=0,c=this.lists,d,e=0;a>=b&&c[e];)d=c[e],b+=d.length,e++;a-=b-d.length;d.view.selection.add(a,d.listIndex);d.view.selection.setOrigin(a,d.listIndex)}else this.view.selection.add(a,this.listIndex),this.view.selection.setOrigin(a,this.listIndex)};
e.prototype.deselect=function(a){this.destroyed||(a&&this.isDiscsList?this.lists[0].view.deselect(a):this.isDiscsList?this._callForEachList("deselect"):this.view.deselect(a))};e.prototype.getSelection=function(a){var a=a||{},b=this;this.lists&&0<this.lists.length&&(b=this.lists[0]);return b.view.selection.getSelectionData(a.onlyThisList?this.listIndex:void 0)};e.prototype._parseOptions=function(a){var b={type:"tracks",layout:"default",height:"dynamic",header:"fixed",numBuckets:3,fetch:"scroll",unplayable:"disabled",
style:"plain",visualOffset:0,throbber:"none"};a&&"hidden"===a.unplayable&&(a.unplayable=b.unplayable);a&&a.parentList&&(this.parentList=a.parentList,this.parentList.lists||(this.parentList.lists=[this]),delete a.parentList);var c=q({},a),d;for(d in b)c[d]=void 0===c[d]?b[d]:c[d];this.options=c;this._originalOptions=a;this.layout=~["default","toplist"].indexOf(c.layout)?c.layout:"default";this.type=~["tracks","artists","albums"].indexOf(c.type)?c.type:"tracks";this.isTrackList="tracks"===this.type;
this.options.header="toplist"===this.layout?"no":this.options.header};e.prototype._init=function(a){function b(a){e.view.createItems(a.start,a.end,function(b){e.view.onInsertRowsCreated(a.start,a.end,b)})}function c(a){e.view.removeItems(a.start,a.end)}function d(){e.view.addFields()}var e=this;this.eventHandlers=[];this.length=0;this.isDiscsList=!1;if(this.isDisc=(this.isPartOfDiscsList=!!this.options.isDisc)||"Disc"===a.className)this.discNumber=this.options.discNumber;this.options.context||(this.options.context=
this.item);this.model=new s(a,this);this.view=new m(this);this.node=this.view.node;this.eventHandlers.push({type:"insert",handler:b,obj:this,dom:!1});this.addEventListener("insert",b);this.eventHandlers.push({type:"remove",handler:c,obj:this,dom:!1});this.addEventListener("remove",c);this.eventHandlers.push({type:"fields-loaded",handler:d,obj:this,dom:!1});this.addEventListener("fields-loaded",d);this.model.init();this.view.init();this.dispatchEvent({type:"list-init",from:"init"})};e.prototype._loadItem=
function(a){var b=this,c=a instanceof g.Album;this.item=a;!this.node&&!this._oldParentNode&&(this.node=document.createElement("div"),this.node.className="sp-list");c?a.load("discs").done(function(){var c=a.discs,e=c.length;if(1===e)c[0].load("tracks").done(function(a){a.tracks.className="Album";b._init(a.tracks)});else{for(var j=[],h=0;h<e;h++)j.push(c[h].load("tracks"));g.Promise.join(j).done(function(){b._createDiscs(c)})}}):a.load("tracks").done(function(){var c;a instanceof g.Disc?c="Disc":a instanceof
g.Playlist&&(c="Playlist");a.tracks.className=c;b._init(a.tracks)})};e.prototype._createDiscs=function(a){if(!this.destroyed){var b=document.createElement("div");b.className="sp-list sp-list-discs-wrapper";for(var c,d=[],f=0,g=a.length;f<g;f++)c=q({},this._originalOptions),c.context=this.options.context,c.isDisc=!0,c.discNumber=f+1,c.parentList=this,a[f].tracks.className="Disc",d[f]=new e(a[f].tracks,c),b.appendChild(d[f].node),r.addClass(d[f].node,"sp-list-album-disc"),d[f-1]&&d[f-1].connect(d[f]);
this.numDiscsInitialized=0;this.numDiscs=a.length;this.node&&(a=this.node.getAttribute("data-connected-lists-index"))&&b.setAttribute("data-connected-lists-index",a);this.node&&this.node.parentNode&&this.node.parentNode.replaceChild(b,this.node);this.node=b;this.isDiscsList=!0;this.lists=d;this.dispatchEvent({type:"list-init",from:"createDiscs"})}};e.prototype._createThrobber=function(){function a(){"toplist"===e.layout?setTimeout(function(){d.hide()},50):d.hide()}function b(){d.setPosition()}var c=
this.options.throbber;if("none"!==c){var d=t.forElement(this.node,50);this.throbber=d;"show-content"===c&&d.showContent();var e=this;this.eventHandlers.push({type:"initial-snapshots-load",handler:a,obj:this,dom:!1});this.addEventListener("initial-snapshots-load",a);this.eventHandlers.push({type:"resize",handler:b,obj:window,dom:!0});k.addEventListener(window,"resize",b)}};e.prototype._addToContextGroup=function(a){if(!this.destroyed)if(this.contextGroup){var b=a.lists?a.lists.concat([a]):[a],c=a.lists?
a.lists[0].model.context:a.model.context,a=++this.contextGroup.indexCounter;this.contextGroup.contexts.add(c);for(var d=0,e=b.length;d<e;d++)c=b[d],c.contextGroup=this.contextGroup,c._indexInContextGroup=a,c._inContextGroup=!0}else if(!1===this.contextGroup)a.contextGroup=!1,a._waitingLists=this._waitingLists,!a._inContextGroup&&!~this._waitingLists.indexOf(a)&&this._waitingLists.push(a);else{this._waitingLists=[a];a._waitingLists=this._waitingLists;this.contextGroup=!1;a.contextGroup=!1;var b=(new Date).getTime(),
j=this;g.Group.create("tmp_contextgroup_"+b).done(function(a){j.contextGroup=a;j.contextGroup.indexCounter=-1;for(var b=j._waitingLists,c,d,e,f=0,g=b.length;f<g;f++)if(void 0!==b[f]){e=b[f].lists?b[f].lists.concat([b[f]]):[b[f]];c=b[f].lists?b[f].lists[0].model.context:b[f].model.context;d=++j.contextGroup.indexCounter;a.contexts.add(c);for(var k=0,m=e.length;k<m;k++)c=e[k],c._indexInContextGroup=d,c.contextGroup=a,c._inContextGroup=!0}j._waitingLists.length=0})}};e.prototype._resetContextGroup=function(){if(!this.destroyed&&
this.contextGroup){var a;a=this.lists?this.lists[0].model.getListChain(!0):this.model.getListChain(!0);for(var b=0,c=a.length;b<c;b++)delete a[b].contextGroup,delete a[b]._indexInContextGroup,delete a[b]._inContextGroup,0<b?a[b-1]._addToContextGroup(a[b]):a[0]._addToContextGroup(a[0])}};e.prototype._callForEachList=function(a,b){if(this.isDiscsList)for(var b=b||[],c=this.lists,d,e,g=0,h=c.length;g<h;g++)d=c[g],e=d[a],"function"===typeof e&&e.apply(d,b)};e.prototype._dispatchEvent=function(a){this.dispatchEvent(a);
this.parentList&&this.parentList.dispatchEvent(a)};e.prototype._getArtistsURIString=function(a){for(var b=[],c=0,d=a.length;c<d;c++)b.push(a[c].uri);return b.join(" ")}});
