function Popup(a,c,b){this.width=a;this.height=c;this.cssClass=b?"sp-popup "+b:"sp-popup"}Popup.withContent=function(a,c,b,d){c=new Popup(c,b,d);c.setContent(a);return c};Popup.withText=function(a,c){var b=new Popup(0,0,c?"sp-text "+c:"sp-text");b.setText(a);return b};
Popup.prototype._update=function(){if(this.attachedTo){var a=this.getNode();a.style.width=this.width+"px";a.style.height=this.height+"px";var c=a.getBoundingClientRect(),b=this.attachedTo.getBoundingClientRect(),d=(b.left+b.right)/2,e=(b.top+b.bottom)/2,h=this._nodeArrowBorder,j=this._nodeArrowSolid,f,i=35<Math.min(_viewportWidth-b.left,b.right);f=b.top>c.height+10;var g=_viewportHeight-b.bottom>c.height+10;if(i&&(g||f)){var e=d-c.width/2,i=Math.max(10,b.left-c.width+25),k=Math.min(_viewportWidth-
c.width-10,b.right-25);e>k&&(e=k);e<i&&(e=i);36>c.width?d=(c.width-6)/2:(d-=e,15>d?d=15:d>c.width-25+10&&(d=c.width-25+10));h.style.left=j.style.left=Math.round(d)+"px";h.style.top=j.style.top=null;(_viewportHeight-b.bottom>b.top||!f)&&g?(f=b.bottom+10,a.className=this.cssClass+" sp-popup-below"):(f=b.top-10-c.height,a.className=this.cssClass+" sp-popup-above")}else f=e-c.height/2,i=Math.max(10,b.top-c.height+25),k=Math.min(_viewportHeight-c.height-10,b.bottom-25),f>k&&(f=k),f<i&&(f=i),36>c.height?
g=(c.height-6)/2:(g=e-f,15>g?g=15:g>c.height-25+10&&(g=c.height-25+10)),h.style.top=j.style.top=Math.round(g)+"px",h.style.left=j.style.left=null,h=b.left>c.width+10,j=_viewportWidth-b.right>c.width+10,(_viewportWidth-b.right>b.left||!h)&&j?(e=b.right+10,a.className=this.cssClass+" sp-popup-right"):h?(e=b.left-10-c.width,a.className=this.cssClass+" sp-popup-left"):(e=0,a.className=this.cssClass);a.style.left=Math.round(_scrollX+e)+"px";a.style.top=Math.round(_scrollY+f)+"px"}};
Popup.prototype.getNode=function(){if(this._node)return this._node;var a=document.createElement("div");a.className=this.cssClass;a.style.visibility="hidden";var c=document.createElement("div");c.className="sp-arrow-border";a.appendChild(c);var b=document.createElement("div");b.className="sp-arrow-solid";a.appendChild(b);this.content&&a.appendChild(this.content);this._node=a;this._nodeArrowBorder=c;this._nodeArrowSolid=b;return a};
Popup.prototype.hide=function(a){if(this.attachedTo)if(a){if(this._hideTimeout&&this._hideTimeoutTime-+new Date>a+50)clearTimeout(this._hideTimeout);else if(this._hideTimeout)return;var c=this;this._hideTimeout=setTimeout(function(){c.hide()},a);this._hideTimeoutTime=+new Date+a}else this._hideTimeout&&(clearTimeout(this._hideTimeout),delete this._hideTimeout,delete this._hideTimeoutTime),document.removeEventListener("mousedown",this._clickToHideHandler),this._node.parentNode.removeChild(this._node),
this._node.style.visibility="hidden",delete this.attachedTo,_unregister(this)};
Popup.prototype.dispose=function(){_unregister(this);this._clickToHideHandler&&(document.removeEventListener("mousedown",this._clickToHideHandler),delete this._clickToHideHandler);this.content&&this.content.parentNode==this._node&&this._node.removeChild(this.content);this._node&&this._node.parentNode&&this._node.parentNode.removeChild(this._node);this._hideTimeout&&(clearTimeout(this._hideTimeout),delete this._hideTimeout,delete this._hideTimeoutTime);delete this.attachedTo;delete this.content;delete this._node;
delete this._nodeArrowBorder;delete this._nodeArrowSolid;delete this._textContainer};Popup.prototype.resize=function(a,c){this.width=a;this.height=c;this._update()};Popup.prototype.setContent=function(a,c,b){a!=this.content&&(this.content&&this._node.removeChild(this.content),this.content=a,this._node&&this._node.appendChild(a),c&&b&&this.resize(c,b))};
Popup.prototype.setText=function(a,c){var b=this._textContainer;b||(this._textContainer=b=document.createElement("span"));b.textContent=a;var d=this.getNode();d.style.width=(c||200)+"px";this.setContent(b);d.parentNode?b=b.getBoundingClientRect():(d.style.visibility="hidden",document.body.appendChild(d),b=b.getBoundingClientRect(),document.body.removeChild(d));this.resize(b.width,b.height)};
Popup.prototype.showFor=function(a){if(a==this.attachedTo)this._hideTimeout&&(clearTimeout(this._hideTimeout),delete this._hideTimeout,delete this._hideTimeoutTime);else{var c=this.getNode();this.attachedTo&&this.hide();this.attachedTo=a;document.body.appendChild(c);_register(this);this._update();c.style.visibility="visible";var b=this;this._clickToHideHandler||(this._clickToHideHandler=function(a){for(var a=a.target,c=!1;a;){if(a==b._node){c=!0;break}a=a.parentNode}c||b.hide()});setTimeout(function(){b._node.parentNode&&
document.addEventListener("mousedown",b._clickToHideHandler)},0)}};var _popups=[];function _register(a){0<=_popups.indexOf(a)||(_popups.length||(_viewportHandler(),window.addEventListener("resize",_viewportHandler),window.addEventListener("scroll",_viewportHandler)),_popups.push(a))}function _unregister(a){a=_popups.indexOf(a);0<=a&&(_popups.splice(a,1),_popups.length||(window.removeEventListener("resize",_viewportHandler),window.removeEventListener("scroll",_viewportHandler)))}
var _viewportWidth,_viewportHeight,_scrollX,_scrollY;function _viewportHandler(){var a=document.documentElement;_viewportWidth=a.clientWidth;_viewportHeight=a.clientHeight;_scrollX=window.pageXOffset||a.scrollLeft;_scrollY=window.pageYOffset||a.scrollTop;for(a=0;a<_popups.length;a++)_popups[a]._update()}exports.Popup=Popup;
