require(["$api/models#Observable","$views/utils/css"],function(j,g){function c(a){this.activeTab=null;this._parseOptions(a);this._tabs={};this._createNode();this._addPointerListeners();this.options.sticky&&(this._stickyData={left:0,right:0},this._addScrollListener(),this._addResizeListener());this._isSticky=!1;var b=this,c=this._getScrollElement();this.addEventListener("scrolltotop",function(a){if("secondclick"!==a.causedBy||b.options.scrollOnSecondClick){var e=c.scrollTop,i=e+b.node.getBoundingClientRect().top;
e>i&&("tabchange"===a.causedBy?c.scrollTop=i:b._animateScroll(c,{scrollTop:i},500))}})}SP.inherit(c,j);c.withTabs=function(a,b){var h=new c(b);h.addTabs(a);return h};c.prototype.addTabs=function(a){for(var b=0,c=a.length;b<c;b++)this.addTab(a[b])};c.prototype.addTab=function(a){if(!this._tabs[a.id]){var b=document.createElement("button");b.className="sp-tabbar-tab";b.innerHTML=a.name;b.setAttribute("data-tab-id",a.id);this.contentNode.appendChild(b);this._tabs[a.id]={id:a.id,name:a.name,element:b};
a.active&&this.setActiveTab(a.id)}};c.prototype.removeTab=function(a){this._tabs[a]&&(this.contentNode.removeChild(this._tabs[a].element),delete this._tabs[a],this.activeTab===a&&(this.activeTab=null))};c.prototype.removeTabs=function(a){for(var b=0,c=a.length;b<c;b++)this._tabs[a[b]]&&this.removeTab(a[b])};c.prototype.setActiveTab=function(a){if(a&&this.activeTab!==a){if(this.activeTab){var b=this._tabs[this.activeTab];g.removeClass(b.element,"sp-tabbar-tab-active");this.activeTab=null}if(this._tabs[a])this.activeTab=
a,g.addClass(this._tabs[a].element,"sp-tabbar-tab-active");else if(a=null,!b)return;this.dispatchEvent({type:"tabchange",id:a,previousId:b&&b.id});a&&this.dispatchEvent({type:"scrolltotop",causedBy:"tabchange"})}};c.prototype.addToDom=function(a,b){switch(b){case "append":a.appendChild(this.node);break;case "prepend":a.insertBefore(this.node,a.firstChild);break;case "after":a.nextSibling?a.parentNode.insertBefore(this.node,a.nextSibling):a.parentNode.appendChild(this.node);break;case "before":a.parentNode.insertBefore(this.node,
a)}"static"===g.getStyle(this.node.parentNode,"position")&&(this.node.parentNode.style.position="relative");this.options.sticky&&this._setSticky()};c.prototype._parseOptions=function(a){var b={sticky:!0,scrollOnSecondClick:!0};if(a)for(var c in a)b[c]=a[c];this.options=b};c.prototype._createNode=function(){this.node=document.createElement("div");this.node.className="sp-tabbar";this.placeholderNode=document.createElement("div");this.placeholderNode.className="sp-tabbar-placeholder";this.node.appendChild(this.placeholderNode);
this.contentNode=document.createElement("div");this.contentNode.className="sp-tabbar-content";this.placeholderNode.appendChild(this.contentNode)};c.prototype._addPointerListeners=function(){var a=this;this._isTouchDevice="ontouchstart"in window||"createTouch"in document;this.node.addEventListener(this._isTouchDevice?"touchstart":"mousedown",function(b){a._onPointerDown(b)},!1);this._isTouchDevice||this.node.addEventListener("mouseover",function(b){a._onPointerMove(b)},!1)};c.prototype._addScrollListener=
function(){var a=this;window.addEventListener("scroll",function(b){a._onScroll(b)},!1)};c.prototype._addResizeListener=function(){var a=this;window.addEventListener("resize",function(b){a._onResize(b)},!1)};c.prototype._onPointerDown=function(a){"button"===a.target.tagName.toLowerCase()&&(a=a.target.getAttribute("data-tab-id"))&&this._tabs[a]&&(this.activeTab!==a?this.setActiveTab(a):this.dispatchEvent({type:"scrolltotop",causedBy:"secondclick"}))};c.prototype._onPointerMove=function(a){"button"===
a.target.tagName.toLowerCase()&&(a=a.target.getAttribute("data-tab-id"))&&this._tabs[a]&&this.dispatchEvent({type:"tabhover",id:a,active:this.activeTab!==a})};c.prototype._onResize=function(){if(this._isSticky){var a=this.node.getBoundingClientRect();this.contentNode.style.width=a.width+"px"}};c.prototype._onScroll=function(){this._setSticky()};c.prototype._setSticky=function(){var a=this.node.getBoundingClientRect(),b=a.height;this._stickyData.left=a.left;this._stickyData.right=a.left+a.width;var c=
this.node.parentNode.getBoundingClientRect(),d=this._getStickyNestingLevel()*b,e=a.top<=d,i=c.bottom>d+b,b=a.top>d-b,c=c.bottom<=d;!this._isSticky&&e&&i?this._enableSticky(d,a):this._isSticky&&(b||c)&&this._disableSticky()};c.prototype._enableSticky=function(a,b){var h=a||0,d=b||this.node.getBoundingClientRect();this._isSticky=!0;c._stickyTabBars.push(this._stickyData);g.addClass(this.contentNode,"sp-tabbar-sticky");this.contentNode.style.top=h+"px";this.contentNode.style.left=d.left+"px";this.contentNode.style.width=
d.width+"px"};c.prototype._disableSticky=function(){this._isSticky=!1;var a=c._stickyTabBars.indexOf(this._stickyData);-1<a&&c._stickyTabBars.splice(a,1);g.removeClass(this.contentNode,"sp-tabbar-sticky");this.contentNode.style.top="";this.contentNode.style.left="";this.contentNode.style.width=""};c.prototype._getStickyNestingLevel=function(){for(var a=0,b=this._stickyData,h=c._stickyTabBars,d=0,e=h.length;d<e;d++)h[d].left<b.right&&h[d].right>b.left&&a++;return a};c.prototype._animateScroll=function(a,
b,c){var d=!0,e=1E3/60;Math.ceil(c/e);var i=+new Date,g={},k={},f;for(f in b)g[f]=a[f],k[f]=b[f]-(a[f]||0);var j=this,l=setInterval(function(){if(d){var e=j._animationEasing(+new Date-i,c),f;for(f in b)a[f]=g[f]+k[f]*e}},e);setTimeout(function(){d=!1;clearInterval(l);for(var c in b)a[c]=b[c]},c)};c.prototype._animationEasing=function(a,b){if(1>(a/=b/2))return a*a*a/2;a-=2;return a*a*a/2+1};c.prototype._getScrollElement=function(){if(c._scrollElement)return c._scrollElement;var a=document.createElement("div");
a.style.height="10000px";document.body.insertBefore(a,document.body.firstChild);var b=document.body.scrollTop+500;document.body.scrollTop=b;b=document.body.scrollTop===b;document.body.removeChild(a);document.body.scrollTop=scroll;c._scrollElement=b?document.body:document.documentElement;return c._scrollElement};c._stickyTabBars=[];exports.TabBar=c});
