require("$api/i18n $api/models $api/relations#Relations $api/toplists#Toplist $shared/events#EventHandler $views/buttons#SubscribeButton $views/image#Image $views/utils/css scripts/features strings/follow.lang".split(" "),function(k,f,l,q,r,s,t,h,i,p){function j(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}function m(a,b){var e=b||new f.Promise,d=a.shift();if(!d)return e.setFail(),d;d.collection.snapshot(0,3).done(function(b){b.length?b.loadAll("name").done(function(a){e.object=
{label:g(d.stringId),items:a};e.setDone()}):m(a,e)}).fail(function(){m(a,e)});return e}function c(a){f.Observable.call(this);this._eventHandler=new r(this);this.set(a)}var g=SP.bind(p.get,p);SP.inherit(c,f.Observable);c.prototype._handleSubscribedChange=function(){if(!this.dispatchEvent({type:"subscriptionchange",user:this.data.user}))return!1;var a=this.data.user.subscribed;this._setCount(this.data.subscriberCount+(a?1:0));if(a){var b=this;this._removalTimer=setTimeout(function(){i.css.HAS_ANIMATION?
h.addClass(b._node,"subscribed"):b.remove()},100)}else clearTimeout(this._removalTimer)};c.prototype._setCount=function(a){"number"!=typeof a?this._subscriberCount.style.visibility="hidden":(this._subscriberCount.style.visibility=null,this._subscriberCount.textContent=g(1==a?"SubscriberCountSingle":"SubscriberCountPlural",k.number(a)))};c.prototype._updateNode=function(){if(this._node){h.addClass(this._node,"loading");var a=this.data.user;this._imagePromise=new f.Promise;this._image.setImage(a);this._subscribe.setItem(a);
this._subscribe.setDisabled(!1);this._name.innerHTML="&nbsp;";this._setCount(this.data.subscriberCount);this._subscriberCount.href=a.uri+":followers";switch(this.data.reason){case "SUBSCRIPTION_OF_SUBSCRIPTION":var b=this.data.reasonProfiles.slice(0,3).map(function(a){return a.load("name")});f.Promise.join(b).done(this,function(a){var b=this.data.subscriberCount;if("number"!=typeof b||0>b)b=Infinity;a.length=Math.min(this.data.reasonProfiles.length,b);this.setMetadata(g("InfoFollowedBy"),a)});break;
case "MY_SUBSCRIBER":this.setMetadata(g("InfoFollowsYou"));break;default:this.setMetadata(),b=q.forUser(a),this._metadataPromise=m([{stringId:"InfoTopArtists",collection:b.artists},{stringId:"InfoPlaylists",collection:b.playlists}]),this._metadataPromise.done(this,function(a){this.setMetadata(a.label,a.items)})}b=[this._imagePromise,a.load("name","subscribed")];"number"!=typeof this.data.subscriberCount&&(a=l.forUser(this.data.user).subscribers.snapshot(0,0),a.done(this,function(a){this.data.subscriberCount=
a.length;this._setCount(a.length)}),b.push(a));f.Promise.join(b).done(this,this._updateNodeDone)}};c.prototype._updateNodeDone=function(){var a=this.data.user;this._name.href=a.uri;this._name.textContent=a.name.decodeForText()||"&nbsp;";h.removeClass(this._node,"loading");h.removeClass(this._node,"dismissed");h.removeClass(this._node,"subscribed");i.css.HAS_ANIMATION||(new Fx.Tween(this._node,{property:"opacity",duration:400})).start(0,1)};c.prototype._animationEnd=function(a){switch(a.animationName){case "dismissed":case "subscribed":this.dispatchEvent({type:"removing"})&&
this.dispose()}};c.prototype.getNode=function(){if(this._node)return this._node;var a=document.createElement("div");a.className="suggestion";var b=document.createElement("span");b.className="dismiss";b.textContent="\u00d7";a.appendChild(b);var e=t.forUser(this.data.user,{link:"auto",style:"plain",width:80,height:80,animate:!1});this._eventHandler.listen(e,"load",function(){this._imagePromise&&this._imagePromise.setDone()}).listen(e,"reset",function(){this._imagePromise&&this._imagePromise.setDone()});
a.appendChild(e.node);var d=document.createElement("a");d.className="name";a.appendChild(d);var c=document.createElement("a");c.className="subscriber-count";a.appendChild(c);var n=document.createElement("span");n.className="metadata";a.appendChild(n);var f=document.createElement("div");f.className="buttonArea";var g=s.forUser(this.data.user);f.appendChild(g.node);a.appendChild(f);this._eventHandler.listen(l.forCurrentUser().dismissed,"add",function(a){-1!=a.uris.indexOf(this.data.user.uri)&&(this.dispatchEvent({type:"dismiss",
user:this.data.user}),this.remove())}).listen(b,"click",function(){l.forCurrentUser().dismiss(this.data.user)}).listen(d,"click",function(){this.dispatchEvent({type:"navigate",href:this.data.user.uri})}).listen(e.node,"click",function(){this.dispatchEvent({type:"navigate",href:this.data.user.uri})}).listen(a,"webkitAnimationEnd",this._animationEnd).listen(a,"mozAnimationEnd",this._animationEnd).listen(a,"animationend",this._animationEnd).listen(g,"click",function(a){g.setDisabled(!0);i.css.HAS_ANIMATION?
h.addClass(self._node,"subscribed"):self.remove();a.preventDefault()});this._image=e;this._metadata=n;this._name=d;this._node=a;this._subscribe=g;this._subscriberCount=c;this._updateNode();return a};c.prototype.dispose=function(){this._node&&(this._eventHandler.removeAll(),this._node.parentNode&&this._node.parentNode.removeChild(this._node),this._metadataPromise&&this._metadataPromise.setFail(),clearTimeout(this._removalTimer),delete this.data,delete this._eventHandler,delete this._image,delete this._metadata,
delete this._metadataPromise,delete this._node,delete this._subscribe)};c.prototype.remove=function(){if(i.css.HAS_ANIMATION)h.addClass(this.getNode(),"dismissed");else{var a=new Fx.Tween(this.getNode(),{property:"opacity",duration:400});a.addEvent("complete",function(){this.dispatchEvent({type:"removing"})&&this.dispose()}.bind(this));a.start(1,0)}};c.prototype.setMetadata=function(a,b){if(b)if(b.length){var c=b.length-3;if(0<c){for(var d=2;0<d&&!b[d];)d--,c++;b=b.slice(0,d);b.push(g("ListXOthers",
k.number(c+1)))}b=b.map(function(a){if(a instanceof f.Loadable){var b=a.name;20<b.length&&(b=b.substr(0,20)+"\u2026");return'<a href="'+a.uri+'">'+j(b)+"</a>"}return j(a)});this._metadata.innerHTML=j(a)+" "+k.list(b)}else this._metadata.innerHTML="";else this._metadata.innerHTML=j(a||"")};c.prototype.set=function(a){this.data&&this._eventHandler.unlisten(this.data.user,"change:subscribed");this._metadataPromise&&this._metadataPromise.setFail();clearTimeout(this._removalTimer);this.data=a;this._eventHandler.listen(a.user,
"change:subscribed",this._handleSubscribedChange);this.dispatchEvent({type:"userchange",user:a.user});this._updateNode()};exports.Suggestion=c});
