# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='mergedprofile.proto',
  package='',
  serialized_pb='\n\x13mergedprofile.proto\"\x16\n\x14MergedProfileRequest\"8\n\x12MergedProfileReply\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08\x61rtistid\x18\x02 \x01(\t')




_MERGEDPROFILEREQUEST = descriptor.Descriptor(
  name='MergedProfileRequest',
  full_name='MergedProfileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=45,
)


_MERGEDPROFILEREPLY = descriptor.Descriptor(
  name='MergedProfileReply',
  full_name='MergedProfileReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='username', full_name='MergedProfileReply.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='artistid', full_name='MergedProfileReply.artistid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=47,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['MergedProfileRequest'] = _MERGEDPROFILEREQUEST
DESCRIPTOR.message_types_by_name['MergedProfileReply'] = _MERGEDPROFILEREPLY

class MergedProfileRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MERGEDPROFILEREQUEST
  
  # @@protoc_insertion_point(class_scope:MergedProfileRequest)

class MergedProfileReply(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MERGEDPROFILEREPLY
  
  # @@protoc_insertion_point(class_scope:MergedProfileReply)

# @@protoc_insertion_point(module_scope)
