require("$api/models /scripts/utils /scripts/env#Environment /scripts/logger#Logger /scripts/promises /scripts/albums_views /scripts/promised_loader#PromisedLoader /scripts/artificial_context#ArtificialContext".split(" "),function(f,k,t,u,y,h,v,w){function i(){this.lists=new b}function b(){this.active=-1}function d(){this.objectLoader=this.view=null}function e(a){this.view=a}function m(){this.objectLoader=q;this.view=new h.AlbumListView(l);this.counter=0}function q(){this.view=new h.AlbumView}function n(){this.objectLoader=
r;this.view=new h.SingleListView(l)}function r(){this.view=new h.SingleView}function p(){this.objectLoader=j;this.view=new h.AppearancesListView(l)}function j(){this.view=new h.AppearanceView}function s(a){if(void 0!==a)for(var c=0;c<a.length;c++)void 0!==a[c].destroy&&a[c].destroy.call(a[c]),delete a[c]}var x=new u,l;i.prototype.init=function(a,c){this.lists.init(a);l=c;this.lists.add(new m);this.lists.add(new n);this.lists.add(new p)};i.prototype.destroy=function(){this.lists.destroy()};i.prototype.setContextManager=
function(a){this.lists.setContextManager(a)};i.prototype.renderAboveTheFold=function(){return this.queueOne()};i.prototype.albumsLoaded=function(){return this.lists.albumsLoaded()};i.prototype.queueOne=function(){return this.lists.getNextObject()};b.prototype.add=function(a){this.lists.push(a);a.init(this.artist,this.renderer);a.addEventListener("ready",SP.bind(this._ready,this));a.addEventListener("done",SP.bind(this._moveActive,this));this.hasArtificalContext()&&a.addEventListener("contextCreated",
SP.bind(this._registerArtificalContext,this))};b.prototype._registerArtificalContext=function(a){this.artificalContext.append(a.data.data.uri,a.data.data.length)};b.prototype.hasArtificalContext=function(){return t.desktop};b.prototype.albumsLoaded=function(){return this._albumsLoaded};b.prototype.init=function(a){this.lists=[];this.artist=a;this.globalOffset=0;this.previousContext=null;this.contextIndex=1;this._albumsLoaded=0;this.first=!0;this.active=0;this.done=!1;this.renderer=new v;this.onDone=
new f.Promise;this.hasArtificalContext()&&(this.artificalContext=new w);this.loadingStarted=k.performanceNow();return this.onDone};b.prototype.setContextManager=function(a){this.contextManager=a};b.prototype.destroy=function(){s(this.lists);this.lists=[];this.renderer&&this.renderer.destroy()};b.prototype.getNextObject=function(){this.promise=new f.Promise(this);if(this.done)return!1;this.active<=this.lists.length-1&&this.lists[this.active].getNextObject(this.globalOffset,this.contextManager);return this.promise};
b.prototype._ready=function(a){this.globalOffset+=a.data.increment;this._albumsLoaded+=a.data.rendered;this.promise.setDone()};b.prototype._sectionReady=function(){this.globalOffset+=1;this.promise.setDone()};b.prototype._moveActive=function(){this.active++;this.active===this.lists.length?this._setDone():this._sectionReady()};b.prototype._setDone=function(){h.ObjectListView.stopWaiting();this.done=!0;k.performanceNow();this.onDone.setDone()};SP.inherit(d,f.Observable);d.prototype.init=function(a,
c){if(this.called)return!1;this.total=-1;this.visibleObjects=this.offset=0;this.artist=a;this.first=!0;this.domVisible=this.dead=!1;this.objects=[];this.renderer=c;this.view.init(c)};d.prototype.destroy=function(){s(this.objects);this.objects=[];this.dead=!0;this.view.destroy()};d.prototype.getNextObject=function(a,c){this.contextManager=c;this.globalOffset=a;this.snapLen=this.first?6:20;this.view.startWaiting();var g=this;SpotifyApi.api.analyticsContext("getNextObject() (offset: "+a+")",function(){g._source().snapshot(g.offset,
g.snapLen).done(g,g._onSnapshot)})};d.prototype._notifyObjectsReady=function(a,c){this.offset+=a;this.dispatchEvent({type:"ready",data:{increment:a,rendered:c}})};d.prototype._onSnapshot=function(a){var c=this.snapLen;this.dead||(this.first&&this._onFirstSnapshot(a),this.offset>this.total-1?this.dispatchEvent("done"):this._getAvailableObjects(a).done(this,function(a){a=a.map(function(a){return a.load("name","image","playable","date","discs","tracks","uri")});f.Promise.join(a).each(this,function(){}).always(this,
function(a){var g=[],b,d;if(void 0===a)this._notifyObjectsReady(c,null);else{for(var e=0,h=a.length;e<h;e++)b=new this.objectLoader,this.objects.push(b),d=b.init(this.artist,this.contextManager,this.globalOffset+e,this.renderer),g.push(d),this._prepareRender(a[e],b);f.Promise.join(g).always(this,function(a){this._notifyObjectsReady(c,a.length)})}})}))};d.prototype._prepareRender=function(a,c){var g=this.dead,b=this;this.domVisible||(this.view.show(),this.domVisible=!0);this.visibleObjects++;c.addEventListener("empty",
function(){b.visibleObjects--;0===b.visibleObjects&&(b.view.hide(),b.domVisible=!1)});c.addEventListener("contextCreated",function(a){b.dispatchEvent({type:"contextCreated",data:a})});var d=c.onObjectReady;(function(a){g||d.call(this,a)}).call(c,a);this.objects.push(a)};d.prototype._getAvailableObjects=function(a){var c=[],g=new f.Promise(c);a.loadAll("albums").always(this,function(a){for(var b=[],d=void 0!==a?a.length:0,e=0;e<d;e++)b.push(this._getFirstValidAlbum(a[e]));f.Promise.join(b).always(function(a){for(var b=
void 0!==a?a.length:0,d=0;d<b;d++){var e=a[d];void 0!==e&&e.hasOwnProperty("album")&&c.push(e.album)}g.setDone()})});return g};d.prototype._getFirstValidAlbum=function(a){var c={},b=new f.Promise(c),d=[];0<a.albums.length?(d=a.albums.map(function(a){return a.load("playable")}),f.Promise.join(d).each(this,function(a){void 0===c.album&&a.playable&&(c.album=a,b.setDone())}).always(this,function(){void 0===c.album&&b.setFail()})):b.setFail();return b};d.prototype._onFirstSnapshot=function(a){this.first=
!1;this.total=a.length;x.clientEvent("start-render-"+this.view.prefix,{scrollPositionY:k.scrollPosition().y})};SP.inherit(e,f.Observable);e.prototype.init=function(a,c,b,d){var e=this;this.result={};this.dead=!1;this.artist=a;this.contextManager=c;this.offset=b;this.renderer=d;this.promise=new f.Promise(this.result);this.view.addEventListener("empty",function(){e.dispatchEvent("empty")});return this.promise};e.prototype.destroy=function(){this.dead=!0;this.view.destroy();delete this.view;this.promise.setDone()};
e.prototype.onObjectReady=function(a){this.object=a;this.options=this._makeOptions(a);this.object.tracks.snapshot().done(this,function(a){this.dispatchEvent({type:"contextCreated",data:{uri:this.options.uri,length:a.length}})});this.render();this.setDone()};e.prototype.setDone=function(){this.promise.setDone()};e.prototype.render=function(){this.dead||(this.view.init(this.object,this.options,this.contextManager,this.offset,this.renderer),this.setDone())};e.prototype._makeOptions=function(a){return{image:a,
name:a.name,uri:a.uri,date:k.readableYear(a.date)}};SP.inherit(m,d);m.prototype._source=function(){return this.artist.albums};q.prototype=new e;SP.inherit(n,d);n.prototype._source=function(){return this.artist.singles};r.prototype=new e;SP.inherit(p,d);p.prototype._source=function(){return this.artist.appearances};SP.inherit(j,e);j.prototype.onObjectReady=function(a){this._filterAppearance(a).done(this,function(a){a.playlist&&(this.object=a.playlist,this.options=a.options,this.render());this.setDone()}).done(this,
function(a){this.dispatchEvent({type:"contextCreated",data:{uri:a.playlist.uri,length:a.playlist.tracks.length}})})};j.prototype.destroy=function(){this.object&&f.Playlist.removeTemporary(this.object);j._superClass.destroy.call(this)};j.prototype.key=function(a){return this.artist.uri+":appears:"+a};j.prototype._filterAppearance=function(a){var c={},b=new f.Promise(c),d=this.offset,e=this.artist.name;a.tracks.snapshot().done(this,function(h){0==h.length?b.setDone():f.Playlist.createTemporary(this.key(d)).done(function(d){d.load("tracks").done(function(){d.tracks.snapshot(0,
0).done(function(f){c.playlist=d;c.options={appearance:a,name:a.name,uri:a.uri,date:a.date};0<f.length?b.setDone():h.loadAll("artists").each(function(a){a.artists.forEach(function(b){b.name===e&&d.tracks.add(a)})}).always(function(){b.setDone()})})})})});return b};exports.ArtistPageList=i});
