require("$api/models $views/image#Image $views/list#List $views/throbber#Throbber /scripts/utils /scripts/env#Environment /scripts/logger#Logger /scripts/promises#TimedPromise".split(" "),function(f,n,v,w,p,k,x,y){function b(a){this.prefix=a;this._localStorageViewTypeKey="com.spotify.artist.viewtypes";this._viewTypeSettings={}}function c(){this.imageSize=180;this.listFields=k.web?["number","track","trackartist","time","popularity"]:"star share number track trackartist time popularity".split(" ")}
function q(a){this.prefix="albums";h=a}function r(){this.selectorPrefix="album";this.parentList=$("albums-list")}function s(a){this.prefix="appearances";h=a}function l(){this.selectorPrefix="appearance";this.parentList=$("appearances-list");this.imageSize=86;this.listFields=k.web?["nowplaying","track","trackartist","time","popularity"]:"star share track trackartist time popularity".split(" ")}function t(a){this.prefix="singles";h=a}function u(){this.selectorPrefix="single";this.parentList=$("singles-list");
this.imageSize=86}var z=new x,h;b.throbber=!1;b.prototype.init=function(a){this.renderer=a;this.throbberNode=document.getElementById("content-throbber");$(this.prefix+"-list").empty();this._bindEvents();this._restoreViewType(this.prefix)};b.prototype.destroy=function(){this.hide();$$(".viewtype."+this.prefix+" span").removeEvents("click")};b.prototype._bindEvents=function(){var a=this._onToggleViewTypeClick.bind(this);$$(".viewtype."+this.prefix+" span").addEvent("click",a)};b.prototype._onToggleViewTypeClick=
function(a){a=~a.target.className.indexOf("covers")?"covers":"list";this._setViewType(this.prefix,a);this._storeViewType(this.prefix,a);z.clientEvent("set-view-type",{list:this.prefix,view:a});this._updateAlbumItemsLayout(this.prefix,a)};b.prototype._setViewType=function(a,d){$$(".viewtype."+this.prefix).removeClass("covers").addClass(d);$(this.prefix+"-list").removeClass("list").removeClass("covers").addClass(d)};b.prototype._storeViewType=function(a,d){localStorage&&(this._viewTypeSettings=JSON.parse(localStorage.getItem(this._localStorageViewTypeKey)||
"{}"),this._viewTypeSettings[a]=d,localStorage.setItem(this._localStorageViewTypeKey,JSON.stringify(this._viewTypeSettings)))};b.prototype._restoreViewType=function(a){localStorage&&(this._viewTypeSettings=JSON.parse(localStorage.getItem(this._localStorageViewTypeKey)||"{}"),"undefined"!==typeof this._viewTypeSettings[a]&&this._setViewType(a,this._viewTypeSettings[a]))};b.prototype._updateAlbumItemsLayout=function(a,d){h.map(function(b,i){if(i.group==a){var c="list"==d?i.el.getProperty("list-view-height"):
"albums"==a?230:150;i.hide();i.setHeight(c)}});h.recalculateAllItems()};b.prototype.hide=function(){$(this.prefix+"-container").addClass("hidden")};b.prototype.show=function(){this.renderer.enqueue(null,function(){var a=new f.Promise;$(this.prefix+"-container").removeClass("hidden");a.setDone();return a},this)};b.startWaiting=function(){clearTimeout(b.contentLoadingTimer);!1===b.throbber&&(b.throbber=new w.forElement(this.throbberNode),b.throbber.setSize("normal"))};b.stopWaiting=function(){clearTimeout(b.contentLoadingTimer);
null!=b.throbber.parentNode&&b.throbber.hide();$("content-loading").setStyle("display","none")};b.prototype.startWaiting=b.startWaiting;b.prototype.stopWaiting=b.stopWaiting;SP.inherit(c,f.Observable);c.prototype.supportsContextGroups=function(){return k.web};c.prototype.destroy=function(){this.dead=!0};c.prototype.init=function(a,d,b,i,c){this.contextManager=b;this.offset=i;this.renderer=c;this.additionalTracks=0;this.willUpdateHeight=null;return this.render(a,d)};c.prototype.render=function(a,d){return this._render(a,
d)};c.prototype._calculateHeight=function(a){var d=new f.Promise;a.load("tracks","discs").done(this,function(){a.tracks.snapshot().done(this,function(b){b.loadAll("playable").done(this,function(b){for(var c=0,m=b?b.length:0,e=0;e<m;e++)b[e].playable?c++:b[e].addEventListener("change:playable",this._itemPlayable.bind(this));d.setDone(25*c+27*(1>=a.discs.length?0:a.discs.length)+20*(a.discs.length-1)+34)})})});return d};c.prototype._itemPlayable=function(){this.additionalTracks++;null===this.willUpdateHeight&&
(this.willUpdateHeight=window.setTimeout(this._heightUpdate.bind(this),0))};c.prototype._heightUpdate=function(){null!=this.scrollItem&&this.scrollItem.modifyHeight(25*this.additionalTracks);this.additionalTracks=0;this.willUpdateHeight=null};c.prototype._render=function(a,d){if(this.dead){var b=new f.Promise;b.setFail();return b}var c=new f.Promise;this._calculateHeight(a).done(this,function(b){var m=this.parentList.id.replace("-list",""),e=this._createContainer(this.offset),g="albums"==m?0<=this.parentList.getAttribute("class").indexOf("cover")?
230:b:0<=this.parentList.getAttribute("class").indexOf("cover")?150:b;e.style.height=g+"px";e.setAttribute("list-view-height",b);this.dead?c.setFail():(this.parentList.grab(e),c.setDone(),b=function(){this._delayedRendering(a,d,e)}.bind(this),this.contextManager.allocate(this.offset,b),this.scrollItem=h.append(e,this.parentList,g,b,m))});return c};c.prototype._delayedRendering=function(a,d,b){if(this.dead)return a=new f.Promise,a.setFail(),a;var c={},h=new f.Promise(c),l=new f.Promise(c),e=new y(c,
100),g=this,c=this._createImage(a,d),k=this._createHeader(),j=this._createList(a,d);b.appendChild(c.node);k.appendChild(this._createTitle(a,d,this.offset));k.appendChild(this._createYear(d));b.appendChild(k);b.appendChild(j.node);j.addEventListener("initialized",function(){g.contextManager.evaluate(g.offset,j);h.setDone()});j.addEventListener("snapshot-load",function(){$$(".sp-list",j.node).setStyle("visibility","visible");l.setDone()});j.addEventListener("play",function(){g.contextManager.evaluateNext(g.offset)});
d=["tracks"];a.discs&&d.push("discs");j.addEventListener("visually-empty",function(){g.scrollItem&&(g.scrollItem.detach(),g.scrollItem=null);g.hide();g.dispatchEvent("empty")});c.view.addEventListener("load",function(){e.setDone()});j.init();return f.Promise.join(h,l,e)};c.prototype._createList=function(a,d){return new v(a,{context:a,title:d.name,type:"tracks",unplayable:"hidden",fields:this.listFields,header:"no",fetch:"greedy",style:"rounded"})};c.prototype._createHeader=function(){var a=document.createElement("div");
a.className="list-header";return a};c.prototype._createYear=function(a){var d=document.createElement("span");d.className="album-year";d.innerHTML=p.readableYear(a.date);return d};c.prototype._createTitle=function(a,d,b){a=document.createElement("a");a.className=this.selectorPrefix+"-title";a.innerHTML=d.name;a.href=d.uri.toSpotifyURL();a.rel=b;a.title=d.name;a.id="artist-"+this.selectorPrefix+"-"+b;return a};c.prototype.show=function(){$(this.selectorPrefix+"-offset-"+this.offset).setStyle("display",
"block")};c.prototype.hide=function(){$(this.selectorPrefix+"-offset-"+this.offset).parentNode.setStyle("display","none")};c.prototype._createContainer=function(a){var b=document.createElement("div");b.className=this.selectorPrefix+"-node cf";b.id=this.selectorPrefix+"-offset-"+a;$$("#"+this.selectorPrefix+"-offset-"+a).destroy();return b};c.prototype._createImageObject=function(a,b){return new n.forAlbum(a,b)};c.prototype._wrapImageObject=function(a){var b=document.createElement("div");b.className=
"image-node";b.appendChild(a.node);return b};c.prototype._createImage=function(a,b){var c={title:b.name,height:this.imageSize,width:this.imageSize,player:!0,animate:!1,overlay:[b.name,p.readableYear(b.date)],placeholder:"album",link:b.uri},i=this;this.supportsContextGroups()&&(c.getContextGroupData=function(){return i.contextManager.contextAt(i.offset)});c=this._createImageObject(a,c,b);return{view:c,node:this._wrapImageObject(c)}};q.prototype=new b;r.prototype=new c;s.prototype=new b;l.prototype=
new c;l.prototype._createImageObject=function(a,b,c){b.playerItem=a;return n.forAlbum(c.appearance,b)};l.prototype._calculateHeight=function(a){var b=new f.Promise;a.load("tracks").done(this,function(){a.tracks.snapshot().done(this,function(a){a.loadAll("playable").done(this,function(a){for(var c=0,f=a?a.length:0,e=0;e<f;e++)a[e].playable&&c++;b.setDone(25*c+34)})})});return b};t.prototype=new b;u.prototype=new c;exports.AlbumView=r;exports.SingleView=u;exports.AppearanceView=l;exports.ObjectListView=
b;exports.AlbumListView=q;exports.AppearancesListView=s;exports.SingleListView=t});
