require("$api/models $views/list#List $views/buttons#Button $views/image#Image $views/throbber#Throbber $api/toplists#Toplist /scripts/toolbar /scripts/header /scripts/toplist /scripts/relatedartists /scripts/albums /scripts/biography /scripts/utils /scripts/benchmark#Benchmark /scripts/logger#Logger /scripts/promises /scripts/config#Config /scripts/config_settings#ConfigSettings /strings/main.lang /scripts/env#Environment /scripts/context_manager#ContextManager /scripts/artificial_context#ArtificialContext /scripts/smoothscroller#SmoothScroller".split(" "),
function(c,Y,Z,aa,I,ba,J,K,L,y,M,N,t,g,O,P,Q,R,z,u,S,A,T){var q,l,d,h,m,i,n,j,p,k=new g,v=new O,f,r,w,B=z.get.bind(z),s;$$(".localize").each(function(a){a.innerHTML=B(a.get("data-string"))});$$(".localize-attribute").each(function(a){a.setAttribute(a.get("data-attribute"),B(a.get("data-string")))});var C=function(){k.start(g.APP_INIT);Q.init(R);u.desktop&&($("the-body").addClass("desktop"),A.init());c.session.load("online","testGroup").done(function(){v.setTestGroup(c.session.testGroup);v.clientEvent("application-init");
c.session.online?(p&&$("offline-notice").dispose(),p=!1,d=J.createToolbar(".tab-containers",".tabs","#header"),l=new K.Header(d),h=new L.Toplist,i=y.RelatedArtists.createStartPanel(),n=y.RelatedArtists.createRelatedPage(),j=new M.ArtistPageList,m=new N.Biography,r=new S,document.getElementById("page-throbber"),d.init(),d.resetOverviewPosition(),c.session.addEventListener("online",C),c.session.addEventListener("offline",D),c.application.addEventListener("arguments",E),c.application.load("arguments").done(E),
$("related-see-all").addEvent("click",U),$$("body").addEvent("click",V),$$(".tabs > ul").addEvent("click",F)):D()})},D=function(){p=!0;G();H();var a=document.createElement("p");a.id="offline-notice";a.innerHTML="Artist pages are not available offline.";$$("body")[0].appendChild(a);l&&l.destroy();i&&i.destroy();h&&h.destroy()},E=function(){k.start(g.LOAD_FROM_URI);p=!1;G();d.show("overview");s&&s.destroy();s=new T;if(c.application.arguments[0])SpotifyApi.api.analyticsContext("Application Load",function(){q=
c.application.arguments[0];var a=c.Artist.fromURI("spotify:artist:"+q);v.clientEvent("load-artist",{artist:q});a.load("albums singles name image portraits popularity related biography".split(" ")).done(W).fail(X)});else return c.application.openApp("home"),!1},X=function(){$$("body > .throbber").setStyle("display","none");$$("body > .error").setStyle("display","block");$("artist-page").setStyle("display","none")},W=function(a){k.measure("artist-load","Artist loaded",g.LOAD_FROM_URI);u.desktop&&A.pushContextGroup(r);
SpotifyApi.api.analyticsContext("renderAboveTheFold()",function(){k.start(g.RENDER_ABOVE_THE_FOLD);$("content-loading").setStyle("display","none");var b=new P.TimedPromise({},5E3);H();l.init(a);i.init(a).done(function(b){n.init(a);n.setResults(b.results);0===b.results&&d.isActiveTab("related")&&d.show("overview")});j.init(a,s);m.init(a)?"undefined"!==typeof c.application.arguments[1]&&"biography"==c.application.arguments[1]&&d.show("biography"):d.isActiveTab("biography")&&d.show("overview");h.init(a,
q,r).done(function(){j.setContextManager(r);j.renderAboveTheFold().done(this,function(){b.setDone()})});i.render();l.render();h.render();b.done(function(){w.hide();$("content-loading").setStyle("display","block");setTimeout(function(){h.view.unhide();i.view.unhide()},100);f&&setTimeout(f);f=setTimeout(x,10);m.render();k.measure("atf-internal","Above the fold execution time",g.RENDER_ABOVE_THE_FOLD);k.measure("atf-inclusive","Above the fold done",g.LOAD_FROM_URI);k.send()})})},U=function(a){F(a);d.show("related");
a.preventDefault()},V=function(a){var b=a.target;if("A"===b.nodeName)if(b=b.getAttribute("href"),b.match(/#artist-/)){d.show("overview");var b=b.match(/#(.*)$/)[1],b=$(b),b=t.elementPosition(b),f=t.elementPosition($$(".tabs")[0]);window.scrollTo(0,b.top-12-d.heightOnPage()-f.height)}else b=b.toSpotifyURI(),c.application.openURI(b);else b.className.match(/spuri/)?(b=b.getAttribute("data-spuri"),c.application.openURI(b)):"IMG"===b.nodeName.toUpperCase()&&"sp-image-img"===b.className&&"A"===b.parentNode.parentNode.nodeName.toUpperCase()?
(b=e.target.parentNode.parentNode.href.toSpotifyURI(),c.application.openURI(b)):"sp-image-wrapper"===b.className&&"A"===b.parentNode.nodeName.toUpperCase()&&(b=b.parentNode.href.toSpotifyURI(),c.application.openURI(b));a.preventDefault();return!1},x=function(){var a=t.getScrollableHeight();(u.web?!(2E3<a||"block"!==$("overview").getStyle("display")):25E3>=a&&500>j.albumsLoaded()||5E3>=a)?(clearTimeout(f),a=j.queueOne(),!1!==a&&a.done(function(){f=setTimeout(x,350)})):f=setTimeout(x,1E3)},F=function(a){if("A"===
a.target.nodeName)switch(a.target.getAttribute("rel")){case "related":n.loaded||n.render();break;case "biography":m.imagesLoaded||m.renderImages()}},G=function(){p||(l.destroy(),h.destroy(),i.destroy(),n.destroy(),m.destroy(),j.destroy());f&&clearInterval(f);void 0!==w&&$$("#overview .sp-throbber").dispose();w=new I.forElement(document.getElementById("overview"),500);$("related-tab-list").empty();$$(".tabs li").setStyle("display","");$("related-artists-wrapper").setStyle("display","block");$("top-tracks-inner-wrapper").setStyle("visibility",
"hidden");$("top-tracks").setStyle("visibility","inherit");$("related-artists-wrapper").setStyle("visibility","hidden");$("related-artists").setStyle("visibility","inherit")},H=function(){$("artist-page").setStyle("display","block");$$("body > .error").setStyle("display","none")};C()});
