require(["$api/models","$views/image#Image","$views/throbber#Throbber","/scripts/utils"],function(i,j,k,l){var e=function(){this.view=new f;this.count=-1;this.loaded=!1};e.createStartPanel=function(){var a=new e;a.count=6;return a};e.createRelatedPage=function(){var a=new e;a.view=new c;return a};e.prototype.init=function(a){this.artist=a;return this.promise=new i.Promise({uri:a.uri})};e.prototype.destroy=function(){this.view.destroy();this.loaded=!1;delete this.artist};e.prototype.render=function(){if(void 0!==
this.artist){this.loaded=!0;this.view.init();var a=0<this.count?this.artist.related.snapshot(0,this.count):this.artist.related.snapshot(),b=this.onSnapshotLoaded.bind(this);a.done(b)}};e.prototype.onSnapshotLoaded=function(a){this.view.prepareSnapshotLoaded(a.range.length);for(var b=["image","name"],g=[],d=0;d<a.range.length;d++)this.prepareArtist(d,a.get(d).uri,this.artist),g.push(a.get(d).load(b));i.Promise.join(g).always(this,function(a){for(var b=0,d=a.length;b<d;b++)this.appendArtist(a[b]);this.view.stopWaiting()});
this.promise.object.results=a.length;this.promise.setDone()};e.prototype.prepareArtist=function(a,b,g){b=b.split(":")[2];this.view.prepareArtist(b,g,g.name,g.uri,a)};e.prototype.appendArtist=function(a){var b=a.uri.split(":")[2];return this.view.appendArtist(b,a,a.name,a.uri,a.uri.toSpotifyURL())};e.prototype.setResults=function(a){this.view.setResults(a)};var h=function(){};h.prototype._createImage=function(a,b,g,d,e,c){a={title:d,height:b,width:a,player:!1,animate:!1,link:e};c&&c.overlay&&(a.overlay=
c.overlay);return new j.forArtist(g,a)};h.prototype.waitBetween=function(){};h.prototype.stopWaiting=function(){};var f=function(){};f.prototype=new h;f.prototype.init=function(){this.relatedList=$("related-artists-list");this.relatedList.innerHTML="";this.throbberTimer=this.throbber=void 0};f.prototype.destroy=function(){this.stopWaiting();this.relatedList&&this.relatedList.empty()};f.prototype.unhide=function(){$("related-artists-wrapper").setStyle("visibility","visible")};f.prototype.prepareSnapshotLoaded=
function(a){$("related-artists").set("class","fluid");$("related-artists-wrapper").setStyle("display",0<a?"block":"none")};f.prototype.waitBetween=function(a,b){this.throbberTimer=setTimeout(this.startWaiting,a);setTimeout(this.stopWaiting,b)};f.prototype.prepareArtist=function(a,b,c,d,e){b=document.createElement("li");b.className="item cf";b.id="related-"+a;b.className=b.className+" related-"+e;this.relatedList.appendChild(b)};f.prototype.appendArtist=function(a,b,c,d,e){var f=new i.Promise,b=this._createImage(30,
30,b,c,d);b.addEventListener("done",function(){f.setDone()});d=document.createElement("a");d.className="name";d.href=e;d.title=c;d.innerHTML=c;$$("#related-"+a+" a").destroy();$$("#related-"+a).grab(b.node);$$("#related-"+a).grab(d);return f};f.prototype.setResults=function(){};var c=function(){this.liNode=document.createElement("li");this.liNode.className="item cf";this.liNode.innerHTML='<div class="portrait"></div>';this.HEIGHT_PER_ROW=200;this.IMAGES_PER_ROW=4};c.prototype=new h;c.prototype.init=
function(){this.relatedWrapper=$("related-tab-list");this.relatedWrapper.innerHTML="";this.throbberPositionY=135;this.throbberTimer=this.throbber=void 0;this.startWaiting();setTimeout(this.stopWaiting,l.THROBBER_MAX_APPEAR_TIME)};c.prototype.destroy=function(){$("related-tab-list").empty()};c.prototype.prepareSnapshotLoaded=function(a){$$("li.related").setStyle("display",0===a?"none":"")};c.prototype.startWaiting=function(){this.throbber=new k.forElement(document.getElementById("related-tab-list"),
300);this.throbber.setPosition("center",this.throbberPositionY)};c.prototype.stopWaiting=function(){clearTimeout(this.throbberTimer);void 0!==this.throbber&&(this.throbber.showContent(),this.throbber.hide())};c.prototype.prepareArtist=function(a){a=this._getListItem(a);this.relatedWrapper.appendChild(a)};c.prototype.appendArtist=function(a,b,c,d){(a=this._findListItem(d))&&a.grab(this._createImage(150,150,b,c,d,{overlay:[b.name]}).node)};c.prototype._getListItem=function(a){var b=this.liNode.clone(!0);
b.id="related-tab-li-"+a;return b};c.prototype._findListItem=function(a){a=a.split(":")[2];return $$("#related-tab-li-"+a+" .portrait")};c.prototype.setResults=function(a){var b=Math.ceil(a/this.IMAGES_PER_ROW);$("related").setStyle("min-height",b*this.HEIGHT_PER_ROW+"px");0===a&&$$("li.related").setStyle("display",0===a?"none":"")};exports.RelatedArtists=e});
