require("$api/models $views/list#List $views/buttons#Button $views/image#Image $api/toplists#Toplist /scripts/env#Environment /scripts/artificial_context#ArtificialContext /scripts/utils".split(" "),function(f,g,d,k,j,h,i){d=function(){this.view=new e;this.playlist2=this.playlist1=null;this.numLists=1};d.prototype=new f.Observable;d.prototype.init=function(a,c,b){this.artist=a;this.artistId=c;this.promise=new f.Promise(this);this.context=b;return this.promise};d.prototype.destroy=function(){this.view.destroy();
null!==this.playlist1&&f.Playlist.removeTemporary(this.playlist1);null!==this.playlist2&&f.Playlist.removeTemporary(this.playlist2);delete this.promise;delete this.artist;delete this.artistId};d.prototype.render=function(){this.view.init();j.forArtist(this.artist).load("tracks").done(this,this.onToplistLoaded).fail(this.promise,this.promise.setFail)};d.prototype.onToplistLoaded=function(a){if(!1==a.tracks)return!1;var c=SP.bind(f.Playlist.createTemporary,f.Playlist),b=this.artistId,d=function(a){return"artist-app-"+
b+"top10-"+a};a.tracks.snapshot(0,10).done(this,function(b){this.view.empty();this.continueLoading();this.view.numTracks=b.length;if(0===b.length)this.onSnapshotLoaded(b);else if(h.desktop)c(d(1)).done(this,function(a){a.load("tracks").done(this,function(a){a.tracks.clear().done(this,function(){var c=5>=b.length?b.length:b.length>>1<<1;this.view.numTracks=c;i.append(a.uri,c);var d=b.toArray();a.tracks.add(d.slice(0,c)).done(this,function(){var b=this.createListFromPlaylist(a,c,0,!0);5<c&&(b.node.addClass("multicolumn"),
b.node.addClass("sp-list-with-"+c+"-items"));b.addEventListener("item-load",this.view.onItemLoaded.bind(this.view));b.init();this.context.place(0,b)})})})});else if(6>b.length){var e=this.createListFromToplist(a,b.length);i.append(a.uri,b.length);e.addEventListener("item-load",this.view.onItemLoaded.bind(this.view));e.init()}else this.numLists=2,f.Promise.join([c(d(1)),c(d(2))]).done(this,function(a){a=[a[0].load("tracks"),a[1].load("tracks")];f.Promise.join(a).done(this,function(a){var c=[a[0].tracks.clear(),
a[1].tracks.clear()];f.Promise.join(c).done(this,function(){var c=Math.floor(b.length/2);this.view.numTracks=2*c;var d=b.toArray();a[0].tracks.add(d.slice(0,c));a[1].tracks.add(d.slice(c));this.createLists(a[0],a[1],c)})})})}).done(this,function(a){this.onSnapshotLoaded(a)})};d.prototype.createLists=function(a,c,b){a=this.createListFromPlaylist(a,b,0);c=this.createListFromPlaylist(c,b,b);a.addEventListener("item-load",this.view.onItemLoaded.bind(this.view));a.init();c.init();a.connect(c);this.context.place(0,
a);this.context.place(1,c);this.continueLoading()};d.prototype.continueLoading=function(){this.promise&&this.promise.setDone()};d.prototype.onSnapshotLoaded=function(a){window.setTimeout(function(){0===a.length?this.view.showNoTracks():this.view.showHasTracks()}.bind(this),0)};d.prototype.createListFromPlaylist=function(a,c,b,d){a=new g(a,{type:"tracks",layout:"toplist",fields:["ordinal","image","track"],header:"no",scrollToFetch:!1,numItems:c,numBuckets:1,visualOffset:b,style:"rounded"});d?$$("#top-tracks .content2").grab(a.node):
this.view.injectList(a,0===b?"l":"r");return a};d.prototype.createListFromToplist=function(a,c){var b={type:"tracks",layout:"toplist",fields:["ordinal","image","track"],header:"no",scrollToFetch:!1,numItems:c,numBuckets:1,style:"rounded"};h.web&&(b.context=a);b=new g(a.tracks,b);$$("#top-tracks .content2").grab(b.node);this.context.place(0,b);this.continueLoading();return b};var e=function(){};e.prototype.init=function(){$("top-tracks-content").innerHTML='<div class="l"></div><div class="r"></div>';
$("top-tracks").className="fluid";this.loadedTracks=this.numTracks=0};e.prototype.destroy=function(){this.empty()};e.prototype.empty=function(){$("top-tracks-content").innerHTML='<div class="l"></div><div class="r"></div>'};e.prototype.onItemLoaded=function(){this.loadedTracks+=1;this.loadedTracks===this.numTracks&&this.showList()};e.prototype.unhide=function(){$("top-tracks-inner-wrapper").setStyle("visibility","visible")};e.prototype.showList=function(){$$("#top-tracks-content .sp-list").setStyle("visibility",
"visible")};e.prototype.injectList=function(a,c){$$("#top-tracks .content2 ."+c).grab(a.node)};e.prototype.showHasTracks=function(){$("no-top-tracks").setStyle("display","none");$$("#top-tracks-inner-wrapper .heading").setStyle("display","block");$$("#top-tracks-inner-wrapper .content2").setStyle("display","block")};e.prototype.showNoTracks=function(){$$("#top-tracks-inner-wrapper .heading").setStyle("display","none");$$("#top-tracks-inner-wrapper .content2").setStyle("display","none");$("no-top-tracks").setStyle("display",
"block")};exports.Toplist=d});
