function readableYearsActive(a){if(void 0===a)return"";try{return a.hasOwnProperty("length")?1===a.length?formatSingleYearsActive(a):formatMultipleYearsActive(a):formatDesktopYearsActive(a)}catch(b){return""}}
function formatDesktopYearsActive(a){var b=(new Date).getFullYear(),c=[];if("2147483647"==a.from)return"";if(a.to===b)c.push(a.from+"-");else if(0===a.from%10)for(b=0;b<a.to-a.from;b+=10)c.push((a.from+b).toString().slice(2)+"s");else 0!==a.to&&"2147483647"!=a.to?c.push(a.from+"-"+a.to):c.push(a.from+"-");return c.join(", ")}
function formatSingleYearsActive(a){var b=(new Date).getFullYear();if(a[0].end===b)return b="spotify:search:year:"+a[0].start+"-2099",'<a class="year" href="'+b.toSpotifyURL()+'">'+a[0].start+"-</a>";if(9===a[0].end-a[0].start&&0===a[0].start%10)return b="spotify:search:year:"+a[0].start+"-"+a[0].end,'<a class="year" href="'+b.toSpotifyURL()+'">'+a[0].start.toString().slice(2)+"s</a>";b="spotify:search:year:"+a[0].start+a[0].end;return'<a class="year" href="'+b.toSpotifyURL()+'">'+a[0].start+"-"+
a[0].end+"</a>"}function formatMultipleYearsActive(a){(new Date).getFullYear();for(var b=[],c=0;c<a.length;c++)9===a[c].end-a[c].start&&b.push('<a class="year" href="'+("spotify:search:year:"+a[c].start+"-"+a[c].end).toSpotifyURL()+'">'+a[c].start.toString().slice(2)+"s</a>");return b.join(", ")}function readableYear(a){return void 0===a?"":"string"===typeof a&&"0"!==a?a:"undefined"!==typeof a.year?a.year.toString():""}var _timeOffset=(new Date).getTime();
function performanceNow(){if(window.performance){if("function"===typeof window.performance.now)return window.performance.now();if("function"===typeof window.performance.webkitNow)return window.performance.webkitNow()}return(new Date).getTime()-_timeOffset}
function elementPosition(a){var b=a.getBoundingClientRect(),c=document.getElementsByTagName("body")[0],a="fixed"===$(a).getStyle("position"),d=c.scrollTop,c=c.scrollLeft;return{top:b.top+(a?0:d),left:b.left+(a?0:c),width:b.width,height:b.height}}
function scrollPosition(){return{x:window.pageXOffset?window.pageXOffset:document.documentElement.scrollLeft?document.documentElement.scrollLeft:document.body.scrollLeft,y:window.pageYOffset?window.pageYOffset:document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop}}function getScrollableHeight(){return window.getScrollSize().y-(window.getScroll().y+window.getSize().y)}
function debounce(a,b,c){var d,e;return function(){var f=this,g=arguments,h=c&&!d;clearTimeout(d);d=setTimeout(function(){d=null;c||(e=a.apply(f,g))},b);h&&(e=a.apply(f,g));return e}}function throttle(a,b){var c,d,e,f,g,h,i=debounce(function(){g=f=!1},b);return function(){c=this;d=arguments;e||(e=setTimeout(function(){e=null;g&&(h=a.apply(c,d));i()},b));f?g=!0:(f=!0,h=a.apply(c,d));i();return h}}exports.THROBBER_MIN_APPEAR_TIME=400;exports.THROBBER_MAX_APPEAR_TIME=15E3;
exports.readableYearsActive=readableYearsActive;exports.readableYear=readableYear;exports.elementPosition=elementPosition;exports.scrollPosition=scrollPosition;exports.getScrollableHeight=getScrollableHeight;exports.debounce=debounce;exports.throttle=throttle;exports.performanceNow=performanceNow;
