require(["$views/image#Image","$views/strings/fields.lang"],function(d,g){function e(a){var a=Math.round(35*(a/100)),b=a%3;return a=100*((1.5<b?a+(3-b):a-b)/35)}var c=SP.bind(g.get,g);exports.LIST_FIELDS={track:{title:c("Track"),className:"sp-list-cell-track",widthWeight:7,neededProperties:{track:["name","explicit"]},get:function(a){var b=a.track.name.decodeForHtml();return"web"===a.list.model.userDevice?'<button type="button" class="sp-list-contextbutton">...</button>'+('<span class="sp-list-cell-track-name">'+
b+"</span>"):b}},"image:track":{title:c("ImageTrack"),className:"sp-list-cell-track",widthWeight:7,neededProperties:{track:["name","image"],album:["image"]},get:function(a){return'<div class="sp-list-artwork"><img src="'+(a.track.image||a.album.image||"")+'" alt=""></div>'+a.track.name.decodeForHtml()}},artist:{title:c("Artist"),className:"sp-list-cell-artist",widthWeight:3,neededProperties:{artist:["uri","name"],track:["explicit"]},get:function(a){for(var b="",f,c=0,d=a.artists.length;c<d;c++)if(f=
a.artists[c],f.name){var e=f.name.decodeForHtml();"spotify:artist:0000000000000000000000"!==f.uri?(b+='<a href="'+f.uri.toSpotifyLink()+'" data-uri="'+f.uri+'">',b+=e,b+="</a>"):b+=e;b+=c<d-1?", ":""}return b}},album:{title:c("Album"),className:"sp-list-cell-album",widthWeight:4,neededProperties:{album:["uri","name"]},get:function(a){var b="",a=a.album;if(a.name){var c=a.name.decodeForHtml();"spotify:album:0000000000000000000000"!==a.uri?(b+='<a href="'+a.uri.toSpotifyLink()+'" data-uri="'+a.uri+
'">',b=b+c+"</a>"):b+=c}return b}},time:{title:c("Time"),className:"sp-list-cell-time",fixedWidth:58,neededProperties:{track:["duration"]},get:function(a){if(0>a.track.duration)return"";var b=Math.round((a.track.duration||0)/1E3),a=Math.floor(b/60),b=Math.round(b%60);return a+":"+(10>b?"0"+b:b)}},"track-popularity":{title:c("TrackPopularity"),className:"sp-list-cell-popularity",fixedWidth:75,fixedWidthNoHeader:51,neededProperties:{track:["popularity"]},get:function(a){return'<span class="sp-popularity-indicator"><span class="sp-popularity-indicator-value" style="width: '+
e(a.track.popularity)+'%"></span></span>'}},"artist-popularity":{title:c("ArtistPopularity"),className:"sp-list-cell-popularity",fixedWidth:75,fixedWidthNoHeader:51,neededProperties:{artist:["popularity"]},get:function(a){return'<span class="sp-popularity-indicator"><span class="sp-popularity-indicator-value" style="width: '+e(a.artists[0].popularity)+'%"></span></span>'}},"album-popularity":{title:c("AlbumPopularity"),className:"sp-list-cell-popularity",fixedWidth:75,fixedWidthNoHeader:51,neededProperties:{album:["popularity"]},
get:function(a){return'<span class="sp-popularity-indicator"><span class="sp-popularity-indicator-value" style="width: '+e(a.album&&a.album.popularity||0)+'%"></span></span>'}},nowplaying:{title:c("NowPlaying"),className:"sp-list-cell-nowplaying",fixedWidth:30,neededProperties:{},get:function(){return'<span class="sp-icon-nowplaying"></span>'}},star:{title:c("Star"),className:"sp-list-cell-star",fixedWidth:30,neededProperties:{track:["starred"]},get:function(a){return'<span class="sp-icon-star-hitarea">'+
('<span class="sp-icon-star'+(a.track.starred?" sp-icon-starred":"")+'"></span>')+'</span><span class="sp-icon-nowplaying"></span>'}},"track-image":{title:c("TrackImage"),className:"sp-list-cell-image",fixedWidth:33,neededProperties:{track:["image"],album:["image"]},get:function(a){var b=a.imageOptions||{placeholder:"track",width:"toplist"===a.list.layout?30:21,style:"inset"};return(a.track.image?d.forTrack(a.track,b):d.forAlbum(a.album,b)).node}},"artist-image":{title:c("ArtistImage"),className:"sp-list-cell-image",
fixedWidth:33,neededProperties:{artist:["image"]},get:function(a){return d.forArtist(a.artists[0],a.imageOptions||{placeholder:"artist",width:"toplist"===a.list.layout?30:21,style:"inset"}).node}},"album-image":{title:c("AlbumImage"),className:"sp-list-cell-image",fixedWidth:33,neededProperties:{album:["image"]},get:function(a){return d.forAlbum(a.album,a.imageOptions||{placeholder:"album",width:"toplist"===a.list.layout?30:21,style:"inset"}).node}},number:{title:c("Number"),className:"sp-list-cell-listnumber",
fixedWidth:32,neededProperties:{track:["number"]},get:function(a){var b=a.list.model.hasStarField;return'<span class="sp-list-listnumber'+(b?"":" sp-list-listnumber-nowplaying")+'">'+(a.track.number||a.index+1)+"</span>"+(b?"":'<span class="sp-icon-nowplaying"></span>')}},ordinal:{title:c("Ordinal"),className:"sp-list-cell-listnumber",fixedWidth:33,neededProperties:{},get:function(a){var b=a.index+1;"toplist"===a.list.layout&&(b+=a.list.options.visualOffset,b=10>b?"0"+b:b);a=a.list.model.hasStarField;
return'<span class="sp-list-listnumber'+(a?"":" sp-list-listnumber-nowplaying")+'">'+b+"</span>"+(a?"":'<span class="sp-icon-nowplaying"></span>')},update:function(a,b){var c=a.index+1;"toplist"===a.list.layout&&(c+=a.list.options.visualOffset,c=10>c?"0"+c:c);b.querySelector(".sp-list-listnumber").innerHTML=c}},share:{title:c("Share"),className:"sp-list-cell-share",fixedWidth:32,neededProperties:{},get:function(){return'<span class="sp-list-share-hitarea" data-button="share"><button type="button" class="sp-list-sharebutton" data-button="share">Share</button></span>'}}};
exports.DEFAULT_FIELDS={"default":{tracks:["star","track","artist","time","album"],artists:["artist"],albums:["album"]},toplist:{tracks:["ordinal","image","track"],artists:["ordinal","image","artist"],albums:["ordinal","image","album"]}}});
