require(["$views/image#Image","$views/strings/fields.lang","$views/utils/html-string","$views/buttons#QuickActionButtons"],function(h,d,j,k){var d=SP.bind(d.get,d),i=exports.LIST_FIELDS={},e=exports.LIST_FIELDS.tracks={},f=exports.LIST_FIELDS.albums={},g=exports.LIST_FIELDS.artists={};e.track={title:d("Track"),className:"sp-list-cell-track",widthWeight:7,neededProperties:{track:["name","explicit"]},get:function(a){var b=a.track.name.decodeForHtml();if("web"===a.list.model.userDevice){var c=k.forItem(a.track,
a.list.item.uri,function(b){b=a.list.view.rows.indexOf(b.target.parentNode.parentNode);return-1<b?b:void 0}),d=j.createElement("span");d.addClass("sp-list-cell-track-name").appendChild(b);return[c.node,d.toString()]}return b}};e["image:track"]={title:d("ImageTrack"),className:"sp-list-cell-track",widthWeight:7,neededProperties:{track:["name","image"],album:["image"]},get:function(a){return'<div class="sp-list-artwork"><img src="'+(a.track.image||a.album.image||"")+'" alt=""></div>'+a.track.name.decodeForHtml()}};
e.artist=g.artist=f.artist={title:d("Artist"),className:"sp-list-cell-artist",widthWeight:3,neededProperties:{artist:["uri","name"],track:["explicit"]},get:function(a){for(var b="",c,d=0,e=a.artists.length;d<e;d++)if(c=a.artists[d],c.name){var f=c.name.decodeForHtml();"spotify:artist:0000000000000000000000"!==c.uri?(b+='<a href="'+c.uri.toSpotifyLink()+'" data-uri="'+c.uri+'">',b+=f,b+="</a>"):b+=f;b+=d<e-1?", ":""}return b}};e.album=f.album={title:d("Album"),className:"sp-list-cell-album",widthWeight:4,
neededProperties:{album:["uri","name"]},get:function(a){var b="",a=a.album;if(a.name){var c=a.name.decodeForHtml();"spotify:album:0000000000000000000000"!==a.uri?(b+='<a href="'+a.uri.toSpotifyLink()+'" data-uri="'+a.uri+'">',b=b+c+"</a>"):b+=c}return b}};e.time={title:d("Time"),className:"sp-list-cell-time",fixedWidth:58,neededProperties:{track:["duration"]},get:function(a){if(0>a.track.duration)return"";var b=Math.round((a.track.duration||0)/1E3),a=Math.floor(b/60),b=Math.round(b%60);return a+":"+
(10>b?"0"+b:b)}};e.popularity=g.popularity=f.popularity={title:d("Popularity"),className:"sp-list-cell-popularity",fixedWidth:82,fixedWidthNoHeader:51,get:function(a){var a=(a="artist"===this.dataProperty?a.artists[0]:a[this.dataProperty])&&a.popularity||0,a=Math.round(35*(a/100)),b=a%3,a=100*((1.5<b?a+(3-b):a-b)/35);return'<span class="sp-popularity-indicator"><span class="sp-popularity-indicator-value" style="width: '+a+'%"></span></span>'}};[["tracks","track"],["artists","artist"],["albums","album"]].forEach(function(a){var b=
i[a[0]];b.popularity=Object.create(b.popularity);b.popularity.neededProperties={};b.popularity.neededProperties[a[1]]=["popularity"];b.popularity.dataProperty=a[1]});e.nowplaying={title:d("NowPlaying"),className:"sp-list-cell-nowplaying",fixedWidth:30,neededProperties:{},get:function(){return'<span class="sp-icon-nowplaying"></span>'}};e.star={title:d("Star"),className:"sp-list-cell-star",fixedWidth:30,neededProperties:{track:["starred"]},get:function(a){return'<span class="sp-icon-star-hitarea">'+
('<span class="sp-icon-star'+(a.track.starred?" sp-icon-starred":"")+'"></span>')+'</span><span class="sp-icon-nowplaying"></span>'}};e.image=g.image=f.image={title:d("Image"),className:"sp-list-cell-image",fixedWidth:33,get:function(a){var b=a.imageOptions||{placeholder:"track",width:"toplist"===a.list.layout?30:21,style:"inset"},c;switch(this.dataProperty){case "track":c=h.forTrack(a.track,b);break;case "artist":c=h.forArtist(a.artists[0],b);break;case "album":c=h.forAlbum(a.album,b)}return c?c.node:
""}};[["tracks","track"],["artists","artist"],["albums","album"]].forEach(function(a){var b=i[a[0]];b.image=Object.create(b.image);b.image.dataProperty=a[1];b.image.neededProperties={};b.image.neededProperties[a[1]]=["image"];"track"===a[1]&&(b.image.neededProperties.album=["image"])});e.number={title:d("Number"),className:"sp-list-cell-listnumber",fixedWidth:33,neededProperties:{track:["number"]},get:function(a){var b=a.list.model.hasStarField;return'<span class="sp-list-listnumber'+(b?"":" sp-list-listnumber-nowplaying")+
'">'+(a.track.number||a.index+1)+"</span>"+(b?"":'<span class="sp-icon-nowplaying"></span>')}};e.ordinal=f.ordinal=g.ordinal={title:d("Ordinal"),className:"sp-list-cell-listnumber",fixedWidth:33,neededProperties:{},get:function(a){var b=a.index+1;"toplist"===a.list.layout&&(b+=a.list.options.visualOffset,b=10>b?"0"+b:b);a=a.list.model.hasStarField;return'<span class="sp-list-listnumber'+(a?"":" sp-list-listnumber-nowplaying")+'">'+b+"</span>"+(a?"":'<span class="sp-icon-nowplaying"></span>')},update:function(a,
b){var c=a.index+1;"toplist"===a.list.layout&&(c+=a.list.options.visualOffset,c=10>c?"0"+c:c);b.querySelector(".sp-list-listnumber").innerHTML=c}};e.share={title:d("Share"),className:"sp-list-cell-share",fixedWidth:32,neededProperties:{},get:function(){return'<span class="sp-list-share-hitarea" data-button="share"><button type="button" class="sp-list-sharebutton" data-button="share">Share</button></span>'}};exports.DEFAULT_FIELDS={"default":{tracks:["star","track","artist","time","album"],artists:["artist"],
albums:["album"]},toplist:{tracks:["ordinal","image","track"],artists:["ordinal","image","artist"],albums:["ordinal","image","album"]}}});
