require(["$api/models","$views/list/fields"],function(i,n){function g(a,c){this.list=c;this.setCollection(a);this.reset();var b=this;i.session.load("device").done(function(){b.userDevice=i.session.device})}var j=n.LIST_FIELDS,s=n.DEFAULT_FIELDS;exports.ListModel=g;g.prototype.setCollection=function(a){var c=this.list.item;this.collection&&(c.removeEventListener("insert",this.lastInsertHandler),c.removeEventListener("remove",this.lastRemoveHandler));this.collection=a;var b=this,a=function(a){b.insertItemsHandler(a)};
this.list.eventHandlers.push({type:"insert",handler:a,obj:c,dom:!1});c.addEventListener("insert",a);this.lastInsertHandler=a;a=function(a){b.removeItemsHandler(a)};this.list.eventHandlers.push({type:"remove",handler:a,obj:c,dom:!1});c.addEventListener("remove",a);this.lastRemoveHandler=a};g.prototype.reset=function(){this.noMoreData=!1;this.context=this.isOptionContext?this.context:void 0;this.offset=0;this.items=[];this.itemData=[];this.uris=[];this.tracksToAddToContext=[];this.snapshots=[];this.lastNumItemsLength=
this.numFailedItems=0;this.maxConcurrentSnapshots=1;this.numRunningSnapshots=0;this.initialized&&this.createContext()};g.prototype.init=function(){this.initialized=!0;this.createContext();this.fields=this.getFields();this.properties=this.getNeededProperties();this.calculateTotalFieldWidths();this.list.dispatchEvent("fields-loaded");this.list.parentList&&this.list.parentList.dispatchEvent("fields-loaded");var a=this;this.list.addEventListener("resize",function(){a.calculateFieldWidths()})};g.prototype.createContext=
function(){if(this.list.options.context)this.context=this.list.options.context,this.isOptionContext=!0;else if(this.list.isTrackList){var a=this,c="tmp_"+(new Date).getTime();i.Playlist.createTemporary(c).done(function(b){b.load("uri","tracks").done(function(){a.context=b;0<a.tracksToAddToContext.length&&(b.tracks.add(a.tracksToAddToContext),a.contextHasUpdates=!0);a.tracksToAddToContext=null})})}};g.prototype.makeInitialSnapshots=function(){var a=this;this.list.options.numItems<=this.numItemsPerBucket&&
(this.list.options.numBuckets=1);var c=this.list.options.numBuckets,b=0,e=function(){"greedy"===a.list.options.fetch?a.offset<(a.totalLength||1)?a.snapshot(null,null,e):(a.list.dispatchEvent("initial-snapshots"),a.list.parentList&&a.list.parentList.dispatchEvent("initial-snapshots")):b++<c&&!a.noMoreData?a.snapshot(null,null,e):(a.list.dispatchEvent("initial-snapshots"),a.list.parentList&&a.list.parentList.dispatchEvent("initial-snapshots"))},d=0,f=function(){d++;if(d===c||a.noMoreData)a.list.removeEventListener("snapshot-load",
f),a.list.dispatchEvent({type:"initial-snapshots-load",snapshots:a.snapshots.slice(0,c)}),a.list.parentList&&a.list.parentList.dispatchEvent({type:"initial-snapshots-load",snapshots:a.snapshots.slice(0,c)}),i.player.load("context","track").done(function(){a.list.view.playerChange(i.player)})};a.list.addEventListener("snapshot-load",f);e()};g.prototype.snapshot=function(a,c,b){if(!this.list.destroyed&&!(this.numRunningSnapshots>=this.maxConcurrentSnapshots)){this.numRunningSnapshots++;var e=this.list.options.numItems;
if(!(e&&this.offset-this.numFailedItems>=e)&&!this.noMoreData){this.list.dispatchEvent("snapshot-start");this.list.parentList&&this.list.parentList.dispatchEvent("snapshot-start");var d=this,f=a||this.offset,a=c||this.numItemsPerBucket;this.offset+=a;this.collection.snapshot(f,a).done(function(a){if(!d.list.destroyed){d.totalLength=a.length;var a=a.toArray(),c=f+a.length;d.snapshots.push({start:f,end:c,numItemsLoaded:0,numItems:a.length});var e=d.snapshots.length-1;d.list.view.nodeHeightAdjusted||
d.list.view.setNodeHeightFromNumItems();var g={type:"snapshot",start:f,end:c,length:a.length,items:[]};if(0===a.length)d.noMoreData=!0,d.list.dispatchEvent(g),d.list.parentList&&d.list.parentList.dispatchEvent(g),0===d.items.length&&(d.list.dispatchEvent({type:"snapshot-load",index:0,items:[]}),d.list.dispatchEvent({type:"empty"}),d.list.dispatchEvent({type:"visually-empty"}));else{for(var l=0,i=a.length,m=f;l<i;l++,m++)d.items[m]=a[l],d.itemData[m]={snapshotIndex:e},d.uris[m]=a[l].uri;d.list.length+=
i;d.list.isTrackList&&!d.isOptionContext&&(d.context&&null===d.tracksToAddToContext?(d.context.tracks.add(a),d.contextHasUpdates=!0):d.tracksToAddToContext=d.tracksToAddToContext.concat(a));d.numRunningSnapshots--;c===d.totalLength&&(d.noMoreData=!0);g.items=d.items.slice(f,c);d.list.dispatchEvent(g);d.list.parentList&&d.list.parentList.dispatchEvent(g);b&&b()}}})}}};g.prototype.getListChain=function(a){for(var c=[],b=this.list.parentList&&a?this.list.parentList:this.list,e=b.previousList||(b.parentList?
b.parentList.previousList:void 0);e;)e.lists&&!a&&(e=e.lists[e.lists.length-1]),c.push(e),e.parentList&&(!e.previousList&&!a)&&(e=e.parentList),e=e.previousList;c.reverse();e=c.length;c.push(b);for(b=b.nextList||(b.parentList?b.parentList.nextList:void 0);b;)b.lists&&!a&&(b=b.lists[0]),c.push(b),b.parentList&&(!b.nextList&&!a)&&(b=b.parentList),b=b.nextList;c.currentIndex=e;return c};g.prototype.getFields=function(){var a,c,b,e,d,f,h;a={tracks:"track-",albums:"album-",artists:"artist-"}[this.list.type]||
"";this.list.options.fields||(this.list.options.fields=s[this.list.layout][this.list.type]);c=this.list.options.fields;b=c.indexOf("star");-1!==b&&"web"===this.userDevice&&(c[b]="nowplaying");b=[];e=0;for(d=c.length;e<d;e++)if("string"===typeof c[e]){f=~" popularity image ".indexOf(" "+c[e]+" ")?a+c[e]:c[e];f="trackartist"===f?"artist":f;b[e]={id:f};"star"===f&&(this.hasStarField=!0);for(h in j[f])b[e][h]=j[f][h];"trackartist"===c[e]&&(b[e].widthWeight=5)}else b[e]=c[e];return b};g.prototype.getNeededProperties=
function(){var a={track:[],album:[],artist:[]},c,b,e,d,f,h,g,i,k;for(e in this.fields)for(f in d=this.fields[e],d.neededProperties){"artist"===f&&(c=!0);"album"===f&&(b=!0);h=d.neededProperties[f];g=0;for(i=h.length;g<i;g++)k=h[g],~(" "+a[f].toString().replace(/,/g," ")+" ").indexOf(" "+k+" ")||a[f].push(k)}c&&(a.track.push("artists"),a.album.push("artists"));b&&a.track.push("album");this.list.isTrackList&&(a.track.push("playable"),~a.track.indexOf("name")||a.track.push("name"),~a.track.indexOf("artists")||
(a.track.push("artists"),~a.artist.indexOf("name")||a.artist.push("name")));return{item:{tracks:a.track,albums:a.album,artists:a.artist}[this.list.type],album:a.album,artist:a.artist}};g.prototype.calculateTotalFieldWidths=function(){var a,c,b,e,d;a=this.fields;c=d=e=0;for(b=a.length;c<b;c++)a[c].fixedWidth="no"===this.list.options.header&&a[c].fixedWidthNoHeader||a[c].fixedWidth,"toplist"===this.list.layout&&(~a[c].id.indexOf("-image")&&a[c].fixedWidth&&(a[c].fixedWidth=40),"ordinal"===~a[c].id&&
a[c].fixedWidth&&(a[c].fixedWidth=30)),a[c].fixedWidth?d+=a[c].fixedWidth:e+=a[c].widthWeight||1;a.totalWeight=e;a.totalFixedWidth=d};g.prototype.calculateFieldWidths=function(){var a,c,b,e,d;a=this.fields;c=this.list.view.fullWidth;a.totalDynamicWidth=c-a.totalFixedWidth;b=0;for(e=a.length;b<e;b++)if(d=a[b],d.fixedWidth?d.width=d.fixedWidth:d.widthWeight?(d.dynamicWidth||(d.dynamicWidth=d.widthWeight/a.totalWeight),d.width=d.dynamicWidth*a.totalDynamicWidth/c):d.width=0,"ordinal"===d.id||"number"===
d.id)d.width=9*this.items.length.toString().length+10};g.prototype.loadItem=function(a,c){if(!this.list.destroyed){var b=this,e=this.list,d=this.properties,f=this.items[a],h={index:a,list:e},g=0<d.artist.length,p=0<d.album.length,k="tracks"===e.type,l="albums"===e.type,n="artists"===e.type,m="custom"===e.type,j=!1,q=!1,r=function(a,d){"album"===d&&(q=!0,h.album=a);"artists"===d&&(j=!0,h.artists=a);var e=g?j:!0;if((p?q:1)&&e){var e=!1,f=b.list.options.fields;if(-1<f.indexOf("ordinal")||-1<f.indexOf("number"))if(f=
b.items.length.toString().length,e=f>b.lastNumItemsLength)b.lastNumItemsLength=f,b.calculateFieldWidths();c(h,e)}};f.load(d.item).done(function(){if(!b.list.destroyed){k&&(h.track=f);l&&(h.album=f,q=!0);if(k&&p){var a=function(){r(f.album,"album")};f.album.load(d.album).done(a).fail(a)}if((k||l)&&g){for(var e=[],a=0,j=f.artists.length;a<j;a++)e.push(f.artists[a].load(d.artist));a=function(){r(f.artists||[],"artists")};i.Promise.join(e).done(a).fail(a)}k&&(!p&&!g)&&c(h);l&&!g&&(h.album=f,c(h));n&&
(h.artists=[f],c(h));m&&c(h);e=b.list.options;e.numItems&&("hidden"===e.unplayable&&!f.playable)&&(b.numFailedItems++,b.snapshot(null,1))}}).fail(function(){b.list.options.numItems&&(b.numFailedItems++,b.snapshot(null,1));c({error:!0})})}};g.prototype.moreWithLimit=function(a){if(!this.list.destroyed&&!this.list.model.noMoreData){var c=this.timeLastFetch||0;if((new Date).getTime()-c>(a||1E3))this.timeLastFetch=(new Date).getTime(),this.isFetchingMore=!0,this.list.dispatchEvent("scroll-fetch"),this.list.parentList&&
this.list.parentList.dispatchEvent("scroll-fetch"),this.list.more();else{var b=this;setTimeout(function(){b.timeLastFetch===c&&(b.timeLastFetch=(new Date).getTime(),b.isFetchingMore=!0,b.list.dispatchEvent("scroll-fetch"),b.list.parentList&&b.list.parentList.dispatchEvent("scroll-fetch"),b.list.more())},100)}}};g.prototype.insertItemsHandler=function(a){var c=a.uris.slice(),b=a.index,e=c.length;if(!(b>this.items.length-1)||this.noMoreData){this.snapshots.push({start:b,end:b+e,numItemsLoaded:0,numItems:e});
for(var d=i.Track,f=this.snapshots.length-1,h=[],g=0;g<e;g++)c[g]=d.fromURI(c[g]),h[g]={snapshotIndex:f};this.list.length+=e;this.totalLength+=e;this.items.splice.apply(this.items,[b,0].concat(c));this.itemData.splice.apply(this.itemData,[b,0].concat(h));this.uris.splice.apply(this.uris,[b,0].concat(a.uris));this.offset+=e;0<this.list.options.numItems&&this.list.view.setNodeHeightFromNumItems();this.list.dispatchEvent({type:"insert",start:b,end:b+e})}};g.prototype.removeItemsHandler=function(a){for(var c=
this.items,b=this.itemData,e=this.uris,d=a.uris,f=a.indices,a=[],g=0,i=f.length;g<i;g++){var j=f[g];j>c.length-1||c[j].uri==d[g]&&a.push(j)}a.sort(function(a,b){return a-b});f=this.list.view.shownIndices;d=f[f.indexOf(a[0])-1]||f[0];for(f=a.length;f--;)g=a[f],b[g].playableChangeHandler&&c[g].removeEventListener("change:playable",b[g].playableChangeHandler),c.splice(g,1),b.splice(g,1),e.splice(g,1),this.list.dispatchEvent({type:"remove",start:g,end:g+1});this.list.length-=a.length;this.totalLength-=
a.length;this.offset-=a.length;0<this.list.options.numItems&&this.list.view.setNodeHeightFromNumItems();f=this.list.view.shownIndices;~this.list.options.fields.indexOf("ordinal")&&(0<a.length&&0<f.length)&&this.list.view.updateOrdinalsFrom(d)}});
