require(["$api/models","$views/list/fields"],function(k,q){function f(a,c){this.list=c;this.setCollection(a);this.reset();var b=this;k.session.load("device").done(function(){b.userDevice=k.session.device})}var u=q.LIST_FIELDS,v=q.DEFAULT_FIELDS;exports.ListModel=f;f.prototype.setCollection=function(a){var c=this.list.item;this.collection&&(c.removeEventListener("insert",this.lastInsertHandler),c.removeEventListener("remove",this.lastRemoveHandler));this.collection=a};f.prototype.setupChangeListeners=
function(){var a=this.list.item,c=this,b=function(a){c.insertItemsHandler(a)};this.list.eventHandlers.push({type:"insert",handler:b,obj:a,dom:!1});a.addEventListener("insert",b);this.lastInsertHandler=b;b=function(a){c.removeItemsHandler(a)};this.list.eventHandlers.push({type:"remove",handler:b,obj:a,dom:!1});a.addEventListener("remove",b);this.lastRemoveHandler=b};f.prototype.reset=function(){this.context=this.list.options.context;this.offset=0;this.items=[];this.itemData=[];this.uris=[];this.tracksToAddToContext=
[];this.snapshots=[];this.totalLength=this.lastNumItemsLength=0};f.prototype.init=function(){this.initialized=!0;this.fields=this.getFields();this.properties=this.getNeededProperties();this.calculateTotalFieldWidths();this.list.dispatchEvent("fields-loaded");this.list.parentList&&this.list.parentList.dispatchEvent("fields-loaded");var a=this;this.list.addEventListener("resize",function(){a.calculateFieldWidths()})};f.prototype.snapshot=function(a,c,b){if(!this.list.destroyed){var e=this.list.options.numItems;
if(!(e&&this.offset>=e)){this.list.dispatchEvent("snapshot-start");this.list.parentList&&this.list.parentList.dispatchEvent("snapshot-start");var d=this,g=a||this.offset,a=c||50;this.offset+=a;this.collection.snapshot(g,a).done(function(a){if(!d.list.destroyed){d.totalLength=a.length;var a=a.toArray(),c=g+a.length;d.snapshots.push({start:g,end:c,numItemsLoaded:0,numItems:a.length});var e=d.snapshots.length-1;d.list.view.nodeHeightAdjusted||d.list.view.setNodeHeightFromNumItems();var f={type:"snapshot",
start:g,end:c,length:a.length,items:[]};if(0===a.length)d.list.dispatchEvent(f),d.list.parentList&&d.list.parentList.dispatchEvent(f),0===d.items.length&&(d.list.dispatchEvent({type:"snapshot-load",index:0,items:[]}),d.list.dispatchEvent({type:"empty"}),d.list.dispatchEvent({type:"visually-empty"}));else{for(var j=0,k=a.length,m=g;j<k;j++,m++)d.items[m]=a[j],d.itemData[m]={snapshotIndex:e},d.uris[m]=a[j].uri;d.list.length+=k;f.items=d.items.slice(g,c);d.list.dispatchEvent(f);d.list.parentList&&d.list.parentList.dispatchEvent(f);
b&&b(g,c)}}})}}};f.prototype.getListChain=function(a){for(var c=[],b=this.list.parentList&&a?this.list.parentList:this.list,e=b.previousList||(b.parentList?b.parentList.previousList:void 0);e;)e.lists&&!a&&(e=e.lists[e.lists.length-1]),c.push(e),e.parentList&&(!e.previousList&&!a)&&(e=e.parentList),e=e.previousList;c.reverse();e=c.length;c.push(b);for(b=b.nextList||(b.parentList?b.parentList.nextList:void 0);b;)b.lists&&!a&&(b=b.lists[0]),c.push(b),b.parentList&&(!b.nextList&&!a)&&(b=b.parentList),
b=b.nextList;c.currentIndex=e;return c};f.prototype.getFields=function(){var a,c,b,e,d,g;this.list.options.fields||(this.list.options.fields=v[this.list.layout][this.list.type]);a=this.list.options.fields;c=a.indexOf("star");-1!==c&&"web"===this.userDevice&&(a[c]="nowplaying");c=[];var h=u[this.list.type];b=0;for(e=a.length;b<e;b++)if("string"===typeof a[b]){d="trackartist"===a[b]?"artist":a[b];c[b]={id:d};"star"===d&&(this.hasStarField=!0);for(g in h[d])c[b][g]=h[d][g];"trackartist"===a[b]&&(c[b].widthWeight=
5)}else c[b]=a[b];return c};f.prototype.getNeededProperties=function(){var a={track:[],album:[],artist:[]},c,b,e,d,g,h,f,l,i;for(e in this.fields)for(g in d=this.fields[e],d.neededProperties){"artist"===g&&(c=!0);"album"===g&&(b=!0);h=d.neededProperties[g];f=0;for(l=h.length;f<l;f++)i=h[f],~(" "+a[g].toString().replace(/,/g," ")+" ").indexOf(" "+i+" ")||a[g].push(i)}c&&(a.track.push("artists"),a.album.push("artists"));b&&a.track.push("album");this.list.isTrackList&&(a.track.push("playable"),~a.track.indexOf("name")||
a.track.push("name"),~a.track.indexOf("artists")||(a.track.push("artists"),~a.artist.indexOf("name")||a.artist.push("name")));return{item:{tracks:a.track,albums:a.album,artists:a.artist}[this.list.type],album:a.album,artist:a.artist}};f.prototype.calculateTotalFieldWidths=function(){var a,c,b,e,d;a=this.fields;c=d=e=0;for(b=a.length;c<b;c++)a[c].fixedWidth="no"===this.list.options.header&&a[c].fixedWidthNoHeader||a[c].fixedWidth,"toplist"===this.list.layout&&(~a[c].id.indexOf("-image")&&a[c].fixedWidth&&
(a[c].fixedWidth=34),"ordinal"===~a[c].id&&a[c].fixedWidth&&(a[c].fixedWidth=30)),a[c].fixedWidth?d+=a[c].fixedWidth:e+=a[c].widthWeight||1;a.totalWeight=e;a.totalFixedWidth=d};f.prototype.calculateFieldWidths=function(){var a,c,b,e,d;a=this.fields;c=this.list.view.fullWidth;a.totalDynamicWidth=c-a.totalFixedWidth;b=0;for(e=a.length;b<e;b++)if(d=a[b],d.fixedWidth?d.width=d.fixedWidth:d.widthWeight?(d.dynamicWidth||(d.dynamicWidth=d.widthWeight/a.totalWeight),d.width=d.dynamicWidth*a.totalDynamicWidth/
c):d.width=0,"ordinal"===d.id||"number"===d.id)d.width=9*this.items.length.toString().length+10};f.prototype.loadItem=function(a,c){if(!this.list.destroyed){var b=this,e=this.list,d=this.properties,g=this.items[a],h={index:a,list:e},f=0<d.artist.length,l=0<d.album.length,i="tracks"===e.type,j="albums"===e.type,q="artists"===e.type,m="custom"===e.type,s=!1,r=!1,t=function(a,b){"album"===b&&(r=!0,h.album=a);"artists"===b&&(s=!0,h.artists=a);var c=f?s:!0;(l?r:1)&&c&&p()},p=function(){var a=!1,d=b.list.options.fields;
if(-1<d.indexOf("ordinal")||-1<d.indexOf("number"))if(d=b.items.length.toString().length,a=d>b.lastNumItemsLength)b.lastNumItemsLength=d,b.calculateFieldWidths();c(h,a)};g.load(d.item).done(function(){if(!b.list.destroyed){i&&(h.track=g);j&&(h.album=g,r=!0);if(i&&l){var a=function(){t(g.album,"album")};g.album.load(d.album).done(a).fail(a)}if((i||j)&&f){for(var c=[],a=0,e=g.artists.length;a<e;a++)c.push(g.artists[a].load(d.artist));a=function(){t(g.artists||[],"artists")};k.Promise.join(c).done(a).fail(a)}i&&
(!l&&!f)&&p();j&&!f&&(h.album=g,p());q&&(h.artists=[g],p());m&&p()}}).fail(function(){c({error:!0})})}};f.prototype.insertItemsHandler=function(a){var c=a.uris.slice(),b=a.index,e=c.length;this.snapshots.push({start:b,end:b+e,numItemsLoaded:0,numItems:e});for(var d=k.Track,g=this.snapshots.length-1,f=[],n=0;n<e;n++)c[n]=d.fromURI(c[n]),f[n]={snapshotIndex:g};this.list.length+=e;this.totalLength+=e;this.items.length<b&&(this.items[b-1]=void 0,this.itemData[b-1]=void 0,this.uris[b-1]=void 0);this.items.splice.apply(this.items,
[b,0].concat(c));this.itemData.splice.apply(this.itemData,[b,0].concat(f));this.uris.splice.apply(this.uris,[b,0].concat(a.uris));this.offset+=e;0<this.list.options.numItems&&this.list.view.setNodeHeightFromNumItems();this.list.dispatchEvent({type:"insert",start:b,end:b+e})};f.prototype.removeItemsHandler=function(a){var c=this.items,b=this.itemData,e=this.uris,a=a.indices,d=a.length;a.sort(function(a,b){return a-b});for(var g=a.length;g--;){var f=a[g];b[f]&&b[f].playableChangeHandler&&c[f].removeEventListener("change:playable",
b[f].playableChangeHandler);c.splice(f,1);b.splice(f,1);e.splice(f,1);this.list.dispatchEvent({type:"remove",start:f,end:f+1})}this.list.length-=d;this.totalLength-=d;this.offset-=d}});
