exports.ListSelection=ListSelection;function ListSelection(){this.indices=[];this.uris=[];this.items=[];this.lists=[];this.isDirectionUp=this.isDirectionDown=!1;this.focus={item:0,list:0};this.origin={item:0,list:0};this.multiselectEnabled=!0}
ListSelection.prototype.addList=function(a){this.indices.push([]);this.uris.push([]);this.items.push([]);var c=this.lists.push(a)-1;0===c&&(this.multiselectEnabled="desktop"===a.model.userDevice);var b=this;a.addEventListener("insert",function(a){b._onItemInsert(c,a)});a.addEventListener("remove",function(a){b._onItemRemove(c,a)})};
ListSelection.prototype.add=function(a,c){var b=this.lists[c];if(b){this.multiselectEnabled||this.clear();var d=this.indices[c],e=this.uris[c],f=this.items[c],g=b.model.uris,i=b.model.items;d.push(a);e.push({index:a,uri:g[a]});f.push({index:a,item:i[a]});d.sort(function(a,b){return a-b});e.sort(function(a,b){return a.index-b.index});f.sort(function(a,b){return a.index-b.index});this.setFocus(a,c);this.isDirectionDown=this.isDirectionUp=!1;b.view.selectItem(a)}};
ListSelection.prototype.remove=function(a,c){var b=this.indices[c],d=this.uris[c],e=this.items[c],f=this.lists[c];if(b){var g=b.indexOf(a);if(~g){b.splice(g,1);d.splice(g,1);e.splice(g,1);f.view.deselectItem(a);b=a+(this.isDirectionDown?-1:this.isDirectionUp?1:0);if(void 0===f.model.items[b]){c=this.isDirectionDown?c-1:c+1;if(void 0===this.lists[c])return;b=this.isDirectionDown?this.lists[c].model.items.length-1:0}this.setFocus(b,c)}}};
ListSelection.prototype.addRange=function(a,c,b){var d=this.indices[b],e=this.uris[b],f=this.items[b],g=this.lists[b],i=g.model.uris,j=g.model.items;if(d){var h=[],l=[],m=[];this.multiselectEnabled||(this.clear(),a=c);for(;a<c+1;a++)~d.indexOf(a)||(h.push(a),l.push({index:a,uri:i[a]}),m.push({index:a,item:j[a]}));d=d.concat(h);e=e.concat(l);f=f.concat(m);d.sort(function(a,b){return a-b});e.sort(function(a,b){return a.index-b.index});f.sort(function(a,b){return a.index-b.index});this.indices[b]=d;
this.uris[b]=e;this.items[b]=f;a=0;for(c=h.length;a<c;a++)g.view.selectItem(h[a])}};ListSelection.prototype.removeRange=function(a,c,b){var d=this.indices[b],e=this.uris[b],f=this.items[b],b=this.lists[b];if(d){var g=d.indexOf(a);~g&&(d.splice(g,c-a+1),e.splice(g,c-a+1),f.splice(g,c-a+1));for(g=a;g<c+1;g++)b.view.deselectItem(g)}};
ListSelection.prototype.addTo=function(a,c){this._removeOverflowingItems(a,c);this.isDirectionUp=c<this.origin.list?!0:c===this.origin.list?a<this.origin.item?!0:!1:!1;this.isDirectionDown=c>this.origin.list?!0:c===this.origin.list?a>this.origin.item?!0:!1:!1;var b={item:a,list:c},d={item:this.focus.item,list:this.focus.list},e=this.isDirectionDown?d:b,d=this.isDirectionDown?b:d;this.multiselectEnabled||(this.clear(),d=e=b);if(e.list===d.list)this.addRange(e.item,d.item,e.list),this.setFocus(a,c);
else for(var b=e.list,f=d.list+1;b<f;b++)b===e.list?this.addRange(e.item,this.lists[b].model.items.length-1,b):b===d.list?this.addRange(0,d.item,b):this.addRange(0,this.lists[b].model.items.length-1,b),b===c&&this.setFocus(a,c)};
ListSelection.prototype.removeTo=function(a,c){var b={item:a,list:c},d={item:this.focus.item,list:this.focus.list},e=this.isDirectionDown?b:d,b=this.isDirectionDown?d:b;if(e.list===b.list)this.removeRange(e.item,b.item,e.list),this.setFocus(a+(this.isDirectionDown?-1:1),c);else for(var d=e.list,f=b.list+1;d<f;d++)d===e.list?this.removeRange(e.item,this.lists[d].model.items.length-1,d):d===b.list?this.removeRange(0,b.item,d):this.removeRange(0,this.lists[d].model.items.length-1,d),d===c&&this.setFocus(a+
(this.isDirectionDown?-1:1),c)};ListSelection.prototype.clear=function(){for(var a=this.lists,c=0,b=a.length;c<b;c++)a[c].view.deselect();for(var a=this.indices,d=this.uris,e=this.items,c=0,b=a.length;c<b;c++)a[c].length=0,d[c].length=0,e[c].length=0;this.isDirectionDown=this.isDirectionUp=!1};ListSelection.prototype.isSelected=function(a,c){var b=this.indices[c];return b?!!~b.indexOf(a):!1};ListSelection.prototype.hasSelection=function(a){return(a=this.indices[a])?0<a.length:!1};
ListSelection.prototype.isInCurrentGroup=function(a,c){if(!this.isSelected(a,c))return!1;var b=this.isDirectionDown?this.origin:this.focus,d=this.isDirectionDown?this.focus:this.origin;return c>b.list&&c<d.list?!0:c===b.list||c===d.list?b.list===c&&a>=b.item?!0:d.list===c&&a<=d.item?!0:!1:!1};ListSelection.prototype.getIndex=function(a,c){var b=this.indices[c];return b?void 0!==b[a]?b[a]:!1:!1};ListSelection.prototype.getSelectionForList=function(a){return this.indices[a]||!1};
ListSelection.prototype.setOrigin=function(a,c){this.indices[c]&&(this.origin.item=a,this.origin.list=c)};ListSelection.prototype.setFocus=function(a,c){this.indices[c]&&(this.focus.item=a,this.focus.list=c,c===this.origin.list&&a===this.origin.item&&(this.isDirectionUp=this.isDirectionDown=!1))};
ListSelection.prototype._removeOverflowingItems=function(a,c){var b=!1,d=this.origin.item,e=this.origin.list;this.isDirectionDown?c<e?b=!0:c===e&&a<d&&(b=!0):this.isDirectionUp&&(c>e?b=!0:c===e&&a>d&&(b=!0));b&&this.removeTo(d+(this.isDirectionDown?1:-1),e)};
ListSelection.prototype.getSelectionData=function(a){for(var c=[],b=[],d=[],e=[],f=this.indices,g=this.uris,i=this.items,j,h,l,m,p=!0,k=0,q=f.length;k<q;k++)if(void 0===a||k===a){j=f[k];h=g[k];l=i[k];0<j.length&&(void 0===m&&(m=k),m!==k&&(p=!1));for(var n=0,r=j.length;n<r;n++)c.push({item:j[n],list:k}),b.push(h[n].uri),d.push(h[n].uri.toSpotifyURL()),e.push(l[n].item)}return{indices:c,uris:b,urls:d,items:e,fromSameList:p}};
ListSelection.prototype._onItemInsert=function(a,c){for(var b=c.start,d=c.end-b,e=this.indices[a],f=this.uris[a],g=this.items[a],i=0,j=e.length;i<j;i++)e[i]>=b&&(e[i]+=d,f[i].index+=d,g[i].index+=d);this.origin.list===a&&this.origin.item>=b&&this.setOrigin(this.origin.item+d,a);this.focus.list===a&&this.focus.item>=b&&this.setFocus(this.focus.item+d,a)};
ListSelection.prototype._onItemRemove=function(a,c){for(var b=c.start,d=c.end,e=d-b,f=this.indices[a],g=this.uris[a],i=this.items[a],j=this.lists[a],h=0,l=f.length;h<l;h++)if(f[h]>=b&&f[h]<d){var m=f[h];f.splice(h,1);g.splice(h,1);i.splice(h,1);j.view.deselectItem(m);h--;l--}else f[h]>=d&&(f[h]=Math.max(f[h]-e,0),g[h].index=Math.max(g[h].index-e,0),i[h].index=Math.max(i[h].index-e,0));this.origin.list===a&&this.origin.item>=b&&(this.origin.item<d?(g=this.focus.item>this.origin.item,g=b+((this.focus.list===
this.origin.list?!g:!(this.focus.list>this.origin.list))?-1:0),f=-1<f.indexOf(g)?g:b,this.setOrigin(f,a)):this.setOrigin(this.origin.item-e,a));this.focus.list===a&&this.focus.item>=b&&(this.focus.item<d?this.setFocus(Math.max(b-1,0),a):this.setFocus(this.focus.item-e,a))};
