var sp=getSpotifyApi(1),$language=sp.require("$util/language"),$presence=sp.require("$unstable/presence"),$react=sp.require("$util/react"),$social=sp.require("$unstable/social"),$staticdata=sp.require("$unstable/staticdata"),$models=sp.require("$api/models"),$feed=sp.require("/scripts/feed"),$recommendations=sp.require("/scripts/recommendations"),$presenceUniqueUserCache=sp.require("/scripts/presence-unique-user-cache"),_currentCanonicalUsername=sp.core.user.canonicalUsername,MAX_INITIAL_ITEMS=30,
_=partial($language.getString,$language.loadCatalog("feed",""),"generic");exports.init=_initializeFeed;var _feed=new $feed.Feed,_eventStream=new $react.EventStream,_throttledStream=$react.throttle(_eventStream,500),_recommendations=new $recommendations.recommendations,startedOnline=1===$models.session.state?!0:!1,_feedInitFlag=!1,_stagger=[2E4,2E4,2E4],_staggeredTimeouts={feed:null},_staggerErrorMessage=!1,$lh=sp.require("/scripts/logging-helper"),_loggingVersion="6",$loggingHelper=new $lh.loggingHelper;
$loggingHelper.init(_loggingVersion);var _feedSection=null,_abTestGroup=sp.core.getAbTestGroupForTest("feed_ab_test");_feed.setLoggingHelper($loggingHelper);_recommendations.setLoggingHelper($loggingHelper);_throttledStream.subscribe(function(a){_feed.addItemsForStates(a,hideFeedThrobber)});function _comparePresenceState(a,b){return _feed.getStickyness(b)-_feed.getStickyness(a)}
function _onInitialPresenceForFeed(a){var b=[],c;for(c in a)Array.prototype.push.apply(b,a[c]);b.sort(_comparePresenceState);_clearErrorMessage();_feedInitFlag=!0;0===b.length&&_feed.isEmpty()&&_feed.noFeedItemsMessage();_feed.addItemsForStates(b.slice(0,MAX_INITIAL_ITEMS),hideFeedThrobber);setTimeout(function(){0!==b.length&&_feed.isEmpty()&&_reloadFeed()},3E4)}
function _getInitialPresenceForFeed(a){a=$presenceUniqueUserCache.uncached("GET",a);a.length&&(a.forEach(function(b){$presenceUniqueUserCache.add("GET",b)}),$presence.getPresenceForUsers(a,_onInitialPresenceForFeed,MAX_INITIAL_ITEMS))}function _onPresenceForUser(a,b){$react.publish(_eventStream,b);$presence.getMostRecentPresence(b)}function _subscribeToPresenceForUsers(a,b){$presence.observePresenceForUsers(a,_onPresenceForUser,!1,b)}
function _showThrobber(a){var b=document.createElement("div"),c=document.createElement("span"),d=b.cloneNode();c.textContent=_("loading");b.appendChild(c);b.appendChild(d);b.className="throbber";a.appendChild(b)}var _throbberHiddenOnce=!1;function _hideThrobber(a){_throbberHiddenOnce||(1===$models.session.state&&logStepTime("feed visible"),_throbberHiddenOnce=!0);var b=a.querySelector(".throbber");b&&(b.style.opacity=0,setTimeout(function(){b&&b.parentNode&&b.parentNode.removeChild(b)},400))}
function hideFeedThrobber(){_hideThrobber(_feedSection)}function _showOfflineMessage(a){logStepTime("showOfflineMessage");_hideThrobber(a);var b=document.createElement("div");b.classList.add("offline-message");b.innerHTML=_("feedUnavailableOffline");a.appendChild(b)}function _hideOfflineMessage(){for(var a=document.querySelectorAll(".offline-message"),b=0,c=a.length;b<c;b+=1)a[b].parentNode.removeChild(a[b])}
function _getSubscriptions(a){sp.social.getSubscriptionUsernames(_currentCanonicalUsername,{onSuccess:a})}function _getPresenceAndSubscribe(a,b){var c=[];b.push(_currentCanonicalUsername);for(var d=0,e=b.length;d<e;d++)$staticdata.getInterestingPeople(b[d])||c.push(b[d]);_getInitialPresenceForFeed(c);_subscribeToPresenceForUsers(c,a)}function _reloadFeed(){logStepTime("reloadFeed");_getSubscriptions(_getPresenceAndSubscribe.bind(null,!1))}
function _onSubscriptionAdded(a){logStepTime("SUBSCRIPTION_ADDED_EVENT fired");_feed.showLoader();a=$presenceUniqueUserCache.uncached("GET",a.detail);a.length&&(a.forEach(function(b){$presenceUniqueUserCache.add("GET",b)}),$presence.getPresenceForUsers(a,function(b){var a=[],d,e,f,g;for(g in b){d=b[g];e=0;for(f=d.length;e<f;e++)d[e].atFront=!0;Array.prototype.push.apply(a,d)}_reloadFeed();setTimeout(function(){_feed.hideLoader();0<a.length&&(_feed.hideNoFeedItemsMessage(),_feed.addItemsForStates(a))},
1800)},5))}function _onLogin(){logStepTime("onLogin");_getSubscriptions(_getPresenceAndSubscribe.bind(null,!0))}function _goOnline(){logStepTime("goOnline");_clearErrorMessage();_hideOfflineMessage();_reloadFeed()}function _initStaggeredReload(a){_staggerFeedReload(a)}
function _staggerFeedReload(a){logStepTime("staggerFeedReload-"+a);a<_stagger.length-1?(logStepTime("staggerFeedReload-"+a+":add stagger retry = "+_stagger[a]),_staggeredTimeouts.feed=setTimeout(function(){_feedInitFlag||($social.loaded&&(logStepTime("staggerFeedReload-"+a+":$social.loaded"),_reloadFeed()),_staggerFeedReload(a+1))},_stagger[a])):(logStepTime("staggerFeedReload-"+a+":_feedInitFlag:"+_feedInitFlag),_staggeredTimeouts.feed=null,_feedInitFlag||(_hideThrobber(_feedSection),_displayErrorMessage(_feedSection)))}
function _displayErrorMessage(a){logStepTime("displayErrorMessage");if(!0!==_staggerErrorMessage){var b=document.createElement("div");b.innerHTML="<p>"+_("notLoadingProperly")+'</p><button class="button reload-btn" onclick="javascript:window.location=window.location">'+_("reload")+"</button>";b.classList.add("error-msg");a.appendChild(b);_staggerErrorMessage=!0}}
function _clearErrorMessage(){for(var a=document.querySelectorAll(".error-msg"),b=0,c=a.length;b<c;b+=1)a[b].parentNode.removeChild(a[b])}var _stepTimeUID=0;function logStepTime(a,b){_stepTimeUID++;$loggingHelper.logClientEvent("TimingStep",a,{sinceAppStart:(b||new Date)-performance.timing.navigationStart,stepTimeId:_stepTimeUID,appStartTime:_beforeRequireTimestamp})}
function _initializeFeed(){logStepTime("before require",_beforeRequireTimestamp);logStepTime("main.init");_feedSection=document.getElementById("feed");document.querySelector(".activity-section-header").innerHTML=_("activity");_recommendations.init(function(){logStepTime("recommendations visible")});_showThrobber(_feedSection);startedOnline?_initStaggeredReload(0):_showOfflineMessage(_feedSection);_feedSection.appendChild(_feed.node);$social.loaded?(logStepTime("$social is ready"),_reloadFeed()):(logStepTime("$social is not ready"),
$social.addEventListener($social.RELATIONS_LOADED_EVENT,function(){logStepTime("RELATIONS_LOADED_EVENT")}),$social.addEventListener($social.RELATIONS_LOADED_EVENT,_reloadFeed));$social.addEventListener($social.RELATIONS_CHANGED_EVENT,function(){logStepTime("RELATIONS_CHANGED_EVENT")});$social.addEventListener($social.RELATIONS_CHANGED_EVENT,_reloadFeed);$models.session.observe($models.EVENT.STATECHANGED,function(){1===$models.session.state&&_goOnline()});sp.core.addEventListener("login",_onLogin);
$social.addEventListener($social.SUBSCRIPTION_ADDED_EVENT,_onSubscriptionAdded);$social.addEventListener($social.SUBSCRIPTION_REMOVED_EVENT,_reloadFeed)};
