var sp=getSpotifyApi(1),$language=sp.require("$util/language"),$presence=sp.require("$unstable/presence"),$react=sp.require("$util/react"),$social=sp.require("$unstable/social"),$staticdata=sp.require("$unstable/staticdata"),$models=sp.require("$api/models"),$promise=sp.require("$util/promise"),$feed=sp.require("/scripts/feed"),$recommendations=sp.require("/scripts/recommendations"),MAX_INITIAL_ITEMS=30,_=partial($language.getString,$language.loadCatalog("feed",""),"generic");exports.init=_initializeFeed;
var _feed=new $feed.Feed,_eventStream=new $react.EventStream,_throttledStream=$react.throttle(_eventStream,500),_recommendations=new $recommendations.recommendations,startedOnline=1===$models.session.state?!0:!1,_feedInitFlag=!1,_stagger=[2E4,2E4,2E4],_staggeredTimeouts={feed:null},_staggerErrorMessage=!1,$lh=sp.require("/scripts/logging-helper"),_loggingVersion="6",$loggingHelper=new $lh.loggingHelper;$loggingHelper.init(_loggingVersion);var _feedSection=null,_abTestGroup=sp.core.getAbTestGroupForTest("feed_ab_test");
_feed.setLoggingHelper($loggingHelper);_recommendations.setLoggingHelper($loggingHelper);_throttledStream.subscribe(function(b){_feed.addItemsForStates(b)});function _comparePresenceState(b,a){return _feed.getStickyness(a)-_feed.getStickyness(b)}
function _onInitialPresenceForFeed(b){var a=[],c;for(c in b)Array.prototype.push.apply(a,b[c]);a.sort(_comparePresenceState);_clearErrorMessage();_feedInitFlag=!0;0===a.length&&_feed.isEmpty()&&_feed.noFeedItemsMessage();_feed.addItemsForStates(a.slice(0,MAX_INITIAL_ITEMS),function(){_hideThrobber(_feedSection)});setTimeout(function(){0!==a.length&&_feed.isEmpty()&&_reloadFeed()},3E4)}
function _getInitialPresenceForFeed(b){$presence.getPresenceForUsers(b,_onInitialPresenceForFeed,MAX_INITIAL_ITEMS)}function _onPresenceForUser(b,a){$react.publish(_eventStream,a);$presence.getMostRecentPresence(a)}function _subscribeToPresenceForUsers(b,a){$presence.observePresenceForUsers(b,_onPresenceForUser,!1,a)}
function _showThrobber(b){var a=document.createElement("div"),c=document.createElement("span"),d=a.cloneNode();c.textContent=_("loading");a.appendChild(c);a.appendChild(d);a.className="throbber";b.appendChild(a)}function _hideThrobber(b){var a=b.querySelector(".throbber");a&&(a.style.opacity=0,setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},400))}
function _showOfflineMessage(b){_hideThrobber(b);var a=document.createElement("div");a.classList.add("offline-message");a.innerHTML=_("feedUnavailableOffline");b.appendChild(a)}function _hideOfflineMessage(){for(var b=document.querySelectorAll(".offline-message"),a=0,c=b.length;a<c;a+=1)b[a].parentNode.removeChild(b[a])}function _fyShuffle(b){var a=b.length,c,d,e;if(0===a)return b;for(;--a;)c=~~(Math.random()*(a+1)),d=b[a],e=b[c],b[a]=e,b[c]=d;return b}
function _getSubscriptions(b){sp.social.getSubscriptionUsernames(sp.core.user.canonicalUsername,{onSuccess:b})}function _getPresenceAndSubscribe(b,a){for(var c=[],d=0,e=a.length;d<e;d++)$staticdata.getInterestingPeople(a[d])||c.push(a[d]);_getInitialPresenceForFeed(c);_subscribeToPresenceForUsers(c,b)}function _reloadFeed(){_getSubscriptions(_getPresenceAndSubscribe.bind(null,!1))}function _onRelationsUpdated(){_reloadFeed()}
function _onSubscriptionAdded(b){_feed.showLoader();$presence.getPresenceForUsers(b.detail,function(a){var b=[],d;for(d in a){for(var e=0;e<a[d].length;e++)a[d][e].atFront=!0;Array.prototype.push.apply(b,a[d])}_onRelationsUpdated();setTimeout(function(){_feed.hideLoader();0<b.length&&(_feed.hideNoFeedItemsMessage(),_feed.addItemsForStates(b))},1800)},5)}function _onLogin(){_getSubscriptions(_getPresenceAndSubscribe.bind(null,!0))}
function _goOnline(){_clearErrorMessage();_hideOfflineMessage();_onRelationsUpdated()}function _initStaggeredReload(b){_staggerFeedReload(b)}function _staggerFeedReload(b){b<_stagger.length-1?_staggeredTimeouts.feed=setTimeout(function(){_feedInitFlag||($social.loaded&&_reloadFeed(),_staggerFeedReload(b+1))},_stagger[b]):(_staggeredTimeouts.feed=null,_feedInitFlag||(_hideThrobber(_feedSection),_displayErrorMessage(_feedSection)))}
function _displayErrorMessage(b){if(!0!==_staggerErrorMessage){var a=document.createElement("div");a.innerHTML="<p>"+_("notLoadingProperly")+'</p><button class="button reload-btn" onclick="javascript:window.location=window.location">'+_("reload")+"</button>";a.classList.add("error-msg");b.appendChild(a);_staggerErrorMessage=!0}}function _clearErrorMessage(){for(var b=document.querySelectorAll(".error-msg"),a=0,c=b.length;a<c;a+=1)b[a].parentNode.removeChild(b[a])}
function _initializeFeed(){_feedSection=document.getElementById("feed");document.querySelector(".activity-section-header").innerHTML=_("activity");_recommendations.init();_showThrobber(_feedSection);startedOnline?_initStaggeredReload(0):_showOfflineMessage(_feedSection);_feedSection.appendChild(_feed.node);$social.loaded?_onRelationsUpdated():$social.addEventListener($social.RELATIONS_LOADED_EVENT,_onRelationsUpdated);$social.addEventListener($social.RELATIONS_CHANGED_EVENT,_onRelationsUpdated);$models.session.observe($models.EVENT.STATECHANGED,
function(){1===$models.session.state&&_goOnline()});sp.core.addEventListener("login",_onLogin);$social.addEventListener($social.SUBSCRIPTION_ADDED_EVENT,_onSubscriptionAdded);$social.addEventListener($social.SUBSCRIPTION_REMOVED_EVENT,_onRelationsUpdated)};
