var sp=getSpotifyApi(),dom=sp.require("$util/dom"),events=sp.require("$util/events"),language=sp.require("$util/language"),i18n=sp.require("scripts/i18n"),social=sp.require("$unstable/social"),socialgraph=sp.require("scripts/socialgraph"),staticdata=sp.require("$unstable/staticdata"),views=sp.require("$api/views"),CATALOG=language.loadCatalog("feed",""),_=partial(language.getString,CATALOG,"recommendations"),firstLoadOfApp=!0,loggingHelper,testGroup,Counter,hideRecommend,Recommendations=function(){var b=
dom.queryOne("#recommended"),a=[],d=[],c=sp.core.user,f=null,e={},g,r=!0;hideRecommend=function(){var b={followCount:Counter.getFollowCount(),dismissCount:Counter.getDismissCount()};loggingHelper.logClientEvent("recommendation close action","close button",b);j()};var i=function(){socialgraph.getRecommendations([socialgraph.ReasonType.EDITORIAL,socialgraph.ReasonType.FACEBOOK,socialgraph.ReasonType.SUBSCRIPTION_OF_SUBSCRIPTION,socialgraph.ReasonType.MY_SUBSCRIBER],function(g){g.length<socialgraph.RECOMMENDATION_BATCH_SIZE&&
(r=!1);if(g.length){for(var s=[],p=[],q=[],h=0,i=0,l=g.length;h<l;h++){for(var k=!1;i<d.length;i++)g[h].user.data.canonicalUsername===d[i].user.data.canonicalUsername&&(k=!0);g[h].user.data.canonicalUsername in e&&(k=!0);!k&&g[h].isFeatured?s.push(g[h]):!k&&g[h].isFacebook?p.push(g[h]):!k&&g[h].isRecommended&&q.push(g[h])}p.sort(function(){return 0.5-Math.random()});q.sort(function(){return 0.5-Math.random()});g=s.concat(p,q);a=a.concat(g);if(0===a.length)j();else{n(!0);var m=function(){0===f&&2>
d.length&&(n(!1),b.classList.add("double"))};f?m():social.getSubscriptionCount(c.canonicalUsername,function(b){f=b[0];m()},t);social.addEventListener(social.SUBSCRIPTION_ADDED_EVENT,u);social.addEventListener(social.DISMISS_EVENT,u)}}else j()},t)},t=function(){j()},u=function(g){for(var c=0,e=0,i=g.detail,c=0;c<d.length;c++)for(e=0;e<i.length;e++)i[e]===d[c].user.data.canonicalUsername&&(d[c].removeNode(),"subscribe"===g.type&&(f+=1,b.classList.remove("double")));for(c=0;c<a.length;c++)for(e=0;e<
i.length;e++)i[e]===a[c].user.data.canonicalUsername&&a.splice(c,1)},n=function(b){var c=a[0];a.splice(0,1);c&&c.user.loaded?l(c,b):c?sp.social.getUsersBatch([c.user.data.canonicalUsername],{onSuccess:function(a){c.user.update(a[0]);c.user.loaded=!0;l(c,b)},onFailure:function(){l(c,b)}}):hideRecommend()},l=function(c,a){if(!c.user.data.icon&&c.user.data.name===c.user.data.username)m();else{if(b.classList.contains("hidden")){b.classList.remove("hidden");g&&g();dom.queryOne("header",b).innerHTML=_("recommendedPeople");
var e=dom.queryOne("header",b),i=new dom.Element("a",{innerHTML:_("close")});i.addEventListener("click",hideRecommend);dom.adopt(e,i)}var h=new RecommendedUser(c,a);-1===d.indexOf(h)&&h.node?a?(e=dom.queryOne("header",b),b.insertBefore(h.node,e.nextSibling),d.unshift(h)):(h.node.classList.add("second"),dom.adopt(b,h.node),d.push(h)):n(a);h.node.addEventListener("nodeRemoved",function(b){d.splice(d.indexOf(h),1);(0===f||0===d.length)&&m(b.firstPosition)})}},m=function(b){0<a.length?n(b):0===a.length&&
r&&i()},j=function(){b.classList.add("close");b.addEventListener("webkitAnimationEnd",function(){b.classList.add("hidden");dom.destroy(b)})},v=0,w=0;Counter={dismiss:function(){v++},follow:function(){w++},getDismissCount:function(){return v},getFollowCount:function(){return w}};return{init:function(b){g=b;sp.social.getSubscriptionUsernames(sp.core.user.canonicalUsername,{onSuccess:function(b){b.map(function(b){e[b]=!0});i()},onFailure:i})},hide:function(){j()},setLoggingHelper:function(b){loggingHelper=
b;testGroup=loggingHelper.getTestGroup()}}},MAX_EXTRA_ENTRIES=5,RecommendedUser=function(b,a){this.node=this.reason=this.user=null;this.firstPosition=a;this.removed=!1;this.events=new events.EventHandler(this);this.target=new events.EventTarget;this.init(b)};RecommendedUser.prototype.init=function(b){this.user=b.user;this.reason=b.reason;var b=b.user.data,a={},d=staticdata.getInterestingPeople(b.canonicalUsername);if(d){for(var c in b)a[c]=b[c];for(var f in d)a[f]=d[f];this.user.data=a}this.createNode()};
RecommendedUser.prototype.createNode=function(){var b=this,a=new dom.Element("div",{className:"recommended-item"}),d=new views.Image(this.user.data.picture?this.user.data.picture:"",this.user.data.uri),c=new dom.Element("p",{className:"content"}),f=new dom.Element("a",{innerHTML:b.user.data.name?b.user.data.name:b.user.data.canonicalUsername,href:b.user.data.uri}),e=new dom.Element("p",{className:"name"});e.appendChild(f);f=new dom.Element("span",{className:"type"});b.renderNumberOfFollowers(f);var g=
this.buildFollowButton();g.addEventListener("click",function(){Counter.follow();loggingHelper.logClientEvent("recommendation follow action","follow button",b.user.data);social.subscribe(b.user.data.canonicalUsername,b.removeNode.bind(b),b.removeNode.bind(b))});c.appendChild(e);c.appendChild(f);c.appendChild(g);e=new dom.Element("p",{className:"listen-to-content"});a.appendChild(d.node);a.appendChild(c);e.innerHTML=_("loadingTopMusic");this.renderInfoAboutFollowers(e);a.appendChild(e);d=new dom.Element("span",
{innerHTML:"\u00d7",className:"dismiss-link"});d.addEventListener("click",function(){Counter.dismiss();loggingHelper.logClientEvent("recommendation dismiss action","dismiss link",b.user.data);social.dismiss(b.user.data.canonicalUsername,b.removeNode.bind(b),b.removeNode.bind(b))});a.appendChild(d);this.node=a;a.addEventListener("click",function(c){if("A"===c.target.tagName){var a={element:"link"};c.target.className.match(/sp-image/)&&(a.element="image");a.uri=c.target.href;loggingHelper.logClientEvent(c.target.href===
b.user.data.uri?"recommendation link click":"recommendation reason click",a.element,a)}})};RecommendedUser.prototype.buildFollowButton=function(){var b=new dom.Element("button",{className:"follow-button"}),a=new dom.Element("div",{className:"follow-icon-add"}),d=new dom.Element("span",{className:"follow-button-text"}),c=new dom.Element("span",{className:"follow-button-background"});d.appendChild(a);d.innerHTML+=_("follow");b.appendChild(d);b.appendChild(c);return b};
RecommendedUser.prototype.getTopArtists=function(b){var a=this,d=function(c){c=c.artists;if(0<c.length){for(var d=_("listeningTo")+" ",e=0;e<=MAX_EXTRA_ENTRIES&&e<c.length;e+=1)d+='<a href="'+c[e].uri+'">'+c[e].name+"</a>",d=e===MAX_EXTRA_ENTRIES||e===c.length-1?d+".":d+", ";b.innerHTML=d}else a.getPlaylists(b)};firstLoadOfApp?(setTimeout(function(){sp.social.getToplist("artist","user",a.user.data.canonicalUsername,{onSuccess:d})},15E3),firstLoadOfApp=!1):sp.social.getToplist("artist","user",a.user.data.canonicalUsername,
{onSuccess:d})};
RecommendedUser.prototype.getPlaylists=function(b){socialgraph.getTopPlaylists(this.user.data.canonicalUsername,function(a){if(0<a.length){for(var d=i18n.plural(a.length,_("fewPlaylists"),_("manyPlaylists"),_("fewPlaylists"))+" ",c=0;c<=MAX_EXTRA_ENTRIES&&c<a.length;c++)var f=a[c],d=d+('<a href="'+f.data.uri+'">'+f.data.name.decodeForHTML()+"</a>"),d=c===MAX_EXTRA_ENTRIES||c===a.length-1?d+".":d+", ";b.innerHTML=d}},function(){console.log("Failed to get top playlists");b.innerHTML=""})};
RecommendedUser.prototype.renderNumberOfFollowers=function(b){var a=this;social.getSubscriberCount(this.user,function(d){b.innerHTML=i18n.number(d[0])+" "+i18n.plural(d[0],_("follower"),_("manyFollowers"),_("fewFollowers"));a.subscribers=d[0]},function(){})};
RecommendedUser.prototype._handleMutualSubscribers=function(b,a,d){for(var c=0,f=[],e=0;e<d.length;e++)d[e]in a&&(c++,f.push(d[e]));0===c?this.getTopArtists(b):(a=[f[0]],1<c&&a.push(f[1]),2<c&&a.push(f[2]),sp.social.getUsersBatch(a,{onSuccess:function(a){if(1===c)a="<a href="+a[0].uri+">"+a[0].name+"</a>.",b.innerHTML=language.format(_("followedByPeople"),a);else if(2===c)a="<a href="+a[0].uri+">"+a[0].name+"</a> "+_("and")+" <a href="+a[1].uri+">"+a[1].name+"</a>.",b.innerHTML=language.format(_("followedByPeople"),
a);else if(3===c)a="<a href="+a[0].uri+">"+a[0].name+"</a>,  <a href="+a[1].uri+">"+a[1].name+"</a> "+_("and")+" <a href="+a[2].uri+">"+a[2].name+"</a>.",b.innerHTML=language.format(_("followedByPeople"),a);else if(2<c){var d=c-2,a="<a href="+a[0].uri+">"+a[0].name+"</a>, <a href="+a[1].uri+">"+a[1].name+"</a> ";b.innerHTML=language.format(_("followedByPeople"),a)+language.format(_("andOthers"),d)}firstLoadOfApp=!1},onFailure:this.getTopArtists.bind(this,b)}))};
RecommendedUser.prototype.renderInfoAboutFollowers=function(b){var a=this;1===a.reason?sp.social.getSubscriptionUsernames(sp.core.user.username,{onSuccess:function(d){for(var c={},f=0;f<d.length;f++)c[d[f]]=!0;sp.social.getSubscriberUsernames(a.user.canonicalName,{onSuccess:a._handleMutualSubscribers.bind(a,b,c),onFailure:a.getTopArtists.bind(a,b)})},onFailure:a.getTopArtists.bind(a,b)}):a.getTopArtists(b)};
RecommendedUser.prototype.removeNode=function(){if(!this.removed&&this.node){var b=this;this.removed=!0;this.node.classList.add("close");this.node.addEventListener("webkitAnimationEnd",function(){dom.destroy(b.node)});setTimeout(function(){var a=document.createEvent("CustomEvent");a.initCustomEvent("nodeRemoved",!0,!1);a.firstPosition=b.firstPosition;b.node.dispatchEvent(a)},500);this.events.removeAll()}};exports.recommendations=Recommendations;
