var sp=getSpotifyApi(),base=sp.require("$util/base"),dom=sp.require("$util/dom"),events=sp.require("$util/events"),fs=sp.require("$util/fs"),language=sp.require("$util/language"),i18n=sp.require("scripts/i18n"),models=sp.require("$api/models"),social=sp.require("$unstable/social"),socialgraph=sp.require("scripts/socialgraph"),staticdata=sp.require("$unstable/staticdata"),views=sp.require("$api/views"),CATALOG=language.loadCatalog("feed",""),_=partial(language.getString,CATALOG,"recommendations"),
firstLoadOfApp=!0,loggingHelper,testGroup,Counter,hideRecommend,Recommendations=function(){var a=dom.queryOne("#recommended"),c=[],b=[],f=sp.core.user,e=null;hideRecommend=function(){var a={followCount:Counter.getFollowCount(),dismissCount:Counter.getDismissCount()};loggingHelper.logClientEvent("recommendation close action","close button",a);l()};var d=function(){var b=[],d=[],n=[];socialgraph.getRecommendations([socialgraph.ReasonType.EDITORIAL,socialgraph.ReasonType.FACEBOOK,socialgraph.ReasonType.SUBSCRIPTION_OF_SUBSCRIPTION,
socialgraph.ReasonType.MY_SUBSCRIBER],function(h){for(var g=0,k=h.length;g<k;g++)h[g].isFeatured?b.push(h[g]):h[g].isFacebook?d.push(h[g]):h[g].isRecommended&&n.push(h[g]);d.sort(function(){return 0.5-Math.random()});n.sort(function(){return 0.5-Math.random()});h=b.concat(d,n);c=c.concat(h);if(0===c.length)l();else{m(!0);var j=function(){0===e&&(m(!1),a.classList.add("double"))};e?j():social.getSubscriptionCount(f.canonicalUsername,function(a){e=a[0];j()},i);social.addEventListener(social.SUBSCRIPTION_ADDED_EVENT,
q);social.addEventListener(social.DISMISS_EVENT,q)}},i)},i=function(){l();console.log("SOCIAL FAILS")},q=function(c){for(var f=c.detail,d=0;d<b.length;d++)for(var h=0;h<f.length;h++)f[h]===b[d].user.data.canonicalUsername&&(b[d].removeNode(),"subscribe"===c.type&&(e+=1,a.classList.remove("double")))},m=function(a){var b=c[0];c.splice(0,1);b&&b.user.loaded?k(b,a):sp.social.getUsersBatch([b.user.data.canonicalUsername],{onSuccess:function(c){b.user.update(c[0]);b.user.loaded=!0;k(b,a)},onFailure:function(){k(b,
a)}})},k=function(c,f){if(!c.user.data.icon&&c.user.data.name===c.user.data.username)r();else{if(a.classList.contains("hidden")){a.classList.remove("hidden");dom.queryOne("header",a).innerHTML=_("recommendedPeople");var d=dom.queryOne("header",a),h=new dom.Element("a",{innerHTML:_("close")});h.addEventListener("click",hideRecommend);dom.adopt(d,h)}var g=new RecommendedUser(c,f);-1===b.indexOf(g)&&g.node?f?(d=dom.queryOne("header",a),a.insertBefore(g.node,d.nextSibling),b.unshift(g)):(g.node.classList.add("second"),
dom.adopt(a,g.node),b.push(g)):m(f);g.node.addEventListener("nodeRemoved",function(a){b.splice(b.indexOf(g),1);(0===e||0===b.length)&&r(a.firstPosition)})}},r=function(a){0<c.length?m(a):0===c.length&&d()},l=function(){a.classList.add("close");a.addEventListener("webkitAnimationEnd",function(){a.classList.add("hidden");dom.destroy(a)})},j=0,p=0;Counter={dismiss:function(){j++;10<=j&&hideRecommend()},follow:function(){p++;10<=p&&hideRecommend()},getDismissCount:function(){return j},getFollowCount:function(){return p}};
return{init:function(){d()},hide:function(){l()},setLoggingHelper:function(a){loggingHelper=a;testGroup=loggingHelper.getTestGroup()}}},RECOMMENDATION_REASON={"0":"",1:"Followed by your followings",2:"Your follower",3:"Similar taste",4:"Facebook friend"},MAX_EXTRA_ENTRIES=5,RecommendedUser=function(a,c){this.node=this.reason=this.user=null;this.firstPosition=c;this.removed=!1;this.events=new events.EventHandler(this);this.target=new events.EventTarget;this.init(a)};
RecommendedUser.prototype.init=function(a){this.user=a.user;this.reason=a.reason;var a=a.user.data,c={},b=staticdata.getInterestingPeople(a.canonicalUsername);if(b){for(var f in a)c[f]=a[f];for(var e in b)c[e]=b[e];this.user.data=c}this.createNode()};
RecommendedUser.prototype.createNode=function(){var a=this,c=new dom.Element("div",{className:"recommended-item"}),b=new views.Image(this.user.data.picture?this.user.data.picture:"",this.user.data.uri),f=new dom.Element("p",{className:"content"}),e=new dom.Element("a",{innerHTML:a.user.data.name?a.user.data.name:a.user.data.canonicalUsername,href:a.user.data.uri}),d=new dom.Element("p",{className:"name"});d.appendChild(e);e=new dom.Element("span",{className:"type"});a.renderNumberOfFollowers(e);var i=
this.buildFollowButton();i.addEventListener("click",function(){Counter.follow();loggingHelper.logClientEvent("recommendation follow action","follow button",a.user.data);social.subscribe(a.user.data.canonicalUsername,a.removeNode.bind(a),a.removeNode.bind(a))});f.appendChild(d);f.appendChild(e);f.appendChild(i);d=new dom.Element("p",{className:"listen-to-content"});c.appendChild(b.node);c.appendChild(f);d.innerHTML=_("loadingTopMusic");this.renderInfoAboutFollowers(d);c.appendChild(d);b=new dom.Element("span",
{innerHTML:"\u00d7",className:"dismiss-link"});b.addEventListener("click",function(){Counter.dismiss();loggingHelper.logClientEvent("recommendation dismiss action","dismiss link",a.user.data);social.dismiss(a.user.data.canonicalUsername,a.removeNode.bind(a),a.removeNode.bind(a))});c.appendChild(b);this.node=c;c.addEventListener("click",function(c){if("A"===c.target.tagName){var b={element:"link"};c.target.className.match(/sp-image/)&&(b.element="image");b.uri=c.target.href;loggingHelper.logClientEvent(c.target.href===
a.user.data.uri?"recommendation link click":"recommendation reason click",b.element,b)}})};RecommendedUser.prototype.buildFollowButton=function(){var a=new dom.Element("button",{className:"follow-button"}),c=new dom.Element("div",{className:"follow-icon-add"}),b=new dom.Element("span",{className:"follow-button-text"}),f=new dom.Element("span",{className:"follow-button-background"});b.appendChild(c);b.innerHTML+=_("follow");a.appendChild(b);a.appendChild(f);return a};
RecommendedUser.prototype.getTopArtists=function(a){var c=this,b=function(b){b=b.artists;if(0<b.length){for(var e=_("listeningTo")+" ",d=0;d<=MAX_EXTRA_ENTRIES&&d<b.length;d+=1)e+='<a href="'+b[d].uri+'">'+b[d].name+"</a>",e=d===MAX_EXTRA_ENTRIES||d===b.length-1?e+".":e+", ";a.innerHTML=e}else c.getPlaylists(a)};firstLoadOfApp?(setTimeout(function(){sp.social.getToplist("artist","user",c.user.data.canonicalUsername,{onSuccess:b})},15E3),firstLoadOfApp=!1):sp.social.getToplist("artist","user",c.user.data.canonicalUsername,
{onSuccess:b})};RecommendedUser.prototype.getPlaylists=function(a){socialgraph.getTopPlaylists(this.user.data.canonicalUsername,function(c){if(0<c.length){for(var b=_("playlists")+" ",f=0;f<=MAX_EXTRA_ENTRIES&&f<c.length;f++)var e=c[f],b=b+('<a href="'+e.data.uri+'">'+e.data.name.decodeForHTML()+"</a>"),b=f===MAX_EXTRA_ENTRIES||f===c.length-1?b+".":b+", ";a.innerHTML=b}},function(){console.log("Failed to get top playlists");a.innerHTML=""})};
RecommendedUser.prototype.renderNumberOfFollowers=function(a){var c=this;social.getSubscriberCount(this.user,function(b){a.innerHTML=i18n.number(b[0])+" "+(1===b[0]?_("follower"):_("followers"));c.subscribers=b[0]},function(){})};
RecommendedUser.prototype._handleMutualSubscribers=function(a,c,b){for(var f=0,e=[],d=0;d<b.length;d++)b[d]in c&&(f++,e.push(b[d]));if(0===f)this.getTopArtists(a);else{c=[e[0]];1<f&&c.push(e[1]);var i=this.subscribers-e.length;sp.social.getUsersBatch(c,{onSuccess:function(b){var c="<a href="+b[0].uri+">"+b[0].name+"</a>";b[1]&&(i--,c+=", <a href="+b[1].uri+">"+b[1].name+"</a>");a.innerHTML=language.format(_("followedByPeople"),c,i18n.number(i));firstLoadOfApp=!1},onFailure:this.getTopArtists.bind(this,
a)})}};RecommendedUser.prototype.renderInfoAboutFollowers=function(a){var c=this;1===c.reason?sp.social.getSubscriptionUsernames(sp.core.user.username,{onSuccess:function(b){for(var f={},e=0;e<b.length;e++)f[b[e]]=!0;sp.social.getSubscriberUsernames(c.user.canonicalName,{onSuccess:c._handleMutualSubscribers.bind(c,a,f),onFailure:c.getTopArtists.bind(c,a)})},onFailure:c.getTopArtists.bind(c,a)}):c.getTopArtists(a)};
RecommendedUser.prototype.removeNode=function(){if(!this.removed&&this.node){var a=this;this.removed=!0;this.node.classList.add("close");this.node.addEventListener("webkitAnimationEnd",function(){dom.destroy(a.node)});setTimeout(function(){var c=document.createEvent("CustomEvent");c.initCustomEvent("nodeRemoved",!0,!1);c.firstPosition=a.firstPosition;a.node.dispatchEvent(c)},500);this.events.removeAll()}};exports.recommendations=Recommendations;
