require("$api/models $shared/events#EventHandler $views/throbber#Throbber scripts/utils scripts/env#Environment scripts/config".split(" "),function(g,k,l,e,i,f){function d(a,b,c){this.data=a;this.view=b;this._logger=c;this._hasRunOnce=!1;this._oldQuery="";this._lastRedirect={query:"",fuzzy:""}}d.prototype.init=function(){this.listen()};d.prototype.listen=function(){this._events=new k(this);g.application.load("arguments").done(this.argumentsLoaded.bind(this));g.application.addEventListener("arguments",
this.argumentsChanged.bind(this))};d.prototype.argumentsChanged=function(a){this._isLoadedTwice=this._hasRunOnce=!1;this.argumentsLoaded(a)};d.prototype.argumentsLoaded=function(a){if(!this._hasRunOnce)if(this._hasRunOnce=!0,this._dispose(),this.view.dispose(),this.data.dispose(),this.view.init(),a=a.arguments?a.arguments:a.data.arguments,e.areArgumentsOK(a)){var b=1<a.length?a.splice(-1,1).join():null;b&&"E"===this._logger.getTestVersion()&&f.CATEGORIES.push("users");b&&!e.isCategoryProper(b)&&(a.push(b),
b=null);var c="";this.query=c=a.join(i.desktop?":":"/");this.category=b;this.view.setQueryAndCategory(c,b);b?this.initLoner(c,b):this.initHeader(c,b)}else this.view._onError.call(this.view)};d.prototype.initHeader=function(a){document.documentElement.addClass("overflow-hidden");this.view.showThrobber({element:"searchResult"});this.view.setSmallSize();var b={amount:this.view.cols+2};"D"===this._logger.getTestVersion()&&(b.keepTracks=!0,b.categories=f.SEARCH_CATEGORIES);var c=this;this.execute(a,b,
function(b){var h=b[0];"E"===c._logger.getTestVersion()&&"undefined"!==typeof b[1]&&(h.users=b[1]);if("D"===c._logger.getTestVersion()&&c.view.doForward){if("undefined"===typeof h.tracks){c.data.getFuzzyMatch().done(function(a){c._hasRunOnce=!1;c.query!==c._oldQuery&&a!==c._oldQuery?(c._oldQuery=c.query,c._lastRedirect={query:c.query,fuzzy:a},c._logger.clientEvent("fuzzy-match-redirect",c._lastRedirect),g.application.openURI("spotify:search:"+a)):(c.view.doForward=!1,c.argumentsLoaded({arguments:[c.query]}))});
return}delete h.tracks;delete c.data.maxLengths[a].tracks}c.view.doForward||(c.view.doForward=!0);0<Object.keys(h).length&&(c.view.createHeaderNodes(h,c.data.maxLengths[a]),b=e.trimData(c.view.cols,h),c.view.addData(b,{realPlaceholders:!0}),c.view.repaintHeader(),c._headerListen());c._setFuzzyMatch();"D"===c._logger.getTestVersion()&&(c._lastRedirect.query===c._oldQuery&&c._lastRedirect.fuzzy===c.query)&&(c.view.setBackToOriginalQueryLink(c._oldQuery),c._events.listen(document.getElement(".back-to-original"),
"click",c._onBackToOriginal.bind(c)));c._oldQuery=c.query;c.view.hideThrobber()})};d.prototype._onBackToOriginal=function(a){if("D"===this._logger.getTestVersion()){a.preventDefault();this.view.doForward=!1;if("A"===a.target.nodeName){var b={type:a.target.className,value:a.target.textContent};this._lastRedirect={query:"",fuzzy:""};this._logger.clientEvent("back-to-original-query-click",b)}g.application.openURI("spotify:search:"+b.value)}};d.prototype.onFail=function(a,b){b._latestTime===this._latestTime&&
this.view._onError()};d.prototype.initLoner=function(a,b){this.view.showThrobber();this.view.setBigSize();this.lonerIndex=0;var c={categories:[b],amount:f.LONER_AMOUNT},d=this;"users"===b&&"E"===this._logger.getTestVersion()?(this.data.maxLengths[a]={},c.start=0,this.data.getUsers(a,c).done(function(c){var f={};f.users=c;d._doLoner(f,a,b)})):this.execute(this.query,c,function(c){d._doLoner(c[0],a,b)})};d.prototype._doLoner=function(a,b,c){this.lonerIndex+=f.LONER_AMOUNT;this.view.createLonerNodes(c,
this.data.maxLengths[b][c]);this.view.addData(a);this._lonerListen();this._resizeLoner();this.view.hideThrobber()};d.prototype.execute=function(a,b,c,d){b=b||{};b.start=b.start||0;b.amount=b.amount||50;b.categories=b.categories||f.SEARCH_CATEGORIES;b.keepTracks=b.keepTracks||!1;var h=this.data.loadSearch(a,b),g=+new Date;this._latestTime=g;h._latestTime=g;var j=this,e;e=d?function(a){d(a)}:function(a){j.onFail(a,h,null)};h.done(function(d){j.onLoadSearch(d,a,g,b,c,e)}).fail(e)};d.prototype.onLoadSearch=
function(a,b,c,d,h,f){var e=d.categories.indexOf("tracks");-1<e&&!d.keepTracks&&(d.categories.splice(e,1),i.web&&!this.category&&this.view.paintList(a.tracks));e=[];e.push(this.data.getData(a,b,d));null===this.category&&("E"===this._logger.getTestVersion()&&i.desktop)&&e.push(this.data.getUsers(this.query,d));a=g.Promise.join(e);a._latestTime=c;a.done(function(a){h(a)}).fail(f)};d.prototype._setFuzzyMatch=function(){var a=this,b=[],c=a._logger.getTestVersion();"C"!==c&&b.push(a.data.getFuzzyMatch());
("B"===c||"C"===c)&&b.push(a.data.getTopHitFromSuggest(a.query));g.Promise.join(b).always(function(b){var d=[];"undefined"!==typeof b[0]&&d.push({type:"C"===c?"suggest-fuzzy-match":"fuzzy-match",name:b[0]});"undefined"!==typeof b[1]&&d.push({type:"suggest-fuzzy-match",name:b[1]});1<d.length&&d[0].name.toLowerCase()===d[1].name.toLowerCase()&&(d[0].type=d[0].type+","+d[1].type,d.splice(-1,1));a.view.setFuzzyMatch(d)})};d.prototype._headerListen=function(){this._events.listen(window,"resize",this._onResizeEvent).listen(document.body,
"click",this._onClickEvent)};d.prototype._lonerListen=function(){this._events.listen(window,"resize",this._onResizeEvent);var a=this;this.interval=setInterval(function(){a._isSameView()},500)};d.prototype._onResizeEvent=function(){clearTimeout(this._resizeTimer);var a=this.category?this._resizeLoner.bind(this):this._resizeHeader.bind(this);this._resizeTimer=setTimeout(a,100)};d.prototype._resizeHeader=function(){0!==this._events._listeners.length&&(0<this.view.windowWidth&&this.view.initialWidth<
e.getWidth()-14&&!this._isLoadedTwice?(this._isLoadedTwice=!0,this.view.showThrobber({showContent:!0}),this.execute(this.query,{categories:f.CATEGORIES,amount:f.LONER_AMOUNT},this._onResizeExecution.bind(this),this._onResizeExecutionFail.bind(this))):this.view.repaintHeader())};d.prototype._onResizeExecution=function(a){var b=a[0];"E"===this._logger.getTestVersion()&&"undefined"!==typeof a[1]&&(b.users=a[1]);a=e.removeAlreadyDisplayedData(b);this.view.addData(a,{realPlaceholders:!0});this.view.repaintHeader();
this.view.loopThroughAndSetImage();this.view.hideThrobber()};d.prototype._onResizeExecutionFail=function(){this._isLoadedTwice=!1;this.view.repaintHeader();this.view.hideThrobber()};d.prototype._onClickEvent=function(a){a.preventDefault();if(a.target.hasClass("see-all")||a.target.hasClass("title")&&!a.target.hasClass("no-link"))a=a.target.getParent(".pod").get("data-category"),i.desktop?g.application.openURI("spotify:app:search-single:"+encodeURIComponent(this.query)+":"+a):g.application.openApp("search",
this.query,a)};d.prototype._dispose=function(){"undefined"!==typeof this._events&&this._events.removeAll()};d.prototype._resizeLoner=function(){if(0!==this._events._listeners.length){var a=document.getElement(".grid").getElement("li"),b=a.getStyle("height").toInt(),b=b+a.getStyle("margin-bottom").toInt();this.view.size=b;this._sectionHeight=f.ROW_OFFSET*b}};d.prototype._isSameView=function(){if(e.getScrollTop()!==this._scrollTop){this._scrollTop=e.getScrollTop();this.data.maxLengths[this.query][this.category]===
document.getElement(".grid").children.length&&clearInterval(this.interval);var a=document.getElement(".grid").getSize().y-window.innerHeight;if(0<a&&this._scrollTop>=a){this.view.showThrobber({addClass:"down"});var b=this,a={categories:[this.category],start:this.lonerIndex,amount:f.LONER_AMOUNT};"users"===this.category?this.data.getUsers(this.query,a).done(function(a){if("undefined"!==typeof a){var d={};d.users=a;b.lonerIndex+=f.LONER_AMOUNT;b.view.addData(d)}b.view.hideThrobber()}).fail(function(){b.view.hideThrobber()}):
this.execute(this.query,a,function(a){b.lonerIndex+=f.LONER_AMOUNT;b.view.addData(a[0]);b.view.hideThrobber()},function(){b.view.hideThrobber()})}this._resizeLoner();a=Math.floor(this._scrollTop/this._sectionHeight);this.scrollSection!==a&&(this.scrollSection=a,this._pruneOrAdd(a))}};d.prototype._pruneOrAdd=function(a){var b=(0===a?0:a-1)*f.ROW_OFFSET_LENGTH,a=document.getElement(".grid"),c=a.getElement("li").get("data-index").toInt();if(c!==b){if(c>b)for(;c>b;)this.view.database[c-1]&&this.view.database[c-
1].inject(a,"top"),c-=1;else if(c<b)for(;c<b;)a.childNodes[0].dispose(),c+=1;b=Math.floor(b/f.COLS*this.view.size);this._paddingTop!==b&&(a.setStyle("padding-top",b),this._paddingTop=b)}};exports.Controller=d});
