var sp=getSpotifyApi(),filesystem=sp.require("$util/fs"),lang=sp.require("$util/language"),models=sp.require("$api/models"),dom=sp.require("$util/dom"),r=sp.require("$util/react"),logger=sp.require("$util/logger"),storage=sp.require("$util/storage"),proto=sp.require("scripts/proto"),nano=sp.require("scripts/nano-scroller-light"),langCatalog=lang.loadCatalog("main"),translateLib=lang.getString.bind(lang,langCatalog),hermesBaseURL="hm://notifications/feed/"+sp.core.user.canonicalUsername+":inclient/",
SOCIAL_2_0_ON=!0,ui=null,social=null;SOCIAL_2_0_ON&&(ui=sp.require("$unstable/ui"),social=sp.require("$unstable/social"));
var NOTIFICATION_TYPE={playlistSubscribe:"playlist-sub",newFollower:"new-follower",friendJoined:"user-signup",playlistUpdated:"playlist-update",albumReleased:"album-release",applicationRelease:"application-release"},BUTTON_TYPE={follow:"follow",view:"view",play:"play"},APPLICATION_TYPES={unknown:0,ios:1,android:2,link:3},SUB_TYPE={none:"none",starredSubscribe:"starred",toplistSubscribe:"toplist"},LOAD_STATE={unloaded:"unloaded",loading:"loading",loaded:"loaded",failed:"failed"},L_LEVEL={reg:-1,prod:0,
debug:1,ver:2},MAX_CACHE_SIZE=500,CACHE_STORAGE_KEY="notifications",CURRENT_LOG_LEVEL=L_LEVEL.reg;function clone(a){if(!a)return null;var c=a instanceof Array?[]:{},b;for(b in a)c[b]=a[b]&&"object"==typeof a[b]?clone(a[b]):a[b];return c}function sLog(a,c,b,e,d){e=e?""+e:"1";d=d?""+d:"1";a<=CURRENT_LOG_LEVEL&&(c&&console.log(c),b&&console.log(b));a==L_LEVEL.prod&&c&&(b=b?b:{},logger.logClientEvent("notification center",c,e,d,b))}
function translate(a,c,b){!SOCIAL_2_0_ON&&b&&(a+="PreSocial");return translateLib(a,c)}
function Notification(a,c){if(c)this.notificationVerb=a.notificationVerb,this.sendersData=clone(a.sendersData),this.senderTotal=a.senderTotal,this.state=clone(a.state),this.playlistSubObjects=clone(a.playlistSubObjects),this.trackAddObjects=clone(a.trackAddObjects),this.albumReleaseObjects=clone(a.albumReleaseObjects),this.applicationReleaseObjects=clone(a.applicationReleaseObjects);else{var b=a.in_client_data;this.notificationVerb=b.notification_verb;this.sendersData=clone(b.subject);this.senderTotal=
b.subject_total;this.state=clone(b.state);this.playlistSubObjects=clone(b.playlist_sub_object);this.trackAddObjects=clone(b.track_add_object);this.albumReleaseObjects=clone(b.album_release_object);this.applicationReleaseObjects=clone(b.application_release_object)}this.loadedModels={};this.subType=SUB_TYPE.none;this.outstandingCallbacks=0;this.loadFailureCallback=this.loadSuccessCallback=this.failureTimeout=null;this.loadState=LOAD_STATE.unloaded;this.MAX_PLAYLISTS=this.MAX_SENDERS=3;this.TIMEOUT_LENGTH=
2E3;return this}
Notification.prototype.loadNodeInfo=function(a,c){function b(a,c){(c.notificationVerb==NOTIFICATION_TYPE.playlistSubscribe||c.notificationVerb==NOTIFICATION_TYPE.playlistUpdated)&&-1!==a.indexOf(SUB_TYPE.starredSubscribe,a.length-SUB_TYPE.starredSubscribe.length)?(c.subType=SUB_TYPE.starredSubscribe,c.loadFinished()):(c.notificationVerb==NOTIFICATION_TYPE.playlistSubscribe||c.notificationVerb==NOTIFICATION_TYPE.playlistUpdated)&&-1!==a.indexOf(SUB_TYPE.toplistSubscribe,a.length-SUB_TYPE.toplistSubscribe.length)?(c.subType=
SUB_TYPE.toplistSubscribe,c.loadFinished()):models.Playlist.fromURI(a,function(a){c.loadFinished(a)})}function e(a,c){models.Album.fromURI(a,function(a){c.loadFinished(a)})}if(this.loadState!=LOAD_STATE.unloaded)this.loadState==LOAD_STATE.loaded?a(this):this.loadState==LOAD_STATE.failed&&c(this);else{var d,g=this;this.loadState=LOAD_STATE.loading;this.loadSuccessCallback=a;this.loadFailureCallback=c;this.outstandingCallbacks=Math.min(this.sendersData?this.sendersData.length:0,this.MAX_SENDERS)+Math.min(this.playlistSubObjects?
this.playlistSubObjects.length:0,this.MAX_PLAYLISTS)+Math.min(this.trackAddObjects?this.trackAddObjects.length:0,this.MAX_PLAYLISTS)+(this.albumReleaseObjects?this.albumReleaseObjects.length:0);if(0==this.outstandingCallbacks)this.loadFinished();else{this.failureTimeout=setTimeout(function(){g.timeoutHit()},this.TIMEOUT_LENGTH);if(this.sendersData)for(d=0;d<this.sendersData.length&&d<this.MAX_SENDERS;d++)models.User.fromURI("spotify:user:"+this.sendersData[d].canonical_username,function(a){g.loadFinished(a)});
if(this.playlistSubObjects)for(d=0;d<this.playlistSubObjects.length&&d<this.MAX_PLAYLISTS;d++)b(this.playlistSubObjects[d].uri,this);if(this.trackAddObjects)for(d=0;d<this.trackAddObjects.length&&d<this.MAX_PLAYLISTS;d++)b(this.trackAddObjects[d].uri,this);if(this.albumReleaseObjects)for(d=0;d<this.albumReleaseObjects.length;d++)e("spotify:album:"+this.albumReleaseObjects[d].album_gid,this)}}};
Notification.prototype.timeoutHit=function(){sLog(L_LEVEL.debug,"notification-load-timeout");this.loadState=LOAD_STATE.failed;this.loadFailureCallback(this)};Notification.prototype.loadFinished=function(a){this.loadState==LOAD_STATE.loading&&(a&&(this.loadedModels[decodeURIComponent(a.uri)]=a),this.outstandingCallbacks--,0<this.outstandingCallbacks||(clearTimeout(this.failureTimeout),this.failureTimeout=null,this.loadState=LOAD_STATE.loaded,this.loadSuccessCallback(this)))};
Notification.prototype.getStringArrayForSystemNotification=function(){var a=[];switch(this.notificationVerb){case NOTIFICATION_TYPE.playlistSubscribe:a.push(translate("systemNotifications","sTitlePlaylistSubscribe",!0));a.push(lang.format(translate("systemNotifications","sBodyPlaylistSubscribe",!0),this.getSenderDisplayName()));break;case NOTIFICATION_TYPE.newFollower:a.push(translate("systemNotifications","sTitleNewFollower"));a.push(lang.format(translate("systemNotifications","sBodyNewFollower"),
this.getSenderDisplayName()));break;case NOTIFICATION_TYPE.friendJoined:a.push(translate("systemNotifications","sTitleFriendJoined"));a.push(lang.format(translate("systemNotifications","sBodyFriendJoined"),this.getSenderDisplayName()));break;case NOTIFICATION_TYPE.playlistUpdated:a.push(translate("systemNotifications","sTitlePlaylistUpdated")),a.push(lang.format(translate("systemNotifications","sBodyPlaylistUpdated"),this.getSenderDisplayName()))}return 2==a.length?a:[]};
Notification.prototype.getSenderDisplayName=function(){var a=this.sendersData[0],c=a.real_name;if(!c||0==c.length)c=(c=this.loadedModels["spotify:user:"+a.canonical_username])&&c.data&&c.data.name&&0<c.data.name.length?c.data.name:a.canonical_username;return c};
Notification.prototype.getApplicationReleaseString=function(){switch(this.applicationReleaseObjects[0].app){case APPLICATION_TYPES.ios:return translate("notifications","sNotificationBodyApplicationReleaseIOS");case APPLICATION_TYPES.android:return translate("notifications","sNotificationBodyApplicationReleaseAndroid");case APPLICATION_TYPES.link:return translate("notifications","sNotificationBodyApplicationReleaseLink")}return""};
Notification.prototype.createNode=function(){function a(a){75<a.length&&(a=a.substring(0,74)+"\u2026");return a}function c(c,b,d){return'<a href="'+("spotify:"+c+":"+d)+'" class="contentLink">'+a(b)+"</a>"}function b(a){switch(a.notificationVerb){case NOTIFICATION_TYPE.playlistUpdated:if(0<a.trackAddObjects.length&&a.trackAddObjects[0].track_uri&&0<a.trackAddObjects[0].track_uri.length){var c=a.trackAddObjects[0];return{trackURI:c.track_uri[0],contextURI:c.uri}}break;case NOTIFICATION_TYPE.albumReleased:c=
["spotify:album:",a.albumReleaseObjects[0].album_gid].join("");if(a.albumReleaseObjects[0].track_gid&&""!=a.albumReleaseObjects[0].track_gid)return{trackURI:"spotify:track:"+a.albumReleaseObjects[0].track_gid,contextURI:c};if(c in a.loadedModels&&(a=a.loadedModels[c].tracks)&&0<a.length)return{trackURI:a[0].uri,contextURI:c}}return null}function e(a){switch(a.notificationVerb){case NOTIFICATION_TYPE.playlistSubscribe:return a.subType==SUB_TYPE.starredSubscribe?translate("notifications","sNotificationBodyStarredSubscribe",
!0):a.subType==SUB_TYPE.toplistSubscribe?translate("notifications","sNotificationBodyToplistSubscribe",!0):translate("notifications","sNotificationBodyPlaylistSubscribe",!0);case NOTIFICATION_TYPE.newFollower:return translate("notifications","sNotificationBodyNewFollower");case NOTIFICATION_TYPE.friendJoined:return translate("notifications","sNotificationBodyFriendJoined");case NOTIFICATION_TYPE.playlistUpdated:return a.trackAddObjects&&a.trackAddObjects[0]&&1==a.trackAddObjects[0].track_count?translate("notifications",
"sNotificationBodyPlaylistUpdatedSingular"):translate("notifications","sNotificationBodyPlaylistUpdatedPlural");case NOTIFICATION_TYPE.albumReleased:return a.albumReleaseObjects[0].exclusive&&!0==a.albumReleaseObjects[0].exclusive?2<a.albumReleaseObjects.length?translate("notifications","sNotificationBodyMultipleExclusiveAlbumsReleased"):1<a.albumReleaseObjects.length?translate("notifications","sNotificationBodyMultipleExclusiveAlbumsReleasedSingular"):translate("notifications","sNotificationBodyExclusiveAlbumReleased"):
2<a.albumReleaseObjects.length?translate("notifications","sNotificationBodyMultipleAlbumsReleased"):1<a.albumReleaseObjects.length?translate("notifications","sNotificationBodyMultipleAlbumsReleasedSingular"):translate("notifications","sNotificationBodyAlbumReleased");case NOTIFICATION_TYPE.applicationRelease:return a.getApplicationReleaseString()}}function d(b){switch(b.notificationVerb){case NOTIFICATION_TYPE.albumReleased:if(1<b.albumReleaseObjects.length){var d=b.albumReleaseObjects[0],e=c("artist",
d.artist_name,d.artist_gid),d=c("album",d.album_name,d.album_gid);return{artist:e,album:d,numOtherAlbums:b.albumReleaseObjects.length-1}}case NOTIFICATION_TYPE.playlistSubscribe:case NOTIFICATION_TYPE.newFollower:case NOTIFICATION_TYPE.friendJoined:case NOTIFICATION_TYPE.playlistUpdated:a:{switch(b.notificationVerb){case NOTIFICATION_TYPE.playlistSubscribe:case NOTIFICATION_TYPE.newFollower:case NOTIFICATION_TYPE.friendJoined:case NOTIFICATION_TYPE.playlistUpdated:e=c("user",b.getSenderDisplayName(),
b.sendersData[0].canonical_username);break a;case NOTIFICATION_TYPE.albumReleased:if(b.albumReleaseObjects[0].track_name&&""!=b.albumReleaseObjects[0].track_name){e=c("album",b.albumReleaseObjects[0].track_name,b.albumReleaseObjects[0].album_gid);break a}e=c("album",b.albumReleaseObjects[0].album_name,b.albumReleaseObjects[0].album_gid);break a}e=void 0}a:{switch(b.notificationVerb){case NOTIFICATION_TYPE.playlistUpdated:var d=null,f;f=b.trackAddObjects[0].uri;b.subType==SUB_TYPE.starredSubscribe?
d=translate("notifications","sNotificationBodyStarredTracksUpdatedName"):b.subType==SUB_TYPE.toplistSubscribe?d=translate("notifications","sNotificationBodyToplistUpdatedName"):b.loadedModels[decodeURIComponent(b.trackAddObjects[0].uri)]&&(d=a(b.loadedModels[decodeURIComponent(b.trackAddObjects[0].uri)].data.name));d=!d?"":' <a href="'+f+'" class="contentLink">'+d+"</a>";break a;case NOTIFICATION_TYPE.playlistSubscribe:if(b.subType==SUB_TYPE.starredSubscribe||b.subType==SUB_TYPE.toplistSubscribe)break;
d=b.playlistSubObjects[0];d=(f=b.loadedModels[decodeURIComponent(d.uri)])?' <a href="'+d.uri+'" class="contentLink">'+a(f.data.name)+"</a>":"";break a;case NOTIFICATION_TYPE.albumReleased:d=c("artist",b.albumReleaseObjects[0].artist_name,b.albumReleaseObjects[0].artist_gid);break a}d=void 0}a:{switch(b.notificationVerb){case NOTIFICATION_TYPE.playlistUpdated:if(b.trackAddObjects&&b.trackAddObjects[0]){if(1==b.trackAddObjects[0].track_count)break;b=" "+b.trackAddObjects[0].track_count;break a}b=" some";
break a}b=void 0}return[e,d,b]}}function g(a){switch(a.notificationVerb){case NOTIFICATION_TYPE.newFollower:case NOTIFICATION_TYPE.friendJoined:if(SOCIAL_2_0_ON&&!social.isSubscribed(a.sendersData[0].canonical_username))return BUTTON_TYPE.follow;break;case NOTIFICATION_TYPE.albumReleased:case NOTIFICATION_TYPE.playlistUpdated:if(b(a))return BUTTON_TYPE.play}return BUTTON_TYPE.view}var f;a:{switch(this.notificationVerb){case NOTIFICATION_TYPE.playlistSubscribe:case NOTIFICATION_TYPE.newFollower:case NOTIFICATION_TYPE.friendJoined:case NOTIFICATION_TYPE.playlistUpdated:f=
this.sendersData[0];var h=this.loadedModels["spotify:user:"+f.canonical_username];f='<a class="imageLink" href="spotify:user:'+f.canonical_username+'"><div class="image" style="background-image: url('+(h&&h.data.icon&&0<h.data.icon.length?h.data.icon:"http://aro.spotify.s3.amazonaws.com/emails/notifications/user50x50.png")+');"></div></a>';break a;case NOTIFICATION_TYPE.albumReleased:f="spotify:album:"+this.albumReleaseObjects[0].album_gid;h="http://aro.spotify.s3.amazonaws.com/emails/notifications/user50x50.png";
f in this.loadedModels&&(h=this.loadedModels[f].data.cover);f='<a href="'+f+'" class="imageLink"><div class="image" style="background-image: url('+h+');"></div></a>';break a;case NOTIFICATION_TYPE.applicationRelease:f=this.applicationReleaseObjects[0].uri;h=this.applicationReleaseObjects[0].image_url;if(!h||""==h)h="../img/notification-icon.png";f='<a href="'+f+'" class="imageLink"><div class="image" style="background-image: url('+h+');"></div></a>';break a}f=void 0}a:{switch(this.notificationVerb){case NOTIFICATION_TYPE.applicationRelease:case NOTIFICATION_TYPE.playlistSubscribe:case NOTIFICATION_TYPE.newFollower:case NOTIFICATION_TYPE.friendJoined:case NOTIFICATION_TYPE.playlistUpdated:case NOTIFICATION_TYPE.albumReleased:h=
lang.format(e(this),d(this));break a}h=void 0}var i;this.state.notification_id_ms?(i=(new Date).getTime()-this.state.notification_id_ms,i=isNaN(i)||0>i?"":2E3>i?translate("time","sJustNow"):6E4>i?lang.format(translate("time","sSecondsAgo"),[Math.floor(i/1E3)]):12E4>i?translate("time","s1Minute"):36E5>i?lang.format(translate("time","sMinutesAgo"),[Math.floor(i/6E4)]):72E5>i?translate("time","s1Hour"):864E5>i?lang.format(translate("time","sHoursAgo"),[Math.floor(i/36E5)]):864E5<i&&1728E5>i?translate("time",
"sYesterday"):31536E6>i?lang.format(translate("time","sDaysAgo"),[Math.floor(i/864E5)]):translate("time","sOverAYear")):i="";f=[f,h,i];f=new dom.Element("div",{html:lang.format(filesystem.readFile("../notification.xml"),f)});f.className="notification "+this.notificationVerb+(!this.state||!this.state.seen?" unread":"");f.id=this.getIdHex();f.dataset.timestamp=this.getTimeStamp();f.dataset.actionUrl=function(a){switch(a.notificationVerb){case NOTIFICATION_TYPE.playlistUpdated:return a.trackAddObjects[0].uri;
case NOTIFICATION_TYPE.playlistSubscribe:return a.playlistSubObjects[0].uri;case NOTIFICATION_TYPE.albumReleased:return"spotify:artist:"+a.albumReleaseObjects[0].artist_gid;case NOTIFICATION_TYPE.newFollower:case NOTIFICATION_TYPE.friendJoined:return"spotify:user:"+a.sendersData[0].canonical_username;case NOTIFICATION_TYPE.applicationRelease:return a.applicationReleaseObjects[0].uri}}(this);f.dataset.type=this.notificationVerb;f.dataset.buttonType=g(this);if(h=b(this))h.trackURI&&(f.dataset.trackURI=
h.trackURI),h.contextURI&&(f.dataset.contextURI=h.contextURI);dom.queryOne(".buttonCell",f).appendChild(function(a){switch(g(a)){case BUTTON_TYPE.follow:return(new ui.SubscribeButton(a.sendersData[0].canonical_username)).node;case BUTTON_TYPE.view:case BUTTON_TYPE.play:var b=document.createElement("button");b.className="sp-button";a=g(a)==BUTTON_TYPE.view?"sViewButtonTitle":"sPlayButtonTitle";b.textContent=translate("buttons",a);return b}}(this));return f};
Notification.prototype.getIdHex=function(){return this.state?this.state.notification_id_hex:null};Notification.prototype.getTimeStamp=function(){return this.state?this.state.notification_id_ms:null};Notification.prototype.updateWithNewState=function(a){this.getIdHex()==a.notification_id_hex&&(this.state=clone(a))};Notification.prototype.getLog=function(){return"      ID   : "+this.getTimeStamp()+" | "+this.getIdHex()+"\n      State: "+this.state.state_id_ms+" | "+this.state.state_id_hex+"\n"};
function NotificationManager(a){this.fetchInProgress=!1;this.unreadCount=0;this.notifications=[];this.oldestNoteId="";this.oldestNoteTimestamp;this.newestNoteId="";this.newestNoteTimestamp;this.notificationDelegate=a;this.SECONDS_BETWEEN_POLLS=2;this.DEFAULT_PAGE_SIZE=50}NotificationManager.prototype.startup=function(){this.loadCache();this.unreadCount=0;this.fetchInProgress=!1;this.startSubscription()};
NotificationManager.prototype.startSubscription=function(){var a=this;sp.core.addEventListener("hermes",function(c){a.notificationUpdatesReceived(c)},!1);sp.core.getHermes("SUB",hermesBaseURL,[],{onSuccess:function(){},onFailure:function(a){sLog(L_LEVEL.prod,"error-subscribe-failed",{code:a,url:hermesBaseURL})},onComplete:function(){a.getPageOfNotificationsFromServer(null,a.DEFAULT_PAGE_SIZE,!0);a.getBadgeCount()}})};
NotificationManager.prototype.notificationUpdatesReceived=function(a){if(0===a.data[0].indexOf("hm://notifications/feed/")&&(a=sp.core.parseHermesReply("Notification",a.data[1])))a=(a=this.notificationsReceived([a],!0))&&"number"==typeof a?a:0,0!=a&&(this.notificationDelegate&&!this.notificationDelegate.showing)&&this.setBadgeCount(-1==a?0:this.unreadCount+a)};
NotificationManager.prototype.getBadgeCount=function(){var a=this;sp.core.getHermes("GET",hermesBaseURL+"counts",[],{onSuccess:function(c){a.setBadgeCount(sp.core.parseHermesReply("NotificationCounts",c).active)},onFailure:function(a){sLog(L_LEVEL.prod,"error-badge-count-get-failed",{code:a,url:hermesBaseURL+"counts"})}})};NotificationManager.prototype.setBadgeCount=function(a){a="number"==typeof a?a:0;this.unreadCount!=a&&sp.desktop.notificationPopup.badgeCountUpdate(a);this.unreadCount=a};
NotificationManager.prototype.getCachedNotificationWithIdHex=function(a,c){for(var b=null,e=0,d=0;d<this.notifications.length;d++)if(this.notifications[d].getIdHex()==a){b=this.notifications[d];e=d;break}c&&b&&this.notifications.splice(e,1);return b};NotificationManager.prototype.trimCache=function(){this.notifications.length>MAX_CACHE_SIZE&&this.notifications.splice(MAX_CACHE_SIZE)};
NotificationManager.prototype.loadCache=function(){try{this.notifications=window.localStorage?JSON.parse(window.localStorage.getItem(CACHE_STORAGE_KEY))||[]:[];for(var a=0;a<this.notifications.length;a++)this.notifications[a]=new Notification(this.notifications[a],!0);0<this.notifications.length&&(this.oldestNoteTimestamp=this.notifications[this.notifications.length-1].state.notification_id_ms,this.oldestNoteId=this.notifications[this.notifications.length-1].state.notification_id_hex,this.newestNoteTimestamp=
this.notifications[0].state.notification_id_ms,this.newestNoteId=this.notifications[0].state.notification_id_hex)}catch(c){sLog(L_LEVEL.prod,"error-invalid-cache-data",{data:window.localStorage.getItem(CACHE_STORAGE_KEY)}),this.clearCache()}};NotificationManager.prototype.clearCache=function(){this.notifications=[];this.oldestNoteId="";this.oldestNoteTimestamp=0;this.newestNoteId="";this.newestNoteTimestamp=0;this.saveCache()};
NotificationManager.prototype.saveCache=function(){if(window.localStorage){for(var a=[],c=0;c<this.notifications.length;c++)a.push(new Notification(this.notifications[c],!0));a=JSON.stringify(a);window.localStorage.setItem(CACHE_STORAGE_KEY,a)}};
NotificationManager.prototype.insertNotificationIntoCache=function(a,c){for(var b=a.getTimeStamp(),e=a.getIdHex(),d=-1,g=0;g<this.notifications.length;g++)if(-1==d&&b>this.notifications[g].getTimeStamp()&&(d=g),this.notifications[g].getIdHex()==e)return!1;-1==d?this.notifications.push(a):this.notifications.splice(d,0,a);c&&this.trimCache();this.oldestNoteTimestamp=this.notifications[this.notifications.length-1].state.notification_id_ms;this.oldestNoteId=this.notifications[this.notifications.length-
1].state.notification_id_hex;this.newestNoteTimestamp=this.notifications[0].state.notification_id_ms;this.newestNoteId=this.notifications[0].state.notification_id_hex;this.saveCache();return!0};NotificationManager.prototype.notificationDataIsValid=function(a){return a&&a.state&&a.state.notification_id_hex&&a.state.notification_id_ms?!0:!1};
NotificationManager.prototype.notificationDataIsAccepted=function(a){var c=!1;if(!a.state.dismissed&&a.subject&&0<a.subject.length)switch(a.notification_verb){case NOTIFICATION_TYPE.playlistUpdated:c=a.track_add_object&&0<a.track_add_object.length?!0:!1;break;case NOTIFICATION_TYPE.playlistSubscribe:c=a.playlist_sub_object&&0<a.playlist_sub_object.length?!0:!1;break;case NOTIFICATION_TYPE.newFollower:c=SOCIAL_2_0_ON;break;case NOTIFICATION_TYPE.friendJoined:c=!0;break;default:c=!1}else if(!a.state.dismissed)switch(a.notification_verb){case NOTIFICATION_TYPE.applicationRelease:c=
a.application_release_object&&0<a.application_release_object.length?!0:!1;break;case NOTIFICATION_TYPE.albumReleased:c=a.album_release_object&&0<a.album_release_object.length?!0:!1;break;default:c=!1}return c};NotificationManager.prototype.getCacheStateDescription=function(){for(var a=1<this.notifications.length?"":"    NONE",c=0;c<this.notifications.length;c++)a+="    NOTE "+c+"\n",a+=this.notifications[c].getLog();return a};
NotificationManager.prototype.notificationsReceived=function(a,c){var b=[],e=[],d=!1,g=null;sLog(L_LEVEL.debug,"notifications-received"+(c?"-subscription":""),a);sLog(L_LEVEL.ver,"cache-stat-pre-insertion",this.getCacheStateDescription());if(a&&0!==a.length){for(var f=0;f<a.length;f++)if(this.notificationDataIsValid(a[f].in_client_data))if(g=a[f].in_client_data,1==a[f].type)if(g.state.seen){for(g=0;g<this.notifications.length;g++)this.notifications[g].state.seen=!0;c&&(d=!0)}else g.state.dismissed&&
(this.notifications=[],this.oldestNoteId="",this.oldestNoteTimestamp=0,c&&(d=!0));else if(7==a[f].type){var h=this.getCachedNotificationWithIdHex(g.state.notification_id_hex);h?(h.updateWithNewState(g.state),e.push(h),sLog(L_LEVEL.debug,"update-cached-notification",{"notification-id":h.getIdHex()})):sLog(L_LEVEL.debug,"drop-notification-update",{"notification-id":g.state.notification_id_hex})}else this.notificationDataIsAccepted(g)?(h=new Notification(a[f]),this.insertNotificationIntoCache(h,c)&&
(sLog(L_LEVEL.prod,"new-note-received",{"notification-id":g.state.notification_id_hex}),e.push(h),b.push(h),"album-release"!=h.notificationVerb&&"application-release"!=h.notificationVerb&&models.User.fromURI("spotify:user:"+h.sendersData[0].canonical_username))):sLog(L_LEVEL.debug,"unaccepted-notification-received",{"notification-id":g.state.notification_id_hex});else sLog(L_LEVEL.prod,"error-invalid-notification-data-received",{data:a[f].in_client_data});this.notificationDelegate&&this.notificationDelegate.displayNewOrUpdatedNotifications&&
this.notificationDelegate.displayNewOrUpdatedNotifications(e);if(c&&0<b.length){e=[];for(f=0;f<b.length;f++)e=e.concat(b[f].getStringArrayForSystemNotification());sp.desktop.notificationPopup.notificationsRecieved(e)}sLog(L_LEVEL.ver,"cache-stat-post-insertion",this.getCacheStateDescription());return d?-1:b.length}};
NotificationManager.prototype.readAllNotes=function(a){sLog(L_LEVEL.debug,"read-all-notifications");var c;c={seen:!0};for(var b=0;b<this.notifications.length;b++)this.notifications[b].state.seen=!0;this.saveCache();this.setBadgeCount(0);if(a){var e=hermesBaseURL+"states/all/";sp.core.getHermes("PUT",e,[["NotificationState",c]],{onSuccess:function(){sLog(L_LEVEL.prod,"read-all-notes-success",{hermesUrl:e})},onFailure:function(a){sLog(L_LEVEL.prod,"error-read-all-notes-failed",{errorCode:a,hermesUrl:e})}})}};
NotificationManager.prototype.deleteAllNotes=function(){this.clearCache();var a=hermesBaseURL+"states/all/";sp.core.getHermes("PUT",a,[["NotificationState",{dismissed:!0}]],{onSuccess:function(){sLog(L_LEVEL.prod,"delete-all-notes-success",{hermesUrl:a})},onFailure:function(c){sLog(L_LEVEL.prod,"error-delete-all-notes-failed",{errorCode:c,hermesUrl:a})}})};
NotificationManager.prototype.getPageOfNotifications=function(a,c){var c=c?c:this.DEFAULT_PAGE_SIZE,b=0<this.notifications.length?0:-1;if(a)for(var b=-1,e=this.notifications.length-2;0<=e;e--)if(this.notifications[e].getIdHex()==a){b=e+1;break}-1!=b&&(0>=b+c-this.notifications.length?c=0:a=this.oldestNoteId,this.notificationDelegate&&this.notificationDelegate.displayNewOrUpdatedNotifications&&this.notificationDelegate.displayNewOrUpdatedNotifications(this.notifications.slice(b,this.notifications.length)));
c&&this.getPageOfNotificationsFromServer(a,c,!1)};
NotificationManager.prototype.getPageOfNotificationsFromServer=function(a,c,b){var e=this,d=hermesBaseURL+(a?"from/"+a+"/":"")+"take/"+c;b&&this.newestNoteId&&(d+="/?etag="+this.newestNoteId);sLog(L_LEVEL.debug,"get-page-of-notifications",{hermesUrl:d});b&&sLog(L_LEVEL.prod,"do-initial-cache-check",{hermesUrl:d});this.fetchInProgress=!0;sp.core.getHermes("GET",d,[],{onSuccess:function(a){b&&(sLog(L_LEVEL.prod,"cache-dirty",{hermesUrl:d}),e.clearCache());e.hermesGetSuccess(a,c)},onFailure:function(a){this.fetchInProgress=
!1;b&&5404==a?sLog(L_LEVEL.prod,"cache-ok",{hermesUrl:d}):(e.notificationDelegate&&e.notificationDelegate.showError&&e.notificationDelegate.showError(),sLog(L_LEVEL.prod,"error-get-page-failed",{errorCode:a,hermesUrl:d}))}})};
NotificationManager.prototype.hermesGetSuccess=function(a,c){sLog(L_LEVEL.debug,"hermes-get-success");var b=sp.core.parseHermesReply("NotificationList",a);this.fetchInProgress=!1;b&&(b.notification&&0<b.notification.length)&&this.notificationsReceived(b.notification);(!b||!b.notification||b.notification.length<c)&&(this.notificationDelegate&&this.notificationDelegate.noMoreNotificationsToLoad)&&this.notificationDelegate.noMoreNotificationsToLoad()};
function NotificationPopup(){this.reconnectOnClose=this.showing=!1;this.lastConnectedTime=0;this.selectedNode=null;this.notificationsLoading=0;var a=this;this.scroller=nano.scroller(document.getElementById("notificationList"),function(){a.nearBottomCallback()});this.noMoreNotes=!1;this.NOTES_PER_PAGE=6;this.noteCenterNode=document.getElementById("noteCenter");document.getElementById("topBar").innerHTML=translate("mainUI","sTitle");this.notificationManager=new NotificationManager(this);sp.desktop.notificationPopup&&
1!=sp.core.getArguments()[0]?(sp.desktop.notificationPopup.addEventListener("shownPop",function(){a.show()}),sp.desktop.notificationPopup.addEventListener("closingPop",function(){a.closePop()}),sp.desktop.notificationPopup.addEventListener("moveup",function(){a.keyUp()}),sp.desktop.notificationPopup.addEventListener("movedown",function(){a.keyDown()}),sp.desktop.notificationPopup.addEventListener("doActionOnSelectedNote",function(){a.doActionOnSelectedNote()}),setTimeout(function(){a.reconnect();
setTimeout(function(){models.session.observe(models.EVENT.LOGIN,function(){a.reconnect()})},3E3)},3E3)):(this.notificationManager.startup(),this.show())}NotificationPopup.prototype.reconnect=function(){this.showing?this.reconnectOnClose=!0:this.notificationManager.startup()};NotificationPopup.prototype.checkConnection=function(){if(1==sp.core.getLoginMode()){var a=(new Date).getTime();4E3<a-this.lastConnectedTime&&this.reconnect();this.lastConnectedTime=a}};
NotificationPopup.prototype.show=function(){this.showing=!0;this.notificationManager.getPageOfNotifications();document.getElementById("noMoreMessage").innerHTML=translate("mainUI","sNoMoreMessage");sLog(L_LEVEL.prod,"shown")};
NotificationPopup.prototype.closePop=function(){this.showing=!1;this.notificationManager.readAllNotes(0<this.notificationManager.unreadCount||dom.queryOne(".unread"));document.getElementById("notificationListContent").innerHTML="";this.noteCenterNode.classList.remove("loaded");this.noteCenterNode.classList.remove("empty");this.scroller.reset();this.selectedNode=null;this.noMoreNotes=!1;this.reconnectOnClose&&(this.reconnectOnClose=!1,this.notificationManager.startup())};
NotificationPopup.prototype.showError=function(){this.showing&&(document.getElementById("noMoreMessage").innerHTML=translate("mainUI","sLoadError"),this.noteCenterNode.classList.add("empty"))};NotificationPopup.prototype.displayNewOrUpdatedNotifications=function(a){sLog(L_LEVEL.ver,"displaying-notifications",a);if(this.showing){var c=this;this.notificationsLoading+=a.length;for(var b=0;b<a.length;b++)a[b].loadNodeInfo(function(a){c.displayLoadedNotification(a)},function(a){c.notificationFailedToLoad(a)})}};
NotificationPopup.prototype.displayLoadedNotification=function(a){function c(a,b,c){return function(){c.linkHit(a,b)}}var b=this,e=document.getElementById("notificationListContent"),d;this.notificationsLoading--;d=document.getElementById(a.getIdHex());if(!d){d=a.createNode();a=dom.query("a",d);r.fromDOMEvent(dom.queryOne("button",d),"click").subscribe(function(){b.buttonHit(d)});for(var g=0;g<a.length;g++)r.fromDOMEvent(a[g],"click").subscribe(c(a[g],d,b));a=e.childNodes;for(g=0;a&&g<a.length&&a[g].dataset.timestamp>
d.dataset.timestamp;)g++;a&&g<a.length?e.insertBefore(d,a[g]):e.appendChild(d);this.noteCenterNode.classList.add("loaded");this.noteCenterNode.classList.remove("empty");document.getElementById("noMoreMessage").innerHTML=translate("mainUI","sNoMoreMessage");sp.desktop.notificationPopup&&sp.desktop.notificationPopup.setHeight(this.noteCenterNode.clientHeight);setTimeout(function(){b.scroller.reset();sp.desktop.notificationPopup.setHeight(b.noteCenterNode.clientHeight)},1)}};
NotificationPopup.prototype.notificationFailedToLoad=function(){this.notificationsLoading--;0===this.notificationsLoading&&0===dom.query(".notification").length&&this.emptyListHandler()};NotificationPopup.prototype.noMoreNotificationsToLoad=function(){this.showing&&(0===dom.query(".notification").length&&(this.noteCenterNode.classList.remove("loaded"),this.noteCenterNode.classList.add("empty")),this.noMoreNotes=!0)};
NotificationPopup.prototype.emptyListHandler=function(a){this.noteCenterNode.classList.remove("loaded");this.scroller.reset();sp.desktop.notificationPopup&&sp.desktop.notificationPopup.setHeight(this.noteCenterNode.clientHeight);a?this.noMoreNotificationsToLoad():this.notificationManager.getPageOfNotifications(null)};
NotificationPopup.prototype.nearBottomCallback=function(){if(!this.fetchInProgress&&!this.noMoreNotes){var a=dom.query(".notification");a&&0<a.length&&this.notificationManager.getPageOfNotifications(a[a.length-1].id)}};
NotificationPopup.prototype.buttonHit=function(a){sLog(L_LEVEL.prod,"button-hit",{id:a.id,data:a.dataset});switch(a.dataset.buttonType){case BUTTON_TYPE.play:a.dataset.trackURI&&models.player.play(a.dataset.trackURI,a.dataset.contextURI);this.linkHit(a.dataset.actionUrl,a,!0);break;case BUTTON_TYPE.view:this.linkHit(a.dataset.actionUrl,a,!0)}};
NotificationPopup.prototype.linkHit=function(a,c,b){event&&event.preventDefault();sp.desktop.notificationPopup.openLink(decodeURIComponent(a));b||sLog(L_LEVEL.prod,"link-hit",{url:a})};NotificationPopup.prototype.keyUp=function(){this.keyBoardMove(!0)};NotificationPopup.prototype.keyDown=function(){this.keyBoardMove(!1)};
NotificationPopup.prototype.keyBoardMove=function(a){if(this.selectedNode||!a)(a=this.selectedNode?a?this.selectedNode.previousSibling:this.selectedNode.nextSibling:dom.queryOne(".notification"))&&this.selectNode(a)};
NotificationPopup.prototype.selectNode=function(a){this.selectedNode!=a&&(this.selectedNode&&this.selectedNode.classList.remove("selected"),a&&a.classList.add("selected"),this.selectedNode=a);var c=a.offsetTop,a=a.clientHeight,b=document.getElementById("notificationListContent");b.scrollTop>c?b.scrollTop=c:b.scrollTop+b.clientHeight<c+a&&(b.scrollTop=c+a-b.clientHeight)};
NotificationPopup.prototype.doActionOnSelectedNote=function(){if(this.selectedNode){var a=dom.queryOne("button",this.selectedNode);a&&a.click()}};var notePopup=new NotificationPopup;
