require("$api/models $views/list#List $views/image#Image $views/buttons#StartRadioButton $views/buttons#ShareButton /strings/main.lang /scripts/similar /scripts/related#RelatedAlbums /scripts/benchmark#Benchmark /scripts/logger#Logger /scripts/env#Environment /scripts/utils".split(" "),function(d,u,v,J,K,w,L,M,h,N,x,y){var j,p=!1,e,b,m,f,i,k=new h,O=new N,l,g=w.get.bind(w),z,A=!1,q,r,B;$$(".localize").each(function(a){a.innerHTML=g(a.get("data-string"))});var E=function(){k.start(h.APP_INIT);x.desktop&&
$("body").addClass("desktop");d.session.load("online").done(function(){d.session.online?($("offline-notice")&&$("offline-notice").dispose(),q=!1,r=!0,d.application.load("arguments").done(C)):D();A||($$("body").addEvent("click",function(a){if("A"===a.target.nodeName){var b=a.target.href.match(/spotify:/)?a.target.href:a.target.href.toSpotifyURI();d.application.openURI(b);a.preventDefault();return!1}if(a.target.className.match(/spuri/))return b=a.target.getAttribute("data-spuri"),d.application.openURI(b),
a.preventDefault(),!1;if("IMG"===a.target.nodeName.toUpperCase()&&"sp-image-img"===a.target.className&&"A"===a.target.parentNode.parentNode.nodeName.toUpperCase()&&a.target.parentNode.parentNode.href.match(/spotify:/))return b=a.target.parentNode.parentNode.href,d.application.openURI(b),a.preventDefault(),!1;"sp-image-wrapper"===a.target.className&&("A"===a.target.parentNode.nodeName.toUpperCase()&&a.target.parentNode.href.match(/spotify:/))&&(b=a.target.parentNode.href,d.application.openURI(b),a.preventDefault());
return!1}),d.session.addEventListener("change:online",P),d.application.addEventListener("arguments",C),A=!0)})},D=function(){q=!0;F();t();$$("body > .throbber").setStyle("display","none");$("album-page").style.display="none";var a=document.createElement("p");a.id="offline-notice";a.innerHTML="Album pages are not available offline.";$$("body")[0].appendChild(a)},t=function(){$("album-page").setStyle("display","block");$$("body > .error").setStyle("display","none")},F=function(){$("album-page").setStyle("display",
"none");$("album-image").empty();$("album-tracks").empty();$("album-additional").empty();$("albums-list").empty();$("album-rights").empty();$("album-rights").removeClass("padded");$("album-buttons").empty();$("artist-details").innerHTML='<div id="artist-image" class="l"></div><div id="album-details-row"><span id="album-by"></span><a id="artist-name"></a></div>';$("artist-details-various").innerHTML="";$("artist-details-various").addClass("hidden");$("album-more-albums").empty();$("album-more-albums").setStyle("display",
"none");$("album-dropdown").empty();$("album-dropdown").removeClass("visible");document.getElementById("album-dropdown").removeEventListener("click",G);document.body.removeEventListener("click",n);window.removeEventListener("click",n);l&&l.destroy();document.getElement("#albums-more h2").empty()},P=function(){d.session.online?E():D()},C=function(){var a;k.start(h.LOAD_FROM_URI);if(!q)if(d.application.arguments[0])SpotifyApi.api.analyticsContext("Application Load",function(){m=null;d.application.arguments[1]&&
(m=d.application.arguments[1]);j=d.application.arguments[0];if(!r&&z===j)return m&&H(m),t(),!1;z=j;F();r=p=!1;a="spotify:album:"+j;b=d.Album.fromURI(a);b.load("name","tracks","playable","artists","image").done(function(a){k.measure("album-load","Album loaded",h.LOAD_FROM_URI);$("album-page").setStyle("display","block");$$("body > .throbber").setStyle("display","none");$$("body > .error").setStyle("display","none");e=a.artists[0];t();e.load("name","albums","image").done(function(){k.measure("artist-load",
"Artist loaded",h.LOAD_FROM_URI);k.send();l=new M(a);l.init();var c=document.createElement("a");c.href=b.uri.toSpotifyURL();c.innerHTML=b.name;c.title=b.name;$("album-title").empty();$("album-title").grab(c);-1<e.name.toLowerCase().indexOf("various")?($("artist-details-various").innerHTML=g("various-artists"),$("artist-details-various").removeClass("hidden")):($("artist-details-various").innerHTML="",$("album-by").innerHTML=g("by")+" ",c=$("artist-name"),c.href=e.uri.toSpotifyURL(),c.className="spuri",
c.innerHTML=e.name,c=new v(e,{style:"none",title:e.name,height:30,width:30,player:!1,animate:!1,link:e.uri}),$("artist-image").appendChild(c.node));var c=$("album-buttons"),d=J.forAlbum(b);if(x.desktop){var Q=K.forAlbum(b);c.appendChild(Q.node)}c.appendChild(d.node);b.load("copyrights").done(function(){if(0<b.copyrights.length)for(var a=b.copyrights.length,c=0;c<a;c++){var d=document.createElement("div");d.innerHTML=b.copyrights[c];$("album-rights").appendChild(d)}});c=v.forAlbum(b,{style:"none",
title:b.name,height:128,width:128,player:!1,animate:!1,link:b.uri});$("album-image").appendChild(c.node);c="sp:"===window.location.protocol?"star share number track trackartist time popularity".split(" "):["number","track","trackartist","time","popularity"];e.name.match(/various/i)&&(c="sp:"===window.location.protocol?"star share number track artist time popularity".split(" "):["number","track","artist","time","popularity"]);f=u.forAlbum(b,{context:b,type:"tracks",fields:c,header:"no",playable:!0,
fetch:"greedy",style:"rounded"});$("album-tracks").appendChild(f.node);f.addEventListener("snapshot-load",function(){H(m)});f.addEventListener("initialized",function(){if(!p){p=!0;var a=new L.SimilarAlbums(b);SpotifyApi.api.analyticsContext("showSimilarAlbums()",function(){a.find().done(function(a){k.measure("additional-albums","Additional albums loaded",h.LOAD_FROM_URI);var c=a.albums.length;if(0<c){$("album-more-albums").setStyle("display","block");$("album-rights").addClass("padded");var b=document.getElementById("album-more-albums");
b.addEventListener("click",G);window.addEventListener("click",n);document.body.addEventListener("click",n);b.innerHTML="<strong>"+c+"</strong> "+(1==c?g("more-release"):g("more-releases"));b=document.createElement("ul");b.id="additional-albums-list";document.getElementById("album-dropdown").appendChild(b);for(var d=0;d<c;d++){var f=a.albums[d],e=document.createElement("li"),s=document.createElement("a");s.href=f.uri;s.innerHTML=f.name;b.appendChild(e);e.appendChild(s)}}});a.createUniquesPlaylist().done(function(a){if(0!=
a.length){i=u.forPlaylist(a.playlist,{type:"tracks",fields:R(),header:"no",fetch:"greedy",style:"rounded"});f.connect(i);var a=document.createElement("div"),b=document.createElement("h2");b.innerText=g("additional-tracks");a.appendChild(b);$(a).addClass("additional-wrapper");$("album-additional").empty();$("album-additional").appendChild(a);$("album-additional").appendChild(i.node);i.init()}})});l.render(document.getElementById("albums-list"))}});f.init()}).fail(function(){})}).fail(function(){$$("body > .throbber").setStyle("display",
"none");d.application.online&&$$("body > .error").setStyle("display","block")})});else return d.application.openURI("spotify:search"),!1},R=function(){var a;a="sp:"===window.location.protocol?["star","share","track","time","popularity"]:["track","time","popularity"];e.name.match(/various/i)&&(a="sp:"===window.location.protocol?"star share track artist time popularity".split(" "):["track","artist","time","popularity"]);return a},H=function(a){null!==a&&(clearTimeout(B),B=setTimeout(function(){var b=
"spotify:track:"+a,c;a:{var e=!1;try{f.deselect();for(var h=$(f.node).getElements("tr.sp-list-item"),k=h.length,g=0;g<k;g++)if("function"===typeof h[g].getAttribute&&h[g].getAttribute("data-uri")==b){f.selectItem(g);I(g);e=!0;break}c=e;break a}catch(m){}c=void 0}if(!c){var l=0,j=0;try{f.deselect();var i=$(f.node).getElements("tr.sp-list-item"),n=i.length;d.Track.fromURI(b).load("name","duration").done(function(a){for(var b=y.durationToReadable(a.duration),c=0;c<n;c++)if("function"===typeof i[c].getAttribute&&
i[c].getElement(".sp-list-cell-track").innerText==a.name&&i[c].getElement(".sp-list-cell-time").innerText==b){l++;j=c;break}1===l&&(f.selectItem(j),I(j))})}catch(p){}}},0))},I=function(a){var b=$("album-main").getElements("tr.sp-list-item");if((a=$(b[a]).getPosition().y)&&"number"===typeof a)b=y.scrollPosition().y,a>window.innerHeight+b-30&&window.scrollTo(0,a-30)},G=function(a){O.clientEvent("click-more-releases");$("album-dropdown").toggleClass("visible");a.preventDefault();return!1},n=function(a){a=
a.target;do{if("album-dropdown"===a.id||"album-more-albums"===a.id)return!1;a=a.parentNode}while(null!==a&&a!==document.body);$("album-dropdown").removeClass("visible")};E()});
