require("$api/models $views/list#List $views/image#Image $views/buttons#StartRadioButton $views/buttons#ShareButton /strings/main.lang /scripts/similar".split(" "),function(c,s,q,w,x,h,y){var t,u,n=0,j=!1,e,b,r,d,i=h.get.bind(h);$$(".localize").each(function(a){a.innerHTML=i(a.get("data-string"))});var h=function(){var a;$("album-page").setStyle("display","none");$("album-image").empty();$("album-tracks").empty();$("album-additional").empty();$("albums-list").empty();$("album-rights").empty();$("album-buttons").empty();
$("artist-details").innerHTML='<div id="artist-image" class="l"></div><div id="album-details-row" class="l"><span id="album-by"></span><a id="artist-name"></a></div>';$("artist-details-various").innerHTML="";$("album-more-albums").empty();$("album-more-albums").setStyle("display","none");$("album-dropdown").empty();$("album-dropdown").removeClass("visible");document.getElementById("album-dropdown").removeEventListener("click",v);document.body.removeEventListener("click",k);window.removeEventListener("click",
k);document.getElement("#albums-more h2").empty();n=0;j=!1;if(c.application.arguments[0])SpotifyApi.api.analyticsContext("Application Load",function(){u=c.application.arguments[0];a="spotify:album:"+u;r=null;c.application.arguments[1]&&(r=c.application.arguments[1]);b=c.Album.fromURI(a);b.load("name","tracks","playable","artists","image").done(function(a){$("album-page").setStyle("display","block");$$("body > .throbber").setStyle("display","none");$$("body > .error").setStyle("display","none");t=
a.artists[0].uri.split(":")[2];e=c.Artist.fromURI("spotify:artist:"+t);e.load("name","albums","image").done(function(){var a=document.createElement("a");a.href=b.uri.toSpotifyURL();a.innerHTML=b.name;a.title=b.name;$("album-title").empty();$("album-title").grab(a);-1<e.name.toLowerCase().indexOf("various")?$("artist-details-various").innerHTML=i("various-artists"):($("artist-details-various").innerHTML="",$("album-by").innerHTML=i("by")+" ",a=$("artist-name"),a.href=e.uri.toSpotifyURL(),a.className=
"spuri",a.innerHTML=e.name,a=new q(e,{style:"none",title:e.name,height:30,width:30,player:!1,animate:!1,link:e.uri}),$("artist-image").appendChild(a.node));var a=$("album-buttons"),c=w.forAlbum(b),l=x.forAlbum(b);a.appendChild(l.node);a.appendChild(c.node);b.load("copyrights").done(function(){if(0<b.copyrights.length)for(var a=b.copyrights.length,m=0;m<a;m++){var g=document.createElement("div");g.innerHTML=b.copyrights[m];$("album-rights").appendChild(g)}});a=q.forAlbum(b,{style:"none",title:b.name,
height:128,width:128,player:!1,animate:!1,link:b.uri});$("album-image").appendChild(a.node);a="sp:"===window.location.protocol?"star share number track trackartist time popularity".split(" "):["number","track","trackartist","time","popularity"];e.name.match(/various/i)&&(a="sp:"===window.location.protocol?"star share number track artist time popularity".split(" "):["number","track","artist","time","popularity"]);d=s.forAlbum(b,{context:b,type:"tracks",fields:a,header:"no",playable:!0,fetch:"greedy",
style:"rounded"});$("album-tracks").appendChild(d.node);d.addEventListener("snapshot-load",function(){var a=r;if(null!==a)try{for(var b=$(d.node).getElements("tr.sp-list-item"),g=b.length,f=0;f<g;f++)"function"===typeof b[f].getAttribute&&-1<b[f].getAttribute("data-uri").indexOf(a)&&d.selectItem(f)}catch(c){}});d.addEventListener("initialized",function(){if(!j){j=!0;var a=new y.SimilarAlbums(b);SpotifyApi.api.analyticsContext("showSimilarAlbums()",function(){a.find().done(function(a){var b=a.albums.length;
if(0<b){$("album-more-albums").setStyle("display","block");var f=document.getElementById("album-more-albums");f.addEventListener("click",v);window.addEventListener("click",k);document.body.addEventListener("click",k);f.innerHTML="<strong>"+b+"</strong> "+(1==b?i("more-release"):i("more-releases"));f=document.createElement("ul");f.id="additional-albums-list";document.getElementById("album-dropdown").appendChild(f);for(var c=0;c<b;c++){var e=a.albums[c],l=document.createElement("li"),d=document.createElement("a");
d.href=e.uri;d.innerText=e.name;f.appendChild(l);l.appendChild(d)}}});a.createUniquesPlaylist().done(function(a){if(0!=a.length){a=s.forPlaylist(a.playlist,{type:"tracks",fields:z(),header:"no",fetch:"greedy",style:"rounded"});d.connect(a);var b=document.createElement("div"),c=document.createElement("h2");c.innerText=i("additional-tracks");b.appendChild(c);$(b).addClass("additional-wrapper");$("album-additional").appendChild(b);$("album-additional").appendChild(a.node);a.init()}})});-1==e.name.toLowerCase().indexOf("various")&&
p(0)}});d.init()}).fail(function(){})}).fail(function(){$$("body > .throbber").setStyle("display","none");$$("body > .error").setStyle("display","block")})});else return c.application.openURI("spotify:search"),!1},z=function(){var a;a="sp:"===window.location.protocol?["star","share","track","time","popularity"]:["track","time","popularity"];e.name.match(/various/i)&&(a="sp:"===window.location.protocol?"star share track artist time popularity".split(" "):["track","artist","time","popularity"]);return a},
p=function(a){var l=$("albums-list");0===a&&l.empty();if(a===(8>e.albums.length?e.albums.length:100)||8===n)return!0;e.albums.snapshot(a,1).done(function(d){for(var d=d.get(a).albums,h=[],k=[],j=0,m=d.length;j<m;j++)h.push(d[j].load("playable"));var g=null,f=new c.Promise;c.Promise.join(h).each(function(a){k.push(a.uri);a.playable&&null==g&&(g=a)}).always(function(){null===g||0<=k.indexOf(b.uri)?f.setFail():f.setDone()});0===h.length&&f.setFail();f.fail(function(){p(a+1)}).done(function(){if(g.uri===
b.uri)return p(a+1),!1;var c=document.createElement("li");c.className="item cf mb";c.innerHTML='<div class="album-cover"></div><div class="title"></div>';g.load("name","image","artists").done(function(b){if(e.uri!==b.artists[0].uri)return!1;if(0===n){var d=e.name;-1<d.toLowerCase().indexOf("various")?(d=i("various-artists"),d='<span class="grey7">'+d+"</span>"):d='<a href="'+e.uri.toSpotifyURL()+'" class="spuri">'+d+"</a>";document.getElement("#albums-more h2").innerHTML='<span class="grey7">'+i("more-by")+
"</span> "+d}d=q.forAlbum(b,{title:b.name,height:30,width:30,player:!1,animate:!1,link:b.uri});c.getElement(".album-cover").appendChild(d.node);c.getElement(".title").innerHTML='<a href="'+b.uri.toSpotifyURL()+'" data-spuri="'+b.uri+'">'+b.name+"</a>";l.appendChild(c);n++;p(a+1)})})})},v=function(a){$("album-dropdown").toggleClass("visible");a.preventDefault();return!1},k=function(a){a=a.target;do{if("album-dropdown"===a.id||"album-more-albums"===a.id)return!1;a=a.parentNode}while(null!==a&&a!==document.body);
$("album-dropdown").removeClass("visible")};"sp:"===window.location.protocol&&$("body").addClass("desktop");c.application.addEventListener("arguments",h);c.application.load("arguments").done(h);$$("body").addEvent("click",function(a){if("A"===a.target.nodeName){var b=a.target.href.match(/spotify:/)?a.target.href:a.target.href.toSpotifyURI();c.application.openURI(b);a.preventDefault();return!1}if(a.target.className.match(/spuri/))return b=a.target.getAttribute("data-spuri"),c.application.openURI(b),
a.preventDefault(),!1;if("IMG"===a.target.nodeName.toUpperCase()&&"sp-image-img"===a.target.className&&"A"===a.target.parentNode.parentNode.nodeName.toUpperCase()&&a.target.parentNode.parentNode.href.match(/spotify:/))return b=a.target.parentNode.parentNode.href,c.application.openURI(b),a.preventDefault(),!1;"sp-image-wrapper"===a.target.className&&("A"===a.target.parentNode.nodeName.toUpperCase()&&a.target.parentNode.href.match(/spotify:/))&&(b=a.target.parentNode.href,c.application.openURI(b),a.preventDefault());
return!1})});
