require(["$api/models","/scripts/utils","/strings/main.lang"],function(j,p,n){function f(a){this.album=a;this.provider=new l(a)}function l(a){this.album=a}var h=j.Promise,i=h.join,m=n.get.bind(n);f.prototype.find=function(){var a={},b=new h(a),c=this.album.uri;this.provider.find().done(this,function(d){d=d.filter(function(a){return a.uri!=c});this._labelAlbums(d).done(this,function(c){a.albums=c;b.setDone()})});return b};f.prototype.createUniquesPlaylist=function(){var a=j.Playlist.createTemporary("extra-tracks-"+
this.album.uri),b={},c=new h(b);this.provider.find().done(this,function(d){var e=[],g={},d=d.concat(this.album);this._loadTracksFromAlbums(d).each(this,function(a){g[a.uri]=a.tracks;for(var c=0,d=a.tracks.length;c<d;c++){var b=a.tracks[c];!this._containsTrack(e,b)&&b.playable&&e.push(b)}}).always(this,function(){var d=this,f=e.filter(function(a){return!d._containsTrack(g[d.album.uri],a)});this._populatePlaylist(a,f).done(function(a){b.playlist=a.playlist;b.length=f.length;c.setDone()})})});return c};
f.prototype._populatePlaylist=function(a,b){var c={},d=new h(c);a.done(function(a){a.load("tracks").done(function(){a.tracks.clear().done(function(){a.tracks.add(b).done(function(){c.playlist=a;d.setDone()})})})});return d};f.prototype._labelAlbums=function(a){var b="name date discs availability type uri".split(" "),c="name date availability discs_length tracks_length type uri".split(" "),d=0,e=this,g=[],k=new h(g);c.forEach(function(){});i(a.map(function(a){return a.load(b.concat("playable"))})).done(function(a){void 0===
a||0==a.length?k.setDone():i(a.map(function(a){return a.playable?(d++,e._loadTransformed(a,c)):null}).filter(function(a){return null!==a})).done(function(a){for(var c=void 0!==a?a.length:0,d=0;d<c;d++){var b=a[d],e=b.name+", "+p.readableYear(b.date)+". "+b.tracks_length+" "+(1==b.tracks_length?m("track"):m("tracks"));"premium"==b.availability&&(e+=" ("+m("premium-edition")+")");g.push({uri:b.uri,name:e})}k.setDone()})});return k};f.prototype._make_discs_length=function(a,b){var c=a.load("discs");
c.done(function(a){b.discs_length=a.discs.length});return c};f.prototype._containsTrack=function(a,b){for(var c=0,d=a.length;c<d;c++)if(this._tracksEqual(a[c],b))return!0;return!1};f.prototype._tracksEqual=function(a,b){if(a.name.toLowerCase()===b.name.toLowerCase()&&2E3>=Math.abs(a.duration-b.duration)){for(var c=a.artists.length,d=0,e=c;d<e;d++)for(var g=0,k=b.artists.length;g<k;g++)a.artists[d]==b.artists[g]&&c--;if(0===c)return!0}return!1};f.prototype._loadTracksFromAlbums=function(a){var b=this._loadTracksFromAlbum.bind(this),
a=a.map(b);return i(a)};f.prototype._loadTracksFromAlbum=function(a){var b={uri:a.uri,tracks:[]},c=new h(b);this._allTracks(a).done(function(a){i(a).done(function(a){a=a.map(function(a){return a.loadAll("name","artists","duration","playable")});a.forEach(function(a){a.each(function(a){b.tracks.push(a)})});i(a).always(function(){c.setDone()})})});return c};f.prototype._allTracks=function(a){var b=[],c=new h(b);a.load("discs").done(function(a){i(a.discs.map(function(a){return a.load("tracks")})).always(function(a){a.forEach(function(a){b.push(a.tracks.snapshot())});
c.setDone()})});return c};f.prototype._make_tracks_length=function(a,b){var c=new h,d=0;this._allTracks(a).done(function(a){i(a).each(function(a){d+=a.range.length}).always(function(){b.tracks_length=d;c.setDone()})});return c};f.prototype._loadTransformed=function(a,b){var c={},d=new h(c),e=[],g=this;b.forEach(function(b){if(a.hasOwnProperty(b))c[b]=a[b];else if(g["_make_"+b])e.push(g["_make_"+b].call(g,a,c));else throw"Tried running _make_"+b+" but failed. This should not happen.";});0==e.length?
d.setDone():i(e).always(function(){d.setDone()});return d};l.prototype.find=function(){var a=[],b=new h(a);j.Artist.fromURI(this.album.artists[0].uri).load("albums","singles").done(this,function(c){var d=new j.Promise,e=new j.Promise;c.albums.snapshot().done(this._filterSnapshot.bind(this,d));c.singles.snapshot().done(this._filterSnapshot.bind(this,e));i(d,e).always(function(c){for(var c=c||[],d=0,e=c.length;d<e;d++)a.push.apply(a,c[d]);b.setDone()})});return b};l.prototype._filterSnapshot=function(a,
b){var c=[];b.loadAll("albums").each(this,function(a){for(var b=!1,g=0,f=a.albums.length;g<f;g++)b=b||a.albums[g].uri===this.album.uri;b&&c.push.apply(c,a.albums)}).always(function(){a.setDone(c)})};exports.SimilarAlbums=f});
