require("$api/models $api/models#Promise $views/image#Image $views/buttons $api/hermes $api/relations#Relations $api/library#Library scripts/utils#$ $views/throbber#Throbber $api/i18n strings/header.lang $api/offline#Offline".split(" "),function(i,s,w,t,R,E,S,g,T,x,y,F){function z(a,b){var d=new w(a,{animate:!0,width:42,height:42,style:"embossed",link:a&&a.uri||"spotify:",placeholder:"user"}),c=document.createElement("div");c.className="name-popover";c.textContent=b||a.name||"";d.node.appendChild(c);
return d.node}var k=y.get.bind(y),j,b,m,A,u=new z(i.session.user,k("You")),v=0,n,h,B=function(){updatename(j)},s=function(){var a=i.application.arguments.join(":");if(j){var e=j;e.addEventListener("change:name",B);e.removeEventListener("change:subscribed",C)}j=i.Playlist.fromURI(a);m._resetImage();b.title.textContent="";b.title.removeAttribute("href");b.desc.textContent="";b.followersImages.innerHTML="";b.ownerName.textContent="";b.ownerName.removeAttribute("href");r(0);b.numberOfTracks.textContent=
"";for(var d in h)a=h[d],(a.node||a).style.display="none";var c=j;if(!h){d=document.createElement("button");d.className="offline-button";d.textContent=k("AvailableOffline");d.addEventListener("click",G,!1);d={subscribeButton:t.SubscribeButton.forPlaylist(c),startRadioButton:t.StartRadioButton.forPlaylist(c),shareButton:t.ShareButton.forPlaylist(c),offlineButton:d};for(var q in d)a=d[q],a=a.node||a,a.style.display="none",b.buttons.appendChild(a);b.buttons.insertBefore(b.numberOfTracks,d.offlineButton);
h=d}c.load("image").done(f(H));c.load("name").done(f(I));c.load("description").done(f(function(){c.description?c.load("description").done(f(J)):D(c)})).fail(function(){D(c)});c.load("owner").done(f(function(){c.owner.load("currentUser").done(f(function(a){!0!==a.currentUser&&(h.subscribeButton.setItem(c),h.subscribeButton.node.style.display="");p()}))}));h.startRadioButton.item=c;h.startRadioButton.node.style.display="";h.shareButton.item=c;h.shareButton.node.style.display="";var g=new i.Promise;
q=i.session.load("capabilities");d=c.load("allows");i.Promise.join([q,d]).done(f(function(){g.object=i.session.capabilities.offlineSync&&c.allows.offlineSync;g.setDone()})).fail(function(a,c){g.setFail(c)});g.done(f(function(a){a?n.getSyncState(c).done(function(a){l(a.enabled);h.offlineButton.style.display="";p()}):(h.offlineButton.style.display="none",p())}));p();c.load("tracks").done(f(K));c.load("owner").done(f(L));setTimeout(f(M),0,c);A||(b.throbber.style.display="none",A=!0);q=j;q.addEventListener("change:name",
B);q.addEventListener("change:subscribed",C)},D=function(a){var e=new i.Promise,d=function(a,b){e.setFail(b||a)};a.load("tracks").done(f(function(){a.tracks.snapshot(0,24).done(f(function(a){a.length?a.loadAll("artists").done(f(function(a){a=a.map(function(a){return a.artists[0].load("name","uri")});i.Promise.join(a).done(f(function(a){var c=[],b=[];a.forEach(function(a){var e=a.uri&&a.name,d=~b.indexOf(a&&a.uri);e&&!d&&(b.push(a.uri),c.push(a))});a=c.slice(0,8);e.object=a;e.setDone()})).fail(d)})).fail(d):
d("No tracks available")})).fail(d)})).fail(d);e.done(f(function(a){a=a.map(function(a){return'<a href="'+a.uri+'">'+a.name+"</a>"});b.desc.innerHTML=['<div class="including-artists">',k("IncludingArtists"),": ",a.join(", "),"</div>"].join("")})).fail(function(a,b){console.error(b&&b.message,b)})},H=function(a){a.image?m.setImage(a.image):m._resetImage()},M=function(a){a.load("subscribers","owner").done(f(N))},N=function(a){a.subscribers.snapshot(0,0).done(f(function(a){r(a.length)}));var b=E.forCurrentUser();
i.Promise.join([a.subscribers.snapshot(0,100),b.subscribers.snapshot(0,100),b.subscriptions.snapshot(0,100),i.session.user.load("username","uri"),a.load("subscribed"),a.owner.load("currentUser")]).done(f(O))},r=function(a){v=a;b.followersLabel.textContent=1===a?k("Follower"):k("Followers");b.followersNumber.textContent=x.number(a)},O=function(a){var e=a[1],d=a[2],c=a[3],g=a[4],h=a[5],a=a[0].toURIs(),j=e.toURIs(),k=d.toURIs(),l;!1===h.currentUser&&(e=a.indexOf("spotify:user:"+(c&&c.username||"")),
-1!==e?l=a.splice(e,1)[0]:g.subscribed&&(l=c.uri));c=a.reverse().map(function(a){var b=-1===j.indexOf(a)?0:1,c=-1===k.indexOf(a)?0:2;return[b+c,a]}).sort().map(function(a){return a[1]});l&&c.unshift(l);var c=c.slice(0,30),m=0,n=0,p=f(function(a){n++;a.image&&!/.*fbcdn.*\.gif$/.test(a.image)&&3>m&&(m++,a.uri===l?(a=u,b.followersImages.appendChild(a)):(a=new z(a,void 0),b.followersImages.insertBefore(a,b.followersImages.firstChild)))});c.forEach(function(a){i.User.fromURI(a).load("name","image","username",
"uri").done(p)})},I=function(a){var e="";a.name?e=a.name:/:starred$/.test(a.uri)?e=k("Starred"):/:toplist$/.test(a.uri)&&(e=k("TopTracks"));b.title.setAttribute("href",a.uri);b.title.textContent=e},J=function(a){b.desc.innerHTML=a.description},K=function(a){a.tracks.snapshot(0,0).done(f(P))},P=function(a){var e=x.number(a.length),a=1===a.length?k("Track"):k("Tracks");b.numberOfTracks.textContent=e+" "+a;p()},L=function(a){a.owner.load("name","currentUser","image").done(f(Q))},Q=function(a){var e=
"",d;if(a.currentUser)e=k("ByYou");else if(d=a.name||a.username)e=k("By")+" "+d;b.ownerName.textContent=e;b.ownerName.href=a.uri},p=function(){var a=b.buttons.style.right||0;b.buttons.style.right="auto";var e=b.buttons.offsetWidth;b.buttons.style.right=a;b.content.style.minWidth=e+"px"},G=function(){n.getSyncState(j).done(f(function(a){h.offlineButton.classList.contains("turn-on")!==a.enabled?l(a.enabled):(a.enabled?(l(!1),n.disableSync(j).fail(function(){l(!0)})):(l(!0),n.enableSync(j).fail(function(){l(!1)})),
h.offlineButton.style.display="")})).fail(function(){console.error("failed to get sync state for: ",j)})},l=function(a){a?h.offlineButton.classList.add("turn-on"):h.offlineButton.classList.remove("turn-on")},f=function(a){var b=j;return function(){b.uri===j.uri&&a.apply(this,arguments)}},C=function(a){a.target.subscribed?(3<=b.followersImages.childNodes.length&&b.followersImages.removeChild(b.followersImages.firstChild),b.followersImages.appendChild(u),r(v+1)):(b.followersImages.removeChild(u),r(Math.max(0,
v-1)))};n=F.forCurrentUser();b={content:g("#content"),throbber:g("#main-throbber"),cover:g("#cover"),metaMoreWrapper:g("#meta-more-wrapper"),titleOwnerWrapper:g("#title-owner-wrapper"),title:g("#title a"),owner:g("#owner a"),ownerName:g("#owner-name a"),desc:g("#desc"),more:g("#more"),buttons:g("#buttons"),followersNumber:g("#followers-number"),followersImages:g("#followers-images"),followersLabel:g("#followers-number-label"),numberOfTracks:g("#number-of-tracks")};m=new w(null,{animate:!1,height:148,
width:148,style:"embossed",placeholder:"playlist"});b.cover.appendChild(m.node);i.application.addEventListener("arguments",s);i.application.load("arguments").done(s).fail(function(){console.error("fail")})});
