require(["$profile/profile-utils","$shared/events#EventHandler","$api/models#Observable","$api/relations#Relations"],function(c,g,h,f){var e={FOLLOWERS:"Subscribers",FOLLOWING:"Subscriptions"},c=function(){this.events=this.user=null};SP.inherit(c,h);c.prototype.debug=!1;c.prototype.isSelf=!1;c.prototype.subscriptionCollection="combinedSubscriptions";c.prototype.reset=function(){this._log("reset");this.events?this.events.removeAll():this.events=new g(this);this.subscribers={start:0,offset:0,total:0,
loaded:[],loading:!1,all:!1,refreshed:!1};this.subscriptions={start:0,offset:0,total:0,loaded:[],loading:!1,all:!1,refreshed:!1};this._resetTimer();this.retries={};this.relations=null;this.subscriptionsRefreshFlag=this.subscribersRefreshFlag=!1};c.prototype.initialize=function(a,b){this._log("init");this.user=a;this.isSelf=b;this.reset();this.relations=this.isSelf?f.forCurrentUser():f.forUser(a)};c.prototype.requestRelations=function(){this.requestSubscribers();this.requestSubscriptions()};c.prototype.requestSubscriptions=
function(){this._log("requesting subscriptions");this.subscriptions.loading||(this.subscriptions.all&&!this.subscriptionsRefreshFlag?this._collectionReady(e.FOLLOWING):(this.subscriptions={start:0,offset:0,total:0,loaded:[],loading:!1,all:!1,refreshed:this.subscriptionsRefreshFlag},this._loadSubscriptions()))};c.prototype.requestSubscribers=function(){this._log("requesting subscribers");this.subscribers.loading||(this.subscribers.all&&!this.subscribersRefreshFlag?this._collectionReady(e.FOLLOWERS):
(this.subscribers={start:0,offset:0,total:0,loaded:[],loading:!1,all:!1,refreshed:this.subscribersRefreshFlag},this._loadSubscribers()))};c.prototype._loadSubscriptions=function(){this.subscriptions.loading=!0;this.relations.load(this.subscriptionCollection).done(this._relationsLoaded.bind(this,e.FOLLOWING)).fail(this,function(a,b){this._relationsFailed(b,e.FOLLOWING)})};c.prototype._loadSubscribers=function(){this.subscribers.loading=!0;this.relations.load("subscribers").done(this._relationsLoaded.bind(this,
e.FOLLOWERS)).fail(this,function(a){this._relationsFailed(a,e.FOLLOWERS)})};c.prototype._relationsLoaded=function(a){this._log("relations loaded:",a,this.isSelf);var b=a.toLowerCase(),d=b===e.FOLLOWING.toLowerCase()?this.subscriptionCollection:b;!this[b].refreshed&&0===this[b].start&&(this.isSelf?this._watchCollection(a):a===e.FOLLOWERS&&this._watchSubscribers());this.relations[d].snapshot(this[b].start,200).done(this,function(a){this._snapshotLoaded(a,b)}).fail(this,function(a){this._snapshotFailed(a,
b)})};c.prototype._watchCollection=function(a){var b=a.toLowerCase(),d=this,a=a===e.FOLLOWING?this.subscriptionCollection:b;this.events.listen(this.relations[a],"add",function(a){d._onChangeEvent(a,b+"_add",b)});this.events.listen(this.relations[a],"remove",function(a){d._onChangeEvent(a,b+"_remove",b)});this._log("setting listener on",a,this.relations[a],this.events)};c.prototype._watchSubscribers=function(){this.user.load("subscribed").done(this,this._readyToWatchSubscribers)};c.prototype._readyToWatchSubscribers=
function(){var a=this;this._log("setting listener for subscribers",this.user,this.events);this.events.listen(this.user,"change:subscribed",function(b){this._log("heard change event",b);this.subscribersRefreshFlag=!0;a._generateEvent("subscribers_change",b)})};c.prototype._onChangeEvent=function(a,b,d){this._log("change event detected",a,b);this[d+"RefreshFlag"]=!0;this._generateEvent(b,{uri:a.uris[0]})};c.prototype._snapshotLoaded=function(a,b){var d=this[b.toLowerCase()];this._log("snapshot loaded",
b,a,d);d.total=a.length;for(var c=0;200>c&&c<a.range.length;c++)d.loaded.push(a.get(d.start+c));d.start+=200;0===a.range.length||d.loaded.length>=a.length||1E3<=d.loaded.length?(d.all=!0,this._collectionReady(b.toLowerCase())):this._relationsLoaded(b.toLowerCase())};c.prototype._collectionReady=function(a){var b=this[a.toLowerCase()];this._log("collection ready",b);b.loading=!1;b={total:b.total,loaded:b.loaded};this._generateEvent(a.toLowerCase()+"_loaded",b);this._checkComplete()};c.prototype._checkComplete=
function(){var a=!0,b;for(b in e)a=a?this[e[b].toLowerCase()].all:!1;a&&this._generateEvent("all_relations_loaded",{numSubscribers:this.subscribers.total,numSubscriptions:this.subscriptions.total,subscribers:this.subscribers.loaded,subscriptions:this.subscriptions.loaded})};c.prototype._relationsFailed=function(a,b){this._log("handle fail",this.retries,arguments);var c=this.retries[b];!c||2>c?(this.retries[b]=!c?1:c+1,this["request"+b].call(this)):console.log(b+" request failed",a)};c.prototype._snapshotFailed=
function(a,b){this._log("handle snapshot fail",this.retries,arguments);var c=this.retries[b+"Snapshot"];!c||2>c?(this.retries[b+"Snapshot"]=!c?1:c+1,this._relationsLoaded.call(this,b)):console.log(b+" snapshot failed",a)};c.prototype._generateEvent=function(a,b){var c=new Event(a);c.data=b||null;this.dispatchEvent(c)};c.prototype._log=function(){this.debug&&window.console&&(window.console.log&&window.console.log.apply)&&window.console.log.apply(console,["   [RelationsHelper]",arguments])};c.prototype._resetTimer=
function(){this.internalTimer=(new Date).getTime()};c.prototype.markLoaded=function(){this.debug&&this._log("loaded in "+((new Date).getTime()-this.internalTimer)+" ms")};c.prototype.LOAD_CEIL=1E3;exports.RelationsHelper=new c;exports.RelationTypes=e});
