require(["$api/search#Search","$api/models","$views/image#Image","$views/utils/dom","$views/utils/css"],function(l,f,m,h,e){function b(a,g,c){this.results=[];this.selected=null;this.hasSelected=!1;this.prev=null;this.templates=g;this.resetSearchButton=a.querySelector(".search-close");this.setEscapeClose=this.setEscapeClose.bind(this);this.selectUp=this.selectUp.bind(this);this.selectDown=this.selectDown.bind(this);this.deselect=this.deselect.bind(this);this.inputField=a.querySelector(".music-input");
this.messageContainer=a.querySelector(".message-input");this.resultContainer=a.querySelector(".music-search");this.selectedDisplay=a.querySelector(".selected-search");this.sendButton=c;h.addEventListener(this.inputField,"keyup",this.sendQuery.bind(this));h.addEventListener(this.resetSearchButton,"click",this.resetSearch.bind(this))}var n=["name","image","popularity"],p=["name","image","popularity","artists"],q=["name","image","popularity","artists"],r=document.createElement("ul"),s=document.createElement("li"),
k=document.createElement("span"),t=document.createElement("div");b.prototype.sendQuery=function(a,g){var c=(a.target||g).value;switch(a.keyCode){case 13:this.select();a.stopImmediatePropagation();a.preventDefault();break;case 27:this.escapeClose();break;case 38:this.selectUp();a.stopImmediatePropagation();a.preventDefault();break;case 40:this.selectDown();a.stopImmediatePropagation();a.preventDefault();break;default:0<c.length?(this.search(c),e.addClass(this.resetSearchButton,"show")):(this.hideSearchResults(),
e.removeClass(this.resetSearchButton,"show"))}};b.prototype.selectUp=function(){this.selected=null===this.selected||0>=this.selected?this.results.length-1:this.selected-1;this.setSelected(this.results[this.selected])};b.prototype.selectDown=function(){this.selected=null===this.selected||this.selected===this.results.length-1?0:this.selected+1;this.setSelected(this.results[this.selected])};b.prototype.setSelected=function(a){void 0!==a&&(this.prev&&e.removeClass(this.prev,"selected"),e.addClass(a,"selected"),
this.prev=a)};b.prototype.select=function(a){var g=this.results[this.selected],c=function(){this.hasSelected=!0;this.selectedDisplay.innerHTML=b(j);e.addClass(this.selectedDisplay,"show");e.addClass(this.inputField,"hide");this.hideSearchResults();this.selected=-1;this.messageContainer.focus();h.addEventListener(this.inputField,"focus",this.deselect);this.sendButton.setDisabled(!1)}.bind(this);if(null!==g||a){var d=g?this.dataObjects[g.getAttribute("data-uri")]:this.dataObjects[a],b,j;switch(d?d.uri.split(":")[1]:
a){case "track":this.selectedItem=f.Track.fromURI(d.uri);b=this.templates.selected_track;d.album.load("name").done(this,function(a){j={song:d.name,album:a.name,by:"by",artist:d.artists[0].name};c()});break;case "album":this.selectedItem=f.Album.fromURI(d.uri);b=this.templates.selected_album;j={album:d.name,by:"by",artist:d.artists[0].name};c();break;case "artist":this.selectedItem=f.Artist.fromURI(d.uri),b=this.templates.selected_artist,j={artist:d.name},c()}}};b.prototype.deselect=function(){this.hasSelected=
!1;h.removeEventListener(this.inputField,"focus",this.deselect);this.inputField.value="";this.selectedDisplay.innerHTML="";e.removeClass(this.selectedDisplay,"show");e.removeClass(this.inputField,"hide");this.sendButton.setDisabled(!0)};b.prototype.search=function(a){a=l.suggest(a);f.Promise.join(a.artists.snapshot(0,3),a.albums.snapshot(0,3),a.tracks.snapshot(0,3)).done(this.onSnapshotDone.bind(this)).fail(this.onSuggestError)};b.prototype.onSnapshotDone=function(a){f.Promise.join(this.loadItems(a[0].toArray(),
n),this.loadItems(a[1].toArray(),p),this.loadItems(a[2].toArray(),q)).done(this.onSearchMore.bind(this)).fail(this.onSuggestError.bind(this))};b.prototype.loadItems=function(a,b){for(var c=[],d=0,i=a.length;d<i;d+=1)c.push(a[d].load(b));return f.Promise.join(c)};b.prototype.onSearchMore=function(a){var b=this.dataObjects||{};this.dataObjects={};var c=!1;a.forEach(function(a){!1!==a instanceof Object&&Object.keys(a).forEach(function(b){this.dataObjects[a[b].uri]=a[b];a.hasOwnProperty(b)&&(c=!0)}.bind(this))}.bind(this));
!1===c&&(this.dataObjects=b);this.onMetadataDone(a)};b.prototype.onMetadataDone=function(a){document.createDocumentFragment();if("function"===typeof this.onSearchResult)this.onSearchResult(a)};b.prototype.onSuggestError=function(){console.error("error",arguments)};b.prototype.onSearchResult=function(a){var b=t.cloneNode(!1),c=[];this.results=[];var d=function(a){for(var b=0;b<a.childNodes.length;b++)this.results.push(a.childNodes[b])}.bind(this);void 0!==a[0]&&c.push(this.buildSection("artists",a[0]));
void 0!==a[1]&&c.push(this.buildSection("albums",a[1]));void 0!==a[2]&&c.push(this.buildSection("tracks",a[2]));void 0!==a[2]&&d(c[2]);void 0!==a[1]&&d(c[1]);void 0!==a[0]&&d(c[0]);for(d=c.length;d;)c[d-1]&&0!==a[d-1].length&&b.appendChild(c[d-1]),d--;this.resultContainer.innerHTML="";this.resultContainer.appendChild(b)};b.prototype.hideSearchResults=function(){this.resultContainer.innerHTML=""};b.prototype.buildSection=function(a,b){if(!b)return"";var c=r.cloneNode(!1),d;e.addClass(c,"search-section");
e.addClass(c,a);for(var i=0,f=b.length;i<f;i++)(d=this.buildItem(b[i]))&&c.appendChild(d);return c};b.prototype.buildItem=function(a){var b=new m(a,{width:25,style:"plain"}),c=s.cloneNode(!1);e.addClass(c,"search-item");c.setAttribute("data-uri",a.uri);var d=k.cloneNode(!1);e.addClass(d,"item-name");d.innerHTML=a.name.decodeForText();c.appendChild(b.node);c.appendChild(d);a.artists&&0<a.artists.length&&(b=k.cloneNode(!1),e.addClass(b,"artist-name"),b.appendChild(document.createTextNode(" by "+a.artists[0].name.decodeForText())),
c.appendChild(b));h.addEventListener(c,"click",function(a){this.select(a.target.getAttribute("data-uri"));a.preventDefault();a.stopImmediatePropagation()}.bind(this));return c};b.prototype.resetSearch=function(){!0===this.hasSelected?(this.deselect(),this.inputField.focus()):(this.inputField.value="",this.hideSearchResults(),e.removeClass(this.resetSearchButton,"show"))};b.prototype.reset=function(){this.results=[];this.selected=null;this.hasSelected=!1;this.selectedItem=this.prev=null;this.inputField.value=
"";this.messageContainer.value="";this.hideSearchResults();e.removeClass(this.resetSearchButton,"show")};b.prototype.setEscapeClose=function(a){this.escapeClose=a};b.prototype.getMessage=function(){return this.messageContainer.value};b.prototype.getSelection=function(){return this.selectedItem};exports.Search=b});
