var templates={offline:function(b){b="\n  "+b.offlineMessage;return b+="\n"},selected_artist:function(b){b='\n  <span class="artist">'+b.artist;return b+="</span>\n"},selected_album:function(b){var a;a='\n  <span class="album">'+b.album;a+="</span> ";a+=b.by;a+=' <span class="artist">';a+=b.artist;return a+="</span>\n"},selected_track:function(b){var a;a='\n  <span class="song">'+b.song;a+='</span> - <span class="album">';a+=b.album;a+="</span> ";a+=b.by;a+=' <span class="artist">';a+=b.artist;return a+=
"</span>\n"},send_done:function(b){b='\n  <div class="item sent-message">'+b.sentMessage;return b+="</div>\n"},send_form:function(b){var a;a='\n  <div class="form-section item">\n    <input placeholder="'+b.inputPlaceholder;a+='" class="music-input" type="text" name="music"></input>\n    <div class="selected-search truncate-text"></div>\n    <button class="search-close"></button>\n    <div class="music-search"></div>\n    <textarea placeholder="(';a+=b.textareaPlaceholder;return a+=')" class="message-input"></textarea>\n  </div>\n  <div class="button-section item"></div>\n'},
send_popup:function(b){b='\n  <div class="share-anchor">\n    <div class="share-content">\n      '+b.content;return b+='\n      <div class="throbber"></div>\n    </div>\n  </div>\n'},empty_message:function(b){b='\n<p class="empty-message">\n  '+b.message;return b+="\n</p>\n"},activity_item:function(b){var a;a='\n  <div class="item-image">\n  </div>\n  <p class="activity">'+b.activity.text;a+="</p>\n  <time>";a+=b.activity.duration;a+='</time>\n  <p class="message">';a+=b.activity.message;return a+=
"</p>\n"},activity:function(b){b='\n  <header class="section-header">\n    <h1 class="apply-width">'+b.activity.heading;return b+='</h1>\n  </header>\n  <div class="section-content apply-width">\n    <div class="recent-activity">\n\n    </div>\n  </div>\n'},toplistplaylist:function(b){var a;a='\n  <div class="playlist-image">\n\n  </div>\n  <a href="'+b.playlist.uri;a+='" class="playlist-name">';a+=b.playlist.name;a+='</a>\n  <p class="playlist-followers">';a+=b.playlist.followers;return a+="</p>\n"},
toplists:function(b){b='\n  <header class="section-header">\n    <h1 class="apply-width">'+b.toplists.heading;return b+='</h1>\n  </header>\n  <div class="section-content">\n    <div class="top-playlists apply-width">\n\n    </div>\n  </div>\n'},subscribee:function(){return'\n  <div class="follower-container">\n    <div class="image-container"></div>\n    <div class="follower-info">\n      <span class="friend-info"></span>\n      <p class="friend-num"></p>\n      <p class="playlist-num"></p>\n    </div>\n    <div class="follow-button-container"></div>\n  </div>\n'},
subscriptions:function(){return'\n<div id="following-container" class="section-content">\n  </div>\n'},subscribers:function(){return'\n<div id="followers-container" class="section-content">\n  </div>\n'},playlistfollowers:function(b){var a;a="\n  <small>"+b.playlist.followersText;a+='</small>\n  <p class="popcount-value">';a+=b.playlist.popcount;return a+="</p>\n"},playlist:function(b){b='\n  <div class="playlist-image"></div>\n  <div class="playlist-content">\n    <div class="flex-box">\n      <header class="playlist-header">\n        <h2><span class="playlist-icon"></span>'+
b.playlist.title;return b+='</h2>\n        <div class="playlist-buttonview flex-box"></div>\n      </header>\n      <div class="playlist-followers">\n\n      </div>\n    </div>\n    <div class="playlist-listview"></div>\n  </div>\n'},playlists:function(b){b='\n  <header class="section-header">\n    <h1 class="apply-width">'+b.playlists.heading;return b+='</h1>\n  </header>\n  <div class="section-content">\n    <div class="playlists">\n\n    </div>\n  </div>\n'},relationsInfo:function(b){var a;a='\n  <a href="'+
b.userUriFollowers;a+='" class="relations-link">\n    <h2 id="followers-heading">';a+=b.followersHeading;a+='</h2>\n    <p id="followers-amount" class="relations-counter" data-followers-amount="'+b.followersAmountUnformatted+'">';a+=b.followersAmount;a+='</p>\n  </a>\n  <hr />\n  <a href="';a+=b.userUriFollowing;a+='" class="relations-link">\n    <h2 id="following-heading">';a+=b.followingHeading;a+='</h2>\n    <p id="following-amount" class="relations-counter" data-following-amount="'+b.followingAmountUnformatted+
'">';a+=b.followingAmount;return a+='</p>\n  </a>\n  <ul id="following-avatars"></ul>\n  <div id="relations-popover" class="item closed"></div>\n'},header:function(b){var a;a='\n  <div class="header apply-width">\n    <div class="header-image-container"></div>\n    <div class="header-content">\n      <a href="'+b.profile.uri;a+='" class="h1 truncate-text ';a+=b.profile.classname;a+='">';a+=b.profile.name;return a+='</a>\n      <span class="info"></span>\n\n      <p class="listening-to-content">\n      </p>\n\n      <div class="buttons-container">\n      </div>\n    </div>\n    <div class="relations-info">\n    </div>\n  </div>\n'}};
exports.templates=templates;
