var dom=sp.require("$util/dom"),kbd=sp.require("$util/keyboard"),r=sp.require("$util/react"),hermes=sp.require("$unstable/hermes"),dnd=sp.require("$util/dnd"),lang=sp.require("$util/language"),eh=sp.require("$util/eventhandler"),models=sp.require("$api/models"),ac=sp.require("sp://radio/scripts/autocomplete"),ic=sp.require("sp://radio/scripts/imageCarousel"),pipes=sp.require("sp://radio/scripts/pipes"),cloud=sp.require("sp://radio/scripts/cloud"),station=sp.require("sp://radio/scripts/station"),util=
sp.require("sp://radio/scripts/util"),rawStrings=models.readFile("strings.json"),strings=JSON.parse(rawStrings),_=function(a){return a in strings?strings[a]:a},Radio=function(){this._showingAutocomplete=!1;this._recommendedStations=this._topTracks=this._topArtists=null;this._linksTried=this._argumentsTried=this._stationLoaded=!1;this._currentSeed="";this._tracks=[];this._history=[];this._pipe=null;this._recent={stations:null,imageCarousel:null,loaded:!1,queue:[]};this._stations={};this._previousContext=
[];this._currentContext=[];this._curTrackUri=this._curTrack=this._stationErrorTimeout=null;this._trackCache={};this._playingCoversElt=null;this._playlistCache={};this._handler=new eh.EventHandler(this);this._addToLikedMutex=new util.Mutex;this._likedPlaylistUri=null;this._playedAndQueuedTracks=[]};
Radio._genreDict={christmas:[_("Christmas"),0,"spotify:mosaic:17da24538a74e61629b05152fefdc39f2e2327e3:af42ef6d2cd8e4a94894a4b10615113931c2ffa5:9c1065b19cc6824c4bada9f100f9685beb474de0:eb5a6a5c801cbbb316395015932ad19529e02774","img/christmas.png",new Date(2012,10,15),new Date(2013,0,15)],alternative:[_("Alternative"),1,"spotify:mosaic:1207d776aa45b693cad70ef95450dc8e0db18d83:47e2da2028246491b0478e406cfdba230ff5b1fa:597def07fa6398d6d35b90d181265fb75424bac5:d386c2a1d1dc719c2940254830831c97c1a8ff0a"],
black_metal:[_("Black Metal"),2,"spotify:mosaic:ddbde13be788ae958a3fbbcef448dbf199610b5f:c3edd0e8343dcf84f04d5788df6a93ec3b0654e2:897f6ac957c4e42907646e6c6624273ea65a005b:f6ab9901b9eee306bd1425911ea0bc722d76cfa4"],blues:[_("Blues"),4,"spotify:mosaic:e94afef050d571055224f89d2b5d29ba9e3b9300:91b2278c242c141aebc5f4164cf1e4eaa9c1e9d5:96175d5bda99b24fd05c614137f76f5c5fc31e21:cb6c654d4fc2a4d78ff00be187d95467424096df"],classical:[_("Classical"),8,"spotify:mosaic:fcfc1d5444184b2036664bed9426668ddf0a9fd0:6a69b6cad2ea198a12e4e77fa6cbc5b3875656a6:f91adc2448a5c7b5adb18fc85bf90fc6c9d6d64f:09890f2fd461a1c577afbc42be97363c32b5d49e"],
country:[_("Country"),16,"spotify:mosaic:f7641a20c01f7758d58c9d364b13d7edd0e879cd:945e69e836de6b244ca6019ecac26ac4cf229ba7:4c8d5465f8bf657f91837dd15154124c8bbf247a:050cb4785cff6411b62b829b9beb2bc063fb5dd3"],dance:[_("Club/House"),32,"spotify:mosaic:7cd9eb1ae4d684ca87228a90e667008393aaa881:d25f570e5a25bb0f746c2a3e86f906abde0ac281:6b8ec3aee1c373572e32ba0e967cc1cf022faaba:588ffff3ef8f1097aa816f0f00cb7bd0267816b3"],death_metal:[_("Death Metal"),64,"spotify:mosaic:dd184055dad8f57cd693683881ae39a9cf9c5582:9a82b57a4f208740bad05046e1ee876a8f7a1f91:3d921ff52b2a731465a0e8a2f92c5f8233ea02ad:45af8d31e3d994addf90fec7b0867b25dd594543"],
electronic:[_("Electronic"),128,"spotify:mosaic:1196dcd5fe2fb9ce78f84f324f2a31dcd6f18b99:171c3048bdf313d824a30d4c52c8dc7bbcc58cfd:8311fdd10a0a9bc60170caaee8ef92e6f9487654:961f901c6b91af8cb640861db629914c0c8a980a"],emo:[_("Emo"),256,"spotify:mosaic:56ff711a44e4770a49f7c240bf228c577effc628:9b4183ba24fcb35cfe40edb6f2762c23fef4aa99:0dfeef9cc746cbf08c9848a929523ec5d088355f:0a919fa5734a469d282876f46825ce5509d33643"],folk:[_("Folk"),512,"spotify:mosaic:3facf19343a4e3204b5c1bf7676ba7f23b1a303e:38f73045ef7424f62d8bffbf304a183e4eb07269:84cb37746c836a900285d7ee0fdf6b2bbf8c7c3d:bb59d4023f2714d5057469f84a4554d2d31e1893"],
hardcore:[_("Hardcore"),1024,"spotify:mosaic:e55c3e91200dd089ac78cc1a3c64dfbf3bc5370d:33ad1fb66fb6a45bb8b0f49b774b72188d05c61a:ab854c15cca135c88bb5a8e95373faee5b15166a:1a9cc1af8bc740a539255cdd256a1565e9180c67"],heavy_metal:[_("Heavy Metal"),2048,"spotify:mosaic:61fa42a2ad6c0d6cd57537b2c751b2c6c317758a:910a245bd2dafa05646683d70045bda63d524f2d:7a21c513cd94aff040ad695947321659c9e1b94b:7835b7891fb5d3dba8af1fa361bb600d65469308"],hip_hop:[_("Hip-Hop"),4096,"spotify:mosaic:9b9cc2b96384754810c46f5aa4d4ed89865615ff:753754a3f01bdcbe7c573ca8a74a6c2015ce7611:f55d28ca1a35496d1e41f4893763dd512dc820c0:b37fbe8e3be71234510cff162d1d1ef346336495"],
indie:[_("Indie"),8192,"spotify:mosaic:7f6cebe3f3df4a95fde0931678abeab0e40308cd:c61bf879b941b4e3a11b2a46d70706ec788350bb:6620449cd7c56a9d17e068ec67a5645ef6561bb0:bf5c73dafeef02d42195cd42e007fe52d790befd"],jazz:[_("Jazz"),16384,"spotify:mosaic:da867b62c0fd0e718b258cf0ada26887624e2346:02d7097cf5c6383ad6523be736cfb6d916403dfe:68f9c89ace8c441168331e21478252c2257f1ea8:9b90ff4da7042657cebba3852e67179baa59c4d5"],latin:[_("Latin"),32768,"spotify:mosaic:4c53a95cc9e6f3f5e93d597be203d7399def992f:4b762fb152e807048cbc026f30bc207d2c829294:642a6caa913fa93829a740b1a3122d195c2cdda1:876cd17f5274d28d153163e83ecf6f26da2b621b"],
pop:[_("Pop"),65536,"spotify:mosaic:2abc9491a29d418572d1c0a555dc27217b9e29db:c9a3235bd39a917d588ff1bed66d788cc95bb1bb:b1720e5ca90f9a6428d97a72839cb9b1fe0d9883:0b44e33dd6deefd66e47bf183b04649017fc0552"],punk:[_("Punk"),131072,"spotify:mosaic:ba0aac39d5de6872e28acfeaaca2090eafad3cc2:f2d77487e24929bb389b99081574f8b6810863a6:767e92219e253bc83abab74d6c6dd166499222f1:772a723d0e4970a7f43a8ea4c73d70daeffd7d76"],reggae:[_("Reggae"),262144,"spotify:mosaic:8c06a3c655a3c52cd8cbfb2b5c299f61038e1930:4a07511acf0a83324021e80b7d677f0e66cc483a:e2f9fc0aa7180e037d05c9cf42ac1df730470d42:cf377968f983f926ba6ea6c2167f1f119a65bea6"],
r_n_b:[_("R&B"),524288,"spotify:mosaic:8fe5e06c997bc793176af7daeefb43ca07636add:397c26076714475fff46b6cd88db8bb9f421ead6:c8c59aa15f5a52287ed354c9fc65eb6ff74e4c3d:ae763483112428a4336e6ec6323bf79228975789"],rock:[_("Rock"),1048576,"spotify:mosaic:8d3a4a465d857afc78734a8924766bde30260151:a0f1f0457556d6628ad90bf81fd751c061c2d1ba:f1a986d8044336ae6b09b5556cb4e140284cc0b0:1b20bd802ecea1cb1e3e35225debf7744294bda4"],singer_songwriter:[_("Singer-Songwriter"),2097152,"spotify:mosaic:37c7c980c10268efce2f20c6992195bd87a26302:582e3edd5030b7d2d240f09652306c62f9afda9d:6bacef6930b03b43826d0e855ea0b29fa06c2e82:8a99c564dd9be04b255c96050ab039d3250ce7d1"],
soul:[_("Soul"),4194304,"spotify:mosaic:74b0d6d7750805926fd459cf114c010510339538:009c43b2bf76a6fa3ed621838f770ebdb393d16a:d4559fcf57b05a0b50a1bfc10cbc1ab1223b0fba:3f86a43016c0f207f12fd4a32da7a567be0d0a09"],trance:[_("Trance"),8388608,"spotify:mosaic:50f92f42b47f048754af4a808a1aca181590e7e8:99e94b809a68b8e37b9bb371535f2b252c213719:b4ad7cf639abd7dcb7f72d7c5888b4986f7dd24e:3ccfcc35121591808ae35c1ee98abc9352f302f7"],"60s":[_("60s"),16777216,"spotify:mosaic:bc2796fd1244da0dd756f12138cb7d918996b301:86be7f57948fa7f3a39c5a56dc5ca2fdb137e1b1:1c9a73dd3c378cd3c521bd01317a3faabcb47817:431b250293487ad8fcdbe490b7c6e21711d0d57e"],
"70s":[_("70s"),33554432,"spotify:mosaic:9f55557d77188544d1c9fe3a24bbf8356fd1cf52:5049ca63240c296644f13c4f2eadfa6e7a68f4b0:3326e1f51f1eb147c3b24a4b828ed5f1191e09db:bd1dae68bd817e11177e7eb58a4eb9faa41d7ef1"],"80s":[_("80s"),67108864,"spotify:mosaic:56b7bec5311cee3945a8eceed91778ad13c083d9:25053d53407cfaaa378a8cad745caaea33204503:fc74c5a8e560a296c6c336a2ef73efe2081741ec:59168df306885f6d2f44ad96e6cb8ebb678cbdea"],"90s":[_("90s"),134217728,"spotify:mosaic:7faf97f3580957f9568592e874fb2e3539149817:84851eb084a308fbdf860174d8835b5e72d9548e:0418233365825a89632d628a9a5b1f69f615f7d0:72a43570b40b67b6efbf3128188a211d95ec043a"]};
Radio.prototype.init=function(){var a=this;ac.setStrings(strings);ic.setStrings(strings);_setTranslations();this._playingCoversElt=dom.id("playing-covers");this._handler.listen(window,"click",this._handleClick).listen(window,"resize",adjustHeaderWidth).listen(window,"beforeunload",this.dispose).listen(dom.id("hide-first-time"),"click",function(){dom.id("first-time").style.display="none"}).listen(dom.id("station-error"),"click",function(){dom.id("station-error").style.visibility="hidden";window.clearTimeout(this._stationErrorTimeout)}).listen(dom.id("thumbsup"),
"click",function(){var a=dom.id("thumbsup").classList,b=dom.id("thumbsdown").classList;!a.contains("selected")&&!a.contains("disabled")&&(a.add("selected"),b.add("disabled"),this._addFeedback(!0))}.bind(this)).listen(dom.id("thumbsdown"),"click",function(){var a=dom.id("thumbsup").classList,b=dom.id("thumbsdown").classList;!b.contains("selected")&&!b.contains("disabled")&&(b.add("selected"),a.add("disabled"),this._addFeedback(!1))}.bind(this));this._setupAutocomplete();this._handler.listen(sp.trackPlayer,
"playerStateChanged",this._playerStateChanged).listen(sp.core.getStarredPlaylist(),"change",this._starredChanged).listen(sp.core,"argumentsChanged",this._loadStationFromArguments).listen(sp.core,"linksChanged",this._loadStationFromLinksChanged).listen(sp.core,"loginModeChanged",loginModeChanged);try{console.log("getting recent stations");var c=function(){console.log("getting recent stations from local storage");var b=JSON.parse(localStorage.getItem("RecentStations"))||[],c=[];console.log("local stations",
b);for(var f=!0,g=0;g<b.length;g++){var h=b[g];console.log("local station",h);if(h.id)f=!1,h=station.Station._createFromHermesStation(h);else{var i,j,k,l,m,n;h.trackName?(i=h.trackName,j=h.trackUri,k=h.artistName,l=h.artistUri,n=[h.trackUri],m=h.imageUri):(i=h.artistName,-1===h.artistUri.search("spotify:genre:")?(j=h.artistUri,m=h.imageUri):(j="",k=h.artistUri.replace("spotify:genre:",""),m=Radio._genreDict[k][2]),l=k="",n=[h.artistUri]);h=station.Station.createNew(i,j,k,l,m,n)}a._stations[h.seeds[0]]=
h;c.push(h)}if(f)for(g=c.length-1;0<=g;g--)c[g].update();console.log("local stations converted",c);a._fillRecentStationList(c);a._recent.loaded=!0;a._autostartStation()};station.Station.getList(function(b){for(var e=0;e<b.length;e++)a._stations[b[e].seeds[0]]=b[e];0===b.length?c():(a._fillRecentStationList(b),a._recent.loaded=!0,a._autostartStation())},function(){console.log("error getting recent stations");c()})}catch(b){}this._recent.imageCarousel=new ic.ImageCarousel("#recent",strings["Your Stations"]);
adjustHeaderWidth();loginModeChanged();this._fillRecommendedStations();this._fillGenres()};
Radio.prototype._autostartStation=function(a){console.log("[RADIO] autostarting station");this._stationLoaded||(console.log("[RADIO] station not already started"),1===sp.core.getLoginMode()&&(console.log("[RADIO] we are online"),!this._argumentsTried&&this._loadStationFromArguments()?this._argumentsTried=!0:(console.log("[RADIO] could not load from arguments"),!this._linksTried&&this._loadStationFromLinksChanged()?this._linksTried=!0:(console.log("[RADIO] could not load from links changed"),this._recent.loaded&&
(console.log("[RADIO] recent stations loaded"),0<this._recent.stations.length?(console.log("[RADIO] have recent stations, start first.",this._recent.stations),this._loadStation(this._recent.stations[0].seeds[0],"spotify:app:radio","","autostartrecent:0",!1)):(console.log("[RADIO] no recent stations"),dom.id("first-time").style.display="block",this._hideLoadingScreen(),"undefined"===typeof a&&(a=0),console.log("[RADIO] playTopArtist. Current state: ",this),null!==this.recommendedStations&&this._recommendedStations.length>
a&&this._loadStation(this._recommendedStations[a].uri,"spotify:app:radio","","autostarttopartist:"+a,!1)))))))};
Radio.prototype._setupAutocomplete=function(){var a=this,c=dom.queryOne(".auto-completeForm"),b=ac.tokenInput.input,d=ac.setupAutoComplete(ac.tokenInput,function(){a._loadStation(b.value,"spotify:app:radio","","search",!0);g()}),d=partial(ac.searchResultHandler,ac.tokenInput,d),e=partial(ac.autoComplete,d,function(){return{tracks:a._topTracks,artists:a._topArtists,albums:[],playlists:[]}}),f=dom.id("create-station"),g=function(){a._showingAutocomplete=!1;dom.queryOne(".upArrowContainer",f).style.display=
"none";dom.queryOne(".auto-completeForm",f).style.display="none";b.value="";ac.tokenInput.clear()},d=r.fromDOMEvent(window,"keydown"),d=r.filter(function(a){return 27===a.keyCode},d);dom.adopt(c,ac.tokenInput.node);kbd.whileFocused(b,d).subscribe(g);this._handler.listen(b,"input",ac.throttle(e,500));this._handler.listen(window,"click",g).listen(f,"click",function(c){this._showingAutocomplete?g():(a._showingAutocomplete=!0,dom.queryOne(".upArrowContainer",f).style.display="block",dom.queryOne(".auto-completeForm",
f).style.display="block",dom.queryOne("input",f).focus(),b.value="",ac.tokenInput.clear(),e({target:b}));c.stopPropagation()}).listen(dom.queryOne(".auto-completeForm",f),"click",function(a){a.stopPropagation()})};
Radio.prototype._showLoadingScreen=function(){function a(){if("none"!=c.style.display){var d=parseInt(b.style.backgroundPositionX.replace("px",""));b.style.backgroundPositionX=(d+30)%360+"px";setTimeout(a,80)}}var c=dom.id("loading");c.style.display="block";var b=dom.id("loading-throbber");b.style.display="block";b.style.backgroundPositionX="0px";a();var d=dom.queryOne("#playing-covers>li>a>div>span");null!=d&&(d.style.display="none");dom.queryOne("#playing-skip>a").style.display="none"};
Radio.prototype._hideLoadingScreen=function(){dom.id("loading").style.display="none";dom.id("loading-throbber").style.display="none";var a=dom.queryOne("#playing-covers>li>a>div>span");null!=a&&(a.style.display="block");dom.queryOne("#playing-skip>a").style.display="block"};
Radio.prototype._fillTopList=function(a,c,b){if("undefined"===typeof b||0===b.length)dom.queryOne(a).style.display="none";else{a=new ic.ImageCarousel(a,c);for(c=0;c<b.length&&10>c;c++){var d=b[c],e,f={},g=[];switch(d.type){case "artist":e=""!=d.portrait?d.portrait:"sp://resources/img/placeholders/64-artist.png";f.name=d.name;f.link=d.uri;break;case "track":e=""!=d.album.cover?d.album.cover:"sp://resources/img/placeholders/50-album.png";f.name=d.name;f.link=d.uri+"?action=browse";var h={};h.name=d.artists[0].name;
h.link=d.artists[0].uri;g.push(h);break;case "playlist":e=""!=d.cover?d.cover:"sp://resources/img/placeholders/50-playlist.png";f.name=d.name;f.link=d.uri;break;default:continue}isValidImageUri(e)||(e="",console.log("[RADIO] Empty image for ",d));a.addItem(d.uri,e,f,g)}a.scrollTo(0)}};
Radio.prototype._fillRecommendedStations=function(){var a=this,c=function(b){a._topTracks=b;for(var b=[],c=!0,e=0;c;)c=!1,a._topArtists.length>e&&(b.push(a._topArtists[e++]),c=!0);a._recommendedStations=b;a._autostartStation();a._fillTopList("#popular",strings["Recommended Stations"],b)};Radio._getToplist("artist",!1,function(b){a._topArtists=b;Radio._getToplist("track",!1,c)})};
Radio._getToplist=function(a,c,b){var d=[];sp.social.getToplist(a,c?"":"user",sp.core.user.canonicalUsername,{onSuccess:function(b){console.log("[RADIO] user top list success",a);d=b[a+"s"]},onComplete:function(){console.log("[RADIO] user top list complete",a);0<d.length||c?b(d):Radio._getToplist(a,!0,b)}})};
Radio.prototype._fillGenres=function(){var a=[],c;for(c in Radio._genreDict)a:{var b=c,d=Radio._genreDict[b];if(5<d.length){var e=new Date;if(e<d[4]||e>d[5])break a}var e=dom.Element("li"),b=dom.Element("a",{className:"main",href:"spotify:genre:"+b}),f=dom.Element("span",{className:"genre-image"}),g=dom.Element("span",{className:"genre-text",innerHTML:d[0]});3<d.length&&d[3]&&(f.style.backgroundImage="url("+d[3]+")");b.appendChild(f);b.appendChild(g);e.appendChild(b);a.push(e)}new cloud.Cloud("#genres>div",
a)};
Radio.prototype._addRecentStation=function(a,c,b,d,e,f){console.log("add recent station ",arguments);var g=this,h=this._stations[f[0]];h||(h=this._stations[f[0]]=station.Station.createNew(a,c,b,d,e,f));if(this._recent.loaded){console.log("loaded, update");h.update(function(){try{var a=JSON.stringify(g._recent.stations);localStorage.setItem("RecentStations",a)}catch(b){console.log("error putting stations",b)}});for(var i=this._recent.stations,j=0;j<i.length&&i[j].seeds[0]!=h.seeds[0];j++);i.splice(j,1);
i.splice(0,0,h);this._fillRecentStationList(i)}else console.log("not loaded, add to queue"),this._recent.queue.push(f[0])};
Radio.prototype._fillRecentStationList=function(a){console.log("fill recent stations called with:",a);console.log("current recent:",this._recent);var c=this._recent;if(!c.loaded)for(var b=0;b<this._recent.queue.length;b++){var d=this._stations[this._recent.queue[b]];d.update();for(var e=0;e<a.length&&a[e].seed!=d.seed;e++);a.splice(e,1);a.splice(0,0,d)}c.stations=a;c.imageCarousel.clear();if(1>=c.stations.length)dom.id("recent").style.display="none";else{for(b=1;21>b&&b<c.stations.length;b++){a=c.stations[b];
d={};e=[];a.title?(d={name:a.titleUri&&":starred"===a.titleUri.substr(a.titleUri.length-8)?strings.Starred:a.title||"",link:a.titleUri||""},e.push({name:a.subtitle||"",link:a.subtitleUri||""})):d={name:a.subtitleUri&&":starred"===a.subtitleUri.substr(a.subtitleUri.length-8)?strings.Starred:a.title||"",link:a.subtitleUri||""};var f=isValidImageUri(a.imageUri)?a.imageUri:"";console.log("adding ",a,d,e.length,e);c.imageCarousel.addItem(a.seeds[0],f,d,e)}dom.id("recent").style.display="block";c.imageCarousel.handleResize();
c.imageCarousel.scrollTo(0)}};
Radio.prototype._addToLikedPlaylist=function(a){var c=this,b=strings["Liked from Radio"],d='Liked from Radio;Radio-Favoriten;Favoritas de la radio;Favoris des radios;Scelto dalla radio;Radio-favorieten;"Lubi\u0119 to" z radia'.split(";"),e=function(){c._addToLikedMutex.release();console.log(arguments)},f=function(){c._addToLikedMutex.release();console.log("adding ",a,"to ",c._likedPlaylistUri);models.Playlist.fromURI(c._likedPlaylistUri,function(b){try{console.log("add to playlist in callback",b);
for(var e=!0,f=0;e&&f<d.length;f++)e=b.name!==d[f];if(b.subscribed&&!e){for(var e=!1,k=b.tracks,f=0;f<k.length;f++)if(k[f].uri===a){e=!0;break}e||b.add(a)}else c._addToLikedMutex.acquire(function(){g(b.uri)})}catch(l){console.log("error adding to liked playlist",l)}})},g=function(a){if(c._likedPlaylistUri!==a)f();else{console.log("creating new liked playlist");try{if(sp.core.library.createPlaylistUri){var d=sp.core.library.createPlaylistUri(b);console.log("created new liked playlist",d,d.uri);sp.core.getHermes("PUT",
"hm://radio/liked-playlist",[["LikedPlaylist",{uri:d.uri}]],{onSuccess:function(){console.log("success adding liked playlist");c._likedPlaylistUri=d.uri;f()},onFailure:e.bind(null,"error putting liked playlist")})}else c._addToLikedMutex.release()}catch(g){e("error creating new playlist")}}};c._addToLikedMutex.acquire(function(){console.log("adding to liked playlist with uri: ",c._likedPlaylistUri);if(c._likedPlaylistUri)f();else try{console.log("getting liked playlist uri"),sp.core.getHermes("GET",
"hm://radio/liked-playlist",[],{onSuccess:function(a){a=sp.core.parseHermesReply("LikedPlaylist",a);console.log("liked playlist: ",a);a.uri?(c._likedPlaylistUri=a.uri,f()):g()},onFailure:e.bind(null,"error getting liked playlist")})}catch(a){e.bind(null,"exception getting liked playlist")}})};
Radio.prototype._addFeedback=function(a){var c=this._stations[this._currentSeed],b=this._curTrackUri;console.log("feedback",a,c,b);if(c&&b){var d=["improvingStation","doneImproving"],e=function(a){var b=dom.queryOne(".improvingFeedback",a);0<d.length?(b.className="improvingFeedback "+d.shift(),setTimeout(e.bind(null,a),3E3)):b.className="improvingFeedback"};a&&e(dom.queryOne("#playing-covers>li"));c.addFeedback(b.replace("spotify:track:",""),a);if(a)this._addToLikedPlaylist(b);else{var f=function(){this._allowSkip&&
1<this._getTemporaryPlaylist().length?this._findNextTrack(!0,e):setTimeout(f,500)}.bind(this);f()}this._loadStation(this._currentSeed,"spotify:app:radio","","updateforfeedback",!1)}};
Radio.prototype._getTemporaryPlaylist=function(){var a=this._currentSeed.substring(8),a="function"===typeof sp.core.getTemporaryPlaylistEx?sp.core.getTemporaryPlaylistEx(a,"spotify:radio:"+a):sp.core.getTemporaryPlaylist(a);sp.trackPlayer.setContextCanSkipPrev(a.uri,!1);sp.trackPlayer.setContextCanRepeat(a.uri,!1);sp.trackPlayer.setContextCanShuffle(a.uri,!1);return a};
Radio.prototype._addTrackToTempList=function(a){var c=idToUri("track",a.trackId);this._playedAndQueuedTracks.push(a.trackId);this._playedAndQueuedTracks.slice(0,50);this._trackCache[c]=a;this._getTemporaryPlaylist().add(c)};Radio.prototype._trackUsage=function(){var a=new Date,a={trackId:this._curTrackUri,albumId:idToUri("album",this._curTrack.albumId),artistId:idToUri("artist",this._curTrack.artistId),timestamp:Math.round(a.getTime()/1E3)};this._history.push(a)};
Radio.prototype._updatePlayPauseControls=function(){var a=sp.trackPlayer.getIsPlaying()&&sp.trackPlayer.getNowPlayingTrack().track.uri==this._curTrackUri;dom.queryOne("#playing-covers>li>a>div>span").className=a?"playButton playing":"playButton paused"};
Radio.prototype._playCurrentTrack=function(){var a=this,c=dom.queryOne("#playing-skip>a");c.className+="disabled";a._allowSkip=!1;var b=this._getTemporaryPlaylist();sp.trackPlayer.playTrackFromContext(b.uri,0,"",{onSuccess:function(){console.log("[RADIO] play ok")},onError:function(){console.log("[RADIO] play error")},onComplete:function(){var b=function(){var e=sp.trackPlayer.getNowPlayingTrack();"undefined"===typeof e||null===e||e.track.uri!==a._curTrackUri?setTimeout(b,500):(c.className=c.className.replace(/disabled/g,
""),a._allowSkip=!0,a._updatePlayPauseControls())};b();console.log("[RADIO] play complete")}})};function _deleteCover(a){a=a.target;"0"===getComputedStyle(a).opacity&&dom.destroy(a)}
Radio.prototype._rotateCovers=function(a,c,b){var d=dom.queryOne("li",this._playingCoversElt),e=document.createElement("li");""==c&&(c="sp://resources/img/placeholders/300-album.png");e.addEventListener("webkitTransitionEnd",_deleteCover);a=dom.Element("a",{className:"outgoing",href:a+"?action=browse",title:b});c=dom.Element("img",{src:c});a.appendChild(c);c=dom.Element("div",{className:"wrapper"});b=dom.Element("span",{className:"playButton"});c.appendChild(b);a.appendChild(c);e.appendChild(a);a=
dom.Element("div",{className:"improvingFeedback"});c=dom.Element("div",{className:"improvingFeedbackCover"});a.appendChild(c);c=dom.Element("div",{className:"improvingFeedbackInfo"});b=dom.Element("div",{className:"improvingFeedbackImg"});c.appendChild(b);b=function(a,b){return dom.Element("div",{className:"text "+a,innerHTML:b})};c.appendChild(b("improvingStation",strings["Improving Station"]));c.appendChild(b("addedToLiked",strings["Added to playlist"]));c.appendChild(b("doneImproving",strings.Done));
a.appendChild(c);e.appendChild(a);this._playingCoversElt.insertBefore(e,d);return e};
Radio.prototype._playTrack=function(a,c){var b=this._getTemporaryPlaylist(),d=b.getTrack(0).uri;console.log("[RADIO] _playTrack",this._curTrack,d,b.length,a);null===d||this._curTrack&&d===this._curTrackUri||(b=this._trackCache[d],console.log("[RADIO] playing",b),this._curTrack=b,this._curTrackUri=idToUri("track",this._curTrack.trackId),replaceLink(dom.id("radio-track"),this._curTrack.trackName,this._curTrackUri+"?action=browse"),replaceLink(dom.id("radio-artist"),this._curTrack.artistName,idToUri("artist",
this._curTrack.artistId)),dom.id("radio-star").className=this._curTrack.starred?"starred":"",d=lang.format(_("Item by artists"),this._curTrack.trackName,this._curTrack.artistName),d=this._rotateCovers(this._curTrackUri,this._curTrack.coverUri,d),dom.id("playing-info").style.visibility="visible",console.log("[RADIO] Play: "+this._curTrackUri),this._hideLoadingScreen(),dom.id("thumbsup").classList.remove("selected"),dom.id("thumbsup").classList.remove("disabled"),dom.id("thumbsdown").classList.remove("selected"),
dom.id("thumbsdown").classList.remove("disabled"),"up"===b.feedback?(dom.id("thumbsup").classList.add("selected"),dom.id("thumbsdown").classList.add("disabled")):"down"===b.feedback&&(dom.id("thumbsup").classList.add("selected"),dom.id("thumbsdown").classList.add("disabled")),"function"===typeof c&&c(d),a?this._playCurrentTrack():this._updatePlayPauseControls(),this._trackUsage())};
Radio.prototype._findNextTrack=function(a,c){function b(a,f){f?(this._addTrackToTempList(f),a?(d.get(0)!==idToUri("track",f.trackId)&&d.remove(0),this._playTrack(!0,c)):this._playTrack(!1,c),2>d.length&&(console.log("[RADIO] findnexttrack: getting next from pipe in play"),this._pipe.next(b.bind(this,!1)))):console.log("[RADIO] No tracks available")}var d=this._getTemporaryPlaylist();console.log("[RADIO] Finding next track",a,d.length);2>d.length?(console.log("[RADIO] findnexttrack: getting next from pipe in if"),
this._pipe.next(b.bind(this,a))):a&&(d.remove(0),this._playTrack(a,c),this._findNextTrack(!1))};
Radio.prototype._stationAvailable=function(a,c,b,d,e,f){var g;function h(){console.log("creating new pipe");i._pipe=pipes.getIdentityPipe(i._tracks,function(a){console.log("doing hermes in start.");i._doHermes(c,!1,{onSuccess:function(b){console.log("doing hermes in start. success");b&&(console.log("doing hermes in start. success2",b),b=sp.core.parseHermesReply("Tracks",b),b=j(b),console.log("doing hermes in start. have tracks, calling back"),a(b),console.log("doing hermes in start. done callback"))},
onFailure:function(a){console.log("[RADIO] Failed to load more tracks for : ",seed,": hermes failure",arguments);sp.core.logClientEvent("","loadstationerror","1","1",{source:source,context:context,element:element,target:target})}})});var a=i._getTemporaryPlaylist();console.log("temp playlist = ",a);if(!f)for(;0<a.length;)a.remove(a.length-1);i._findNextTrack(d)}console.log("[RADIO] Station available for: "+a);console.log("[RADIO] Tracks in the station: ",b);console.log("[RADIO] Source for station: ",
e);console.log("[RADIO] Is this station update?: ",f);var i=this;f||(this._trackCache={},this._playedAndQueuedTracks=[]);dom.id("playing").style.display="block";var j=function(a){var b=[],c={},d;for(d in a.feedback){var e=a.feedback[d];c[e.uri]=e.type}for(d in a.gids)b.push({trackId:a.gids[d],trackName:"",albumId:"",albumName:"",artistId:"",artistName:"",coverUri:"",starred:!1,hasMetadata:!1,feedback:c[a.gids[d]]});return b};this._tracks=j(b);f?h():(0<=e.indexOf("en")&&(dom.id("echonest").style.display=
"block",setTimeout(function(){dom.id("echonest").style.display="none"},3E3)),dom.empty(this._playingCoversElt),replaceLink(dom.id("radio-track"),"",""),replaceLink(dom.id("radio-artist"),"",""),this._currentSeed=a,-1!==a.search("spotify:user")?(b=a,e=this._playlistCache[a].name,g=this._playlistCache[a].cover,_setStationHeader(this._playlistCache[a].cover||"sp://resources/img/placeholders/50-playlist.png",lang.format(_("Current playlist station"),"<a class='outgoing' href='"+b+"'>"+e+"</a>")),this._addRecentStation(e,
b,"","",g,[b]),h()):-1!==a.search("spotify:genre:")?(g=a.replace("spotify:genre:",""),g in Radio._genreDict?(b=a,e=Radio._genreDict[g][0],g=Radio._genreDict[g][2],_setStationHeader(g,lang.format(_("Current genre station"),e)),this._addRecentStation(e,"","","",g,[b])):a in this._stations?(b=this._stations[a],_setStationHeader(b.imageUri,lang.format(_("Current genre station"),b.title)),this._addRecentStation(b.title,"","","",b.imageUri,b.seeds)):(_setStationHeader("/img/genre.png",lang.format(_("Current genre station"),
g)),this._addRecentStation(g,"","","","/img/genre.png",[a])),h()):sp.core.getMetadata(a,{onSuccess:function(a){if("track"===a.type){i._addRecentStation(a.name,a.uri,a.artists[0].name,a.artists[0].uri,a.album.cover,[a.uri]);var b="<a class='outgoing' href='"+a.uri+"?action=browse'>"+a.name+"</a>",c="<a class='outgoing' href='"+a.artists[0].uri+"'>"+a.artists[0].name+"</a>";_setStationHeader(a.album.cover,lang.format(_("Current track station"),b,c))}else if("artist"===a.type)i._addRecentStation(a.name,
a.uri,"","",a.portrait,[a.uri]),b=""!=a.portrait?a.portrait:"sp://resources/img/placeholders/64-artist.png",c="<a class='outgoing' href='"+a.uri+"'>"+a.name+"</a>",_setStationHeader(b,lang.format(_("Current artist station"),c));else if("album"===a.type){i._addRecentStation(a.name,a.uri,a.artist.name,a.artist.uri,a.cover,[a.uri]);var b=""!==a.cover?a.cover:"sp://resources/img/placeholders/50-album.png",d="<a class='outgoing' href='"+a.uri+"'>"+a.name+"</a>",c="<a class='outgoing' href='"+a.artist.uri+
"'>"+a.artist.name+"</a>";_setStationHeader(b,lang.format(_("Current album station"),d,c))}console.log("[RADIO] pipes = ",pipes);h()},onFailure:function(){console.log("[RADIO] Failed to fetch metadata for: ",a);i._hideLoadingScreen()}}))};
Radio.prototype._parseTracksHermes=function(a,c,b,d,e,f,g,h,i){a=sp.core.parseHermesReply("Tracks",a);console.log("[RADIO] source: ",a.source);console.log("[RADIO] identity: ",a.identity);i||sp.core.logClientEvent("","loadstation","1","1",{source:e,context:f,element:g,target:h,targetsource:a.source});this._stationAvailable(c,b,a,d,a.source,i)};
Radio.prototype._stationNotFound=function(a,c){var b=0,d=!0;0===c.search(/^autostartrecent/)&&(b=1+c.replace("autostartrecent:",""),d=!1);0===c.search(/^autostarttopartist/)&&(b=1+c.replace("autostarttopartist:",""),d=!1);if(d){var e=dom.id("station-error");e.style.visibility="visible";this._stationErrorTimeout=window.setTimeout(function(){e.style.visibility="hidden"},5E3)}0==dom.id("playing-covers").children.length&&(this._stationLoaded=!1,0<this._recent.stations.length?this._recent.stations.length>
b&&this._loadStation(this._recent.stations[b].seeds[0],"spotify:app:radio","","autostartrecent:"+b,!1):this._autostartStation(b))};
Radio.prototype._artistFallback=function(a,c,b,d,e){console.log("[RADIO] Track seed not found - trying to create station for artist.");var f=this;sp.core.getMetadata(a,{onSuccess:function(g){var h="",h=0==a.search("spotify:album:")?g.artist.uri:g.artists[0].uri,i=seedToRadioUri(h);f._doHermes(h,!0,{onSuccess:function(g){void 0===g?f._stationNotFound(a,e):f._parseTracksHermes(g,a,h,c,b,d,e,i)},onFailure:function(c){console.log("[RADIO] Failed to load fallback station for : ",a,": hermes failure",arguments);
sp.core.logClientEvent("","loadstationerror","1","1",{source:b,context:d,element:e,target:i});f._stationNotFound(a,e)}})},onFailure:function(){f._stationNotFound(a,e)}})};
Radio.prototype._loadStation=function(a,c,b,d,e){function f(b,d,f){sp.core.logClientEvent("","loadstationerror","1","1",{source:c,context:b,element:d,target:f});0==a.search("spotify:track:")||0==a.search("spotify:album:")?k._artistFallback(a,e,c,b,d,f,h):h||k._stationNotFound(a,d)}0===a.search(/^http/)&&(console.log("[RADIO] http uri used as seed"),a="spotify:"+a.split("/").slice(3).join(":"));a=a.replace(/^spotify:radio/,"spotify");console.log("[RADIO] new seed is",a);var g=seedToRadioUri(a),c=c.replace(/\^/g,
":"),b=b.replace(/\^/g,":"),d=d.replace(/\^/g,":"),h=this._currentSeed===a;"spotify:app:radio"==c&&""==b&&(b=seedToRadioUri(this._currentSeed));console.log("[RADIO] load station, current seed: ["+this._currentSeed+"], source: ["+c+"], context: ["+b+"], element: ["+d+"], target: "+g+"]");for(var i=window.pageYOffset,j=1;-100<=i;i-=100,++j)setTimeout("window.scrollTo(window.pageXOffset, "+Math.max(i,0)+")",10*j);(new dom.Event("radioPlayLoading")).dispatch(window);this._stationLoaded=!0;var k=this;
h||this._showLoadingScreen();this._doHermes(a,!0,{onSuccess:function(i){void 0===i?f(b,d,g):k._parseTracksHermes(i,a,a,e,c,b,d,g,h)},onFailure:function(c){console.log("[RADIO] Failed to load station for : ",a,": hermes failure",arguments);k._hideLoadingScreen();f(b,d,g)}})};
Radio.prototype._loadStationFromArguments=function(){var a=sp.core.getArguments();console.log("arguments: ",a);var c=unescape(a[0]),b=unescape(a[1]);if("genre"==c&&!isNaN(+b)){var d=+b,b="pop",e;for(e in Radio._genreDict)if(d&Radio._genreDict[e][1]){b=e;break}}return 8<=a.length?(c="spotify:"===b.substr(0,8)?b:idToUri(c,b),this._loadStation(c,unescape(a[3]),unescape(a[5]),unescape(a[7]),!0),!0):"user"===c?(3<a.length?this._loadStation(idToUri(unescape(a[2]),unescape(a[3]),unescape(a[1])),"","","externallink",
!0):"starred"===a[2]&&this._loadStation(idToUri(unescape(a[2]),"",unescape(a[1])),"","","externallink",!0),!0):2<=a.length?(this._loadStation(idToUri(c,b),"","","externallink",!0),!0):!1};Radio.prototype._loadStationFromLinksChanged=function(){var a=sp.core.getLinks();console.log("[RADIO] Trying to load station from link ",a);return a.length?(this._loadStation(a[0],"spotify:app:radio","","drop",!0),!0):!1};
Radio.prototype._playerStateChanged=function(a){console.log("[RADIO] playerStateChanged event",a);a.data.curcontext&&(this._previousContext=this._currentContext,this._currentContext=sp.trackPlayer.getPlayingContext(),console.log("[RADIO] context changed, previousContext: ",this._previousContext));if(a.data.playstate){var c=this._getTemporaryPlaylist();console.log("[RADIO] temp list is",c);if(a.data.curtrack){console.log("[RADIO] Track ended or skipped.");a=sp.trackPlayer.getPlayingContext();console.log("[RADIO] playing context: ",
a,"temporaryPlaylist.name",c.name);var b=c.name.replace("app:radio@","radio:"),d;d=a.length?a[0].replace("spotify:internal:temp_playlist:","").replace("app:radio@","radio:"):null;console.log("[RADIO] currentContext: ",d,"radioPlaylistName",b);if(null!==d&&d===b)if(console.log("[RADIO] In radio. Did new track already start?."),sp.trackPlayer.getNowPlayingTrack()){for(console.log("[RADIO] Next track started. Update UI.");0<c.length&&c.getTrack(0).uri!==sp.trackPlayer.getNowPlayingTrack().track.uri;)c.remove(0);
this._playTrack(!1);this._findNextTrack(!1)}else console.log("[RADIO] No new track started, playing next."),this._findNextTrack(!0);else 0==a.length&&(this._previousContext[0]==b&&!sp.trackPlayer.getIsPlaying())&&(console.log("[RADIO] working around temp playlist race condition"),this._playCurrentTrack())}this._updatePlayPauseControls()}};
Radio.prototype._playPause=function(){var a=this,c=sp.trackPlayer.getNowPlayingTrack();if(!c||c.track.uri!=this._curTrackUri)if(null!=this._curTrack){var b=dom.queryOne("#playing-skip>a");b.className+="disabled";a._allowSkip=!1;a=this;sp.trackPlayer.playTrackFromContext(this._getTemporaryPlaylist().uri,0,"",{onSuccess:function(){console.log("[RADIO] play ok")},onError:function(){console.log("[RADIO] play error")},onComplete:function(){var c=function(){var e=sp.trackPlayer.getNowPlayingTrack();"undefined"===
typeof e||null===e||e.track.uri!==a._curTrackUri?setTimeout(c,500):(b.className=b.className.replace(/disabled/g,""),a._allowSkip=!0,a._updatePlayPauseControls())};c();console.log("[RADIO] play complete")}})}else this._findNextTrack(!0);else sp.trackPlayer.setIsPlaying(!sp.trackPlayer.getIsPlaying())};
Radio.prototype._starredChanged=function(){this._curTrack&&sp.core.getMetadata(this._curTrackUri,{onSuccess:function(a){this._curTrack&&a.uri==this._curTrackUri&&(this._curTrack.starred=a.starred,dom.id("radio-star").className=this._curTrack.starred?"starred":"")}.bind(this),onFailure:function(){}})};
Radio.prototype._handleClick=function(a){for(var c=a.target;c&&c!=a.currentTarget;c=c.parentNode)if("A"==c.tagName)if("spotify:"==c.href.substr(0,8)){if(-1==c.className.indexOf("outgoing")){a.preventDefault();for(var a="link",b=c;b=b.parentNode;)if("SECTION"==b.tagName){a=b.id;break}this._loadStation(c.href,"spotify:app:radio","",a,!0)}break}else if("radio:skip"==c.href)a.preventDefault(),-1===c.className.search("disabled")&&this._findNextTrack(!0);else if("radio:star"==c.href){if(a.preventDefault(),
this._curTrack){this._curTrack.starred=!this._curTrack.starred;var b=this._curTrackUri,d=sp.core.getStarredPlaylist();if(this._curTrack.starred)d.add(b);else for(var e=d.length,f=0;f<e;++f)if(d.get(f)==b){d.remove(f);break}dom.id("radio-star").className=this._curTrack.starred?"starred":""}}else if("radio:play-pause"==c.href)a.preventDefault(),this._playPause();else{if("radio:share"==c.href){b=seedToRadioUri(this._currentSeed);a.preventDefault();console.log("[RADIO]",b);d=parseInt(c.offsetWidth)/2;
e=parseInt(c.offsetHeight);f=c;do d+=f.offsetLeft,e+=f.offsetTop;while(f=f.offsetParent);sp.social.showSharePopup(parseInt(d),parseInt(e),b)}}else c.className&&-1!==c.className.search("playButton")&&(a.preventDefault(),this._playPause())};Radio.prototype._selectPlaylistSeed=function(a,c){for(var b=a.all().slice(0),d=[],e=b.length,f=0;f<e;f++){var g=f+Math.floor(Math.random()*(e-f)),h=b[g];if("spotify:local:"!==h.substr(0,14)&&d.push(h)>=c)break;b[g]=b[f];b[f]=h}return d};
Radio.prototype._doHermes=function(a,c,b){var d=this,e=a.split(":");console.log("doing hermes");var f=function(e){var f=Math.floor(127*Math.random()),e={uris:e,salt:f,length:20,lastTracks:c?[]:d._playedAndQueuedTracks};if((f=d._stations[a])&&f.id)e.stationId=f.id;sp.core.getHermes("GET","hm://radio/",[["RadioRequest",e]],b)};if("user"===e[1]){if("playlist"===e[3]||"starred"===e[3]){var g=sp.core.getPlaylist(a);if("playlist"===g.type){this._playlistCache[a]=g;if(g.loaded)e=d._selectPlaylistSeed(g,
20),f(e);else{var h=function(){var a=d._selectPlaylistSeed(g,20);f(a);d._handler.unlisten(g,"load",h)};this._handler.listen(g,"load",h)}return}}throw Error("Invalid seed for radio: "+a);}f([a])};
Radio.prototype._initHermesSchemas=function(){sp.core.registerSchema([{name:"Rules",id:1,fields:[{id:1,name:"js",type:"string"}]}]);sp.core.registerSchema([{name:"RadioRequest",id:1,fields:[{id:1,name:"uris",type:"*string"},{id:2,name:"salt",type:"int32"},{id:3,name:"offset",type:"int32"},{id:4,name:"length",type:"int32"},{id:5,name:"stationId",type:"string"},{id:6,name:"lastTracks",type:"*string"}]}]);sp.core.registerSchema([{name:"MultiSeedRequest",id:1,fields:[{id:1,name:"uris",type:"*string"}]}]);
sp.core.registerSchema([{name:"Feedback",id:1,fields:[{id:1,name:"uri",type:"string"},{id:2,name:"type",type:"string"},{id:3,name:"timestamp",type:"double"}]}]);sp.core.registerSchema([{name:"Tracks",id:1,fields:[{id:1,name:"gids",type:"*string"},{id:2,name:"source",type:"string"},{id:3,name:"identity",type:"string"},{id:4,name:"tokens",type:"*string"},{id:5,name:"feedback",type:"*Feedback"}]}]);sp.core.registerSchema([{name:"Station",id:1,fields:[{id:1,name:"id",type:"string"},{id:2,name:"title",
type:"string"},{id:3,name:"titleUri",type:"string"},{id:4,name:"subtitle",type:"string"},{id:5,name:"subtitleUri",type:"string"},{id:6,name:"imageUri",type:"string"},{id:7,name:"lastListen",type:"double"},{id:8,name:"seeds",type:"*string"},{id:9,name:"thumbsUp",type:"int32"},{id:10,name:"thumbsDown",type:"int32"}]}]);sp.core.registerSchema([{name:"StationResponse",id:1,fields:[{id:1,name:"station",type:"Station"},{id:2,name:"feedback",type:"Feedback"}]}]);sp.core.registerSchema([{name:"StationList",
id:1,fields:[{id:1,name:"stations",type:"*Station"}]}]);sp.core.registerSchema([{name:"StationListRequest",id:1,fields:[{id:1,name:"canReadNewStations",type:"bool"}]}]);sp.core.registerSchema([{name:"LikedPlaylist",id:1,fields:[{id:1,name:"uri",type:"string"}]}])};Radio.prototype.dispose=function(){this._handler.removeAll()};function adjustHeaderWidth(){var a=dom.id("playing-header"),c=dom.id("radio-seed"),b=dom.id("right-header");c.style.width=a.offsetWidth-b.offsetWidth-34+"px"}
function isInAutoComplete(a){for(var c=dom.queryOne(".auto-completeForm");a;){if(a===c)return!0;a=a.parentNode}return!1}function isValidImageUri(a){return a&&0<a.length?0!=a.substr(a.lastIndexOf(":")+1):!1}function replaceLink(a,c,b){c=dom.Element("a",{text:c.decodeForText(),href:b,className:"outgoing"});dom.empty(a);a.appendChild(c)}
function loginModeChanged(){1==sp.core.getLoginMode()?(dom.id("offline-panel").style.visibility="hidden",dom.id("offline-error").style.visibility="hidden"):(dom.id("offline-panel").style.visibility="visible",dom.id("offline-error").style.visibility="visible")}
function _setTranslations(){dom.queryOne("#first-time h2").innerHTML=_("First time header");dom.queryOne("#first-time div").innerHTML=_("First time message");dom.queryOne("#first-time button").innerHTML=_("First time hide");dom.id("offline-error").innerHTML=_("Offline");dom.id("station-error").innerHTML=_("Missing station");dom.queryOne("#share-radio span#text").innerHTML=_("Share Station");dom.queryOne("#create-station .button span").innerHTML=_("Create Station");dom.queryOne("#echonest div").innerHTML=
_("Powered By");dom.queryOne("#genres h2").innerHTML=strings["Genre Stations"]}function _setStationHeader(a,c){var b=dom.id("radio-seed");b.style.display="block";var d=dom.queryOne("span",b);dom.empty(d);"spotify:mosaic:"==a.substr(0,15)?(d.style.backgroundImage="",d.appendChild((new util.SPImage(a)).node)):d.style.backgroundImage="url("+a+")";dom.queryOne("h2",b).innerHTML=c}
function idToUri(a,c,b){return"playlist"===a?"spotify:user:"+b+":"+a+":"+c:"starred"===a?"spotify:user:"+b+":"+a:"spotify:"+a+":"+c}function seedToRadioUri(a){return a.replace(/^spotify/,"spotify:radio")}exports.init=function(){var a=new Radio;a._initHermesSchemas();dom.listen(window,"DOMContentLoaded",a.init.bind(a));return a};exports.Radio=Radio;
