var sp=getSpotifyApi();exports.Pager=Pager;var dom=sp.require("$util/dom"),logger=sp.require("$util/logger");
function Pager(b,a){a=a||{};this.datasource=b;this._pages={};this._bullets=[];this._orientation="vertical"===a.orientation?"vertical":"horizontal";this._pagingLocation="top"===a.pagingLocation?"top":"bottom";this._showBullets=void 0!==a.bullets?a.bullets:!0;this._perPage=a.perPage?a.perPage:5;this._hidePartials=a.hidePartials?a.hidePartials:!1;this._listType="table"===a.listType?"table":"list";this._currentPage=0;this._context=void 0!==a.context?a.context:"pager";this._pageSize=this._currentPageEl=
null;this._running=0;this._heightLocked=!1;this._pageCount=this._hidePartials?Math.floor(this.datasource.count()/this._perPage):Math.ceil(this.datasource.count()/this._perPage);_build.call(this);_buildPage.call(this,0)}Pager.prototype.setOptions=function(b){b.perPage&&(this._perPage=b.perPage,this._pageCount=this._hidePartials?Math.floor(this.datasource.count()/this._perPage):Math.ceil(this.datasource.count()/this._perPage))};
Pager.prototype.reflow=function(){var b=this;this._window.classList.add("no-animations");this.displayPage(0,!0);setTimeout(function(){b._window.classList.remove("no-animations")},10);if(this._showBullets)if(this._pageCount<this._bullets.length){for(var a=this._pageCount;a<this._bullets.length;a++)dom.destroy(this._bullets[a]);this._bullets=this._bullets.slice(0,this._pageCount)}else if(this._pageCount>this._bullets.length)for(a=this._bullets.length;a<this._pageCount;a++){var c=new dom.Element("li",
{html:'<a href="#'+a+'">Page '+(a+1)+"</a>"});this._bullets.push(c);dom.inject(c,this.nextButton,"before")}};
Pager.prototype.displayPage=function(b,a){0>b&&(b=0);b>this._pageCount-1&&(b=this._pageCount-1);if(this._currentPage!==b||!0===a)0>b||b>this._pageCount-1||(_buildPage.call(this,b),1===this._pageCount?(this.prevButton.classList.remove("inactive"),this.nextButton.classList.remove("inactive"),this._showBullets&&this._bullets[this.currentPage].classList.remove("inactive"),this._paging.classList.remove("active")):(this._paging.classList.add("active"),0===b?this.prevButton.classList.add("inactive"):0===
this._currentPage&&this.prevButton.classList.remove("inactive"),b===this._pageCount-1?this.nextButton.classList.add("inactive"):this.nextButton.classList.remove("inactive"),this._showBullets&&(this._bullets[this._currentPage].classList.remove("active"),this._bullets[b].classList.add("active"))),this._currentPage=b)};
function _build(){this.h2=new dom.Element("h2");this.node=new dom.Element("div",{className:"pager"});this._window=new dom.Element("div",{className:"window"});this._paging=new dom.Element("div",{className:"paging"});"vertical"===this._orientation&&this.node.classList.add("vertical");_buildPaging.call(this);"top"===this._pagingLocation?(this.node.classList.add("paging-top"),dom.adopt(this.node,this.h2,this._paging,this._window)):dom.adopt(this.node,this.h2,this._window,this._paging)}
function _buildPaging(){this.prevButton=new dom.Element("li",{className:"prev",html:'<a href="#previous">Previous</a>'});this.nextButton=new dom.Element("li",{className:"next",html:'<a href="#next">Next</a>'});1<this._pageCount&&this.prevButton.classList.add("inactive");var b=this,a=new dom.Element("ul");dom.adopt(a,this.prevButton);if(this._showBullets)for(var c=0;c<this._pageCount;c++){var d=new dom.Element("li",{html:'<a href="#'+c+'">Page '+(c+1)+"</a>"});0===c&&d.classList.add("active");this._bullets.push(d);
dom.adopt(a,d)}dom.adopt(a,this.nextButton);dom.adopt(this._paging,a);1<this._pageCount&&this._paging.classList.add("active");dom.listen(this._paging,"click",function(a){a.preventDefault();"A"===a.target.tagName&&(a.target.parentNode===b.prevButton?(logger.logClientEvent(b._context+" paging","click","1","1",{page:"-1"}),b.displayPage(b._currentPage-1)):a.target.parentNode===b.nextButton?(logger.logClientEvent(b._context+" paging","click","1","1",{page:"+1"}),b.displayPage(b._currentPage+1)):(logger.logClientEvent(b._context+
" paging","click","1","1",{page:b._bullets.indexOf(a.target.parentNode)}),b.displayPage(b._bullets.indexOf(a.target.parentNode))))})}
function _buildPage(b){if(!(0>b||b>this._pageCount)){if("table"===this._listType){var a=new dom.Element("table");a.cellSpacing=0}else a=new dom.Element("ul");for(var c=this._perPage*b,d=c;d<c+this._perPage&&d<this.datasource.count();d++){var g=this.datasource.makeNode(d);dom.adopt(a,g)}if(this._currentPageEl){b=b<this._currentPage?-1:1;this._running++;_lock.call(this);a.style.position="absolute";"vertical"===this._orientation?(a.style.top=(-1===b?"-":"")+this._pageSize.y+"px",a.style.left=0):(a.style.top=
0,a.style.left=(-1===b?"-":"")+this._pageSize.x+"px");dom.inject(a,this._window);"vertical"===this._orientation?(this._currentPageEl.style.top=(1===b?"-":"")+this._pageSize.y+"px",a.style.top=0):(this._currentPageEl.style.left=(1===b?"-":"")+this._pageSize.x+"px",a.style.left=0);var e=this,f=!1;this._window.classList.contains("no-animations")?(dom.destroy(this._currentPageEl),e._running--,0===e._running&&_unlock.call(this)):dom.listen(this._currentPageEl,"webkitTransitionEnd",function(a){f||(dom.destroy(a.target),
e._running--,0===e._running&&_unlock.call(e),f=!0)})}else dom.inject(a,this._window);this._currentPageEl=a}}function _lock(){this._pageSize=dom.getSize(this._currentPageEl);this._heightLocked||(this._window.style.height=this._pageSize.y+"px",this._heightLocked=!0);"horizontal"===this._orientation&&(this._window.style.width=this._pageSize.x+"px");this._currentPageEl.style.position="absolute";this._currentPageEl.style.top=0;this._currentPageEl.style.left=0}
function _unlock(){this._currentPageEl.style.removeProperty("position");this._currentPageEl.style.removeProperty("top");this._currentPageEl.style.removeProperty("left");this._window.style.removeProperty("width")};
