var sp=getSpotifyApi(),md=sp.require("$api/metadata"),dom=sp.require("$util/dom"),fs=sp.require("$util/fs"),lang=sp.require("$util/language"),log=sp.require("$util/logger"),react=sp.require("$util/react"),social=sp.require("$unstable/social"),util=sp.require("$util/util"),ui=sp.require("$unstable/ui"),CATALOG=lang.loadCatalog("$resources/cef_views"),_=partial(lang.getString,CATALOG,"Generic");exports.showPopover=popover;exports.sharePopup=showSharePopover;exports.shareSocialPopup=showSocialSharePopover;
exports.hidePopover=function(){null!==_popover&&hidePopover(_popover)};Object.defineProperty(exports,"popover",{get:function(){return _popover}});var shareTemplate=lang.format(fs.readFile("$unstable/templates/share.html"),_("sGenericShareMessagePlaceholder"),_("sGenericCancel"),_("sGenericSend"),_("sGenericLoading")),DEFAULTS={contentNode:null,relativeNode:document.body,offsetLeft:0,offsetFlippedLeft:0,offsetTop:0,offsetInvertedTop:0,sharePopoverPrependElem:null},_popover=null;
function getPosition(a){var b=findPos(a);return{x:a.offsetLeft,y:a.offsetTop,width:a.clientWidth,height:a.clientHeight,dX:b[0],dY:b[1]}}function findPos(a){var b=0,c=0;if(a.offsetParent){do b+=a.offsetLeft,c+=a.offsetTop;while(a=a.offsetParent)}return[b,c]}function removePopover(a){a.node.parentNode&&!a.visible&&a.node.parentNode.removeChild(a.node);return a}
function hidePopover(a,b,c){if(!1===a.visible)return a;a.visible=!1;a.targetNode.classList.remove("selected");if(!0===b)return removePopover(a),a;a.targetNode=null;a.node.offsetWidth;!0===c?a.node.classList.add("sent"):a.node.classList.add("hidden");react.takeFirst(react.fromDOMEvent(a.node,"webkitAnimationEnd")).subscribe(partial(removePopover,a));return a}
function showPopover(a,b){var c=a.options.relativeNode;if(!0===a.visible){b.classList.remove("selected");if(a.targetNode===b)return a.hide(!1),a;a.hide(!0)}sp.core.activate();a.visible=!0;a.targetNode=b;b.classList.add("selected");var e=getPosition(b);getPosition(c);var d=e.dY-c.scrollTop,e=e.dX-c.scrollLeft,k=-50,g=0,f=c.scrollTop;react.throttle(react.fromDOMEvent(c,"scroll"),50).subscribe(function(b){5<Math.abs(f-b.target.scrollTop)&&a.hide()});react.takeFirst(react.filter(function(a){return 27===
a.which},react.fromDOMEvent(window,"keyup"))).subscribe(partial(hidePopover,a));react.fromDOMEvent(window,"resize").subscribe(partial(hidePopover,a));document.body.appendChild(a.node);a.node.offsetWidth;k+=document.documentElement.clientHeight-d-a.node.clientHeight;g+=document.documentElement.clientWidth-e-a.node.clientWidth-a.options.offsetLeft;0>=k?(a.node.classList.add("inverted"),a.node.style.top=d-a.node.clientHeight+a.options.offsetInvertedTop+"px"):(a.node.classList.remove("inverted"),a.node.style.top=
d+a.options.offsetTop+"px");0>=g?(a.node.classList.add("flipped"),a.node.style.left=e-a.node.clientWidth+a.options.offsetFlippedLeft+"px"):(a.node.classList.remove("flipped"),a.node.style.left=e+a.options.offsetLeft+"px");a.node.classList.remove("hidden");a.node.classList.remove("sent");return a}
function showSharePopover(a,b,c,e){var d=document.createElement("div"),k=sp.core.getLinkType(b),g,f;d.innerHTML=shareTemplate;e&&e.sharePopoverPrependElem&&d.insertBefore(e.sharePopoverPrependElem,d.firstChild);d.classList.add("popover-share");var m=dom.queryOne(".artwork",d),h=dom.queryOne(".title",d),i=dom.queryOne(".artist",d),n=dom.queryOne("form",d),j=dom.queryOne("textarea",n),q=dom.queryOne(".cancel",n);setTimeout(function(){j.select()},10);5===k?(f=sp.core.getPlaylist(b),f.loaded?(g=new ui.SPImage(f.cover,
f.uri,f.name),h.textContent=f.name.decodeForText(),i.textContent=f.owner.name.decodeForText(),m.appendChild(g.node)):f.addEventListener("change",function r(){f.loaded&&(g=new ui.SPImage(f.cover,f.uri,f.name),h.textContent=f.name.decodeForText(),i.textContent=f.owner.name.decodeForText(),m.appendChild(g.node),f.removeEventListener("change",r))})):md.getMetadata(b,function(a){null!==a&&("track"===a.type?(g=new ui.SPImage(a.album.cover,a.uri,a.name),h.innerHTML=lang.format('<a href="{0}">{1}</a>',a.uri,
a.name),i.innerHTML=map(function(a){return lang.format('<a href="{0}">{1}</a>',a.uri,a.name)},a.artists).join(", ")):"artist"===a.type?(g=new ui.SPImage(a.portrait,a.uri,a.name),h.textContent=a.name.decodeForText(),dom.empty(i)):"album"===a.type?(g=new ui.SPImage(a.cover,a.uri,a.name),h.textContent=a.name.decodeForText(),i.textContent=a.artist.name.decodeForText()):"playlist"===a.type&&(g=new ui.SPImage(a.cover,a.uri,a.name),h.textContent=a.name.decodeForText(),i.textContent=a.owner.name.decodeForText()),
g.node.classList.add(a.type),m.appendChild(g.node))});e&&(e.contentNode=d);var l=popover(e),p=+new Date;log.logClientEvent("share popover","open","1","1",{popupId:p,uri:b});d.addEventListener("click",function(a){"A"===a.target.tagName&&a.target.href&&log.logClientEvent("share popover","link","1","1",{popupId:p,uri:a.target.href})});react.fromDOMEvent(q,"click").subscribe(function(){log.logClientEvent("share popover","cancel","1","1",{popupId:p,message:!!j.value});hidePopover(l)});react.merge(react.fromDOMEvent(n,
"submit"),react.fromDOMEvent(j,"keyup")).subscribe(function(e){if(!("keyup"===e.type&&13!==e.which)){e.preventDefault();var e=l.node,d=0,g=partial(sp.core.showClientMessage,2,_("sGenericSendMessageError")),f=function(){(null!==a.facebookUid&&2===d||null===a.facebookUid&&1===d)&&g()},c=new dom.Element("div",{className:"checkmark"});c.style.height=e.clientHeight-16+"px";c.style.width=e.clientWidth-8+"px";dom.adopt(c,document.createElement("div"));dom.adopt(e,c);a.canonicalUsername&&sp.social.sendToInbox(a.canonicalUsername,
j.value,b,{onSuccess:function(){},onFailure:function(){d++},onComplete:f});a.facebookUid&&social.sendFacebookMessage(a.facebookUid,j.value,sp.core.spotifyUriToHttpLink(b),null,function(){d++},f);log.logClientEvent("popover","share-send","","",{id:l.id,toFacebook:!!a.facebookUid,toSpotify:!!a.canonicalUsername,message:!!j.value});setTimeout(function(){l.hide(!1,!0)},400)}});l.show(c);return a}function showSocialSharePopover(a,b){sp.social.showSharePopup(a.clientX,a.clientY,b)}
function popover(a){null===_popover&&(_popover=new Popover(a));_popover.id=+new Date;_popover.setContent(a);var b={id:_popover.id};a&&a.type&&(b.type=a.type);a&&a.uri&&(b.uri=a.uri);log.logClientEvent("popover","open","","",b);return _popover}
function Popover(a){var b=this;this.options=util.merge({},DEFAULTS,a||{});this.node=document.createElement("div");this.targetNode=null;this.visible=!1;this.node.classList.add("popover");react.fromDOMEvent(this.node,"click").subscribe(function(a){var d=a.target.classList.contains("popover"),c,g;"A"===a.target.tagName&&a.target.href&&log.logClientEvent("popover","link","","",{id:b.id,uri:a.target.href});d&&(c=!!(0>a.offsetX-10||a.offsetX-5>a.target.clientWidth),g=a.target.classList.contains("inverted")?
!!(0>a.offsetY-7||a.offsetY>a.target.clientHeight):!!(0>a.offsetY-12||a.offsetY-3>a.target.clientHeight));(!d||!c&&!g)&&a.stopPropagation()});var a=react.fromDOMEvent(window,"click"),c=react.fromDOMEvent(window,"blur");react.merge(a,c).subscribe(function(){sp.core.isApplicationFocused&&b.hide()})}Popover.prototype.setContent=function(a){for(this.options.relativeNode=a.relativeNode||DEFAULTS.relativeNode;this.node.firstChild;)this.node.removeChild(this.node.firstChild);this.node.appendChild(a.contentNode)};
Popover.prototype.show=function(a){return showPopover(this,a)};Popover.prototype.hide=function(a,b){return hidePopover(this,a,b)};
