var sp=getSpotifyApi(),models=sp.require("$api/models"),storage=sp.require("$util/storage"),social=sp.require("$unstable/social");sp.require("$unstable/hermes");
var PRESENCE_CACHE_KEY="cachedPresences",PRESENCE_CACHE_SAVE_TIMEOUT=1E3,PRESENCE_BATCH_SIZE=15,PRESENCE_BATCH_INTERVAL=1E3,PRESENCE_BATCH_DEFAULT_MAX=30,APP_BLACKLIST={album:!0,"album-header":!0,artist:!0,feed:!0,finder:!0,home:!0,"notification-popup":!0,"og-popup":!0,"onboarding-popup":!0,people:!0,profile:!0,"profile-header":!0,"playlist-header":!0,search:!0,"search-dropdown":!0,"search-header":!0,"subscribe-popup":!0,tutorial:!0},APP_REGEX=RegExp(/^spotify:app:([^:]*)(:|$)/);
exports.getMostRecentPresence=getMostRecentPresence;exports.getPresenceForUser=getPresenceForUser;exports.getPresenceForUsers=getPresenceForUsers;exports.observePresenceForUser=observePresenceForUser;exports.observePresenceForUsers=observePresenceForUsers;exports.PresenceState=PresenceState;
var _cachedPresences=storage.getWithDefault(PRESENCE_CACHE_KEY,{}),_observedUsers={},_saveCacheTimeout=0,_saveCacheNow=function(){storage.set(PRESENCE_CACHE_KEY,_cachedPresences)},_saveCacheLater=function(){_saveCacheTimeout&&clearTimeout(_saveCacheTimeout);_saveCacheTimeout=setTimeout(_saveCacheNow,PRESENCE_CACHE_SAVE_TIMEOUT)};sp.core.addEventListener("hermes",_presenceUpdated,!1);window.addEventListener("beforeunload",_saveCacheNow);
function PresenceState(a,b,c){this.type=b;this.username=c;this.timestamp=a.timestamp;this.message=this.appUri=this.contextUri=this.referrerUri=this.artistUri=this.albumUri=this.playlistUri=this.trackUri=null;PresenceState.extractURIs(this,a);return this}
PresenceState.TYPE={UNKNOWN:-1,FACEBOOK_ACTIVITY:0,TRACK_FINISHED_PLAYING:1,PLAYLIST_PUBLISHED:2,PLAYLIST_TRACK_ADDED:3,PLAYLIST_TRACK_STARRED:4,PLAYLIST_SUBSCRIBED:5,MY_PLAYLIST_SUBSCRIBED:6,APP_ADDED:7,APP_TRACK_FINISHED_PLAYING:8,RADIO_TRACK_FINISHED_PLAYING:9,TRACK_STARTED_PLAYING:10,TRACK_SHARED:11,PLAYLIST_SHARED:12,ALBUM_SHARED:13,ARTIST_SHARED:14};
PresenceState.getType=function(a,b,c){switch(b){case "track_started_playing":return PresenceState.TYPE.TRACK_STARTED_PLAYING;case "track_finished_playing":if(c=APP_REGEX.exec(a[b].referrer_uri))if((c=c[1])&&!APP_BLACKLIST[c])return"radio"==c?PresenceState.TYPE.RADIO_TRACK_FINISHED_PLAYING:PresenceState.TYPE.APP_TRACK_FINISHED_PLAYING;return PresenceState.TYPE.TRACK_FINISHED_PLAYING;case "playlist_track_added":return a[b].playlist_uri&&_isStarredPlaylist(a[b].playlist_uri)?PresenceState.TYPE.PLAYLIST_TRACK_STARRED:
PresenceState.TYPE.PLAYLIST_TRACK_ADDED;case "playlist_published":return a=decodeURIComponent(a[b].uri.split(":")[2]),a===c?PresenceState.TYPE.PLAYLIST_PUBLISHED:a===sp.core.user.canonicalUsername?PresenceState.TYPE.MY_PLAYLIST_SUBSCRIBED:PresenceState.TYPE.PLAYLIST_SUBSCRIBED;case "favorite_app_added":return PresenceState.TYPE.APP_ADDED;case "facebook_activity":return PresenceState.TYPE.FACEBOOK_ACTIVITY;case "uri_shared":return _isTrack(a[b].uri)?PresenceState.TYPE.TRACK_SHARED:_isPlaylist(a[b].uri)?
PresenceState.TYPE.PLAYLIST_SHARED:_isAlbum(a[b].uri)?PresenceState.TYPE.ALBUM_SHARED:_isArtist(a[b].uri)?PresenceState.TYPE.ARTIST_SHARED:PresenceState.TYPE.UNKNOWN;default:return PresenceState.TYPE.UNKNOWN}};
PresenceState.extractURIs=function(a,b){switch(a.type){case PresenceState.TYPE.PLAYLIST_PUBLISHED:case PresenceState.TYPE.PLAYLIST_SUBSCRIBED:case PresenceState.TYPE.MY_PLAYLIST_SUBSCRIBED:a.playlistUri=b.uri||null;break;case PresenceState.TYPE.PLAYLIST_TRACK_ADDED:case PresenceState.TYPE.PLAYLIST_TRACK_STARRED:a.trackUri=b.track_uri||null;a.playlistUri=b.playlist_uri||null;break;case PresenceState.TYPE.TRACK_STARTED_PLAYING:case PresenceState.TYPE.TRACK_FINISHED_PLAYING:case PresenceState.TYPE.RADIO_TRACK_FINISHED_PLAYING:case PresenceState.TYPE.APP_TRACK_FINISHED_PLAYING:a.trackUri=
b.uri||null;a.contextUri=b.context_uri||null;a.referrerUri=b.referrer_uri||null;break;case PresenceState.TYPE.APP_ADDED:a.appUri=b.app_uri||null;break;case PresenceState.TYPE.TRACK_SHARED:a.trackUri=b.uri||null;a.message=b.message||"";break;case PresenceState.TYPE.PLAYLIST_SHARED:a.playlistUri=b.uri||null;a.message=b.message||"";break;case PresenceState.TYPE.ALBUM_SHARED:a.albumUri=b.uri||null;a.message=b.message||"";break;case PresenceState.TYPE.ARTIST_SHARED:a.artistUri=b.uri||null,a.message=b.message||
""}};function _isStarredPlaylist(a){return-1!==a.indexOf(":starred",a.length-8)||-1!==a.indexOf(":publishedstarred",a.length-17)}function _isTrack(a){return 0===a.indexOf("spotify:track:")}function _isPlaylist(a){return 0===a.indexOf("spotify:user:")&&-1!==a.indexOf(":playlist:")||_isStarredPlaylist(a)}function _isAlbum(a){return 0===a.indexOf("spotify:album:")}function _isArtist(a){return 0===a.indexOf("spotify:artist:")}
function _subscribeToUsers(a){var b,c,d=0,e=Math.ceil(a.length/300);b=function(){var b=a.slice(d,d+300);d+=300;c(b)};c=function(a){sp.core.getHermes("SUB","hm://presence/user/",a,{onSuccess:function(){},onFailure:function(){},onComplete:function(){0<--e&&setTimeout(b,500)}})};b()}
function _presenceUpdated(a){var b=a.data[0];if(0===b.indexOf("hm://presence/user/")&&(b=b.slice(19,-1),a=sp.core.parseHermesReply("PresenceState",a.data[1]),a=_extractPresenceStates(b,a),a.length))_observedUsers[b](b,a)}function _extractPresenceStates(a,b){if(b){var c=[],d;for(d in b)if(b.hasOwnProperty(d)&&0<b[d].timestamp){var e=PresenceState.getType(b,d,a);c.push(new PresenceState(b[d],e,a))}_cachedPresences[a]={states:c};_saveCacheLater();return c}}
function _getUsername(a){if(a.hasOwnProperty("canonicalUsername"))return a.canonicalUsername;if("string"===typeof a)return a;throw"Invalid arguments: no user or username provided";}function _getCachedPresenceForUsers(a){for(var b={},c=0;c<a.length;c++){var d=a[c];if(d.length){var e;_cachedPresences[d]?(e=_cachedPresences[d].states,e instanceof Array&&(e[0]&&e[0].username?b[d]=e:_cachedPresences[d]=null)):_cachedPresences[d]=null}}_saveCacheLater();return b}
function _fyShuffle(a){var b=a.length,c,d,e;if(0===b)return a;for(;--b;)c=~~(Math.random()*(b+1)),d=a[b],e=a[c],a[b]=e,a[c]=d;return a}function getPresenceForUser(a,b){getPresenceForUsers([_getUsername(a)],b,1)}
function getPresenceForUsers(a,b,c){for(var d=_getCachedPresenceForUsers(a),e=[],c=c||PRESENCE_BATCH_DEFAULT_MAX,f=0;f<a.length;f++){var i=a[f];d[i]||e.push(i)}c=Math.min(c,e.length);if(!e.length||Object.keys(d).length>=c)b(d);else{_fyShuffle(e);var h,j,g=0,k=Math.ceil(e.length/PRESENCE_BATCH_SIZE);h=function(){var a=e.slice(g,g+PRESENCE_BATCH_SIZE);g+=PRESENCE_BATCH_SIZE;j(a)};j=function(a){var e=function(){Object.keys(d).length<c&&0<--k?setTimeout(h,PRESENCE_BATCH_INTERVAL):b(d)};sp.core.getHermes("GET",
"hm://presence/user/",a,{onSuccess:function(){for(var b=0;b<arguments.length;++b){var c=a[b],f=sp.core.parseHermesReply("PresenceState",arguments[b]),f=_extractPresenceStates(c,f);f.length?d[c]=f:delete d[c]}e()},onFailure:e})};h()}}function observePresenceForUser(a,b,c,d){observePresenceForUsers([_getUsername(a)],b,c,d)}
function observePresenceForUsers(a,b,c,d){var e=[];c&&getPresenceForUsers(a,b,PRESENCE_BATCH_DEFAULT_MAX);for(var f in a)c=a[f],c.length&&((d||!_observedUsers[c])&&e.push(c),_observedUsers[c]=b);e.length&&_subscribeToUsers(e)}function getMostRecentPresence(a){if(!a)return null;for(var b=null,c=0,d=a.length;c<d;++c){var e=a[c];if(!b||e.timestamp>b.timestamp)b=e}return b};
