var sp=getSpotifyApi();exports.SPImage=SPImage;exports.ContextMenu=ContextMenu;exports.NodeObject=NodeObject;exports.SubscribeButton=SubscribeButton;var base=sp.require("$util/base"),events=sp.require("$util/events"),promise=sp.require("$util/promise"),social=sp.require("$unstable/social");
function SPImage(a,c,f){var b=this;c?(b.node=document.createElement("a"),b.node.href=c,b.node.style.display="none"):b.node=document.createElement("div");f&&(b.node.title=f);b.node.classList.add("image");if(0==a.indexOf("spotify:mosaic:")){var e=[],c=map(function(a){return"spotify:image:"+a},a.slice(15).split(/[,;:]/)),g=new promise.Promise;b.node.addEventListener("DOMNodeInserted",function h(){b.node.style.display="block";g.resolve();b.node.removeEventListener("DOMNodeInserted",h)});e.push(g);c.forEach(function(a){var b=
new Image,c=new promise.Promise;b.src=a;b.complete?c.resolve(b):(b.addEventListener("load",function j(){c.resolve(b);b.removeEventListener("load",j)}),b.addEventListener("error",function k(){c.reject(b);b.removeEventListener("error",k)}));e.push(c)});promise.join.apply(promise,e).always(function(){var a=2*b.node.offsetWidth||300,c=2*b.node.offsetHeight||300,e=Math.floor(Math.sqrt(arguments.length)),d=~~(1E6*Math.random()),f=document.getCSSCanvasContext("2d","cover-"+d,a,c);f.clearRect(0,0,a,c);for(var g=
0;g<arguments.length&&g<e*e;g++)f.drawImage(arguments[g],g%e*a/e,Math.floor(g/e)*c/e,a/e,c/e);b.node.style.backgroundImage="-webkit-canvas(cover-"+d+")"})}else if(a.length){var d=new Image;d.src=a;d.complete?(b.node.style.backgroundImage='url("'+a+'")',b.node.style.display="block"):d.addEventListener("load",function i(){b.node.style.backgroundImage='url("'+a+'")';b.node.style.display="block";d.removeEventListener("load",i)})}}
var attr=function(a,c){return void 0!=a.attributes[c]?a.attributes[c].value:""},bool=function(a){return/^(true|1)$/i.test(a)};
function ContextMenuData(a,c,f){var b=this;b.label=a||"";b.flags=c||0;b.onSelect=f||null;b.onMenu=null;b.addItem=function(a,c,d){b.add(new ContextMenuData(a,c,d))};b.addSeparator=function(){b.add(new ContextMenuData)};b.addSubMenu=function(a,c){var d=new ContextMenuData(a,c);b.add(d);return d};b.add=function(a){null==b.onMenu&&(b.onMenu=[]);b.onMenu.push(a)};b.addFromElementById=function(a){b.addNode(document.getElementById(a))};b.addNode=function(a){if(!("menu"!=a.localName||"context"!=attr(a,"type")))for(var c=
0;c<a.children.length;c++){var d=a.children[c];"command"==d.localName?b.addItem(attr(d,"label"),bool(attr(d,"disabled"))*ContextMenu.FLAGS.DISABLED|bool(attr(d,"checked"))*ContextMenu.FLAGS.CHECKED|("bold"==d.style.fontWeight)*ContextMenu.FLAGS.BOLD,d.onclick):"menu"==d.localName&&b.addSubMenu(attr(d,"label")).addNode(d)}}}
function ContextMenu(a){var c=this;a instanceof ContextMenuData?c.data=a:(c.data=new ContextMenuData,"string"==typeof a&&c.data.addFromElementById(a));c.attach=function(){if(0!=arguments.length){var a=arguments;window.addEventListener("contextmenu",function(b){if(void 0!=b.target.href)for(var e=0;e<a.length;e++)if(a[e].test(b.target.href)){c.show(b.clientX,b.clientY);b.preventDefault();break}})}};c.show=function(a,b){sp.desktop.showContextMenu(c.data,a,b)}}
ContextMenu.FLAGS={CHECKED:1,DISABLED:2,BOLD:4};ContextMenu.REGEXP={ARTIST:/^spotify:artist:[0-9a-zA-Z]{22}$/,ALBUM:/^spotify:album:[0-9a-zA-Z]{22}$/,SEARCH:/^spotify:search:[^:]+$/,TRACK:/^spotify:track:[0-9a-zA-Z]{22}(\?.+)*(#[0-9]+:[0-9]+)*$/,PLAYLIST:/^spotify:user:[^:]+:playlist:[0-9a-zA-Z]{22}$/,PROFILE:/^spotify:user:[^:]+$/,STARRED:/^spotify:user:[^:]+:starred$/,AD:/^spotify:ad:[0-9a-zA-Z]{22}$/,IMAGE:/^spotify:image:[0-9a-zA-Z]{22}$/,APP:/^spotify:app:[^:]+$/};
function NodeObject(){events.EventTarget.call(this);this._node=null}base.inherit(NodeObject,events.EventTarget);NodeObject.prototype._buildNode=function(){throw Error("Unimplemented _buildNode called on "+this.constructor.name);};Object.defineProperty(NodeObject.prototype,"node",{get:function(){return this._node?this._node:this._node=this._buildNode()}});
NodeObject.prototype.remove=function(){NodeObject._superClass.remove.call(this);var a=this._node;a.parentNode&&a.parentNode.removeChild(a);this._node=null};var _subscribeButtons={};function _subscriptionChange(a,c){var f=_subscribeButtons[a];f&&f.forEach(function(b){b.dispatchEvent({type:"subscriptionchange",username:a,subscribed:c})})}social.addEventListener(social.SUBSCRIPTION_ADDED_EVENT,function(a){a.detail.forEach(function(a){_subscriptionChange(a,!0)})});
social.addEventListener(social.SUBSCRIPTION_REMOVED_EVENT,function(a){a.detail.forEach(function(a){_subscriptionChange(a,!1)})});function SubscribeButton(a){NodeObject.call(this);this.username=a;_subscribeButtons[a]||(_subscribeButtons[a]=[]);_subscribeButtons[a].push(this)}base.inherit(SubscribeButton,NodeObject);
SubscribeButton.prototype._buildNode=function(){var a=document.createElement("button");a.className="sp-button sp-subscription";var c;this.addEventListener("subscriptionchange",function(b){(c=b.subscribed)?(a.classList.add("sp-subscribed"),a.textContent="Following"):(a.classList.remove("sp-subscribed"),a.textContent="Follow")});this.dispatchEvent({type:"subscriptionchange",username:this.username,subscribed:social.isSubscribed(this.username)});var f=this;a.addEventListener("click",function(){f.dispatchEvent({type:"click"})&&
(c?social.unsubscribe:social.subscribe)(f.username)});return a};SubscribeButton.prototype.setUser=function(a){var c=this.username;a!=c&&(this.username=a,c=_subscribeButtons[c],c.splice(c.indexOf(this),1),(c=_subscribeButtons[a])||(c=_subscribeButtons[a]=[]),c.push(this),this.dispatchEvent({type:"subscriptionchange",username:a,subscribed:social.isSubscribed(a)}))};
