# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='socialgraph.proto',
  package='spotify.socialgraph.proto',
  serialized_pb='\n\x11socialgraph.proto\x12\x19spotify.socialgraph.proto\"\x1c\n\nCountReply\x12\x0e\n\x06\x63ounts\x18\x01 \x03(\x05\"M\n\x0fUserListRequest\x12\x13\n\x0blast_result\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x16\n\x0einclude_length\x18\x03 \x01(\x08\"O\n\rUserListReply\x12.\n\x05users\x18\x01 \x03(\x0b\x32\x1f.spotify.socialgraph.proto.User\x12\x0e\n\x06length\x18\x02 \x01(\x05\"N\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x18\n\x10subscriber_count\x18\x02 \x01(\x05\x12\x1a\n\x12subscription_count\x18\x03 \x01(\x05\"E\n\x0f\x41rtistListReply\x12\x32\n\x07\x61rtists\x18\x01 \x03(\x0b\x32!.spotify.socialgraph.proto.Artist\"4\n\x06\x41rtist\x12\x10\n\x08\x61rtistid\x18\x01 \x01(\t\x12\x18\n\x10subscriber_count\x18\x02 \x01(\x05\"!\n\x11StringListRequest\x12\x0c\n\x04\x61rgs\x18\x01 \x03(\t\" \n\x0fStringListReply\x12\r\n\x05reply\x18\x01 \x03(\t\"6\n\x13TopPlaylistsRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"!\n\x11TopPlaylistsReply\x12\x0c\n\x04uris\x18\x01 \x03(\t')




_COUNTREPLY = descriptor.Descriptor(
  name='CountReply',
  full_name='spotify.socialgraph.proto.CountReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='counts', full_name='spotify.socialgraph.proto.CountReply.counts', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=48,
  serialized_end=76,
)


_USERLISTREQUEST = descriptor.Descriptor(
  name='UserListRequest',
  full_name='spotify.socialgraph.proto.UserListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='last_result', full_name='spotify.socialgraph.proto.UserListRequest.last_result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count', full_name='spotify.socialgraph.proto.UserListRequest.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='include_length', full_name='spotify.socialgraph.proto.UserListRequest.include_length', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=78,
  serialized_end=155,
)


_USERLISTREPLY = descriptor.Descriptor(
  name='UserListReply',
  full_name='spotify.socialgraph.proto.UserListReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='users', full_name='spotify.socialgraph.proto.UserListReply.users', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='length', full_name='spotify.socialgraph.proto.UserListReply.length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=157,
  serialized_end=236,
)


_USER = descriptor.Descriptor(
  name='User',
  full_name='spotify.socialgraph.proto.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='username', full_name='spotify.socialgraph.proto.User.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='subscriber_count', full_name='spotify.socialgraph.proto.User.subscriber_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='subscription_count', full_name='spotify.socialgraph.proto.User.subscription_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=238,
  serialized_end=316,
)


_ARTISTLISTREPLY = descriptor.Descriptor(
  name='ArtistListReply',
  full_name='spotify.socialgraph.proto.ArtistListReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='artists', full_name='spotify.socialgraph.proto.ArtistListReply.artists', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=318,
  serialized_end=387,
)


_ARTIST = descriptor.Descriptor(
  name='Artist',
  full_name='spotify.socialgraph.proto.Artist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='artistid', full_name='spotify.socialgraph.proto.Artist.artistid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='subscriber_count', full_name='spotify.socialgraph.proto.Artist.subscriber_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=389,
  serialized_end=441,
)


_STRINGLISTREQUEST = descriptor.Descriptor(
  name='StringListRequest',
  full_name='spotify.socialgraph.proto.StringListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='args', full_name='spotify.socialgraph.proto.StringListRequest.args', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=443,
  serialized_end=476,
)


_STRINGLISTREPLY = descriptor.Descriptor(
  name='StringListReply',
  full_name='spotify.socialgraph.proto.StringListReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='reply', full_name='spotify.socialgraph.proto.StringListReply.reply', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=478,
  serialized_end=510,
)


_TOPPLAYLISTSREQUEST = descriptor.Descriptor(
  name='TopPlaylistsRequest',
  full_name='spotify.socialgraph.proto.TopPlaylistsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='username', full_name='spotify.socialgraph.proto.TopPlaylistsRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count', full_name='spotify.socialgraph.proto.TopPlaylistsRequest.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=512,
  serialized_end=566,
)


_TOPPLAYLISTSREPLY = descriptor.Descriptor(
  name='TopPlaylistsReply',
  full_name='spotify.socialgraph.proto.TopPlaylistsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='uris', full_name='spotify.socialgraph.proto.TopPlaylistsReply.uris', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=568,
  serialized_end=601,
)

_USERLISTREPLY.fields_by_name['users'].message_type = _USER
_ARTISTLISTREPLY.fields_by_name['artists'].message_type = _ARTIST
DESCRIPTOR.message_types_by_name['CountReply'] = _COUNTREPLY
DESCRIPTOR.message_types_by_name['UserListRequest'] = _USERLISTREQUEST
DESCRIPTOR.message_types_by_name['UserListReply'] = _USERLISTREPLY
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['ArtistListReply'] = _ARTISTLISTREPLY
DESCRIPTOR.message_types_by_name['Artist'] = _ARTIST
DESCRIPTOR.message_types_by_name['StringListRequest'] = _STRINGLISTREQUEST
DESCRIPTOR.message_types_by_name['StringListReply'] = _STRINGLISTREPLY
DESCRIPTOR.message_types_by_name['TopPlaylistsRequest'] = _TOPPLAYLISTSREQUEST
DESCRIPTOR.message_types_by_name['TopPlaylistsReply'] = _TOPPLAYLISTSREPLY

class CountReply(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COUNTREPLY
  
  # @@protoc_insertion_point(class_scope:spotify.socialgraph.proto.CountReply)

class UserListRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERLISTREQUEST
  
  # @@protoc_insertion_point(class_scope:spotify.socialgraph.proto.UserListRequest)

class UserListReply(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERLISTREPLY
  
  # @@protoc_insertion_point(class_scope:spotify.socialgraph.proto.UserListReply)

class User(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USER
  
  # @@protoc_insertion_point(class_scope:spotify.socialgraph.proto.User)

class ArtistListReply(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ARTISTLISTREPLY
  
  # @@protoc_insertion_point(class_scope:spotify.socialgraph.proto.ArtistListReply)

class Artist(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ARTIST
  
  # @@protoc_insertion_point(class_scope:spotify.socialgraph.proto.Artist)

class StringListRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STRINGLISTREQUEST
  
  # @@protoc_insertion_point(class_scope:spotify.socialgraph.proto.StringListRequest)

class StringListReply(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STRINGLISTREPLY
  
  # @@protoc_insertion_point(class_scope:spotify.socialgraph.proto.StringListReply)

class TopPlaylistsRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TOPPLAYLISTSREQUEST
  
  # @@protoc_insertion_point(class_scope:spotify.socialgraph.proto.TopPlaylistsRequest)

class TopPlaylistsReply(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TOPPLAYLISTSREPLY
  
  # @@protoc_insertion_point(class_scope:spotify.socialgraph.proto.TopPlaylistsReply)

# @@protoc_insertion_point(module_scope)
