require("$api/models $views/image#Image $shared/events#EventHandler $views/throbber#Throbber $views/list#List scripts/utils scripts/env#Environment scripts/config strings/main.lang".split(" "),function(f,k,p,q,t,h,r,u,e){function d(a){this._logger=a;this._elements={};this._events=new p(this);this.database=[];this.loops=[];this.doForward=!0;this.initialWidth=0}d.prototype.init=function(){var a=this._elements;this.isError=!1;a.page=new Element("div",{"class":"page"});a.searchQuery=new Element("div",
{"class":"search-query hidden"});this._events.listen(a.searchQuery,"click",function(a){a.preventDefault();a.target.href&&f.application.openURI(a.target.href)});a.searchParagraph=new Element("p",{"class":"search-paragraph",html:"<p>"+e.get("search-paragraph-results")+"</p>"});a.fuzzyMatch=new Element("p",{"class":"fuzzy-match hidden",html:e.get("did-you-mean")});this._events.listen(a.fuzzyMatch,"click",this._onFuzzyClick);a.backToOriginalQuery=new Element("p",{"class":"original-query hidden",html:""});
this._events.listen(a.backToOriginalQuery,"click",this._onBackToOriginalQueryClick);a.emptySearchResult=new Element("div",{"class":"empty-search-result",html:"<div><p>"+e.get("empty-search-result","&ldquo;<strong></strong>&rdquo;")+"</p></div>"});a.emptySearchResultText=$$(a.emptySearchResult.getElement("strong"));a.searchResult=new Element("div",{"class":"search-result"});a.dump=new Element("div",{"class":"dump hidden"});document.body.adopt(a.page.adopt(a.dump,a.searchQuery.adopt(a.searchParagraph,
a.backToOriginalQuery,a.fuzzyMatch),a.searchResult,a.emptySearchResult));this.showThrobber()};d.prototype.dispose=function(){"undefined"!==typeof this._events&&this._events.removeAll();this._elements.page&&this._elements.page.dispose();this.isError=!1;this.initialWidth=0};d.prototype.setSmallSize=function(){this.size=128;this.windowWidth=this.windowWidth||0;this.initialWidth=this.initialWidth||this.windowWidth;this.windowWidth=0<h.getWidth()?h.getWidth():this.windowWidth;this.initialWidth=this.windowWidth>
this.initialWidth?this.windowWidth:this.initialWidth;this.setCols();this.setMargin()};d.prototype.setBigSize=function(){this.size=230;this.margin=0};d.prototype.setMargin=function(){this.margin=Math.floor((this.windowWidth-this.cols*this.size)/(this.cols-1))};d.prototype.setCols=function(a){a=a||u.MINIMAL_MARGIN;this.cols=Math.floor((this.windowWidth+a)/(this.size+a))};d.prototype.setRows=function(){this.rows=this.getRows();this._elements.page.removeClass("rows-0").removeClass("rows-1").removeClass("rows-2").addClass("rows-"+
this.rows)};d.prototype.getRows=function(){var a=h.getAmountOfObjectsFromDOM().obj;return h.getWireframe(this.cols,a).length};d.prototype.setHeaderSize=function(a){var b=40;2===this.rows?b=414:1===this.rows&&(b=237);this.isError||_getSpotifyModule("core")._set_body_size(10,"undefined"!==typeof a?a:b,!0)};d.prototype.setQueryAndCategory=function(a,b){var c;c=null===b?new Element("a",{href:h.getHref(a),text:a}):new Element("span",{text:a});this._elements.searchParagraph.set("html",e.get("search-paragraph-"+
(null===b?"results":b),"&ldquo;"+c.outerHTML+"&rdquo;"));this._elements.searchQuery.removeClass("hidden")};d.prototype.setFuzzyMatch=function(a){if(0<a.length){var b=[],c=this._elements;c.fuzzyMatchAnchor=new Element("a",{href:h.getHref(a[0].name),"class":a[0].type,text:a[0].name});b.push(c.fuzzyMatchAnchor.outerHTML);2===a.length&&(c.fuzzyMatchSecondAnchor=new Element("a",{href:h.getHref(a[1].name),"class":a[1].type,text:a[1].name}),b.push(c.fuzzyMatchSecondAnchor.outerHTML));c.fuzzyMatch.set("html",
e.get.apply(e,["did-you-mean-"+a.length].concat(b)));c.fuzzyMatch.removeClass("hidden")}this.setRows();r.desktop&&this.setHeaderSize()};d.prototype.setBackToOriginalQueryLink=function(a){if(0<a.length){var b=this._elements;b.backToOriginalQueryAnchor=new Element("a",{href:h.getHref(a),"class":"back-to-original",text:a});b.backToOriginalQuery.set("html",e.get("back-to-original-query",b.backToOriginalQueryAnchor.outerHTML));b.backToOriginalQuery.removeClass("hidden")}};d.prototype.loopThroughAndSetImage=
function(){for(var a,b=0,c=this.loops.length;b<c;b+=1)a=this.loops[b],a.img.setImage(a.obj),a.obj instanceof f.Album&&0===a.img._overlay[1].indexOf("<a")&&this._events.listen(a.img.node.getElement(".sp-image-overlay-line2 a"),"click",this._openLink);this.loops=[]};d.prototype.repaintHeader=function(){this.setSmallSize();this.setRows();r.desktop&&this.setHeaderSize();var a=h.getAmountOfObjectsFromDOM(),b=a.obj,a=a.order,c=h.getWireframe(this.cols,b),b=h.getSpliceStructure(this.cols,b),d=document.getElement(".search-result").getStyle("padding-left").toInt(),
i,g,j,l;g=0;for(var n=d,f=0,e=0,k=c.length;e<k;e+=1)for(var n=d,s=0,p=c[e].length;s<p;s+=1){i=a[f];i=document.getElement("."+i);g=i.getElement("ul");j=i.getElement("button");l=i.getElement("h2");i.get("data-max-length")&&b[f]<i.get("data-max-length").toInt()?(l.removeClass("no-link"),j.removeClass("hidden")):j.hasClass("hidden")||(j.addClass("hidden"),l.addClass("no-link"));j.getStyle("right").toInt()!==this.margin-2&&j.setStyle("right",this.margin-2);for(var m=0,q=g.children.length;m<q;m+=1)j=g.children[m],
l=0===m?0:this.margin,j.getStyle("margin-left").toInt()!==l&&j.setStyle("margin-left",l),m<b[f]?j.removeClass("hidden"):j.addClass("hidden");g=(this.size+this.margin)*b[f];j=i.getStyles("width","top","left");l={width:g+"px",top:(0<e?i.getPrevious().getStyle("height").toInt():0)+"px",left:n+"px"};h.isSimpleEqual(j,l)||i.setStyles(l);n+=g;f+=1}};d.prototype.createHeaderNodes=function(a,b){k.prototype._artificialLoading=function(){return!1};var c=document.createDocumentFragment(),d,i,g,j,f,h;for(h in a)d=
new Element("section",{"class":"pod "+h,"data-category":h,"data-max-length":b[h]}),i=new Element("hgroup",{"class":"hgroup"}),g=new Element("h2",{text:e.get(h),"class":"title no-link"}),j=new Element("button",{"class":"see-all hidden",text:e.get("see-all"),styles:{right:this.margin-2}}),f=new Element("ul",{"class":"grid"}),c.appendChild(d.adopt(i.adopt(g),j,f));this._elements.searchResult.appendChild(c)};d.prototype.createLonerNodes=function(a,b){this._elements.page.addClass("loner");var c=new Element("section",
{"class":"pod "+a,"data-category":a,"data-max-length":b}),d=new Element("hgroup",{"class":"hgroup"}),i=new Element("h2",{text:e.get(a)}),g=new Element("ul",{"class":"grid"});c.adopt(d.adopt(i),g);this._elements.searchResult.adopt(c)};d.prototype.addData=function(a,b){var b=b||{},c=b.placeholders||!1,d,i,g,j,f,h;for(h in a){f=a[h];d=document.createDocumentFragment();i=document.getElement("."+h+" ul");g=i.getChildren("li");j=(g=g[g.length-1])?g.get("data-index").toInt():0;for(var e=0,k=f.length;e<k;e+=
1)g=this._getListItem(f[e],b),j+=1,g.set("data-index",j),g.set("data-uri",f[e].uri),0===e&&g.setStyle("margin-left",0),c&&g.addClass("placeholder"),d.appendChild(g);i.appendChild(d)}};d.prototype.paintList=function(a){var a=t.forCollection(a,{fields:["track","artist","time","album","popularity"],height:"fixed",throbber:"hide-content",numBuckets:1}),b=this;this._events.listen(a,"empty",function(){b._onNoTracks()});this._events.listen(a,"list-click",function(a){b._onListClick(a)});var c=new Element("section",
{"class":"tracks","data-category":"tracks"});this._elements.searchResult.adopt(c.adopt(a.node));a.init()};d.prototype.showThrobber=function(a){this._throbber&&this._throbber.hide();a=a||{};this._throbber=q.forElement(this._elements[a.element]||this._elements.page);a.showContent&&this._throbber.showContent();a.addClass&&this._throbber.node.addClass(a.addClass)};d.prototype.hideThrobber=function(){this._throbber.hide()};d.prototype._onFuzzyClick=function(a){a.preventDefault();"A"===a.target.nodeName&&
(a={type:a.target.className,value:a.target.textContent},this._logger.clientEvent("fuzzy-match-click",a),f.application.openURI("spotify:search:"+a.value))};d.prototype._onCoverClick=function(a){if("E"===this._logger.getTestVersion()||"F"===this._logger.getTestVersion()||"G"===this._logger.getTestVersion()||"H"===this._logger.getTestVersion()){a.preventDefault();a.stopPropagation();var b=a.target,c=a.target.tagName+" "+a.target.className,d="A"===b.nodeName?b.get("href"):b.getParent(".ui").get("data-uri"),
i=b.getParent(".pod").get("data-category");if(2===this.getRows()&&4===h.getOrder().length)var g=a.x.toString(),e=a.y.toString(),b={selector:c,uri:d,category:i,"page-x":g,"page-y":e,"percentage-x":Math.floor(100*g/window.innerWidth).toString(),"percentage-y":Math.floor(100*e/b.getParent(".page").getStyle("height").toInt()).toString()};else b={uri:d,category:i,selector:c};this._logger.clientEvent("header-click",b)}b=a.target.getParent(".sp-image");"#"===b.get("href")&&!a.target.getParent().hasClass("sp-image-overlay-line2")&&
f.application.openURI(b.get("data-uri"))};d.prototype._onListClick=function(a){this._logger.clientEvent("list-click",{uri:a.uri})};d.prototype._getEmptyImage=function(a){var b={width:this.size,height:this.size,link:a.uri,player:!0,overlay:[a.name]};a instanceof f.Artist?b.placeholder="artist":a instanceof f.Album?b.placeholder="album":a instanceof f.Playlist?b.placeholder="playlist":(b.placeholder="user",b.player=!1,b.overlay=[a.full_name],b.link="spotify:user:"+a.username,a.image=h.fixImageURL(a));
if(a instanceof f.Album){var c=a.artists[0].name,d="various artists"!==c.toLowerCase()?a.artists[0].uri.toSpotifyURL():"",c=""!==d?new Element("a",{html:c,href:d}):new Element("span",{html:c});b.overlay.push(c.outerHTML)}var b=k.fromSource("data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",b),e={obj:a,img:b};"undefined"!==typeof a.username&&(e.obj=a.image);"undefined"!==typeof e.obj&&this._events.listen(b,"load",function(){this._imageLoad(e)});this._events.listen(b.node,
"click",this._onCoverClick);return b};d.prototype._imageLoad=function(a){this._events.unlisten(a.img,"load");a.img.setImage(a.obj);var b=a.img.node.getElements(".sp-image-overlay");1<b.length&&b[1].dispose();a.obj instanceof f.Album&&0===a.img._overlay[1].indexOf("<a")&&this._events.listen(a.img.node.getElement(".sp-image-overlay-line2 a"),"click",this._openLink)};d.prototype._openLink=function(a){a.stopPropagation();a.preventDefault();var b=a.target.get("href").toSpotifyURI();f.application.openURI(b);
this._onCoverClick(a)};d.prototype._getImage=function(a){var b={width:this.size,height:this.size,link:a.uri,player:!0,overlay:[a.name]},c=null;if(a instanceof f.Artist)c=k.forArtist(a,b);else if(a instanceof f.Album){var c=a.artists[0].name,d="various artists"!==c.toLowerCase()?a.artists[0].uri.toSpotifyURL():"",c=""!==d?new Element("a",{html:c,href:d}):new Element("span",{html:c});b.overlay.push(c.outerHTML);c=k.forAlbum(a,b);""!==d&&this._events.listen(c.node.getElement(".sp-image-overlay-line2 a"),
"click",this._openLink)}else a instanceof f.Playlist?c=k.forPlaylist(a,b):(b.player=!1,b.overlay=[a.full_name],b.link="spotify:user:"+a.username,b.placeholder="user",a.image=h.fixImageURL(a),c="undefined"!==typeof a.image?k.fromSource(a.image,b):k.fromSource("data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",b));this._events.listen(c.node,"click",this._onCoverClick);return c};d.prototype._getListItem=function(a,b){var b=b||{},c=new Element("li",{"class":"ui"+(b.hidden?
" hidden":""),"data-uri":a.uri,styles:{"margin-left":this.margin}});b.realPlaceholders?(c.adopt(this._getEmptyImage(a).node),c.getElement(".sp-image").removeClass("sp-image-hidden")):c.adopt(this._getImage(a).node);c.getElement(".sp-image-placeholder").removeClass("sp-image-placeholder-hidden");this.database.push(c);return c};d.prototype._onNoTracks=function(){this._elements.page.hasClass("error")||(this._throbber.hide(),this._elements.page.addClass("no-tracks"),this._elements.searchResult.firstChild.hasClass("tracks")&&
this._elements.searchResult.setStyle("height",0),this._elements.emptySearchResult.set("html","<div><p>"+e.get("no-tracks")+"</p></div>"))};d.prototype._onError=function(){console.error("Error!");this._throbber&&this._throbber.hide();(0===this._elements.searchResult.children.length||this._elements.searchResult.firstChild.hasClass("tracks"))&&this._elements.searchResult.setStyle("height",0);this._elements.page.addClass("error");this._elements.emptySearchResult.set("html","<div><p>"+e.get("snapshot-failed")+
"</p></div>");if(r.desktop){var a=0;this._elements.searchParagraph.getElement("a")&&(a=""!==this._elements.searchParagraph.getElement("a").innerHTML?40:0);this.setHeaderSize(a);this.isError=!0}};exports.View=d});
